-- =====================================================
-- HAUL COMMAND PHASE 1 CONTROL SYSTEM
-- Florida → Texas → Canada → Global
-- =====================================================
-- 
-- PURPOSE: Implement the complete Phase 1 Master Plan
-- - Intake Rail (VAPI + GHL)
-- - Movement Intelligence Engine
-- - Dynamic Pricing Engine
-- - White-Label Dispatch
-- - HaulPay (Escrow + Split + Instant Payout)
-- - 5 Money Moves
-- - Telematics Layer
-- - Failsafe Architecture
-- - 3-Tier Data Capture
-- - HallScore™ Credit System
--
-- ARCHITECTURE: phase1_master_plan.md
-- =====================================================

-- =====================================================
-- I. MOVEMENT INTELLIGENCE ENGINE
-- =====================================================

CREATE TABLE IF NOT EXISTS movement_records (
    movement_record_id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    
    -- Intake Data (VAPI JSON)
    origin_location TEXT NOT NULL,
    destination_location TEXT NOT NULL,
    load_width_inches NUMERIC(6,2),
    load_height_inches NUMERIC(6,2),
    load_length_inches NUMERIC(6,2),
    load_weight_pounds INT,
    movement_date DATE,
    commodity_type TEXT,
    segment TEXT, -- wind, mobile_home, transformer, energy, construction, etc.
    
    -- Rule Processing Outputs
    escorts_required INT,
    police_required BOOLEAN DEFAULT FALSE,
    utility_coordination_required BOOLEAN DEFAULT FALSE,
    height_pole_required BOOLEAN DEFAULT FALSE,
    night_movement_allowed BOOLEAN DEFAULT TRUE,
    
    -- Risk & Intelligence Outputs
    risk_score NUMERIC(5,2), -- 0.00 to 100.00
    suggested_price_floor NUMERIC(10,2),
    corridor_scarcity_index NUMERIC(5,2), -- 0.00 to 10.00 (scarcity multiplier)
    
    -- Metadata
    created_at TIMESTAMPTZ DEFAULT NOW(),
    created_by UUID REFERENCES auth.users(id),
    ghl_opportunity_id TEXT, -- GHL CRM link
    
    CONSTRAINT movement_records_valid_dimensions CHECK (
        load_width_inches > 0 
        AND load_height_inches > 0 
        AND load_length_inches > 0
    )
);

CREATE INDEX idx_movement_records_date ON movement_records(movement_date);
CREATE INDEX idx_movement_records_segment ON movement_records(segment);
CREATE INDEX idx_movement_records_corridor ON movement_records(origin_location, destination_location);

COMMENT ON TABLE movement_records IS 'Core movement intelligence records generated by Anti-Gravity from VAPI intake. Each record represents a broker request processed through the rule engine.';

-- =====================================================
-- II. DYNAMIC PRICING ENGINE
-- =====================================================

CREATE TABLE IF NOT EXISTS corridor_pricing_index (
    corridor_id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    corridor_name TEXT NOT NULL UNIQUE, -- e.g., "I-75 FL North", "I-10 TX West"
    
    -- Scarcity Multipliers
    base_scarcity_multiplier NUMERIC(4,2) DEFAULT 1.00, -- 1.00 = no scarcity
    current_scarcity_multiplier NUMERIC(4,2) DEFAULT 1.00, -- auto-updated by demand
    
    -- Metro & Risk Multipliers
    metro_multiplier NUMERIC(4,2) DEFAULT 1.00, -- urban density premium
    wind_corridor_multiplier NUMERIC(4,2) DEFAULT 1.00, -- wind exposure premium
    
    -- Historical Pricing Data
    avg_escort_cost_per_mile NUMERIC(8,2),
    avg_police_coordination_fee NUMERIC(8,2),
    avg_utility_coordination_fee NUMERIC(8,2),
    
    -- Metadata
    last_updated TIMESTAMPTZ DEFAULT NOW(),
    
    CONSTRAINT corridor_valid_multipliers CHECK (
        base_scarcity_multiplier > 0 
        AND current_scarcity_multiplier > 0
    )
);

CREATE INDEX idx_corridor_pricing_name ON corridor_pricing_index(corridor_name);

COMMENT ON TABLE corridor_pricing_index IS 'Dynamic pricing intelligence by corridor. Scarcity multipliers auto-adjust based on real-time demand. This is margin intelligence, not flat pricing.';

CREATE TABLE IF NOT EXISTS pricing_calculations (
    pricing_id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    movement_record_id UUID REFERENCES movement_records(movement_record_id) ON DELETE CASCADE,
    corridor_id UUID REFERENCES corridor_pricing_index(corridor_id),
    
    -- Pricing Variables (8-Factor Model)
    base_escort_cost NUMERIC(10,2) NOT NULL,
    scarcity_multiplier NUMERIC(4,2) DEFAULT 1.00,
    risk_multiplier NUMERIC(4,2) DEFAULT 1.00,
    police_coordination_fee NUMERIC(10,2) DEFAULT 0.00,
    utility_coordination_fee NUMERIC(10,2) DEFAULT 0.00,
    platform_fee NUMERIC(10,2) NOT NULL, -- HC platform revenue
    rush_multiplier NUMERIC(4,2) DEFAULT 1.00, -- urgency premium
    metro_multiplier NUMERIC(4,2) DEFAULT 1.00,
    
    -- Final Pricing
    final_broker_price NUMERIC(10,2) NOT NULL, -- what broker pays
    
    -- Metadata
    calculated_at TIMESTAMPTZ DEFAULT NOW(),
    
    CONSTRAINT pricing_valid_amounts CHECK (
        base_escort_cost > 0 
        AND final_broker_price > 0
    )
);

CREATE INDEX idx_pricing_movement ON pricing_calculations(movement_record_id);

COMMENT ON TABLE pricing_calculations IS 'Dynamic pricing calculation records. Each movement gets 8-variable pricing: base + scarcity + risk + police + utility + platform + rush + metro = final price.';

-- =====================================================
-- III. WHITE-LABEL DISPATCH SYSTEM
-- =====================================================

CREATE TABLE IF NOT EXISTS escort_dispatch (
    dispatch_id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    movement_record_id UUID REFERENCES movement_records(movement_record_id) ON DELETE CASCADE,
    
    -- Assignment Logic
    assigned_operator_id UUID REFERENCES operator_master(operator_id),
    hall_id TEXT, -- HallID (identity graph)
    hall_score NUMERIC(5,2), -- credit score at time of assignment
    
    -- Certification & Compliance
    certification_verified BOOLEAN DEFAULT FALSE,
    equipment_compliant BOOLEAN DEFAULT FALSE,
    
    -- Location Intelligence
    proximity_miles NUMERIC(8,2), -- distance from operator to pickup
    
    -- Telematics Integration (Navify)
    navify_tracking_enabled BOOLEAN DEFAULT FALSE,
    navify_tracking_url TEXT,
    
    -- Dispatch Status
    dispatch_status TEXT DEFAULT 'pending', -- pending, assigned, en_route, completed, cancelled
    
    -- Metadata
    assigned_at TIMESTAMPTZ DEFAULT NOW(),
    completed_at TIMESTAMPTZ,
    
    CONSTRAINT dispatch_valid_status CHECK (
        dispatch_status IN ('pending', 'assigned', 'en_route', 'completed', 'cancelled')
    )
);

CREATE INDEX idx_dispatch_movement ON escort_dispatch(movement_record_id);
CREATE INDEX idx_dispatch_operator ON escort_dispatch(assigned_operator_id);
CREATE INDEX idx_dispatch_hall_id ON escort_dispatch(hall_id);
CREATE INDEX idx_dispatch_status ON escort_dispatch(dispatch_status);

COMMENT ON TABLE escort_dispatch IS 'White-label dispatch records. Closed network assignment based on HallID → certification → equipment → proximity → HallScore. Never allow direct broker→escort payments.';

-- =====================================================
-- IV. HAULPAY (PAYMENT RAIL CONTROL)
-- =====================================================

CREATE TABLE IF NOT EXISTS haulpay_escrow (
    escrow_id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    movement_record_id UUID REFERENCES movement_records(movement_record_id) ON DELETE CASCADE,
    dispatch_id UUID REFERENCES escort_dispatch(dispatch_id),
    
    -- Broker Deposit
    broker_deposit_amount NUMERIC(10,2) NOT NULL,
    broker_payment_received BOOLEAN DEFAULT FALSE,
    broker_payment_date TIMESTAMPTZ,
    
    -- Split Logic
    platform_fee_amount NUMERIC(10,2) NOT NULL, -- HC revenue
    escort_payout_amount NUMERIC(10,2) NOT NULL,
    police_passthrough_amount NUMERIC(10,2) DEFAULT 0.00,
    utility_passthrough_amount NUMERIC(10,2) DEFAULT 0.00,
    
    -- Payout Triggers
    payout_status TEXT DEFAULT 'held', -- held, released, instant_released
    payout_released_at TIMESTAMPTZ,
    
    -- Metadata
    created_at TIMESTAMPTZ DEFAULT NOW(),
    
    CONSTRAINT haulpay_valid_split CHECK (
        broker_deposit_amount = platform_fee_amount + escort_payout_amount + police_passthrough_amount + utility_passthrough_amount
    ),
    CONSTRAINT haulpay_valid_status CHECK (
        payout_status IN ('held', 'released', 'instant_released')
    )
);

CREATE INDEX idx_haulpay_movement ON haulpay_escrow(movement_record_id);
CREATE INDEX idx_haulpay_dispatch ON haulpay_escrow(dispatch_id);
CREATE INDEX idx_haulpay_status ON haulpay_escrow(payout_status);

COMMENT ON TABLE haulpay_escrow IS 'HaulPay escrow layer. Broker → HaulPay → platform fee retained → escort payout delayed until completion. Payment rail control = network control.';

CREATE TABLE IF NOT EXISTS haulpay_instant_payout (
    instant_payout_id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    escrow_id UUID REFERENCES haulpay_escrow(escrow_id) ON DELETE CASCADE,
    
    -- Instant Payout Economics (3% fee model)
    original_payout_amount NUMERIC(10,2) NOT NULL,
    instant_payout_fee NUMERIC(10,2) NOT NULL, -- 3% of original amount
    net_instant_payout NUMERIC(10,2) NOT NULL, -- original - fee
    
    -- Timing
    requested_at TIMESTAMPTZ DEFAULT NOW(),
    processed_at TIMESTAMPTZ,
    
    CONSTRAINT instant_payout_valid_fee CHECK (
        instant_payout_fee = original_payout_amount * 0.03
        AND net_instant_payout = original_payout_amount - instant_payout_fee
    )
);

CREATE INDEX idx_instant_payout_escrow ON haulpay_instant_payout(escrow_id);

COMMENT ON TABLE haulpay_instant_payout IS 'Instant payout feature: 3% fee vs 7-day free ACH. Proto-factoring model.';

-- =====================================================
-- V. THE 5 MONEY MOVES
-- =====================================================

-- MONEY MOVE #3: Proof Pack Upsells
CREATE TABLE IF NOT EXISTS proof_pack_upsells (
    proof_pack_id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    movement_record_id UUID REFERENCES movement_records(movement_record_id) ON DELETE CASCADE,
    
    -- Proof Pack Components
    live_tracking_link TEXT,
    route_proof_pdf_url TEXT,
    geostamped_timeline_json JSONB, -- timestamps + GPS coordinates
    auto_generated_recap TEXT,
    
    -- Upsell Economics
    upsell_price NUMERIC(8,2) DEFAULT 25.00, -- charge extra, costs almost nothing
    purchased BOOLEAN DEFAULT FALSE,
    
    -- Metadata
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX idx_proof_pack_movement ON proof_pack_upsells(movement_record_id);

COMMENT ON TABLE proof_pack_upsells IS 'Money Move #3: Auto-attach live tracking + RouteProof PDF + geostamped timeline + recap. Charge extra. Costs almost nothing.';

-- MONEY MOVE #4: Payment Speed Modeling
CREATE TABLE IF NOT EXISTS payment_speed_tracking (
    payment_tracking_id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    escrow_id UUID REFERENCES haulpay_escrow(escrow_id) ON DELETE CASCADE,
    
    -- Payment Timing
    invoice_sent_at TIMESTAMPTZ NOT NULL,
    payment_received_at TIMESTAMPTZ,
    days_to_payment INT GENERATED ALWAYS AS (
        EXTRACT(DAY FROM (payment_received_at - invoice_sent_at))
    ) STORED,
    
    -- Incentives & Penalties
    early_pay_discount_offered NUMERIC(8,2) DEFAULT 0.00, -- 2% 3-day discount
    late_fee_charged NUMERIC(8,2) DEFAULT 0.00, -- auto-late fee
    
    -- Metadata
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX idx_payment_speed_escrow ON payment_speed_tracking(escrow_id);
CREATE INDEX idx_payment_speed_days ON payment_speed_tracking(days_to_payment);

COMMENT ON TABLE payment_speed_tracking IS 'Money Move #4: Track broker pay time. Charge late fees automatically. Offer 2% 3-day discounts. Proto-factoring model.';

-- =====================================================
-- VI. TELEMATICS LAYER (NAVIFY + HERE)
-- =====================================================

CREATE TABLE IF NOT EXISTS movement_telematics (
    telematics_id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    dispatch_id UUID REFERENCES escort_dispatch(dispatch_id) ON DELETE CASCADE,
    
    -- Breadcrumb Data (GPS Trail)
    breadcrumb_data JSONB, -- [{timestamp, lat, lng, speed, heading}, ...]
    
    -- Arrival/Departure Timestamps
    pickup_arrival_time TIMESTAMPTZ,
    pickup_departure_time TIMESTAMPTZ,
    delivery_arrival_time TIMESTAMPTZ,
    delivery_departure_time TIMESTAMPTZ,
    
    -- Delay Durations
    total_delay_minutes INT,
    delay_reasons JSONB, -- [{"reason": "police coordination", "minutes": 45}, ...]
    
    -- Metadata
    created_at TIMESTAMPTZ DEFAULT NOW(),
    last_updated TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX idx_telematics_dispatch ON movement_telematics(dispatch_id);

COMMENT ON TABLE movement_telematics IS 'Telematics layer: Navify tracking → breadcrumb data → arrival/departure timestamps → delay logging. Real operational movement data = Risk Index foundation.';

-- =====================================================
-- VII. HALLSCORE™ (CREDIT SYSTEM - BUILT DAY 1)
-- =====================================================

CREATE TABLE IF NOT EXISTS hall_score (
    hall_score_id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    hall_id TEXT UNIQUE NOT NULL, -- HallID (identity graph)
    entity_type TEXT NOT NULL, -- 'escort' or 'broker'
    
    -- Escort Scoring Factors
    escort_reliability_score NUMERIC(5,2), -- 0.00 to 100.00
    escort_on_time_percentage NUMERIC(5,2), -- 0.00 to 100.00
    escort_compliance_accuracy NUMERIC(5,2), -- 0.00 to 100.00
    escort_incident_count INT DEFAULT 0,
    
    -- Broker Scoring Factors
    broker_payment_speed_avg_days NUMERIC(6,2),
    broker_dispute_rate NUMERIC(5,2), -- 0.00 to 100.00
    broker_cancellation_frequency NUMERIC(5,2), -- 0.00 to 100.00
    
    -- Composite Score
    composite_hall_score NUMERIC(5,2), -- 0.00 to 100.00 (overall credit score)
    
    -- Display Control
    display_publicly BOOLEAN DEFAULT FALSE, -- internal now, public later
    
    -- Metadata
    created_at TIMESTAMPTZ DEFAULT NOW(),
    last_updated TIMESTAMPTZ DEFAULT NOW(),
    
    CONSTRAINT hall_score_valid_entity CHECK (
        entity_type IN ('escort', 'broker')
    )
);

CREATE INDEX idx_hall_score_hall_id ON hall_score(hall_id);
CREATE INDEX idx_hall_score_entity_type ON hall_score(entity_type);
CREATE INDEX idx_hall_score_composite ON hall_score(composite_hall_score DESC);

COMMENT ON TABLE hall_score IS 'HallScore™: Heavy Haul Credit Score. Score escorts (reliability, on-time, compliance, incidents) and brokers (payment speed, disputes, cancellations). Display internally now, publicly later. This becomes monopoly lever.';

-- =====================================================
-- VIII. 3-TIER DATA CAPTURE SYSTEM
-- =====================================================

CREATE TABLE IF NOT EXISTS movement_event_log (
    event_id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    movement_record_id UUID REFERENCES movement_records(movement_record_id) ON DELETE CASCADE,
    
    -- Data Tier Classification
    data_tier INT NOT NULL, -- 1 = Operational, 2 = Behavioral/Risk, 3 = Financial/Economic
    
    -- Tier 1: Operational Exhaust (Table Stakes)
    operational_data JSONB, -- dimensions, routes, timing, delays, costs
    
    -- Tier 2: Behavioral + Risk Data (Predictive Intelligence)
    behavioral_data JSONB, -- broker payment behavior, escort reliability, police delays, corridor patterns
    
    -- Tier 3: Financial + Economic Intelligence (Billion Territory)
    economic_data JSONB, -- true cost per escort mile, margin by corridor, scarcity index, risk correlations
    
    -- Event Details
    event_type TEXT NOT NULL, -- 'delay', 'cancellation', 'police_coordination', 'utility_coordination', 'incident', etc.
    event_timestamp TIMESTAMPTZ DEFAULT NOW(),
    
    -- Metadata
    created_at TIMESTAMPTZ DEFAULT NOW(),
    
    CONSTRAINT movement_event_valid_tier CHECK (
        data_tier IN (1, 2, 3)
    )
);

CREATE INDEX idx_movement_event_record ON movement_event_log(movement_record_id);
CREATE INDEX idx_movement_event_tier ON movement_event_log(data_tier);
CREATE INDEX idx_movement_event_type ON movement_event_log(event_type);
CREATE INDEX idx_movement_event_timestamp ON movement_event_log(event_timestamp);

COMMENT ON TABLE movement_event_log IS '3-Tier Data Capture: Tier 1 (Operational - table stakes), Tier 2 (Behavioral/Risk - predictive intelligence), Tier 3 (Financial/Economic - Heavy Haul Economic Index™). Pure exhaust capture. No forms. No friction. Stripe logic.';

-- =====================================================
-- IX. FAILSAFE ARCHITECTURE
-- =====================================================

CREATE TABLE IF NOT EXISTS human_review_queue (
    review_id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    movement_record_id UUID REFERENCES movement_records(movement_record_id) ON DELETE CASCADE,
    
    -- Review Trigger
    review_reason TEXT NOT NULL, -- 'captcha_block', 'portal_change', 'permit_rejected', 'low_confidence'
    rule_confidence_score NUMERIC(5,2), -- < 85% triggers human review
    
    -- Review Data
    ai_recommendation JSONB, -- what the AI suggested
    human_override JSONB, -- what the human decided
    override_reasoning TEXT,
    
    -- Training Data Capture
    becomes_training_data BOOLEAN DEFAULT TRUE,
    
    -- Review Status
    review_status TEXT DEFAULT 'pending', -- pending, in_review, resolved
    reviewed_by UUID REFERENCES auth.users(id),
    reviewed_at TIMESTAMPTZ,
    
    -- Metadata
    created_at TIMESTAMPTZ DEFAULT NOW(),
    
    CONSTRAINT review_valid_status CHECK (
        review_status IN ('pending', 'in_review', 'resolved')
    )
);

CREATE INDEX idx_review_movement ON human_review_queue(movement_record_id);
CREATE INDEX idx_review_status ON human_review_queue(review_status);
CREATE INDEX idx_review_confidence ON human_review_queue(rule_confidence_score);

COMMENT ON TABLE human_review_queue IS 'Failsafe architecture: CAPTCHA blocks, portal changes, permit rejections, low confidence (<85%) → route to human review. Human logs override. Override data becomes training set. System improves.';

-- =====================================================
-- X. ROW-LEVEL SECURITY (RLS)
-- =====================================================

-- Enable RLS on all tables
ALTER TABLE movement_records ENABLE ROW LEVEL SECURITY;
ALTER TABLE corridor_pricing_index ENABLE ROW LEVEL SECURITY;
ALTER TABLE pricing_calculations ENABLE ROW LEVEL SECURITY;
ALTER TABLE escort_dispatch ENABLE ROW LEVEL SECURITY;
ALTER TABLE haulpay_escrow ENABLE ROW LEVEL SECURITY;
ALTER TABLE haulpay_instant_payout ENABLE ROW LEVEL SECURITY;
ALTER TABLE proof_pack_upsells ENABLE ROW LEVEL SECURITY;
ALTER TABLE payment_speed_tracking ENABLE ROW LEVEL SECURITY;
ALTER TABLE movement_telematics ENABLE ROW LEVEL SECURITY;
ALTER TABLE hall_score ENABLE ROW LEVEL SECURITY;
ALTER TABLE movement_event_log ENABLE ROW LEVEL SECURITY;
ALTER TABLE human_review_queue ENABLE ROW LEVEL SECURITY;

-- Admin full access
CREATE POLICY admin_all_movement_records ON movement_records FOR ALL USING (auth.jwt() ->> 'role' = 'admin');
CREATE POLICY admin_all_corridor_pricing ON corridor_pricing_index FOR ALL USING (auth.jwt() ->> 'role' = 'admin');
CREATE POLICY admin_all_pricing_calculations ON pricing_calculations FOR ALL USING (auth.jwt() ->> 'role' = 'admin');
CREATE POLICY admin_all_escort_dispatch ON escort_dispatch FOR ALL USING (auth.jwt() ->> 'role' = 'admin');
CREATE POLICY admin_all_haulpay_escrow ON haulpay_escrow FOR ALL USING (auth.jwt() ->> 'role' = 'admin');
CREATE POLICY admin_all_haulpay_instant_payout ON haulpay_instant_payout FOR ALL USING (auth.jwt() ->> 'role' = 'admin');
CREATE POLICY admin_all_proof_pack_upsells ON proof_pack_upsells FOR ALL USING (auth.jwt() ->> 'role' = 'admin');
CREATE POLICY admin_all_payment_speed_tracking ON payment_speed_tracking FOR ALL USING (auth.jwt() ->> 'role' = 'admin');
CREATE POLICY admin_all_movement_telematics ON movement_telematics FOR ALL USING (auth.jwt() ->> 'role' = 'admin');
CREATE POLICY admin_all_hall_score ON hall_score FOR ALL USING (auth.jwt() ->> 'role' = 'admin');
CREATE POLICY admin_all_movement_event_log ON movement_event_log FOR ALL USING (auth.jwt() ->> 'role' = 'admin');
CREATE POLICY admin_all_human_review_queue ON human_review_queue FOR ALL USING (auth.jwt() ->> 'role' = 'admin');

-- =====================================================
-- XI. INITIAL SEED DATA
-- =====================================================

-- Seed corridor pricing index for Florida + Texas
INSERT INTO corridor_pricing_index (corridor_name, base_scarcity_multiplier, metro_multiplier, wind_corridor_multiplier, avg_escort_cost_per_mile) VALUES
('I-75 FL North', 1.00, 1.15, 1.05, 3.50),
('I-75 FL South', 1.00, 1.20, 1.10, 3.75),
('I-95 FL North', 1.00, 1.10, 1.00, 3.25),
('I-95 FL South', 1.00, 1.25, 1.15, 4.00),
('I-10 FL Panhandle', 1.00, 1.05, 1.20, 3.50),
('I-10 TX West', 1.00, 1.05, 1.30, 3.25),
('I-10 TX East', 1.00, 1.10, 1.15, 3.50),
('I-35 TX North', 1.00, 1.15, 1.10, 3.75),
('I-35 TX South', 1.00, 1.20, 1.25, 4.00),
('I-45 TX (Houston-Dallas)', 1.00, 1.30, 1.10, 4.25)
ON CONFLICT (corridor_name) DO NOTHING;

-- =====================================================
-- END OF PHASE 1 CONTROL SYSTEM
-- =====================================================
