-- ============================================================================
-- SEED DATA: JURISDICTIONS (US + CA + PR)
-- The Canonical Source of Truth for Haul Command
-- ============================================================================

INSERT INTO jurisdictions (code, country, name, type, dot_links_json) VALUES
-- 🇺🇸 UNITED STATES (States)
('US-AL', 'US', 'Alabama', 'STATE', '{"permits": "https://www.dot.state.al.us/"}'),
('US-AK', 'US', 'Alaska', 'STATE', '{"permits": "http://dot.alaska.gov/"}'),
('US-AZ', 'US', 'Arizona', 'STATE', '{"permits": "https://azdot.gov/"}'),
('US-AR', 'US', 'Arkansas', 'STATE', '{"permits": "https://www.ardot.gov/"}'),
('US-CA', 'US', 'California', 'STATE', '{"permits": "https://dot.ca.gov/"}'),
('US-CO', 'US', 'Colorado', 'STATE', '{"permits": "https://www.codot.gov/"}'),
('US-CT', 'US', 'Connecticut', 'STATE', '{"permits": "https://portal.ct.gov/DOT"}'),
('US-DE', 'US', 'Delaware', 'STATE', '{"permits": "https://deldot.gov/"}'),
('US-FL', 'US', 'Florida', 'STATE', '{"permits": "https://www.fdot.gov/"}'),
('US-GA', 'US', 'Georgia', 'STATE', '{"permits": "http://www.dot.ga.gov/"}'),
('US-HI', 'US', 'Hawaii', 'STATE', '{"permits": "http://hidot.hawaii.gov/"}'),
('US-ID', 'US', 'Idaho', 'STATE', '{"permits": "https://itd.idaho.gov/"}'),
('US-IL', 'US', 'Illinois', 'STATE', '{"permits": "https://idot.illinois.gov/"}'),
('US-IN', 'US', 'Indiana', 'STATE', '{"permits": "https://www.in.gov/indot/"}'),
('US-IA', 'US', 'Iowa', 'STATE', '{"permits": "https://iowadot.gov/"}'),
('US-KS', 'US', 'Kansas', 'STATE', '{"permits": "https://www.ksdot.org/"}'),
('US-KY', 'US', 'Kentucky', 'STATE', '{"permits": "https://transportation.ky.gov/"}'),
('US-LA', 'US', 'Louisiana', 'STATE', '{"permits": "http://wwwsp.dotd.la.gov/"}'),
('US-ME', 'US', 'Maine', 'STATE', '{"permits": "https://www.maine.gov/mdot/"}'),
('US-MD', 'US', 'Maryland', 'STATE', '{"permits": "https://mdot.maryland.gov/"}'),
('US-MA', 'US', 'Massachusetts', 'STATE', '{"permits": "https://www.mass.gov/orgs/massachusetts-department-of-transportation"}'),
('US-MI', 'US', 'Michigan', 'STATE', '{"permits": "https://www.michigan.gov/mdot"}'),
('US-MN', 'US', 'Minnesota', 'STATE', '{"permits": "http://www.dot.state.mn.us/"}'),
('US-MS', 'US', 'Mississippi', 'STATE', '{"permits": "https://mdot.ms.gov/"}'),
('US-MO', 'US', 'Missouri', 'STATE', '{"permits": "https://www.modot.org/"}'),
('US-MT', 'US', 'Montana', 'STATE', '{"permits": "https://www.mdt.mt.gov/"}'),
('US-NE', 'US', 'Nebraska', 'STATE', '{"permits": "https://dot.nebraska.gov/"}'),
('US-NV', 'US', 'Nevada', 'STATE', '{"permits": "https://www.dot.nv.gov/"}'),
('US-NH', 'US', 'New Hampshire', 'STATE', '{"permits": "https://www.nh.gov/dot/"}'),
('US-NJ', 'US', 'New Jersey', 'STATE', '{"permits": "https://www.state.nj.us/transportation/"}'),
('US-NM', 'US', 'New Mexico', 'STATE', '{"permits": "https://dot.state.nm.us/"}'),
('US-NY', 'US', 'New York', 'STATE', '{"permits": "https://www.dot.ny.gov/"}'),
('US-NC', 'US', 'North Carolina', 'STATE', '{"permits": "https://www.ncdot.gov/"}'),
('US-ND', 'US', 'North Dakota', 'STATE', '{"permits": "https://www.dot.nd.gov/"}'),
('US-OH', 'US', 'Ohio', 'STATE', '{"permits": "https://www.transportation.ohio.gov/"}'),
('US-OK', 'US', 'Oklahoma', 'STATE', '{"permits": "https://oklahoma.gov/odot.html"}'),
('US-OR', 'US', 'Oregon', 'STATE', '{"permits": "https://www.oregon.gov/odot/"}'),
('US-PA', 'US', 'Pennsylvania', 'STATE', '{"permits": "https://www.penndot.gov/"}'),
('US-RI', 'US', 'Rhode Island', 'STATE', '{"permits": "http://www.dot.ri.gov/"}'),
('US-SC', 'US', 'South Carolina', 'STATE', '{"permits": "https://www.scdot.org/"}'),
('US-SD', 'US', 'South Dakota', 'STATE', '{"permits": "https://dot.sd.gov/"}'),
('US-TN', 'US', 'Tennessee', 'STATE', '{"permits": "https://www.tn.gov/tdot.html"}'),
('US-TX', 'US', 'Texas', 'STATE', '{"permits": "https://www.txdot.gov/"}'),
('US-UT', 'US', 'Utah', 'STATE', '{"permits": "https://www.udot.utah.gov/"}'),
('US-VT', 'US', 'Vermont', 'STATE', '{"permits": "https://vtrans.vermont.gov/"}'),
('US-VA', 'US', 'Virginia', 'STATE', '{"permits": "https://www.virginiidot.org/"}'),
('US-WA', 'US', 'Washington', 'STATE', '{"permits": "https://wsdot.wa.gov/"}'),
('US-WV', 'US', 'West Virginia', 'STATE', '{"permits": "https://transportation.wv.gov/"}'),
('US-WI', 'US', 'Wisconsin', 'STATE', '{"permits": "https://wisconsindot.gov/"}'),
('US-WY', 'US', 'Wyoming', 'STATE', '{"permits": "https://www.dot.state.wy.us/"}'),
('US-DC', 'US', 'District of Columbia', 'TERRITORY', '{"permits": "https://ddot.dc.gov/"}'),
('US-PR', 'US', 'Puerto Rico', 'TERRITORY', '{"permits": "https://dtop.pr.gov/"}'),

-- 🇨🇦 CANADA (Provinces & Territories)
('CA-AB', 'CA', 'Alberta', 'PROVINCE', '{"permits": "https://www.alberta.ca/transportation.aspx"}'),
('CA-BC', 'CA', 'British Columbia', 'PROVINCE', '{"permits": "https://www.cvse.ca/"}'),
('CA-MB', 'CA', 'Manitoba', 'PROVINCE', '{"permits": "https://www.gov.mb.ca/mit/"}'),
('CA-NB', 'CA', 'New Brunswick', 'PROVINCE', '{"permits": "https://www2.gnb.ca/content/gnb/en/departments/dti.html"}'),
('CA-NL', 'CA', 'Newfoundland and Labrador', 'PROVINCE', '{"permits": "https://www.gov.nl.ca/ti/"}'),
('CA-NS', 'CA', 'Nova Scotia', 'PROVINCE', '{"permits": "https://novascotia.ca/tran/"}'),
('CA-ON', 'CA', 'Ontario', 'PROVINCE', '{"permits": "http://www.mto.gov.on.ca/"}'),
('CA-PE', 'CA', 'Prince Edward Island', 'PROVINCE', '{"permits": "https://www.princeedwardisland.ca/en/topic/transportation-infrastructure-and-energy"}'),
('CA-QC', 'CA', 'Quebec', 'PROVINCE', '{"permits": "https://www.transports.gouv.qc.ca/"}'),
('CA-SK', 'CA', 'Saskatchewan', 'PROVINCE', '{"permits": "https://www.saskatchewan.ca/residents/transportation"}'),
('CA-NT', 'CA', 'Northwest Territories', 'TERRITORY', '{"permits": "https://www.inf.gov.nt.ca/"}'),
('CA-NU', 'CA', 'Nunavut', 'TERRITORY', '{"permits": "https://www.gov.nu.ca/edt"}'),
('CA-YT', 'CA', 'Yukon', 'TERRITORY', '{"permits": "https://yukon.ca/en/driving-and-transportation"}')

ON CONFLICT (code) DO UPDATE 
SET dot_links_json = EXCLUDED.dot_links_json;
