-- Auto-Generated Seed Data from pilot_cars_raw.txt
INSERT INTO driver_profiles (status, home_market_id, home_jurisdiction_id, pevo_cert_number, insurance_policy_number) VALUES
('PENDING_VERIFICATION', 'US', 'US-AL', NULL, NULL) -- Captain Harloch Pilot Service Robert Cook | captainharloch@gmail.com,
('PENDING_VERIFICATION', 'US', 'US-AL', NULL, NULL) -- Captain Harloch Pilot Service Robert Cook | captainharloch@gmail.com,
('PENDING_VERIFICATION', 'US', 'US-AL', NULL, NULL) -- Captain Harloch Pilot Service Robert Cook | captainharloch@gmail.com,
('PENDING_VERIFICATION', 'US', 'US-AL', NULL, NULL) -- Captain Harloch Pilot Service Robert Cook | captainharloch@gmail.com,
('PENDING_VERIFICATION', 'US', 'US-AL', NULL, NULL) -- Captain Harloch Pilot Service Robert Cook | captainharloch@gmail.com,
('PENDING_VERIFICATION', 'US', 'US-AL', NULL, NULL) -- 5 Star Pilot Escort Kelson Mitchell | kelsonmitchell1111@gmail.com,
('PENDING_VERIFICATION', 'US', 'US-AL', NULL, NULL) -- 5 Star Pilot Escort Kelson Mitchell | kelsonmitchell1111@gmail.com,
('PENDING_VERIFICATION', 'US', 'US-AL', NULL, NULL) -- 5 Star Pilot Escort ( ONLY CREDS ) Gerald Hale | halegerald2017@gmail.com,
('PENDING_VERIFICATION', 'US', 'US-AL', NULL, NULL) -- A J Escort Service Antonio Jones | antoniojones1818@icloud.com,
('PENDING_VERIFICATION', 'US', 'US-AL', NULL, NULL) -- A&C Pilot Car Service Marc Spaulding | bippga@hotmail.com,
('PENDING_VERIFICATION', 'US', 'US-AL', NULL, NULL) -- A1 Pilot Car Service Charles W. Coolidge | pilotcar1@icloud.com,
('PENDING_VERIFICATION', 'US', 'US-AL', NULL, NULL) -- Ada Trucking and Transportation LLC Aaron Hamilton Katina Hamilton | adatruckingandtransportation@gmail.com,
('PENDING_VERIFICATION', 'US', 'US-AL', NULL, NULL) -- AJ’s piloting Antonio | Antoniojones1819@gmail.com,
('PENDING_VERIFICATION', 'US', 'US-AL', NULL, NULL) -- Allegiant Express Services LLC Delarian Preston | Depreston8@gmail.com,
('PENDING_VERIFICATION', 'US', 'US-AL', NULL, NULL) -- Andry Logistics LLC Dequan Andry / Jelani Williamson | andrylogistics@gmail.com,
('PENDING_VERIFICATION', 'US', 'US-AL', NULL, NULL) -- Andry Logistics LLC Dequan Andry / Jelani Williamson | andrylogistics@gmail.com,
('PENDING_VERIFICATION', 'US', 'US-AL', NULL, NULL) -- Anthony Ray Franks Anthony Ray Franks | frankstrucking251@gmail.com,
('PENDING_VERIFICATION', 'US', 'US-AL', NULL, NULL) -- Bo Jo’s Pilot Service, LLC David Prestage | bojopilotservice@gmail.com,
('PENDING_VERIFICATION', 'US', 'US-AL', NULL, NULL) -- Brandon Trucking Brandon Garcia | brandongarcia768@yahoo.com,
('PENDING_VERIFICATION', 'US', 'US-AL', NULL, NULL) -- Byrd Logistics Kevin Byrd | kbyrd3923@gmail.com,
('PENDING_VERIFICATION', 'US', 'US-AL', NULL, NULL) -- Checkrunners Pilot Car Service Nigel Pryor | checkrunnerbrand@gmail.com,
('PENDING_VERIFICATION', 'US', 'US-AL', NULL, NULL) -- CJSmith Transportation Christopher Smith | cjsmithtransportation@gmail.com,
('PENDING_VERIFICATION', 'US', 'US-AL', NULL, NULL) -- CJSmith Transportation Christopher Smith | cjsmithtransportation@gmail.com,
('PENDING_VERIFICATION', 'US', 'US-AL', NULL, NULL) -- Coco Unlimited Corlette "Coco" Stewart Burns | cocoknows@cocounlimitedllc.com,
('PENDING_VERIFICATION', 'US', 'US-AL', NULL, NULL) -- Crimson Pilot Services Jamie Cooper | jamie@crimsonpilotservices.com,
('PENDING_VERIFICATION', 'US', 'US-AL', NULL, NULL) -- Currys Pilot Car Service LLC Barry Curry | curryspilotcarservice@yahoo.com,
('PENDING_VERIFICATION', 'US', 'US-AL', NULL, NULL) -- Joshua/Donald Brown DandJ Pilot Car LLC | dandjpilotcar@gmail.com,
('PENDING_VERIFICATION', 'US', 'US-AL', NULL, NULL) -- Darryl Gordon Darryl Gordon | Bgodon807@gmail.com,
('PENDING_VERIFICATION', 'US', 'US-AL', NULL, NULL) -- DayTrippers Express Inc Gary Blackburn | mrbthatsme@gmail.com,
('PENDING_VERIFICATION', 'US', 'US-AL', NULL, NULL) -- DDLM PCS, LLC Samantha Anderson | ddlmpcs@gmail.com,
('PENDING_VERIFICATION', 'US', 'US-AL', NULL, NULL) -- DLS Pilot Car Service Cameron Burroughs | caburroughs98@gmail.com,
('PENDING_VERIFICATION', 'US', 'US-AL', NULL, NULL) -- DLS Pilot Car Services Keelan Kennedy | statebound56@yahoo.com,
('PENDING_VERIFICATION', 'US', 'US-AL', NULL, NULL) -- F.A.F.O Piloting Services LLC Kathi (Kat) | fafopiloting9092@gmail.com,
('PENDING_VERIFICATION', 'US', 'US-AL', NULL, NULL) -- Flower Child Pilot Chimere Myles | flowerchildpilotcar@gmail.com,
('PENDING_VERIFICATION', 'US', 'US-AL', NULL, NULL) -- Frank McKinney Pilot Car Services Frank McKinney | hfrankmckinney@gmail.com,
('PENDING_VERIFICATION', 'US', 'US-AL', NULL, NULL) -- Franks Trucking Sole Anthony Ray Franks | frankstrucking251@gmail.com,
('PENDING_VERIFICATION', 'US', 'US-AL', NULL, NULL) -- FXPILOTCAR Michael Costido | FXPILOTCAR@OUTLOOK.COM,
('PENDING_VERIFICATION', 'US', 'US-AL', NULL, NULL) -- G.W. Trucking carriers Jayr | g.wtrucking1@yahoo.com,
('PENDING_VERIFICATION', 'US', 'US-AL', NULL, NULL) -- Ginger Arnold | awyldchyld@aol.com,
('PENDING_VERIFICATION', 'US', 'US-AL', NULL, NULL) -- Golden Pilot Car Service Dreama Dreama | dreamao94@gmail.com,
('PENDING_VERIFICATION', 'US', 'US-AL', NULL, NULL) -- Guardian Guides Pilot Service LLC Marvin Lark | guardianguidespcs@gmail.com,
('PENDING_VERIFICATION', 'US', 'US-AL', NULL, NULL) -- Hammer Lane Logistics Kristina Massey Kristna''s#: | 256-566-290322kriscoley@gmail.com,
('PENDING_VERIFICATION', 'US', 'US-AL', NULL, NULL) -- Hammer Lane Logistics Kristina Massey Kristna''s#: | 256-566-290322kriscoley@gmail.com,
('PENDING_VERIFICATION', 'US', 'US-AL', NULL, NULL) -- Immanuel PCS,LLC MICHAEL REMALA | mremala@yahoo.com,
('PENDING_VERIFICATION', 'US', 'US-AL', NULL, NULL) -- J and M Escort Michael walck | michael.walck@icloud.com,
('PENDING_VERIFICATION', 'US', 'US-AL', NULL, NULL) -- JDM&L Services LLC Jay Moulds | jaymoulds100@icloud.com,
('PENDING_VERIFICATION', 'US', 'US-AL', NULL, NULL) -- JW''s Pilot and Escort Car Services LLC Joycelyn Williams | Jwpilotcarsvc@gmail.com,
('PENDING_VERIFICATION', 'US', 'US-AL', NULL, NULL) -- Le Transport Service Hieu Le | hieule251@gmail.com,
('PENDING_VERIFICATION', 'US', 'US-AL', NULL, NULL) -- LTS Express Transport Pilot Car Services LLCLeonard Sewell | leonard.sewell33@gmail.com,
('PENDING_VERIFICATION', 'US', 'US-AL', NULL, NULL) -- M & E Lawn Services Medric Bullard | medricb@gmail.com,
('PENDING_VERIFICATION', 'US', 'US-AL', NULL, NULL) -- Latanya M. Jackson Maulk Pilot Escort Service | cinnamonred40@gmail.com,
('PENDING_VERIFICATION', 'US', 'US-AL', NULL, NULL) -- Mighty knight logistics, LLC Christopher Knight Johnson. | knightjohnsonc896@gmail.com,
('PENDING_VERIFICATION', 'US', 'US-AL', NULL, NULL) -- Monster Tick Pilot Car Rickey Hale | rhlamar400@gmail.com,
('PENDING_VERIFICATION', 'US', 'US-AL', NULL, NULL) -- P&L Pilot Car Services Patrice Peterson | escortdrivers9@gmail.com,
('PENDING_VERIFICATION', 'US', 'US-AL', NULL, NULL) -- PDL Trucking LLC Preston Lewis | pdltruckingllc@yahoo.com,
('PENDING_VERIFICATION', 'US', 'US-AL', NULL, NULL) -- QTRbacking Pilot Car Services LLC Joshua Harris | qtrbackingpcsllc@gmail.com,
('PENDING_VERIFICATION', 'US', 'US-AL', NULL, NULL) -- R & D Express Pilot car Robert J. Jones | robertj1622@gmail.com,
('PENDING_VERIFICATION', 'US', 'US-AL', NULL, NULL) -- R & J Martin Logistics LLC Rashaun Martin | randjmartinllc@gmail.com,
('PENDING_VERIFICATION', 'US', 'US-AL', NULL, NULL) -- Rottweiler Transportation Wendy J Hale | rottweilertransport@gmail.com,
('PENDING_VERIFICATION', 'US', 'US-AL', NULL, NULL) -- Rottweiler Transportation Wendy J Hale | rottweilertransport@gmail.com,
('PENDING_VERIFICATION', 'US', 'US-AL', NULL, NULL) -- Safeway Pilot Car Escort Services Lydell Moore | thesafepilotcar@gmail.com,
('PENDING_VERIFICATION', 'US', 'US-AL', NULL, NULL) -- Sherry''s Pilot Car Velon Brewer | SherryBrewer3413@outlook.com,
('PENDING_VERIFICATION', 'US', 'US-AL', NULL, NULL) -- Sherry''s Pilot Car Velon Brewer | SherryBrewer3413@outlook.com,
('PENDING_VERIFICATION', 'US', 'US-AL', NULL, NULL) -- Snells Pilot Car Services Kelwonn Carson | jcbumpers@gmail.com,
('PENDING_VERIFICATION', 'US', 'US-AL', NULL, NULL) -- Southern Charm Transport LLC Heather Knight | heatherschuelke@icloud.com,
('PENDING_VERIFICATION', 'US', 'US-AL', NULL, NULL) -- Thien Le Thien Lee | gixxer110@yahoo.com,
('PENDING_VERIFICATION', 'US', 'US-AL', NULL, NULL) -- Triple D Pilot Service LLC Deborah Leatherwood-Smith | tripledpilot@gmail.com,
('PENDING_VERIFICATION', 'US', 'US-AL', NULL, NULL) -- Vip Exclusive Pilot Car Service LLC Cortez Williams Sr | cwilliams@vipexclusivepilotcar.com,
('PENDING_VERIFICATION', 'US', 'US-AL', NULL, NULL) -- Wilson Pilot Service Becky Wilson | bwilson@wilsonpilotservice.com,
('PENDING_VERIFICATION', 'US', 'US-WV', NULL, NULL) -- Genesis Pilot Car Services Terrance Taylor | Genesispilotcarservices@gmail.com,
('PENDING_VERIFICATION', 'US', 'US-FL', NULL, NULL) -- Carsons Elite Transports LLC Reginald Carson | Reginaldcrsn@yahoo.com,
('PENDING_VERIFICATION', 'US', 'US-TN', NULL, NULL) -- AKN LOGISTICS LLC Anh Nguyen | anhn1990@icloud.com,
('PENDING_VERIFICATION', 'US', 'US-TX', NULL, NULL) -- Crump and son transport Christopher Crump | chriscrump5049@gmail.com,
('PENDING_VERIFICATION', 'US', 'US-AR', NULL, NULL) -- All-Around PCS LLC Brian Krumm | allaroundhwy65@gmail.com,
('PENDING_VERIFICATION', 'US', 'US-AR', NULL, NULL) -- AMC Pilot Cras Richard Lee Johnson | milesaheadpilotcarservice@gmail.com,
('PENDING_VERIFICATION', 'US', 'US-AR', NULL, NULL) -- 1 Arkansas Pilot Car Services Robert Adams | arkpcs@yahoo.com,
('PENDING_VERIFICATION', 'US', 'US-AR', NULL, NULL) -- Arkansas Pilot Escort Academy Chukwu Ochi | ifliorstetscortacademy@gmail.com,
('PENDING_VERIFICATION', 'US', 'US-AR', NULL, NULL) -- Arkansas Pilot Escort Academy Chukwu Ochi | ifliorstetscortacademy@gmail.com,
('PENDING_VERIFICATION', 'US', 'US-AR', NULL, NULL) -- C.U. Tamara Pilot Cars L.L.C. Randy Vest | rheath823054@gmail.com,
('PENDING_VERIFICATION', 'US', 'US-AR', NULL, NULL) -- CJones Customz LLC Bobby givens | bobby.givens70@gmail.com,
('PENDING_VERIFICATION', 'US', 'US-AR', NULL, NULL) -- Crossroads Pilot Services LLC Bobby | crossroadspilot24@gmail.com,
('PENDING_VERIFICATION', 'US', 'US-AR', NULL, NULL) -- Crossroads Pilot Services LLC Bobby | crossroadspilot24@gmail.com,
('PENDING_VERIFICATION', 'US', 'US-AR', NULL, NULL) -- F & M Pilot Car Mary Pohjola | mpohjola1002@hotmail.com,
('PENDING_VERIFICATION', 'US', 'US-AR', NULL, NULL) -- GMA Pilot Truck Service Gary Muth | gmuth4454@gmail.com,
('PENDING_VERIFICATION', 'US', 'US-AR', NULL, NULL) -- International PCS Seif (call him Steve) | internationalpilotservice@gmail.com,
('PENDING_VERIFICATION', 'US', 'US-AR', NULL, NULL) -- Jack''s Pilot Car Services Jack V. Holt | jvholt63@gmail.com,
('PENDING_VERIFICATION', 'US', 'US-AR', NULL, NULL) -- Miles Ahead Pilot Car LLC Saloam Huggins | pilotgirl.s87@gmail.com,
('PENDING_VERIFICATION', 'US', 'US-AR', NULL, NULL) -- Monroe Top Gear Pilot Car Service Amanda Mouawad | monroetopgear@gmail.com,
('PENDING_VERIFICATION', 'US', 'US-AR', NULL, NULL) -- R & R Pilot Service Randy Farmer | randyfarmer48@yahoo.com,
('PENDING_VERIFICATION', 'US', 'US-AR', NULL, NULL) -- Rottweilers Farms Inc David Harrison | harrison@arbbs.net,
('PENDING_VERIFICATION', 'US', 'US-AR', NULL, NULL) -- Todd’s Pilot Car Service Todd E. Neeper | Tneeper12@gmail.com,
('PENDING_VERIFICATION', 'US', 'US-AR', NULL, NULL) -- Truckerette Pilot Car, LLC Brenda Vannoy | truckerettebrenda@gmail.com,
('PENDING_VERIFICATION', 'US', 'US-AR', NULL, NULL) -- Tyson PCS Spencer Tyson Spencer: | tytftk@gmail.com,
('PENDING_VERIFICATION', 'US', 'US-AR', NULL, NULL) -- Tyson PCS Spencer Tyson Spencer: | tytftk@gmail.com,
('PENDING_VERIFICATION', 'US', 'US-AR', NULL, NULL) -- Worldwide Pilot Escort Services Solomon Emmanuel Miles | Solomon.miles25@yahoo.com,
('PENDING_VERIFICATION', 'US', 'US-CO', NULL, NULL) -- Landy PCS Lacey Anderson | landerson86.la@gmail.com,
('PENDING_VERIFICATION', 'US', 'US-MI', NULL, NULL) -- 612 Enterprise Inc Trent Eriksen/ William (bill) | tseriksen@msn.com,
('PENDING_VERIFICATION', 'US', 'US-KS', NULL, NULL) -- Shannon Johnson Richie Johnson | richiebanksggm@gmail.com,
('PENDING_VERIFICATION', 'US', 'US-WA', NULL, NULL) -- Safe Guard Escort LLC christopher morgan | safeguardescortllc@gmail.com,
('PENDING_VERIFICATION', 'US', 'US-AZ', NULL, NULL) -- Alfredo Garrido Alfredo Garrido | sgarrido@bigalspilotcarservice.com,
('PENDING_VERIFICATION', 'US', 'US-AZ', NULL, NULL) -- American Pilot Car LLC Jay Jeffries | americanpilotcar2023@gmail.com,
('PENDING_VERIFICATION', 'US', 'US-AZ', NULL, NULL) -- Back of the Moon LLC Kelly Collins | backofthemoonescort@gmail.com,
('PENDING_VERIFICATION', 'US', 'US-AZ', NULL, NULL) -- BSS Pilot car services Brian Schmitt | bsspcs0714@gmail.com,
('PENDING_VERIFICATION', 'US', 'US-AZ', NULL, NULL) -- Chance Westley Tuttle Chance Westley Tuttle | bozobuy@gmail.com,
('PENDING_VERIFICATION', 'US', 'US-AZ', NULL, NULL) -- Flying John’s PCS John Heakins | johnheakins@icloud.com,
('PENDING_VERIFICATION', 'US', 'US-AZ', NULL, NULL) -- John Heakins John Heakins | johnheakins@icloud.com,
('PENDING_VERIFICATION', 'US', 'US-AZ', NULL, NULL) -- John Siler Siler Ranch Pilot Service LLC | T1maddog@yahoo.com,
('PENDING_VERIFICATION', 'US', 'US-AZ', NULL, NULL) -- Run 4 Ur Money Transport LLC Derek Davis | r4umt2019@gmail.com,
('PENDING_VERIFICATION', 'US', 'US-AZ', NULL, NULL) -- Scott M. Allred Scott M. Allreo | scott68allred@gmail.com,
('PENDING_VERIFICATION', 'US', 'US-AZ', NULL, NULL) -- Siler Ranch Pilot Service Nancy Siler | sizlinhot@gmail.com,
('PENDING_VERIFICATION', 'US', 'US-AZ', NULL, NULL) -- Skyler Feigel Skylar Feigel | skybluepilotcars@gmail.com,
('PENDING_VERIFICATION', 'US', 'US-AZ', NULL, NULL) -- Stone temple pilot cars Edward M. Crooke | emcinaz50@icloud.com,
('PENDING_VERIFICATION', 'US', 'US-AZ', NULL, NULL) -- Suazo Escort Services Juan Suazo | Juansuazo101010@gmail.com,
('PENDING_VERIFICATION', 'US', 'US-AZ', NULL, NULL) -- Valkyrie Escort LLC Dallas Stephan | dstephan@valkyrieescort.com,
('PENDING_VERIFICATION', 'US', 'US-AZ', NULL, NULL) -- West Valley Pilot Car Service Richard Stuart | Stuarts777@yahoo.com,
('PENDING_VERIFICATION', 'US', 'US-NM', NULL, NULL) -- ASAP Services Jose Navaro | tms.llc.az@gmail.com,
('PENDING_VERIFICATION', 'US', 'US-MO', NULL, NULL) -- Timber Pilot Cars. LLC Tim Burrage | timburpilots@gmail.com,
('PENDING_VERIFICATION', 'US', 'US-NM', NULL, NULL) -- John Forrey John Forrey | Spiritswest1@hotmail.com,
('PENDING_VERIFICATION', 'US', 'US-CA', NULL, NULL) -- DD Elite Escort Ezekiel Yasharahla (Zeke) | doubledelite24@gmail.com,
('PENDING_VERIFICATION', 'US', 'US-CA', NULL, NULL) -- 1Family pilot escort Walter (Chuck) Bittick | Familytransport22@gmail.com,
('PENDING_VERIFICATION', 'US', 'US-CA', NULL, NULL) -- 2 brothers PCS Matt Zamiska | matt_zamiska@yahoo.com,
('PENDING_VERIFICATION', 'US', 'US-CA', NULL, NULL) -- 33 Signs USA Inc Richard Logan | richardlogan0728@gmail.com,
('PENDING_VERIFICATION', 'US', 'US-CA', NULL, NULL) -- 1195 Pilot Car Service Rod Rifredi | rod@1195pilotcarservice.com,
('PENDING_VERIFICATION', 'US', 'US-CA', NULL, NULL) -- Anytime Pilot Car Service David C. Ritchey | anytimepilotcarservice@gmail.com,
('PENDING_VERIFICATION', 'US', 'US-CA', NULL, NULL) -- B And K Pilot Car Service Bret A. Killingsworth | bakpilotcarservice@gmail.com,
('PENDING_VERIFICATION', 'US', 'US-CA', NULL, NULL) -- Barrons pilot car services Scottie barron | scottybarron09@gmail.com,
('PENDING_VERIFICATION', 'US', 'US-CA', NULL, NULL) -- Bradley pilot car services Cecil Bradley | cecilbradley97@gmail.com,
('PENDING_VERIFICATION', 'US', 'US-CA', NULL, NULL) -- Bradleys pilot car services Cecil | cecilbradley97@gmail.com,
('PENDING_VERIFICATION', 'US', 'US-CA', NULL, NULL) -- Brent Higham Pilot Car Services Brent Higham | bhpilotcarservices@gmail.com,
('PENDING_VERIFICATION', 'US', 'US-CA', NULL, NULL) -- Capernaum Heavy Haul Trucking Jesenia Andrade | capernaumheavyhaul@gmail.com,
('PENDING_VERIFICATION', 'US', 'US-CA', NULL, NULL) -- Chase''s Pilot Vehicle LLC. Adam Chase | chasechaos909@gmail.com,
('PENDING_VERIFICATION', 'US', 'US-CA', NULL, NULL) -- Danmhar Pilot Service Danial Anthony Gilliland | danmharpilot@yahoo.com,
('PENDING_VERIFICATION', 'US', 'US-CA', NULL, NULL) -- Del Real Heavy haul LLC Florentino Del real | tinodelreal@gmail.com,
('PENDING_VERIFICATION', 'US', 'US-CA', NULL, NULL) -- La Huerta Transport Armando Al | al.armando@rocketmail.com,
('PENDING_VERIFICATION', 'US', 'US-CA', NULL, NULL) -- Lighthouse Pilot Car Russell & Maria Wells | wellsrussell1017@gmail.com,
('PENDING_VERIFICATION', 'US', 'US-CA', NULL, NULL) -- Madames Pilot Cars LLC Miriam Jackson | Empressqt67@gmail.com,
('PENDING_VERIFICATION', 'US', 'US-CA', NULL, NULL) -- Mike''s Anywhere Pilot Car Michael Abara | michaelabara111@gmail.com,
('PENDING_VERIFICATION', 'US', 'US-CA', NULL, NULL) -- Neil''s Pilot Car Escort Services Neil Scroy | rns.pevo@gmail.com,
('PENDING_VERIFICATION', 'US', 'US-CA', NULL, NULL) -- Neil''s Pilot Car Escort Services Neil Scroy | rns.pevo@gmail.com,
('PENDING_VERIFICATION', 'US', 'US-CA', NULL, NULL) -- PANTHER PILOT CAR Aiken | pantherpilotcat@hotmail.com,
('PENDING_VERIFICATION', 'US', 'US-CA', NULL, NULL) -- Paul''s Pilot C.S Paul Syrbu | psyrbu@gmail.com,
('PENDING_VERIFICATION', 'US', 'US-CA', NULL, NULL) -- Pirch Pilot Car Service Andrey Pirch | pirchandrey@yahoo.com,
('PENDING_VERIFICATION', 'US', 'US-CA', NULL, NULL) -- R and F Pilot Car Services LLC Opal Weaver | randfpilot@gmail.com,
('PENDING_VERIFICATION', 'US', 'US-CA', NULL, NULL) -- Reliant Pilot Car LLC Krystal McManus | reliantpilotcar@gmail.com,
('PENDING_VERIFICATION', 'US', 'US-CA', NULL, NULL) -- Roach PCS Steve R. Roach | roachpilotcar@gmail.com,
('PENDING_VERIFICATION', 'US', 'US-CA', NULL, NULL) -- Road Dog Services LLC Rob Solis | robert@rdspilotcars.com,
('PENDING_VERIFICATION', 'US', 'US-CA', NULL, NULL) -- Scottie B. Barron Scottie Barron | scottybarron09@gmail.com,
('PENDING_VERIFICATION', 'US', 'US-CA', NULL, NULL) -- Sunrise Pilot Car Service Tina M. Hulburt | tina.hulburt@gmail.com,
('PENDING_VERIFICATION', 'US', 'US-CA', NULL, NULL) -- Svetlana Vaculchik Svetlana Mikhaylovna | svakulchik68@gmail.com,
('PENDING_VERIFICATION', 'US', 'US-CA', NULL, NULL) -- Terry''s Pilot Car Service Terence T. Witt | witttrans@sbcglobal.net,
('PENDING_VERIFICATION', 'US', 'US-CA', NULL, NULL) -- Terry’s Pilot Cars Terry Hardesty | terryspilotcars@gmail.com,
('PENDING_VERIFICATION', 'US', 'US-CA', NULL, NULL) -- Yogie Enterprises LLC Ronald C Johnson | yogieenterprises@gmail.com,
('PENDING_VERIFICATION', 'US', 'US-CA', NULL, NULL) -- Yogie Enterprises LLC Ronald C Johnson | yogieenterprises@gmail.com,
('PENDING_VERIFICATION', 'US', 'US-CA', NULL, NULL) -- 2 Zephyr Pilot, LLC. ANGLEA CHAIN | zephyrpilot@yahoo.com;