import { scoreLinkableAsset } from "@/lib/growth/link-pr-share-engine";

export type LinkableAssetStatus = "draft" | "source_review" | "active";
export type LinkableAssetIndexability = "index" | "noindex";
export type LinkableAssetMediaStatus = "planned" | "ready" | "blocked";

export type LinkableAssetRecord = {
  slug: string;
  title: string;
  summary: string;
  assetType: "map" | "guide" | "checklist" | "calendar" | "directory" | "visual" | "matrix" | "safety";
  status: LinkableAssetStatus;
  indexabilityStatus: LinkableAssetIndexability;
  sourceSurfaceType: "regulation" | "directory" | "training" | "corridor" | "safety" | "market_intelligence";
  countryCodes: string[];
  roleKeys: string[];
  corridorKeys: string[];
  topicTags: string[];
  methodologyNote: string;
  sourceUrls: string[];
  sourceConfidence: number;
  dataAsOf: string;
  refreshCadence: string;
  media: {
    downloadableImage: LinkableAssetMediaStatus;
    shortVideo: LinkableAssetMediaStatus;
    youtubeVideo: LinkableAssetMediaStatus;
    embedCode: LinkableAssetMediaStatus;
    faq: LinkableAssetMediaStatus;
    quoteSheet: LinkableAssetMediaStatus;
  };
  journalistPitchAngle: string;
  podcastTalkingPoints: string[];
  relatedRoutes: string[];
};

const SOURCE_REVIEW_NOTE =
  "This asset is staged for source review. It should remain noindexed until official sources, methodology, and update cadence are verified.";

export const linkableAssetRegistry: LinkableAssetRecord[] = [
  {
    slug: "120-country-oversize-transport-authority-map",
    title: "120-Country Oversize Transport Authority Map",
    summary: "A country-by-country map of official permit, abnormal-load, oversize, and heavy-transport authority surfaces.",
    assetType: "map",
    status: "source_review",
    indexabilityStatus: "noindex",
    sourceSurfaceType: "regulation",
    countryCodes: [],
    roleKeys: ["broker", "carrier", "permit_service", "pilot_car_operator"],
    corridorKeys: [],
    topicTags: ["authorities", "permits", "global"],
    methodologyNote: SOURCE_REVIEW_NOTE,
    sourceUrls: [],
    sourceConfidence: 45,
    dataAsOf: "2026-05-20",
    refreshCadence: "Quarterly source review after launch",
    media: {
      downloadableImage: "planned",
      shortVideo: "planned",
      youtubeVideo: "planned",
      embedCode: "planned",
      faq: "planned",
      quoteSheet: "planned",
    },
    journalistPitchAngle: "Why oversize-load authority discovery is fragmented across countries and agencies.",
    podcastTalkingPoints: [
      "How carriers currently find permit authorities",
      "Why country-specific terms matter in abnormal-load research",
      "What needs source review before publishing authority maps",
    ],
    relatedRoutes: ["/escort-requirements", "/directory", "/data-products"],
  },
  {
    slug: "pilot-car-escort-vehicle-terminology-by-country",
    title: "Pilot Car and Escort Vehicle Terminology by Country",
    summary: "A terminology crosswalk for pilot car, escort vehicle, abnormal load escort, and related role names across markets.",
    assetType: "guide",
    status: "source_review",
    indexabilityStatus: "noindex",
    sourceSurfaceType: "training",
    countryCodes: [],
    roleKeys: ["pilot_car_operator", "escort_driver", "trainer"],
    corridorKeys: [],
    topicTags: ["terminology", "localization", "training"],
    methodologyNote: SOURCE_REVIEW_NOTE,
    sourceUrls: [],
    sourceConfidence: 50,
    dataAsOf: "2026-05-20",
    refreshCadence: "Quarterly localization review",
    media: {
      downloadableImage: "planned",
      shortVideo: "planned",
      youtubeVideo: "planned",
      embedCode: "planned",
      faq: "planned",
      quoteSheet: "planned",
    },
    journalistPitchAngle: "How the same heavy-haul support job is described differently by country and regulator.",
    podcastTalkingPoints: [
      "Why U.S.-only pilot car language does not translate cleanly",
      "How terminology affects search and compliance",
      "Where operator education needs local wording",
    ],
    relatedRoutes: ["/glossary", "/training", "/directory"],
  },
  {
    slug: "high-pole-visual-guide",
    title: "High Pole Visual Guide",
    summary: "A plain-language visual explaining high-pole escort positioning, clearance checks, and why route context matters.",
    assetType: "visual",
    status: "source_review",
    indexabilityStatus: "noindex",
    sourceSurfaceType: "safety",
    countryCodes: ["US", "CA"],
    roleKeys: ["high_pole_operator", "pilot_car_operator", "broker"],
    corridorKeys: [],
    topicTags: ["high-pole", "clearance", "safety"],
    methodologyNote: SOURCE_REVIEW_NOTE,
    sourceUrls: [],
    sourceConfidence: 55,
    dataAsOf: "2026-05-20",
    refreshCadence: "Semiannual safety review",
    media: {
      downloadableImage: "planned",
      shortVideo: "planned",
      youtubeVideo: "planned",
      embedCode: "planned",
      faq: "planned",
      quoteSheet: "planned",
    },
    journalistPitchAngle: "Why high-pole work is a safety layer, not a decorative escort add-on.",
    podcastTalkingPoints: [
      "What a high-pole car is intended to prevent",
      "Why clearance confidence depends on route context",
      "How operators and brokers talk about high-pole readiness",
    ],
    relatedRoutes: ["/training", "/directory", "/escort-requirements"],
  },
  {
    slug: "pilot-car-equipment-checklist",
    title: "Pilot Car Equipment Checklist Graphic",
    summary: "A role-aware checklist template for signs, flags, lighting, radios, safety equipment, and documentation review.",
    assetType: "checklist",
    status: "source_review",
    indexabilityStatus: "noindex",
    sourceSurfaceType: "training",
    countryCodes: ["US", "CA", "AU"],
    roleKeys: ["pilot_car_operator", "escort_driver", "trainer", "equipment_supplier"],
    corridorKeys: [],
    topicTags: ["equipment", "readiness", "training"],
    methodologyNote: SOURCE_REVIEW_NOTE,
    sourceUrls: [],
    sourceConfidence: 52,
    dataAsOf: "2026-05-20",
    refreshCadence: "Semiannual role and jurisdiction review",
    media: {
      downloadableImage: "planned",
      shortVideo: "planned",
      youtubeVideo: "planned",
      embedCode: "planned",
      faq: "planned",
      quoteSheet: "planned",
    },
    journalistPitchAngle: "What equipment turns a vehicle from a car into a work-ready escort unit.",
    podcastTalkingPoints: [
      "Which equipment categories show up repeatedly",
      "Why checklists need country and state filters",
      "How readiness checklists can feed operator profiles",
    ],
    relatedRoutes: ["/training", "/tools", "/directory"],
  },
  {
    slug: "escort-requirement-threshold-explorer",
    title: "Escort Requirement Threshold Explorer",
    summary: "A structured explainer for how escort thresholds can vary by jurisdiction, dimension, route, and load condition.",
    assetType: "guide",
    status: "source_review",
    indexabilityStatus: "noindex",
    sourceSurfaceType: "regulation",
    countryCodes: [],
    roleKeys: ["broker", "carrier", "permit_service", "pilot_car_operator"],
    corridorKeys: [],
    topicTags: ["requirements", "thresholds", "permits"],
    methodologyNote: SOURCE_REVIEW_NOTE,
    sourceUrls: [],
    sourceConfidence: 45,
    dataAsOf: "2026-05-20",
    refreshCadence: "Quarterly source review",
    media: {
      downloadableImage: "planned",
      shortVideo: "planned",
      youtubeVideo: "planned",
      embedCode: "planned",
      faq: "planned",
      quoteSheet: "planned",
    },
    journalistPitchAngle: "Why escort requirements are not a single national rule and need source-backed context.",
    podcastTalkingPoints: [
      "Why dimension thresholds are only part of the decision",
      "How route and permit terms change escort planning",
      "Why Haul Command should show source confidence",
    ],
    relatedRoutes: ["/escort-requirements", "/tools", "/data-products"],
  },
  {
    slug: "heavy-haul-corridor-demand-map",
    title: "Heavy Haul Corridor Demand Map",
    summary: "A future corridor snapshot format for showing where heavy-haul support demand is visible from platform activity.",
    assetType: "map",
    status: "draft",
    indexabilityStatus: "noindex",
    sourceSurfaceType: "corridor",
    countryCodes: [],
    roleKeys: ["broker", "carrier", "pilot_car_operator", "advertiser"],
    corridorKeys: [],
    topicTags: ["corridors", "demand", "market-intelligence"],
    methodologyNote: "This page is a format scaffold only. It must not cite demand, scarcity, or trend values until aggregated platform data is live and privacy-reviewed.",
    sourceUrls: [],
    sourceConfidence: 25,
    dataAsOf: "2026-05-20",
    refreshCadence: "Monthly after data product launch",
    media: {
      downloadableImage: "planned",
      shortVideo: "planned",
      youtubeVideo: "planned",
      embedCode: "planned",
      faq: "planned",
      quoteSheet: "planned",
    },
    journalistPitchAngle: "How corridor-level support gaps could become a market-intelligence product when backed by aggregated activity.",
    podcastTalkingPoints: [
      "Why corridor context matters more than generic national supply",
      "How to avoid overstating early market signals",
      "What a privacy-safe corridor snapshot should include",
    ],
    relatedRoutes: ["/corridors", "/data-products", "/directory"],
  },
  {
    slug: "pilot-car-shortage-index",
    title: "Pilot Car Shortage Index",
    summary: "A planned index format for comparing operator supply signals against broker and carrier demand by geography.",
    assetType: "matrix",
    status: "draft",
    indexabilityStatus: "noindex",
    sourceSurfaceType: "market_intelligence",
    countryCodes: [],
    roleKeys: ["pilot_car_operator", "broker", "carrier", "advertiser"],
    corridorKeys: [],
    topicTags: ["scarcity", "supply", "demand"],
    methodologyNote: "This is an index scaffold. It requires aggregated platform demand, profile density, privacy thresholds, and source notes before publication.",
    sourceUrls: [],
    sourceConfidence: 20,
    dataAsOf: "2026-05-20",
    refreshCadence: "Monthly after telemetry coverage is sufficient",
    media: {
      downloadableImage: "planned",
      shortVideo: "planned",
      youtubeVideo: "planned",
      embedCode: "planned",
      faq: "planned",
      quoteSheet: "planned",
    },
    journalistPitchAngle: "What a responsible shortage index would need before claiming operator gaps.",
    podcastTalkingPoints: [
      "Why shortage claims need privacy thresholds",
      "How searches, claims, and load posts can become derived signals",
      "Why early indexes should show confidence and caveats",
    ],
    relatedRoutes: ["/data-products", "/directory", "/claim"],
  },
  {
    slug: "route-survey-checklist",
    title: "Route Survey Checklist",
    summary: "A route-survey planning checklist for clearance, turns, bridges, restrictions, documentation, and broker handoff review.",
    assetType: "checklist",
    status: "source_review",
    indexabilityStatus: "noindex",
    sourceSurfaceType: "training",
    countryCodes: [],
    roleKeys: ["route_surveyor", "broker", "carrier", "permit_service"],
    corridorKeys: [],
    topicTags: ["route-survey", "planning", "permits"],
    methodologyNote: SOURCE_REVIEW_NOTE,
    sourceUrls: [],
    sourceConfidence: 48,
    dataAsOf: "2026-05-20",
    refreshCadence: "Semiannual role review",
    media: {
      downloadableImage: "planned",
      shortVideo: "planned",
      youtubeVideo: "planned",
      embedCode: "planned",
      faq: "planned",
      quoteSheet: "planned",
    },
    journalistPitchAngle: "Why a route survey is a planning product, not just a drive-through.",
    podcastTalkingPoints: [
      "What route surveyors need to document",
      "How survey outputs affect permit and broker decisions",
      "Why checklists should be tied to profile trust",
    ],
    relatedRoutes: ["/training", "/tools", "/directory"],
  },
  {
    slug: "oversize-friendly-staging-yard-map",
    title: "Oversize-Friendly Staging Yard Map",
    summary: "A planned map format for yards, secure parking, and staging locations that can support oversize moves.",
    assetType: "map",
    status: "draft",
    indexabilityStatus: "noindex",
    sourceSurfaceType: "directory",
    countryCodes: [],
    roleKeys: ["yard_owner", "carrier", "broker", "dispatcher"],
    corridorKeys: [],
    topicTags: ["yards", "staging", "infrastructure"],
    methodologyNote: "This map must remain noindexed until locations are verified, permissioned, and categorized without exposing private or sensitive infrastructure details.",
    sourceUrls: [],
    sourceConfidence: 20,
    dataAsOf: "2026-05-20",
    refreshCadence: "Monthly after partner verification workflow is live",
    media: {
      downloadableImage: "planned",
      shortVideo: "planned",
      youtubeVideo: "planned",
      embedCode: "planned",
      faq: "planned",
      quoteSheet: "planned",
    },
    journalistPitchAngle: "Why staging is a hidden infrastructure layer behind project-cargo moves.",
    podcastTalkingPoints: [
      "What makes a staging location useful for oversize loads",
      "Why public maps need permission and safety review",
      "How staging-yard partners fit the heavy-haul graph",
    ],
    relatedRoutes: ["/directory", "/corridors", "/data-products"],
  },
  {
    slug: "holiday-movement-restriction-calendar",
    title: "Oversize Movement Holiday Restriction Calendar",
    summary: "A calendar format for jurisdiction-specific holiday, weekend, curfew, and seasonal movement restriction research.",
    assetType: "calendar",
    status: "source_review",
    indexabilityStatus: "noindex",
    sourceSurfaceType: "regulation",
    countryCodes: [],
    roleKeys: ["broker", "carrier", "permit_service", "dispatcher"],
    corridorKeys: [],
    topicTags: ["restrictions", "calendar", "permits"],
    methodologyNote: SOURCE_REVIEW_NOTE,
    sourceUrls: [],
    sourceConfidence: 45,
    dataAsOf: "2026-05-20",
    refreshCadence: "Annual calendar review plus jurisdiction updates",
    media: {
      downloadableImage: "planned",
      shortVideo: "planned",
      youtubeVideo: "planned",
      embedCode: "planned",
      faq: "planned",
      quoteSheet: "planned",
    },
    journalistPitchAngle: "How public holidays and curfews can affect oversize-load routing and scheduling.",
    podcastTalkingPoints: [
      "Why movement windows are operationally expensive",
      "How calendars should cite official sources",
      "Why brokers need route and date context together",
    ],
    relatedRoutes: ["/escort-requirements", "/tools", "/data-products"],
  },
  {
    slug: "country-permit-authority-directory",
    title: "Country Permit Authority Directory",
    summary: "A directory scaffold for official permit authorities and abnormal-load guidance pages by country and region.",
    assetType: "directory",
    status: "source_review",
    indexabilityStatus: "noindex",
    sourceSurfaceType: "regulation",
    countryCodes: [],
    roleKeys: ["permit_service", "broker", "carrier"],
    corridorKeys: [],
    topicTags: ["permit-authorities", "country", "source-list"],
    methodologyNote: SOURCE_REVIEW_NOTE,
    sourceUrls: [],
    sourceConfidence: 45,
    dataAsOf: "2026-05-20",
    refreshCadence: "Quarterly source review",
    media: {
      downloadableImage: "planned",
      shortVideo: "planned",
      youtubeVideo: "planned",
      embedCode: "planned",
      faq: "planned",
      quoteSheet: "planned",
    },
    journalistPitchAngle: "Why permit authority discovery is one of the first data gaps in cross-border heavy haul.",
    podcastTalkingPoints: [
      "How permit services use source directories",
      "Why country and province/state coverage should be explicit",
      "What changes when source links go stale",
    ],
    relatedRoutes: ["/escort-requirements", "/directory", "/data-products"],
  },
  {
    slug: "heavy-haul-support-stack-visuals",
    title: "Heavy Haul Support Stack Visuals by Load Type",
    summary: "A visual guide to the roles that may surround oversize, superload, wind, industrial, and project-cargo moves.",
    assetType: "visual",
    status: "source_review",
    indexabilityStatus: "noindex",
    sourceSurfaceType: "directory",
    countryCodes: [],
    roleKeys: ["broker", "carrier", "pilot_car_operator", "route_surveyor", "permit_service"],
    corridorKeys: [],
    topicTags: ["roles", "load-types", "support-stack"],
    methodologyNote: SOURCE_REVIEW_NOTE,
    sourceUrls: [],
    sourceConfidence: 50,
    dataAsOf: "2026-05-20",
    refreshCadence: "Semiannual taxonomy review",
    media: {
      downloadableImage: "planned",
      shortVideo: "planned",
      youtubeVideo: "planned",
      embedCode: "planned",
      faq: "planned",
      quoteSheet: "planned",
    },
    journalistPitchAngle: "The hidden support network behind a single oversize load.",
    podcastTalkingPoints: [
      "Why a move is more than a truck and trailer",
      "How role maps help buyers understand who to hire",
      "Why the directory needs role-specific surfaces",
    ],
    relatedRoutes: ["/directory", "/data-products", "/training"],
  },
  {
    slug: "operator-report-card-explainer",
    title: "Operator Report Card Explainer",
    summary: "A public explanation of profile completeness, insurance readiness, credentials, service coverage, and trust signals.",
    assetType: "guide",
    status: "source_review",
    indexabilityStatus: "noindex",
    sourceSurfaceType: "directory",
    countryCodes: [],
    roleKeys: ["pilot_car_operator", "broker", "carrier", "insurance_partner"],
    corridorKeys: [],
    topicTags: ["profiles", "trust", "readiness"],
    methodologyNote: "This explainer can publish only after each displayed badge has a truthful source, verification status, and user-facing caveat.",
    sourceUrls: [],
    sourceConfidence: 40,
    dataAsOf: "2026-05-20",
    refreshCadence: "Quarterly trust-signal review",
    media: {
      downloadableImage: "planned",
      shortVideo: "planned",
      youtubeVideo: "planned",
      embedCode: "planned",
      faq: "planned",
      quoteSheet: "planned",
    },
    journalistPitchAngle: "Why brokers need more than a name and phone number when hiring support.",
    podcastTalkingPoints: [
      "What belongs in an operator readiness profile",
      "Why verification language must be precise",
      "How report cards can reduce broker uncertainty",
    ],
    relatedRoutes: ["/claim", "/directory", "/data-products"],
  },
  {
    slug: "training-to-readiness-matrix",
    title: "Training-to-Readiness Matrix",
    summary: "A matrix that maps training, credentials, insurance, equipment, and profile completeness into job-readiness milestones.",
    assetType: "matrix",
    status: "source_review",
    indexabilityStatus: "noindex",
    sourceSurfaceType: "training",
    countryCodes: [],
    roleKeys: ["pilot_car_operator", "trainer", "broker", "insurance_partner"],
    corridorKeys: [],
    topicTags: ["training", "credentials", "readiness"],
    methodologyNote: SOURCE_REVIEW_NOTE,
    sourceUrls: [],
    sourceConfidence: 48,
    dataAsOf: "2026-05-20",
    refreshCadence: "Quarterly training review",
    media: {
      downloadableImage: "planned",
      shortVideo: "planned",
      youtubeVideo: "planned",
      embedCode: "planned",
      faq: "planned",
      quoteSheet: "planned",
    },
    journalistPitchAngle: "How operators move from interest to work-ready status without relying on guesswork.",
    podcastTalkingPoints: [
      "Why training alone is not the whole readiness picture",
      "How insurance and equipment fit the job-readiness path",
      "Why readiness should be visible to brokers",
    ],
    relatedRoutes: ["/training", "/claim", "/directory"],
  },
  {
    slug: "public-safety-driving-near-oversize-loads",
    title: "Public Safety: How to Drive Near Oversize Loads",
    summary: "A public safety explainer for drivers approaching pilot cars, escort vehicles, wide turns, and oversize-load convoys.",
    assetType: "safety",
    status: "source_review",
    indexabilityStatus: "noindex",
    sourceSurfaceType: "safety",
    countryCodes: [],
    roleKeys: ["public_safety", "pilot_car_operator", "carrier", "trainer"],
    corridorKeys: [],
    topicTags: ["public-safety", "oversize-loads", "convoys"],
    methodologyNote: SOURCE_REVIEW_NOTE,
    sourceUrls: [],
    sourceConfidence: 50,
    dataAsOf: "2026-05-20",
    refreshCadence: "Annual safety review",
    media: {
      downloadableImage: "planned",
      shortVideo: "planned",
      youtubeVideo: "planned",
      embedCode: "planned",
      faq: "planned",
      quoteSheet: "planned",
    },
    journalistPitchAngle: "What ordinary drivers should know when they see amber lights and an oversize load.",
    podcastTalkingPoints: [
      "Why public safety content can be sponsored without becoming spam",
      "How escort vehicles communicate risk to the public",
      "What should be source-reviewed before publishing safety claims",
    ],
    relatedRoutes: ["/training", "/escort-requirements", "/directory"],
  },
];

export function getLinkableAssets(): LinkableAssetRecord[] {
  return linkableAssetRegistry;
}

export function getLinkableAssetBySlug(slug: string): LinkableAssetRecord | undefined {
  return linkableAssetRegistry.find((asset) => asset.slug === slug);
}

export function getLinkableAssetScore(asset: LinkableAssetRecord) {
  return scoreLinkableAsset({
    sourceConfidence: asset.sourceConfidence,
    sourceUrlCount: asset.sourceUrls.length,
    hasMethodology: asset.methodologyNote.trim().length > 0,
    hasDownloadableImage: asset.media.downloadableImage === "ready",
    hasShortVideo: asset.media.shortVideo === "ready",
    hasYoutubeVideo: asset.media.youtubeVideo === "ready",
    hasEmbedCode: asset.media.embedCode === "ready",
    hasShareButton: true,
    hasFaq: asset.media.faq === "ready",
    hasQuoteSheet: asset.media.quoteSheet === "ready",
    countrySpecific: asset.countryCodes.length > 0,
    roleSpecific: asset.roleKeys.length > 0,
    corridorSpecific: asset.corridorKeys.length > 0,
    journalistPitchAngle: asset.journalistPitchAngle,
    podcastTalkingPointCount: asset.podcastTalkingPoints.length,
  });
}

export function canIndexLinkableAsset(asset: LinkableAssetRecord): boolean {
  const score = getLinkableAssetScore(asset);
  return asset.status === "active" && asset.indexabilityStatus === "index" && score.publishable;
}
