/**
 * POST /api/operators/rate-card
 * Rate Card PDF Generator API — Revenue Leak #8
 * Generates professional rate card HTML (convertible to PDF).
 * Free: Basic card (with HC branding). Pro ($99/mo): No branding, QR code.
 */
export const dynamic = 'force-dynamic';

import { NextRequest, NextResponse } from 'next/server';
import { generateRateCardHTML, buildRateCardFromProfile } from '@/core/revenue/RateCardGenerator';
import { getSupabaseAdmin } from '@/lib/supabase/admin';

export async function POST(req: NextRequest) {
  try {
    const body = await req.json();
    const { operatorId, format } = body;

    if (!operatorId) {
      return NextResponse.json({ error: 'operatorId is required' }, { status: 400 });
    }

    const db = getSupabaseAdmin();

    // Fetch operator profile
    const { data: profile, error } = await db
      .from('directory_listings')
      .select('*')
      .eq('id', operatorId)
      .single();

    if (error || !profile) {
      return NextResponse.json({ error: 'Operator not found' }, { status: 404 });
    }

    const rateCardData = buildRateCardFromProfile({
      name: profile.name,
      company_name: profile.metadata?.company_name,
      phone: profile.metadata?.phone || '',
      email: profile.metadata?.email || '',
      website: profile.metadata?.website,
      region_code: profile.region_code,
      rates: profile.metadata?.rates || [
        { corridor: 'General', service_type: 'Pilot Car', rate_type: 'hourly', rate: profile.metadata?.hourly_rate || 85 },
      ],
      certifications: profile.metadata?.certifications || [],
      insurance_amount: profile.metadata?.insurance_amount || 'Verified',
      response_guarantee: profile.metadata?.response_guarantee,
      escrow_enabled: profile.metadata?.escrow_enabled || false,
      av_certified: profile.metadata?.av_certified || false,
      subscription_tier: profile.metadata?.subscription_tier || 'basic',
    });

    const html = generateRateCardHTML(rateCardData);

    if (format === 'html') {
      return new NextResponse(html, {
        headers: {
          'Content-Type': 'text/html',
          'Cache-Control': 'private, max-age=300',
        },
      });
    }

    // Return JSON data (frontend can render or send to PDF service)
    return NextResponse.json({
      rateCard: rateCardData,
      html,
      pdfUrl: null, // Would be generated by a PDF service (Puppeteer, @react-pdf/renderer, etc.)
    });

  } catch (error: any) {
    console.error('[RATE CARD ERROR]', error);
    return NextResponse.json({ error: error.message || 'Failed to generate rate card' }, { status: 500 });
  }
}
