import React from 'react';
import { cookies } from 'next/headers';
import { createServerClient } from '@supabase/ssr';
import Link from 'next/link';
import { redirect } from 'next/navigation';

export const dynamic = 'force-dynamic';

export default async function LessonPage({ params }: { params: { track: string, module: string, lesson: string } }) {
    const cookieStore = await cookies();
    const supabase = createServerClient(
        process.env.NEXT_PUBLIC_SUPABASE_URL!,
        process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!,
        { cookies: { getAll: () => cookieStore.getAll(), setAll: () => {} } }
    );
    
    // Fetch the lesson from the database mapped by the AI Content Engine
    const { data: lessonData, error } = await supabase
        .from('hc_training_lessons')
        .select('*')
        .eq('track_slug', params.track)
        .eq('module_slug', params.module)
        .eq('lesson_slug', params.lesson)
        .single();
        
    if (error || !lessonData) {
        // Fallback or handle missing lesson
        console.error("Lesson not found:", error);
    }
    
    const title = lessonData?.title || params.lesson.replace(/-/g, ' ').toUpperCase();
    
    // Parse the markdown JSON payload generated by the AI 
    let contentPack = {
        quick_answer: "Executing a safe corridor transition requires absolute adherence to federal axle weight limits and localized escort vector positioning ahead of structural chokepoints.",
        step_by_step: ["Verify Route IQ Parameters", "Lock Escort Formation", "Activate Settlement Escrow"],
        common_mistakes: "Operating without active RF contact past the blind-curve apex. Do not rely on cellular networks in Zone B environments. Loss of signal = Immediate Halt.",
        professional_standard: "Top operators run redundant satellite comms and record the entire route matrix via 4K dash arrays for automated compliance uploads upon delivery.",
        monetization_hook: "Equip Comms Upgrade"
    };

    if (lessonData?.lesson_markdown) {
        try {
            contentPack = JSON.parse(lessonData.lesson_markdown);
        } catch(e) {
            console.error("Failed to parse lesson_markdown:", e);
        }
    }

    return (
        <div className="min-h-screen bg-transparent text-white font-sans selection:bg-blue-500/30">
            {/* PROGRESS HEADER */}
            <div className="w-full bg-gray-900 border-b border-gray-800 sticky top-0 z-50">
                <div className="max-w-6xl mx-auto px-6 h-16 flex items-center justify-between">
                    <div className="flex space-x-2 text-xs font-mono tracking-widest uppercase text-gray-500">
                        <Link href="/training" className="hover:text-blue-500 transition-colors">TRAINING</Link>
                        <span>/</span>
                        <Link href={`/training/${params.track}`} className="hover:text-blue-500 transition-colors">{params.track}</Link>
                        <span>/</span>
                        <span className="text-white truncate max-w-[200px]">{title}</span>
                    </div>
                    <div className="text-xs font-bold font-mono tracking-widest text-green-500 flex items-center gap-2">
                        <div className="w-2 h-2 bg-green-500 rounded-full animate-pulse"></div>
                        ACTIVE SESSION
                    </div>
                </div>
            </div>

            <div className="max-w-6xl mx-auto px-6 py-12">
                <header className="mb-10">
                    <h1 className="text-5xl md:text-6xl font-black uppercase tracking-tight text-white">{title}</h1>
                    <p className="mt-4 text-xl text-gray-400 max-w-3xl font-light border-l-2 border-blue-600 pl-4">
                        Master the tactical requirements. Failure to execute this protocol results in immediate contract suspension.
                    </p>
                </header>

                {/* 8K VISUAL SLOT (DARK OPS TAXONOMY) */}
                <div className="relative w-full aspect-video bg-gray-900 border border-gray-800 rounded-none overflow-hidden group mb-12">
                    {/* Assuming visual_assets array has a hero image path. Fallback to default. */}
                    <div className="absolute inset-0 bg-[url('/assets/lesson_hero.jpg')] bg-cover bg-center opacity-50 group-hover:opacity-75 transition-opacity duration-1000"></div>
                    <div className="absolute inset-0 bg-gradient-to-t from-gray-950 via-transparent to-transparent"></div>
                    
                    <div className="absolute bottom-6 left-6 right-6 flex justify-between items-end">
                        <div>
                            <p className="text-xs font-mono font-bold text-blue-500 tracking-widest mb-1">VISUAL INTEL LOG</p>
                            <p className="text-sm text-gray-300 backdrop-blur-md bg-gray-950/50 px-4 py-2 border border-gray-800 uppercase tracking-wider">
                                [ Operation Vector Confirmed ]
                            </p>
                        </div>
                    </div>
                </div>

                <div className="grid grid-cols-1 lg:grid-cols-3 gap-12">
                    {/* MAIN CONTENT COLUMN */}
                    <div className="lg:col-span-2 space-y-12">
                        
                        {/* QUICK ANSWER / SEO SNIPPET */}
                        <div className="bg-blue-950/20 border border-blue-900/50 p-6 rounded-none">
                            <h3 className="text-sm font-bold font-mono text-blue-400 tracking-widest uppercase mb-3 flex items-center gap-2">
                                <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M13 10V3L4 14h7v7l9-11h-7z"></path></svg>
                                Protocol Summary
                            </h3>
                            <p className="text-lg text-blue-100 font-light leading-relaxed">
                                {contentPack.quick_answer}
                            </p>
                        </div>

                        {/* STEP BY STEP LOGIC */}
                        <div className="prose prose-invert prose-blue max-w-none">
                            <h2 className="text-2xl font-black uppercase text-white mb-6">Standard Operating Procedure</h2>
                            <ul className="space-y-6 list-none pl-0">
                                {Array.isArray(contentPack.step_by_step) && contentPack.step_by_step.map((step, idx) => (
                                    <li key={idx} className="flex gap-4">
                                        <div className="flex-shrink-0 w-8 h-8 bg-gray-900 border border-gray-700 flex justify-center items-center font-mono font-bold text-gray-400 text-sm">
                                            0{idx + 1}
                                        </div>
                                        <div>
                                            <h4 className="text-lg font-bold text-white mb-1">{step}</h4>
                                        </div>
                                    </li>
                                ))}
                            </ul>
                        </div>
                    </div>

                    {/* SIDEBAR INTELLIGENCE */}
                    <div className="space-y-8">
                        {/* FATAL MISTAKE (RED ZONE) */}
                        <div className="bg-red-950/20 border border-red-900/50 p-6 relative overflow-hidden">
                            <div className="absolute top-0 left-0 w-1 h-full bg-red-600"></div>
                            <h3 className="text-sm font-bold font-mono text-red-500 tracking-widest uppercase mb-3 flex items-center gap-2">
                                <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M12 9v2m0 4h.01m-6.938 4h13.856c1.54 0 2.502-1.667 1.732-3L13.732 4c-.77-1.333-2.694-1.333-3.464 0L3.34 16c-.77 1.333.192 3 1.732 3z"></path></svg>
                                The Fatal Mistake
                            </h3>
                            <p className="text-gray-300 text-sm leading-relaxed font-light">
                                {contentPack.common_mistakes}
                            </p>
                        </div>

                        {/* PROFESSIONAL STANDARD (ELITE TIER) */}
                        <div className="bg-gray-900 border border-gray-800 p-6 relative overflow-hidden group hover:border-yellow-500/50 transition-colors">
                            <div className="absolute top-0 right-0 w-16 h-16 bg-yellow-500/10 rounded-full blur-2xl group-hover:bg-yellow-500/20"></div>
                            <h3 className="text-sm font-bold font-mono text-yellow-500 tracking-widest uppercase mb-3">
                                Elite 1% Standard
                            </h3>
                            <p className="text-gray-400 text-sm leading-relaxed mb-4">
                                {contentPack.professional_standard}
                            </p>
                            <Link href="/vendors/comms" className="block text-xs font-bold text-yellow-500 uppercase tracking-widest border border-yellow-500/30 px-4 py-3 hover:bg-yellow-500/10 transition-colors text-center w-full">
                                {contentPack.monetization_hook} <span className="font-mono ml-2">→</span>
                            </Link>
                        </div>

                        {/* COMPLETION ACTION */}
                        <form action={async () => {
                            'use server';
                            // Implementation of marking lesson as complete inside db here.
                            // ...
                        }}>
                            <button className="w-full bg-blue-600 hover:bg-blue-500 text-white py-4 font-bold font-mono text-sm tracking-widest uppercase transition-all shadow-[0_0_20px_-5px_rgba(37,99,235,0.4)]">
                                Verify & Proceed
                            </button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    )
}
