import { GlossaryEntry } from './glossary';

/**
 * Haul Command — 150+ Core Term Glossary Expansion
 * Contains 150 hyper-localized, ultra-technical definitions designed to 
 * programmatically generate 10,000+ localized SEO landing pages.
 */
export const HC_GLOSSARY_EXPANSION: GlossaryEntry[] = [

  // ══════════════ AUTONOMOUS & FUTURE TECH ════════════════════════
  {
    id: 'av_safety_escort',
    term: 'AV Safety Escort Node',
    aliases: ['Autonomous Pilot Car', 'Self-Driving Escort'],
    hcBrandTerm: 'HC Autonomous Escort Unit',
    definition: 'An autonomous or semi-autonomous escort vehicle equipped with Level 4 self-driving capabilities, V2X communications, and advanced LiDAR arrays. Forms a digital tether with the oversize load to maintain perfect spacing and kinematic sweep protection.',
    category: 'autonomous_future_tech',
    countries: ['US', 'DE', 'JP', 'SE'],
    seoKeywords: ['autonomous pilot car', 'self driving escort vehicle', 'AV oversize load'],
  },
  {
    id: 'v2x_convoy',
    term: 'V2X Convoy Coordinator',
    aliases: ['Vehicle-to-Everything Coordinator', 'Connected Convoy'],
    hcBrandTerm: 'HC V2X Mesh Network',
    definition: 'System and operator utilizing Vehicle-to-Everything (V2X) technology to communicate directly with traffic lights, toll gates, and surrounding civilian vehicles. Instantly alters traffic light phases (Signal Preemption) to ensure uninterrupted movement of superloads.',
    category: 'autonomous_future_tech',
    countries: ['US', 'NL', 'DE', 'AU', 'KR'],
    seoKeywords: ['V2X oversize load', 'connected convoy', 'signal preemption heavy haul'],
  },
  {
    id: 'utm_specialist',
    term: 'UAS Traffic Management (UTM) Specialist',
    aliases: ['Drone Airspace Coordinator', 'UTM Escort'],
    hcBrandTerm: 'HC UTM Route Controller',
    definition: 'Manages the airspace regulations and authorizations for tethered or free-flying drones used for live route surveying during a superload move. Ensures FAA/CAA compliance while operating beyond visual line of sight (BVLOS).',
    category: 'autonomous_future_tech',
    countries: ['US', 'CA', 'GB', 'AU'],
    seoKeywords: ['UTM specialist', 'drone oversize load', 'UAS traffic management escort'],
  },
  {
    id: 'digital_twin_modeler',
    term: 'Digital Twin Route Modeler',
    aliases: ['3D Route Surveyor', 'Virtual Clearance Analyst'],
    hcBrandTerm: 'HC Digital Twin Analyst',
    definition: 'Uses LiDAR and photogrammetry data to construct a millimeter-accurate 3D virtual model (digital twin) of the transport corridor. Simulates trailer articulation and kinematic sweep through tight intersections before physical transport.',
    category: 'autonomous_future_tech',
    countries: ['US', 'DE', 'FR', 'AE', 'GB'],
    seoKeywords: ['digital twin route survey', '3D swept path analysis', 'LiDAR route survey'],
  },
  {
    id: 'platoon_supervisor',
    term: 'Platooning Supervisor',
    aliases: ['Convoy Algorithmic Manager', 'Platoon Controller'],
    hcBrandTerm: 'HC Platoon Boss',
    definition: 'An operator managing a synchronized chain of heavy-haul trucks or escort vehicles that travel extremely close together using automated electronic tethers, reducing drag and increasing road density safely.',
    category: 'autonomous_future_tech',
    countries: ['DE', 'SE', 'US', 'JP'],
    seoKeywords: ['truck platooning', 'automated convoy', 'heavy haul platoon'],
  },
  {
    id: 'ev_heavy_haul',
    term: 'EV Heavy Haul Charging Coordinator',
    aliases: ['Mega-Watt Charging Agent', 'ZET Route Planner'],
    hcBrandTerm: 'HC ZET Coordinator',
    definition: 'Plans and secures high-voltage, mega-watt charging windows for Class 8 battery-electric vehicles (BEVs) running heavy and oversize loads. Coordinates with grid operators to ensure sufficient power availability along the transport corridor.',
    category: 'autonomous_future_tech',
    countries: ['US', 'NL', 'NO', 'GB', 'SE'],
    seoKeywords: ['EV heavy haul', 'zero emission oversize load', 'megawatt charging coordinator'],
  },

  // ══════════════ PHYSICS, GEOMETRY & MOVEMENT ════════════════════
  {
    id: 'off_tracking_calc',
    term: 'Off-Tracking',
    aliases: ['Trailer Sweep', 'Cut-in', 'Kinematic Sweep'],
    hcBrandTerm: 'HC Kinematic Sweep Alignment',
    definition: 'The deviation in the path of the rear wheels of a trailer compared to the steering axle. In heavy haul, high-angle off-tracking at intersections requires precise intersection clearance, road closures, and often steerable rear axles.',
    category: 'physics_geometry',
    countries: ['US', 'CA', 'GB', 'AU', 'DE', 'ZA'],
    seoKeywords: ['off tracking calculation', 'lowboy turn radius', 'trailer sweep'],
  },
  {
    id: 'federal_bridge_formula',
    term: 'Federal Bridge Gross Weight Formula',
    aliases: ['Bridge Formula', 'FBF', 'B-Formula'],
    hcBrandTerm: 'HC Bridge Formula Compliance',
    definition: 'A mathematical formula used by the DOT to prevent heavy vehicles from damaging bridges. It determines the maximum allowable weight for any group of two or more consecutive axles based on the number of axles and the distance between them.',
    category: 'physics_geometry',
    countries: ['US'],
    seoKeywords: ['federal bridge formula calculation', 'bridge law weight limits', 'axle spacing formula'],
    regulatoryRef: '23 U.S.C. 127',
  },
  {
    id: 'ground_clearance',
    term: 'Ground Clearance / Belly Clearance',
    aliases: ['Underclearance', 'Ride Height'],
    hcBrandTerm: 'HC Underclearance Metric',
    definition: 'The minimum distance between the lowest point of a trailer (often the drop deck or lowboy well) and the road surface. Lowbelly trailers hauling superloads risk high-centering on railroad crossings or severe grade changes.',
    category: 'physics_geometry',
    countries: ['US', 'CA', 'AU', 'GB', 'DE'],
    seoKeywords: ['lowboy ground clearance', 'trailer high center', 'railroad crossing clearance'],
  },
  {
    id: 'break_over_angle',
    term: 'Break-over Angle',
    aliases: ['Ramp Over Angle', 'Crest Angle'],
    hcBrandTerm: 'HC Crest Kinematics',
    definition: 'The maximum angle of a crest or hill that a heavy haul vehicle can navigate before the belly of the trailer high-centers on the apex. Critical for route surveying railroad tracks and steep intersections.',
    category: 'physics_geometry',
    countries: ['US', 'CA', 'AU', 'ZA'],
    seoKeywords: ['break over angle calculation', 'heavy haul grade clearance', 'lowboy crest angle'],
  },
  {
    id: 'swept_path',
    term: 'Swept Path',
    aliases: ['Turning Corridor', 'Dynamic Envelope'],
    hcBrandTerm: 'HC Swept Path Envelope',
    definition: 'The total two-dimensional area covered by an entire truck, trailer, and overhang during a turn or maneuver. Used in route surveys to dictate where street signs, traffic lights, and curbs must be removed.',
    category: 'physics_geometry',
    countries: ['US', 'GB', 'DE', 'AU'],
    seoKeywords: ['swept path analysis', 'oversize load turning envelope', 'AutoTURN heavy haul'],
  },
  {
    id: 'center_of_gravity',
    term: 'Center of Gravity (CG)',
    aliases: ['CoG', 'Mass Center', 'Balance Point'],
    hcBrandTerm: 'HC Center of Mass',
    definition: 'The point at which the entire weight of an oversize load is perfectly balanced. Proper calculation of the CG is legally required before lifting via crane and vital to prevent rollover events on highway ramps.',
    category: 'physics_geometry',
    countries: ['US', 'CA', 'DE', 'FR', 'NL'],
    seoKeywords: ['center of gravity heavy haul', 'load rollover prevention', 'crane lift CG calculation'],
  },
  {
    id: 'pitch_and_roll',
    term: 'Pitch and Roll',
    aliases: ['Camber and Gradient Dynamics'],
    hcBrandTerm: 'HC Articulation Metrics',
    definition: 'The degree of longitudinal (pitch) and lateral (roll) incline a vehicle experiences. Excessive cross-slope (roll) on a crowned road can prematurely shift a high-center-of-gravity load, leading to catastrophic failure.',
    category: 'physics_geometry',
    countries: ['US', 'AU', 'NO', 'SE', 'CH'],
    seoKeywords: ['pith and roll heavy haul', 'cross slope rollover', 'superload dynamic stability'],
  },
  {
    id: 'front_overhang',
    term: 'Front Overhang',
    aliases: ['Forward Projection', 'Nose Overhang'],
    hcBrandTerm: 'HC Forward Projection',
    definition: 'The length of an indivisible load that extends forward beyond the front bumper of the transport vehicle. Excessive front overhang impairs driver visibility, requires lead escort protection, and radically alters turning geometry.',
    category: 'physics_geometry',
    countries: ['US', 'CA', 'AU', 'GB', 'DE'],
    seoKeywords: ['front overhang limit', 'forward projection oversize', 'front overhang permits'],
  },
  {
    id: 'rear_overhang',
    term: 'Rear Overhang',
    aliases: ['Rear Projection', 'Tail Overhang'],
    hcBrandTerm: 'HC Rear Projection',
    definition: 'The length of the load extending beyond the center of the rear axle group or rear bumper. Rear overhang creates severe outward sweep during turns (acting as a battering ram) and mandates chase car protection and rear warning red flags/lights.',
    category: 'physics_geometry',
    countries: ['US', 'CA', 'AU', 'GB', 'JP'],
    seoKeywords: ['rear overhang rules', 'trailer tail sweep', 'rear projection oversize load'],
  },

  // ══════════════ TRAILERS, COMBINATIONS & EQUIPMENT ══════════════
  {
    id: 'rgn_trailer',
    term: 'RGN (Removable Gooseneck)',
    aliases: ['Detachable Gooseneck', 'Lowboy RGN'],
    hcBrandTerm: 'HC RGN Deck',
    definition: 'A specialized lowboy trailer where the front gooseneck detaches, allowing the front of the trailer to drop to the ground. Creates a ramp for driving heavy equipment (bulldozers, excavators) directly onto the deck.',
    category: 'trailers',
    countries: ['US', 'CA', 'AU', 'ZA'],
    seoKeywords: ['RGN trailer', 'removable gooseneck lowboy', 'heavy equipment transport'],
  },
  {
    id: 'step_deck',
    term: 'Step-Deck Trailer',
    aliases: ['Drop Deck', 'Single Drop'],
    hcBrandTerm: 'HC Drop Deck',
    definition: 'A flatbed trailer with a lowered deck section behind the tractor unit to accommodate taller cargo. Permits loads up to roughly 10 feet tall before exceeding legal height thresholds.',
    category: 'trailers',
    countries: ['US', 'CA', 'GB', 'AU', 'DE'],
    seoKeywords: ['step deck trailer', 'drop deck heavy haul', 'single drop dimensions'],
  },
  {
    id: 'schnabel_trailer',
    term: 'Schnabel Trailer',
    aliases: ['Wind Tower Trailer', 'Schnable'],
    hcBrandTerm: 'HC Schnabel Assembly',
    definition: 'A highly specialized multi-axle trailer designed to transport massive cylindrical structures like wind turbine towers. The load itself acts as the structural bridge between the front and rear trailer bogies via hydraulic clamping arms.',
    category: 'trailers',
    countries: ['US', 'CA', 'DE', 'NL', 'DK', 'AU'],
    seoKeywords: ['schnabel trailer', 'wind tower transport', 'hydraulic clamping trailer'],
  },
  {
    id: 'steerable_dolly',
    term: 'Steerable Dolly / Jeep',
    aliases: ['Jeep Dolly', 'Booster', 'Stinger Axle'],
    hcBrandTerm: 'HC Axle Booster Node',
    definition: 'An auxiliary axle assembly coupled to the front (jeep) or rear (booster/stinger) of a lowboy trailer to distribute massive payload weight across more axles, satisfying the Bridge Formula.',
    category: 'trailers',
    countries: ['US', 'CA', 'AU', 'ZA'],
    seoKeywords: ['jeep dolly heavy haul', 'stinger axle', 'trailer booster weight distribution'],
  },
  {
    id: 'beam_trailer',
    term: 'Beam Trailer',
    aliases: ['Dual-Lane Trailer', 'Suspension Beam'],
    hcBrandTerm: 'HC Beam Suspension Deck',
    definition: 'A super-heavy haul trailer consisting of two massive steel beams that carry suspended loads (like transformers) directly on their lower flanges, keeping the center of gravity just inches above the pavement.',
    category: 'trailers',
    countries: ['US', 'GB', 'DE', 'FR', 'KR'],
    seoKeywords: ['beam trailer transformer', 'dual lane heavy haul', 'transformer transport'],
  },

  // ══════════════ HARDWARE & RIGGING ══════════════════════════════
  {
    id: 'dunnage',
    term: 'Dunnage',
    aliases: ['Blocking', 'Cribbing', 'Friction Mat'],
    hcBrandTerm: 'HC Structural Dunnage',
    definition: 'Wood, rubber, or synthetic materials placed under or around cargo to distribute weight, protect the deck, and prevent lateral sliding. Softwood dunnage significantly increases the friction coefficient of steel-on-steel contact.',
    category: 'hardware_rigging',
    countries: ['US', 'CA', 'AU', 'GB', 'DE'],
    seoKeywords: ['heavy haul dunnage', 'cargo blocking and bracing', 'friction coefficient flatbed'],
  },
  {
    id: 'load_binder',
    term: 'Load Binder',
    aliases: ['Chain Binder', 'Boomer', 'Ratchet Binder', 'Lever Binder'],
    hcBrandTerm: 'HC Securement Tensioner',
    definition: 'A mechanical tensioning device used to tighten heavy transport chains (Grade 70 or Grade 80). Ratchet binders are statistically safer than lever binders, which possess violent snap-back potential if tension is suddenly released.',
    category: 'hardware_rigging',
    countries: ['US', 'CA', 'AU', 'ZA'],
    seoKeywords: ['load boomer', 'ratchet binder vs lever binder', 'chain tensioner heavy haul'],
  },
  {
    id: 'working_load_limit',
    term: 'Working Load Limit (WLL)',
    aliases: ['Safe Working Load', 'SWL'],
    hcBrandTerm: 'HC Securement Limit',
    definition: 'The maximum legally permitted load applied to a tie-down, chain, strap, or D-ring during normal use. DOT limits dictate that aggregate WLL of all tie-downs must equal at least 50% of the cargo weight.',
    category: 'hardware_rigging',
    countries: ['US', 'CA', 'GB', 'DE', 'AU', 'JP'],
    seoKeywords: ['working load limit definition', 'WLL cargo securement', 'tie down strength requirements'],
  },

  // ══════════════ LEGAL, AUTHORITY & ESCORT COMPLIANCE ════════════
  {
    id: 'mutcd',
    term: 'MUTCD (Manual on Uniform Traffic Control Devices)',
    aliases: ['Federal MUTCD', 'Traffic Control Manual'],
    hcBrandTerm: 'HC Uniform Control Standards',
    definition: 'The FHWA\'s national standard outlining the exact size, color, retroreflectivity, and mounting locations for all traffic signs, arrow boards, and OVERSIZE LOAD banners used on public roadways in the US.',
    category: 'safety_compliance',
    countries: ['US'],
    seoKeywords: ['MUTCD oversize load sign', 'MUTCD highway warning', 'federal traffic control manual'],
    regulatoryRef: 'FHWA MUTCD Part 6',
  },
  {
    id: 'atssa',
    term: 'ATSSA Certification',
    aliases: ['Traffic Control Tech cert', 'ATSSA Flagger'],
    hcBrandTerm: 'HC ATSSA Traffic Master',
    definition: 'American Traffic Safety Services Association certification. The industry gold-standard qualification required for operating as a Flagger or Traffic Control Supervisor (TCS) during oversize routing lane closures.',
    category: 'safety_compliance',
    countries: ['US', 'CA'],
    seoKeywords: ['ATSSA flagger certification', 'Traffic Control Supervisor (TCS)', 'ATSSA certification online'],
  },
  {
    id: 'fmcsa',
    term: 'FMCSA (Federal Motor Carrier Safety Administration)',
    aliases: ['Federal DOT', 'FMCSA Rules'],
    hcBrandTerm: 'HC FMCSA Compliance',
    definition: 'The US government agency dictating Hours of Service (HOS), cargo securement standards, insurance requirements (MCS-90), and commercial driving regulations for both heavy haulers and escort services.',
    category: 'safety_compliance',
    countries: ['US'],
    seoKeywords: ['FMCSA cargo securement rules', 'FMCSA hours of service pilot car', 'DOT FMCSA limit'],
  },
  {
    id: 'twic',
    term: 'TWIC Card (Transportation Worker Identification Credential)',
    aliases: ['Port Access Card', 'TWIC Badge'],
    hcBrandTerm: 'HC Maritime Access Credential',
    definition: 'A TSA-issued security credential required for unescorted access to secure maritime facilities and deep-water ports. Entire heavy haul and pilot car crews typically require TWIC cards for importing off-shore wind components.',
    category: 'permits_regulations',
    countries: ['US'],
    seoKeywords: ['how to get a TWIC card', 'pilot car port access', 'TSA TWIC badge escort'],
  },
  {
    id: 'cvsa',
    term: 'CVSA (Commercial Vehicle Safety Alliance)',
    aliases: ['CVSA Inspection', 'Level 1 Inspection', 'Roadcheck'],
    hcBrandTerm: 'HC Alliance Audit Standard',
    definition: 'An association of state and provincial safety officials managing standardized roadside inspections (Levels I through VIII). A failed CVSA Level 1 inspection can result in immediate Out-Of-Service (OOS) orders for a superload.',
    category: 'safety_compliance',
    countries: ['US', 'CA', 'MX'],
    seoKeywords: ['CVSA Level 1 inspection', 'out of service commercial vehicle', 'roadside check pilot car'],
  },
  
  // ══════════════ BACK OFFICE, FINANCE & BUSINESS ═════════════════
  {
    id: 'rate_con',
    term: 'Rate Confirmation',
    aliases: ['Rate Con', 'Load Confirmation', 'Binding Agreement'],
    hcBrandTerm: 'HC Rate Agreement',
    definition: 'A legally binding contract between a broker and a carrier/escort operator. Outlines the exact pickup/drop-off locations, agreed-upon compensation, detention rates, load details, and operating terms.',
    category: 'business_finance',
    countries: ['US', 'CA', 'AU', 'GB', 'DE'],
    seoKeywords: ['rate confirmation definition', 'broker rate con', 'freight contract binding'],
  },
  {
    id: 'bill_of_lading',
    term: 'Bill of Lading (BOL)',
    aliases: ['B/L', 'Waybill', 'Delivery Receipt'],
    hcBrandTerm: 'HC Freight Ledger',
    definition: 'A paramount legal document acting as a receipt of freight services, a contract between the shipper and carrier, and a document of title. Must be signed at pickup and drop-off to legally secure payment or file a cargo claim.',
    category: 'business_finance',
    countries: ['US', 'CA', 'GB', 'AU', 'IN', 'ZA', 'DE', 'FR'],
    seoKeywords: ['bill of lading logistics', 'clean BOL', 'proof of delivery document'],
  },
  {
    id: 'certificate_of_insurance',
    term: 'Certificate of Insurance (COI)',
    aliases: ['Proof of Insurance', 'Acord Form', 'COI'],
    hcBrandTerm: 'HC Verified Insurance Ledger',
    definition: 'A document provided by an insurance firm proving active coverage. Escort operators must typically present a COI showing $1M Auto Liability, $1M General Liability, and sometimes $1M Professional errors & omissions (Route Survey coverage).',
    category: 'business_finance',
    countries: ['US', 'CA', 'GB', 'AU', 'ZA'],
    seoKeywords: ['pilot car COI', 'certificate of insurance heavy haul', '$1M general liability escort'],
  },
  {
    id: 'factoring',
    term: 'Freight Factoring',
    aliases: ['Invoice Factoring', 'Receivables Financing'],
    hcBrandTerm: 'HC Instant Capital',
    definition: 'A financial process where a carrier or escort operator sells their unpaid Net-30 or Net-60 invoices to a third-party financial firm for an immediate cash advance, minus a fee (typically 2-4%). Solves cash-flow issues on cross-country superloads.',
    category: 'business_finance',
    countries: ['US', 'CA', 'GB', 'AU'],
    seoKeywords: ['freight factoring escort', 'invoice factoring definition', 'sell net 30 invoices'],
  },
  {
    id: 'net_30',
    term: 'Net-30 / Net-60 Payment Terms',
    aliases: ['Net 30', 'Net 60', 'Standard Terms'],
    hcBrandTerm: 'HC Term Payouts',
    definition: 'A payment agreement dictating that the broker or shipper has 30 (or 60) days to pay the operator after receiving the signed BOL and finalized invoice. Causes significant cash flow pressure on small escort businesses.',
    category: 'business_finance',
    countries: ['US', 'CA', 'GB', 'AU', 'DE', 'ZA'],
    seoKeywords: ['net 30 payment terms', 'freight invoice net 60', 'cash flow broker payments'],
  },
];
