export interface PermitAuthority {
  countryCode: string;
  countryName: string;
  flag: string;
  slug: string;
  tier: 'A' | 'B' | 'C' | 'D';
  agencyName: string;
  agencyUrl: string;
  permitPortalUrl: string;
  phone: string;
  widthFirstEscort: string;
  heightTrigger: string;
  weightSuperload: string;
  localTermEscort: string;
  localTermLoad: string;
  permitSystem: string;
  travelRestrictions: string;
  specialNotes: string;
}

export const PERMIT_AUTHORITIES: PermitAuthority[] = [
  // ═══ TIER A ═══
  { countryCode:'US', countryName:'United States', flag:'🇺🇸', slug:'us', tier:'A', agencyName:'FHWA / State DOTs', agencyUrl:'https://ops.fhwa.dot.gov/freight/sw/permit_report/', permitPortalUrl:'https://ops.fhwa.dot.gov/freight/sw/permit_report/', phone:'+1 (202) 366-4000', widthFirstEscort:'12\'0"', heightTrigger:'14\'6"', weightSuperload:'200,000 lbs', localTermEscort:'Pilot Car', localTermLoad:'Oversize Load', permitSystem:'Per-state DOT (50 systems)', travelRestrictions:'Varies by state — see state sub-pages', specialNotes:'Permits are issued at state level — each state has its own portal. Use /permits/us/[state] for state-specific info.' },
  { countryCode:'CA', countryName:'Canada', flag:'🇨🇦', slug:'ca', tier:'A', agencyName:'Provincial MoTs', agencyUrl:'https://tc.canada.ca/en/road-transportation/vehicle-weights-dimensions', permitPortalUrl:'https://tc.canada.ca/en/road-transportation/vehicle-weights-dimensions', phone:'+1 (613) 990-2309', widthFirstEscort:'3.85m', heightTrigger:'4.15m', weightSuperload:'105,000 kg', localTermEscort:'Pilot Car', localTermLoad:'Oversize Load', permitSystem:'Per-province (10 provincial systems)', travelRestrictions:'Spring weight restrictions across all provinces Mar–May', specialNotes:'provinces follow CCMTA standards but each has its own permit portal.' },
  { countryCode:'AU', countryName:'Australia', flag:'🇦🇺', slug:'au', tier:'A', agencyName:'NHVR', agencyUrl:'https://www.nhvr.gov.au', permitPortalUrl:'https://www.nhvr.gov.au/road-access/heavy-vehicle-permits', phone:'+61 1300 696 487', widthFirstEscort:'2.5m', heightTrigger:'4.3m', weightSuperload:'≥160t GCM', localTermEscort:'Pilot Vehicle (PV)', localTermLoad:'Over-Dimensional (OD)', permitSystem:'NHVR National Heavy Vehicle Regulator (online)', travelRestrictions:'Chain of Responsibility (CoR) — all parties liable', specialNotes:'NHVR provides national permit portal. WA and NT handled separately by their own DoT.' },
  { countryCode:'GB', countryName:'United Kingdom', flag:'🇬🇧', slug:'gb', tier:'A', agencyName:'DVSA / National Highways', agencyUrl:'https://www.gov.uk/abnormal-loads', permitPortalUrl:'https://esdal.highwaysengland.co.uk', phone:'+44 300 123 9000', widthFirstEscort:'3.0m', heightTrigger:'4.0m', weightSuperload:'>150t', localTermEscort:'Abnormal Load Escort', localTermLoad:'Abnormal Indivisible Load (AIL)', permitSystem:'ESDAL2 (Electronic Service Delivery for Abnormal Loads)', travelRestrictions:'STGO Cat 3 requires police escort and advance ESDAL2 notification', specialNotes:'STGO categories 1/2/3 determine escort requirements. Scotland has additional notification requirements.' },
  { countryCode:'NZ', countryName:'New Zealand', flag:'🇳🇿', slug:'nz', tier:'A', agencyName:'NZTA (Waka Kotahi)', agencyUrl:'https://www.nzta.govt.nz', permitPortalUrl:'https://www.nzta.govt.nz/roads-and-rail/high-productivity-motor-vehicles/overdimension-permits/', phone:'+64 0800 699 000', widthFirstEscort:'2.5m', heightTrigger:'4.25m', weightSuperload:'>80t', localTermEscort:'Pilot Vehicle Operator', localTermLoad:'Overdimension Load', permitSystem:'NZTA Permit System (online)', travelRestrictions:'Cook Strait ferry coordination required for South Island moves', specialNotes:'New Zealand uses metric system exclusively. North/South Island moves require ferry coordination.' },
  { countryCode:'ZA', countryName:'South Africa', flag:'🇿🇦', slug:'za', tier:'A', agencyName:'RTMC / Provincial DoT', agencyUrl:'https://www.rtmc.co.za', permitPortalUrl:'https://www.rtmc.co.za/index.php/permits', phone:'+27 12 999 5200', widthFirstEscort:'3.0m', heightTrigger:'4.0m', weightSuperload:'>60t', localTermEscort:'Abnormal Load Escort Operator', localTermLoad:'Abnormal Load', permitSystem:'RTMC / eNaTIS (online permit system)', travelRestrictions:'N1/N3 corridor restrictions during rush hours', specialNotes:'Mining and petrochemical freight drives demand. Escort required from 3.0m width.' },
  { countryCode:'DE', countryName:'Germany', flag:'🇩🇪', slug:'de', tier:'A', agencyName:'BAG (Bundesamt für Güterverkehr)', agencyUrl:'https://www.bag.bund.de', permitPortalUrl:'https://www.bag.bund.de/EN/Navigation/Handling/Accompanying_transport/accompanying_transport_node.html', phone:'+49 221 5776-0', widthFirstEscort:'3.0m', heightTrigger:'4.0m', weightSuperload:'>80t', localTermEscort:'Begleitfahrzeug (BF3/BF4)', localTermLoad:'Großraum- und Schwertransport (GST)', permitSystem:'VEMAGS (Verfahrensmanagement für Großraum- und Schwertransporte)', travelRestrictions:'No weekend travel for category 2/3 loads without special permit', specialNotes:'BF3/BF4 certified escorts required. VEMAGS is the federal permit coordination platform used by all 16 Länder.' },
  { countryCode:'NL', countryName:'Netherlands', flag:'🇳🇱', slug:'nl', tier:'A', agencyName:'RDW (Dienst Wegverkeer)', agencyUrl:'https://www.rdw.nl', permitPortalUrl:'https://www.rdw.nl/particulier/voertuigen/ontheffingen', phone:'+31 88 489 3000', widthFirstEscort:'3.0m', heightTrigger:'4.0m', weightSuperload:'>80t', localTermEscort:'Transportbegeleider', localTermLoad:'Exceptioneel Transport', permitSystem:'RDW Ontheffingssysteem (online)', travelRestrictions:'Port of Rotterdam corridors have specific route restrictions', specialNotes:'Netherlands is a major transit country. Cross-border coordination with Belgium and Germany common.' },
  { countryCode:'AE', countryName:'UAE', flag:'🇦🇪', slug:'ae', tier:'A', agencyName:'RTA / Federal Roads Authority', agencyUrl:'https://www.rta.ae', permitPortalUrl:'https://www.rta.ae/wps/portal/rta/ae/home/rta-initiatives/commercial-transport', phone:'+971 800 9090', widthFirstEscort:'3.0m', heightTrigger:'4.5m', weightSuperload:'>60t', localTermEscort:'Escort Vehicle', localTermLoad:'Abnormal Load', permitSystem:'RTA Dubai / FRA Abu Dhabi (separate systems)', travelRestrictions:'No daylight movement of large loads on Sheikh Zayed Road', specialNotes:'Dubai and Abu Dhabi have separate permit authorities. Major SPMT/heavy lift market for oil and gas.' },
  { countryCode:'BR', countryName:'Brazil', flag:'🇧🇷', slug:'br', tier:'A', agencyName:'ANTT (Agência Nacional de Transportes Terrestres)', agencyUrl:'https://www.gov.br/antt', permitPortalUrl:'https://www.gov.br/antt/pt-br/assuntos/cargas-especiais', phone:'+55 61 3410-1500', widthFirstEscort:'3.2m', heightTrigger:'4.4m', weightSuperload:'>120t', localTermEscort:'Batedor / Escolteiro', localTermLoad:'Carga Especial / Indivisível', permitSystem:'SELOG (federal) + state DAER/DER systems', travelRestrictions:'DNIT controls federal highways; state roads have separate rules', specialNotes:'Brazil is largest OSOW market in Latin America. Pre-salt oil industry and wind energy drive demand.' },

  // ═══ TIER B ═══
  { countryCode:'IE', countryName:'Ireland', flag:'🇮🇪', slug:'ie', tier:'B', agencyName:'Transport Infrastructure Ireland (TII)', agencyUrl:'https://www.tii.ie', permitPortalUrl:'https://www.permitsonline.ie', phone:'+353 1 646 3600', widthFirstEscort:'3.0m', heightTrigger:'4.0m', weightSuperload:'>80t', localTermEscort:'Abnormal Load Escort', localTermLoad:'Abnormal Indivisible Load', permitSystem:'PermitsOnline.ie', travelRestrictions:'Dublin Ring Road restrictions during rush hours', specialNotes:'Aligns with UK STGO categories. Cross-border with Northern Ireland requires both Irish and UK permits.' },
  { countryCode:'SE', countryName:'Sweden', flag:'🇸🇪', slug:'se', tier:'B', agencyName:'Trafikverket', agencyUrl:'https://www.trafikverket.se', permitPortalUrl:'https://www.trafikverket.se/tjanster/tillstand-och-regelverk/tillstand-for-tunga-transporter/', phone:'+46 771 921 921', widthFirstEscort:'3.0m', heightTrigger:'4.5m', weightSuperload:'>100t', localTermEscort:'Följebil', localTermLoad:'Specialtransport', permitSystem:'Trafikverket ATOFF', travelRestrictions:'Spring thaw weight restrictions on unpaved roads', specialNotes:'Sweden has among Europe\'s highest weight limits. Wind energy and mining drive demand.' },
  { countryCode:'NO', countryName:'Norway', flag:'🇳🇴', slug:'no', tier:'B', agencyName:'Statens vegvesen (SVV)', agencyUrl:'https://www.vegvesen.no', permitPortalUrl:'https://www.vegvesen.no/kjoretoy/yrkestransport/godstransport/spesialtransport/', phone:'+47 22 07 30 00', widthFirstEscort:'3.0m', heightTrigger:'4.0m', weightSuperload:'>60t', localTermEscort:'Følgebilsjåfør', localTermLoad:'Spesialtransport', permitSystem:'Vegvesenets dispensasjonssystem', travelRestrictions:'Fjord crossings require ferry coordination', specialNotes:'Offshore oil & gas equipment and wind farm transport. Remote routes require advance planning.' },
  { countryCode:'DK', countryName:'Denmark', flag:'🇩🇰', slug:'dk', tier:'B', agencyName:'Vejdirektoratet', agencyUrl:'https://www.vejdirektoratet.dk', permitPortalUrl:'https://www.vejdirektoratet.dk/side/tilladelse-til-bredde-og-tung-transport', phone:'+45 7244 3333', widthFirstEscort:'3.0m', heightTrigger:'4.0m', weightSuperload:'>80t', localTermEscort:'Følgebil', localTermLoad:'Specialtransport', permitSystem:'Vejdirektoratets tilladelsessystem', travelRestrictions:'Great Belt and Øresund bridges have specific protocols', specialNotes:'Compact country — most moves cross into Germany or Sweden requiring multi-country permits.' },
  { countryCode:'FI', countryName:'Finland', flag:'🇫🇮', slug:'fi', tier:'B', agencyName:'Traficom', agencyUrl:'https://www.traficom.fi', permitPortalUrl:'https://www.traficom.fi/en/transport/road/permit-exceptional-transports', phone:'+358 29 534 5000', widthFirstEscort:'3.0m', heightTrigger:'4.4m', weightSuperload:'>100t', localTermEscort:'Saattoauto', localTermLoad:'Erikoiskuljetus', permitSystem:'Traficomin poikkeuslupajärjestelmä', travelRestrictions:'Spring weight restrictions (kelirikko) on unpaved roads', specialNotes:'Finland allows very high GVW on designated routes. Mining and forestry equipment drive demand.' },
  { countryCode:'BE', countryName:'Belgium', flag:'🇧🇪', slug:'be', tier:'B', agencyName:'SPW / Agentschap Wegen en Verkeer (AWV)', agencyUrl:'https://www.wegenenverkeer.be', permitPortalUrl:'https://www.wegenenverkeer.be/ondernemer/uitzonderlijk-vervoer', phone:'+32 70 222 666', widthFirstEscort:'3.0m', heightTrigger:'4.0m', weightSuperload:'>80t', localTermEscort:'Begeleidingsvoertuig', localTermLoad:'Uitzonderlijk transport', permitSystem:'AWV Uitzonderlijk Vervoer portal', travelRestrictions:'Brussels Ring restrictions for wide loads', specialNotes:'Belgium is at the crossroads of EU oversize corridors. Port of Antwerp and port of Zeebrugge are major entry points.' },
  { countryCode:'AT', countryName:'Austria', flag:'🇦🇹', slug:'at', tier:'B', agencyName:'BMK (Federal Ministry for Climate Action)', agencyUrl:'https://www.bmk.gv.at', permitPortalUrl:'https://www.bmk.gv.at/themen/strasse/strassenrecht/schwertransporte.html', phone:'+43 1 711 62-0', widthFirstEscort:'3.0m', heightTrigger:'4.0m', weightSuperload:'>80t', localTermEscort:'Begleitfahrzeug (BF3/BF4)', localTermLoad:'Großraum- und Schwertransport', permitSystem:'VEMAGS (shared with Germany)', travelRestrictions:'Alpine passes closed seasonally', specialNotes:'Austria shares the BF3/BF4 escort certification with Germany (DACH standard).' },
  { countryCode:'CH', countryName:'Switzerland', flag:'🇨🇭', slug:'ch', tier:'B', agencyName:'ASTRA (Bundesamt für Strassen)', agencyUrl:'https://www.astra.admin.ch', permitPortalUrl:'https://www.astra.admin.ch/astra/de/home/fachleute/schwerverkehr/ausnahmetransporte.html', phone:'+41 31 323 4011', widthFirstEscort:'3.0m', heightTrigger:'4.0m', weightSuperload:'>72t', localTermEscort:'Begleitfahrzeug', localTermLoad:'Ausnahmetransport', permitSystem:'ASTRA Ausnahmetransport system', travelRestrictions:'Alpine road and tunnel restrictions strictly enforced', specialNotes:'Switzerland has strict weight limits. St. Gotthard and Lötschberg tunnels have height/weight restrictions.' },
  { countryCode:'ES', countryName:'Spain', flag:'🇪🇸', slug:'es', tier:'B', agencyName:'DGT (Dirección General de Tráfico)', agencyUrl:'https://www.dgt.es', permitPortalUrl:'https://www.dgt.es/inicio/tramites/otras-gestiones/transportes-especiales/', phone:'+34 060', widthFirstEscort:'3.0m', heightTrigger:'4.0m', weightSuperload:'>60t', localTermEscort:'Vehículo de Acompañamiento', localTermLoad:'Transporte Especial', permitSystem:'DGT Sede Electrónica', travelRestrictions:'No movement on public holidays for category 2/3 loads', specialNotes:'Major wind energy market. Offshore wind installing driving demand in Bilbao and Cádiz corridors.' },
  { countryCode:'FR', countryName:'France', flag:'🇫🇷', slug:'fr', tier:'B', agencyName:'DGITM / Préfectures', agencyUrl:'https://www.ecologie.gouv.fr/transports-exceptionnels', permitPortalUrl:'https://www.demarches-simplifiees.fr/commencer/autorisation-de-transport-exceptionnel', phone:'+33 1 40 81 21 22', widthFirstEscort:'3.0m', heightTrigger:'4.0m', weightSuperload:'>200t', localTermEscort:'Guideur / Véhicule Pilote', localTermLoad:'Convoi Exceptionnel', permitSystem:'Préfecture system (decentralized)', travelRestrictions:'No Saturday afternoon or Sunday travel for Cat 3 convois', specialNotes:'3 categories: CE1 (self-permit), CE2 (prefectural authorization), CE3 (police escort required). Cat 3 > 5m wide or > 72t.' },
  { countryCode:'IT', countryName:'Italy', flag:'🇮🇹', slug:'it', tier:'B', agencyName:'MIT (Ministero delle Infrastrutture)', agencyUrl:'https://www.mit.gov.it', permitPortalUrl:'https://www.mit.gov.it/temi/strade-e-autostrade/trasporti-eccezionali', phone:'+39 06 44321', widthFirstEscort:'3.0m', heightTrigger:'4.0m', weightSuperload:'>100t', localTermEscort:'Scorta Tecnica', localTermLoad:'Trasporto Eccezionale', permitSystem:'AISCAT / Autostrade permit system', travelRestrictions:'No movement on major highways during public holidays', specialNotes:'Autostrade concessions have separate permit requirements from state roads. Annual permit available for repeat dimensions.' },
  { countryCode:'PT', countryName:'Portugal', flag:'🇵🇹', slug:'pt', tier:'B', agencyName:'IMT (Instituto da Mobilidade e dos Transportes)', agencyUrl:'https://www.imt-ip.pt', permitPortalUrl:'https://www.imt-ip.pt/sites/IMTT/Portugues/Foruns/TM_pesada_excepcional/', phone:'+351 21 781 5800', widthFirstEscort:'3.0m', heightTrigger:'4.0m', weightSuperload:'>60t', localTermEscort:'Veículo Batedor', localTermLoad:'Transporte Especial', permitSystem:'IMT Balcão Único de Transportes', travelRestrictions:'No movement on EN roads during summer tourist season peak hours', specialNotes:'Cross-border with Spain common. Major wind energy installations in interior.' },
  { countryCode:'SA', countryName:'Saudi Arabia', flag:'🇸🇦', slug:'sa', tier:'B', agencyName:'GAZT / MOT (Ministry of Transport)', agencyUrl:'https://www.mot.gov.sa', permitPortalUrl:'https://www.mot.gov.sa/en/Services/Pages/default.aspx', phone:'+966 11 404 4447', widthFirstEscort:'3.0m', heightTrigger:'4.5m', weightSuperload:'>60t', localTermEscort:'مركبة المرافقة', localTermLoad:'الشحنة الكبيرة', permitSystem:'MOT Naqla system', travelRestrictions:'No daytime movement in summer for some load categories', specialNotes:'Major oil & gas and industrial project market. NEOM and Vision 2030 infrastructure driving massive OSOW demand.' },
  { countryCode:'QA', countryName:'Qatar', flag:'🇶🇦', slug:'qa', tier:'B', agencyName:'Ashghal (Public Works Authority)', agencyUrl:'https://www.ashghal.gov.qa', permitPortalUrl:'https://portal.ashghal.gov.qa', phone:'+974 4495 0000', widthFirstEscort:'3.0m', heightTrigger:'4.5m', weightSuperload:'>60t', localTermEscort:'Escort Vehicle', localTermLoad:'Abnormal Load', permitSystem:'Ashghal I-Portal', travelRestrictions:'Rush hour restrictions on Doha expressways', specialNotes:'Post-FIFA World Cup infrastructure still generating SPMT/heavy lift demand.' },
  { countryCode:'MX', countryName:'Mexico', flag:'🇲🇽', slug:'mx', tier:'B', agencyName:'SCT (Secretaría de Comunicaciones y Transportes)', agencyUrl:'https://www.gob.mx/sct', permitPortalUrl:'https://www.gob.mx/tramites/ficha/permiso-para-el-transporte-de-carga-excepcional/SCT193', phone:'+52 55 5723 9300', widthFirstEscort:'3.5m', heightTrigger:'4.5m', weightSuperload:'>60t', localTermEscort:'Vehículo Escolta', localTermLoad:'Carga Fuera de Dimensiones', permitSystem:'SCT SICT portal', travelRestrictions:'No night movement on highway toll roads for certain loads', specialNotes:'Northern border corridor (Monterrey-Laredo) is highest-volume for cross-border OSOW with US.' },
  { countryCode:'IN', countryName:'India', flag:'🇮🇳', slug:'in', tier:'B', agencyName:'MoRTH (Ministry of Road Transport & Highways)', agencyUrl:'https://morth.nic.in', permitPortalUrl:'https://vahan.parivahan.gov.in', phone:'+91 11 2371 4116', widthFirstEscort:'3.0m', heightTrigger:'4.5m', weightSuperload:'>40t', localTermEscort:'Escort Vehicle / Pilot Vehicle', localTermLoad:'Over Dimensional Cargo (ODC)', permitSystem:'VAHAN portal (state-wise processing)', travelRestrictions:'Movement restricted on national highways during festivals', specialNotes:'India\'s renewable energy build-out (500GW target) driving massive wind turbine + transformer OSOW demand.' },
  { countryCode:'ID', countryName:'Indonesia', flag:'🇮🇩', slug:'id', tier:'B', agencyName:'Kementerian Perhubungan (Kemenhub)', agencyUrl:'https://kemenhub.go.id', permitPortalUrl:'https://hubdarat.dephub.go.id', phone:'+62 21 3811 308', widthFirstEscort:'2.5m', heightTrigger:'4.2m', weightSuperload:'>40t', localTermEscort:'Kendaraan Pengawal', localTermLoad:'Angkutan Barang Khusus', permitSystem:'SIMOPEL (Sistem Informasi Monitoring Perizinan Elektronik)', travelRestrictions:'Cross-island transport requires inter-island ferry coordination', specialNotes:'Island nation — frequent ferry transfers required. Mining and energy sector driving demand.' },
  { countryCode:'TH', countryName:'Thailand', flag:'🇹🇭', slug:'th', tier:'B', agencyName:'DLT (Department of Land Transport)', agencyUrl:'https://www.dlt.go.th', permitPortalUrl:'https://e-service.dlt.go.th', phone:'+66 2 271 8888', widthFirstEscort:'2.5m', heightTrigger:'4.0m', weightSuperload:'>40t', localTermEscort:'รถนำขบวน', localTermLoad:'รถขนส่งพิเศษ', permitSystem:'DLT e-Service portal', travelRestrictions:'Bangkok metro restrictions during rush hours', specialNotes:'EEC (Eastern Economic Corridor) industrial development driving OSOW growth.' },

  // ═══ TIER C ═══
  { countryCode:'PL', countryName:'Poland', flag:'🇵🇱', slug:'pl', tier:'C', agencyName:'GDDKiA (Generalna Dyrekcja Dróg Krajowych)', agencyUrl:'https://www.gddkia.gov.pl', permitPortalUrl:'https://ziszs.gddkia.gov.pl', phone:'+48 22 375 8888', widthFirstEscort:'3.0m', heightTrigger:'4.0m', weightSuperload:'>80t', localTermEscort:'Pojazd Pilotujący', localTermLoad:'Transport Nadzwyczajny', permitSystem:'ZISZS (Zezwolenia i System Zarządzania Specjalnymi)', travelRestrictions:'Summer tourist season restrictions on some roads', specialNotes:'Poland is a major transit route for EU oversize loads. BF3/BF4 escort certs gaining adoption.' },
  { countryCode:'CZ', countryName:'Czech Republic', flag:'🇨🇿', slug:'cz', tier:'C', agencyName:'ŘSD (Road Directorate)', agencyUrl:'https://www.rsd.cz', permitPortalUrl:'https://www.rsd.cz/wps/portal/web/Sluzby/Oversize', phone:'+420 800 150 150', widthFirstEscort:'3.0m', heightTrigger:'4.0m', weightSuperload:'>60t', localTermEscort:'Doprovodné vozidlo', localTermLoad:'Nadměrný náklad', permitSystem:'ŘSD permit system', travelRestrictions:'D1 motorway restrictions for wide loads', specialNotes:'Central EU location makes CZ a major transit country. Cross-border with Germany, Austria, Poland common.' },
  { countryCode:'SK', countryName:'Slovakia', flag:'🇸🇰', slug:'sk', tier:'C', agencyName:'NDS (Národná diaľničná spoločnosť)', agencyUrl:'https://www.nds.sk', permitPortalUrl:'https://www.nds.sk/en/permits', phone:'+421 2 5826 8222', widthFirstEscort:'3.0m', heightTrigger:'4.0m', weightSuperload:'>60t', localTermEscort:'Sprevádzajúce vozidlo', localTermLoad:'Nadrozmerný náklad', permitSystem:'NDS permits system', travelRestrictions:'Mountain pass restrictions in winter', specialNotes:'Cross-border moves with CZ and AT common. Industrial corridor through Bratislava-Trnava.' },
  { countryCode:'HU', countryName:'Hungary', flag:'🇭🇺', slug:'hu', tier:'C', agencyName:'NIF (Nemzeti Infrastruktúra Fejlesztő)', agencyUrl:'https://www.nif.hu', permitPortalUrl:'https://www.utdokumentumok.hu', phone:'+36 1 436 5400', widthFirstEscort:'3.0m', heightTrigger:'4.0m', weightSuperload:'>60t', localTermEscort:'Kísérő jármű', localTermLoad:'Rendkívüli szállítmány', permitSystem:'ÚT (Útdokumentumok) portal', travelRestrictions:'Budapest ring road restrictions', specialNotes:'Major cross-border route between Western and Eastern EU countries.' },
  { countryCode:'SI', countryName:'Slovenia', flag:'🇸🇮', slug:'si', tier:'C', agencyName:'DRSI (Roads Agency)', agencyUrl:'https://www.di.gov.si', permitPortalUrl:'https://www.di.gov.si/si/delovna_podrocja/ceste/dovolilnice_za_izredni_prevoz/', phone:'+386 1 478 8000', widthFirstEscort:'3.0m', heightTrigger:'4.0m', weightSuperload:'>60t', localTermEscort:'Spremljevalno vozilo', localTermLoad:'Izredni prevoz', permitSystem:'DRSI permit system', travelRestrictions:'Karavanke tunnel weight restrictions', specialNotes:'Alps terrain creates specific challenges. Key corridor between Italy and Central/Eastern EU.' },
  { countryCode:'EE', countryName:'Estonia', flag:'🇪🇪', slug:'ee', tier:'C', agencyName:'Maanteeamet (Road Administration)', agencyUrl:'https://www.mnt.ee', permitPortalUrl:'https://www.mnt.ee/en/professional/exceptional-transport', phone:'+372 620 1200', widthFirstEscort:'3.0m', heightTrigger:'4.0m', weightSuperload:'>60t', localTermEscort:'Saatja sõiduk', localTermLoad:'Erivedu', permitSystem:'Maanteeamet e-service', travelRestrictions:'Spring thaw weight restrictions', specialNotes:'Baltic state — cross-border moves with Latvia and Finland (ferry) common.' },
  { countryCode:'LV', countryName:'Latvia', flag:'🇱🇻', slug:'lv', tier:'C', agencyName:'CSDD (Road Traffic Safety Directorate)', agencyUrl:'https://www.csdd.lv', permitPortalUrl:'https://www.csdd.lv/en/transportation-permits', phone:'+371 6702 3100', widthFirstEscort:'3.0m', heightTrigger:'4.0m', weightSuperload:'>60t', localTermEscort:'Pavadošais transportlīdzeklis', localTermLoad:'Pārgabarīta krava', permitSystem:'CSDD e-services', travelRestrictions:'Spring weight limits on regional roads', specialNotes:'Port of Riga is key entry point. Cross-border with Estonia and Lithuania common.' },
  { countryCode:'LT', countryName:'Lithuania', flag:'🇱🇹', slug:'lt', tier:'C', agencyName:'VIA Lietuva (Road Administration)', agencyUrl:'https://www.ltg.lt', permitPortalUrl:'https://www.e.ltg.lt', phone:'+370 5 232 9600', widthFirstEscort:'3.0m', heightTrigger:'4.0m', weightSuperload:'>60t', localTermEscort:'Lydimasis transportas', localTermLoad:'Nesuskaidoma krovinys', permitSystem:'VIA Lietuva e-system', travelRestrictions:'Spring weight restrictions on secondary roads', specialNotes:'Klaipeda port and Vilnius industrial zone are main hubs.' },
  { countryCode:'HR', countryName:'Croatia', flag:'🇭🇷', slug:'hr', tier:'C', agencyName:'HAC (Croatian Motorways)', agencyUrl:'https://www.hac.hr', permitPortalUrl:'https://www.hac.hr/en/users/special-transport-permits', phone:'+385 1 4899 900', widthFirstEscort:'3.0m', heightTrigger:'4.0m', weightSuperload:'>60t', localTermEscort:'Prateće vozilo', localTermLoad:'Izvanredni prijevoz', permitSystem:'HAC permit system', travelRestrictions:'Adriatic coast summer traffic restrictions', specialNotes:'Adriatic highway corridor. Cross-border with Slovenia, Hungary, Bosnia common.' },
  { countryCode:'RO', countryName:'Romania', flag:'🇷🇴', slug:'ro', tier:'C', agencyName:'CNAIR (National Roads Administration)', agencyUrl:'https://www.cnair.ro', permitPortalUrl:'https://portalpermite.cnadnr.ro', phone:'+40 21 264 3100', widthFirstEscort:'3.0m', heightTrigger:'4.0m', weightSuperload:'>60t', localTermEscort:'Vehicul de însoțire', localTermLoad:'Transport agabaritic', permitSystem:'CNAIR portal (online)', travelRestrictions:'Mountain pass Carpathian restrictions in winter', specialNotes:'Growing renewable energy sector and Black Sea port (Constanța) driving OSOW demand.' },
  { countryCode:'BG', countryName:'Bulgaria', flag:'🇧🇬', slug:'bg', tier:'C', agencyName:'Agency Road Infrastructure (ARI)', agencyUrl:'https://www.api.bg', permitPortalUrl:'https://www.api.bg/wps/portal/api/business/Permits', phone:'+359 2 9173 000', widthFirstEscort:'3.0m', heightTrigger:'4.0m', weightSuperload:'>60t', localTermEscort:'Придружаващо превозно средство', localTermLoad:'Извънгабаритен товар', permitSystem:'ARI e-permit system', travelRestrictions:'Trakia motorway restrictions for wide loads', specialNotes:'Key transit country between EU and Turkey.' },
  { countryCode:'GR', countryName:'Greece', flag:'🇬🇷', slug:'gr', tier:'C', agencyName:'YPYMED (Ministry of Infrastructure)', agencyUrl:'https://www.yme.gov.gr', permitPortalUrl:'https://www.yme.gov.gr/en/permits-for-exceptional-transports/', phone:'+30 210 650 8000', widthFirstEscort:'3.0m', heightTrigger:'4.0m', weightSuperload:'>60t', localTermEscort:'Όχημα συνοδείας', localTermLoad:'Υπεράριθμο Φορτίο', permitSystem:'YPYMED permit system', travelRestrictions:'Island transport requires ferry; Athens ring restrictions', specialNotes:'Island logistics require ferry coordination. Thessaloniki port is key entry point.' },
  { countryCode:'TR', countryName:'Turkey', flag:'🇹🇷', slug:'tr', tier:'C', agencyName:'KGM (Karayolları Genel Müdürlüğü)', agencyUrl:'https://www.kgm.gov.tr', permitPortalUrl:'https://www.kgm.gov.tr/Sayfalar/KGM/SiteTr/Trafik/ozelizin.aspx', phone:'+90 312 402 3200', widthFirstEscort:'3.0m', heightTrigger:'4.5m', weightSuperload:'>60t', localTermEscort:'Refakat Aracı / Eskort', localTermLoad:'Gabari Dışı Yük', permitSystem:'KGM e-permit portal', travelRestrictions:'Istanbul Bosphorus Bridge restrictions', specialNotes:'Key corridor between Europe and Asia. Growing renewables market and major construction projects.' },
  { countryCode:'KW', countryName:'Kuwait', flag:'🇰🇼', slug:'kw', tier:'C', agencyName:'Ministry of Public Works', agencyUrl:'https://www.mpw.gov.kw', permitPortalUrl:'https://www.mpw.gov.kw', phone:'+965 2401 8000', widthFirstEscort:'3.0m', heightTrigger:'4.5m', weightSuperload:'>60t', localTermEscort:'مركبة المرافقة', localTermLoad:'الحمولة الكبيرة', permitSystem:'MPW permit system', travelRestrictions:'Kuwait City expressway restrictions', specialNotes:'Oil and gas infrastructure drives SPMT and heavy lift demand.' },
  { countryCode:'OM', countryName:'Oman', flag:'🇴🇲', slug:'om', tier:'C', agencyName:'Muscat Municipality / ROP', agencyUrl:'https://www.rop.gov.om', permitPortalUrl:'https://www.rop.gov.om/english/services_trafficpermits.asp', phone:'+968 2452 0000', widthFirstEscort:'3.0m', heightTrigger:'4.5m', weightSuperload:'>60t', localTermEscort:'مركبة المرافقة', localTermLoad:'الشحنة الاستثنائية', permitSystem:'ROP Traffic Department permits', travelRestrictions:'Muscat highway restrictions during peak hours', specialNotes:'Duqm Special Economic Zone driving heavy equipment demand.' },
  { countryCode:'BH', countryName:'Bahrain', flag:'🇧🇭', slug:'bh', tier:'C', agencyName:'Traffic Directorate (MOI)', agencyUrl:'https://www.moi.gov.bh', permitPortalUrl:'https://www.moi.gov.bh/en/eservices', phone:'+973 1787 0000', widthFirstEscort:'3.0m', heightTrigger:'4.5m', weightSuperload:'>60t', localTermEscort:'مركبة مرافقة', localTermLoad:'الشحنة الضخمة', permitSystem:'MOI e-services', travelRestrictions:'King Fahd Causeway coordination for Saudi cross-border', specialNotes:'Small island nation. Cross-border with Saudi Arabia via King Fahd Causeway.' },
  { countryCode:'SG', countryName:'Singapore', flag:'🇸🇬', slug:'sg', tier:'C', agencyName:'LTA (Land Transport Authority)', agencyUrl:'https://www.lta.gov.sg', permitPortalUrl:'https://www.lta.gov.sg/content/ltagov/en/industry_innovations/industry/permits.html', phone:'+65 1800 2255 582', widthFirstEscort:'2.5m', heightTrigger:'4.0m', weightSuperload:'>40t', localTermEscort:'Escort Vehicle', localTermLoad:'Abnormal Load', permitSystem:'LTA permit system (online)', travelRestrictions:'ERP zones require special clearance', specialNotes:'Very dense urban environment. Most moves at night. Port of Singapore drives heavy equipment demand.' },
  { countryCode:'MY', countryName:'Malaysia', flag:'🇲🇾', slug:'my', tier:'C', agencyName:'JPJ (Jabatan Pengangkutan Jalan)', agencyUrl:'https://www.jpj.gov.my', permitPortalUrl:'https://www.jpj.gov.my/en/web/guest/permits', phone:'+60 3 7726 5500', widthFirstEscort:'2.5m', heightTrigger:'4.3m', weightSuperload:'>40t', localTermEscort:'Kenderaan Pengiring', localTermLoad:'Muatan Luar Biasa', permitSystem:'MyJPJ e-Permit', travelRestrictions:'North-South Highway restrictions during peak festivals', specialNotes:'Palm oil and petrochemical industry drives OSOW demand. East Malaysia (Sabah/Sarawak) has different rules.' },
  { countryCode:'JP', countryName:'Japan', flag:'🇯🇵', slug:'jp', tier:'C', agencyName:'MLIT (Ministry of Land, Infrastructure, Transport and Tourism)', agencyUrl:'https://www.mlit.go.jp', permitPortalUrl:'https://www.mlit.go.jp/road/sign/kijyun/tokusha/', phone:'+81 3 5253 8111', widthFirstEscort:'3.0m', heightTrigger:'4.1m', weightSuperload:'>40t', localTermEscort:'誘導車 (Yūdō-sha)', localTermLoad:'特殊車両 (Tokushu Sharyō)', permitSystem:'特車ゴールド (TOCAS online permit system)', travelRestrictions:'Strict urban route approvals required in major cities', specialNotes:'Japan has a sophisticated online permit system (TOCAS). Nuclear plant decommission and wind energy driving demand.' },
  { countryCode:'KR', countryName:'South Korea', flag:'🇰🇷', slug:'kr', tier:'C', agencyName:'MOLIT (Ministry of Land Infrastructure and Transport)', agencyUrl:'https://www.molit.go.kr', permitPortalUrl:'https://www.olt.go.kr', phone:'+82 44 201 3000', widthFirstEscort:'3.0m', heightTrigger:'4.0m', weightSuperload:'>40t', localTermEscort:'선도차량 (Seondo Charyang)', localTermLoad:'특수차량 (Teuksu Charyang)', permitSystem:'OLT 화물운송 특수차량 portal', travelRestrictions:'Seoul metropolitan area permits require additional approval', specialNotes:'Semiconductor fab and shipyard equipment drives SPMT and heavy lift demand.' },
  { countryCode:'CL', countryName:'Chile', flag:'🇨🇱', slug:'cl', tier:'C', agencyName:'MTT (Ministerio de Transportes)', agencyUrl:'https://www.mtt.gob.cl', permitPortalUrl:'https://www.mtt.gob.cl/archivos/4271', phone:'+56 2 2421 3000', widthFirstEscort:'3.0m', heightTrigger:'4.2m', weightSuperload:'>60t', localTermEscort:'Vehículo Escolta', localTermLoad:'Carga Sobredimensionada', permitSystem:'SERNAC/SECTRA permit system', travelRestrictions:'Andean mountain passes closed seasonally', specialNotes:'Mining (copper, lithium) and renewable energy driving OSOW demand. Atacama solar corridor growing rapidly.' },
  { countryCode:'AR', countryName:'Argentina', flag:'🇦🇷', slug:'ar', tier:'C', agencyName:'CNRT (Comisión Nacional de Regulación del Transporte)', agencyUrl:'https://www.argentina.gob.ar/transporte/cnrt', permitPortalUrl:'https://www.argentina.gob.ar/tramites/habilitacion-para-transporte-de-cargas-peligrosas-y-especiales', phone:'+54 11 4819 0800', widthFirstEscort:'3.2m', heightTrigger:'4.4m', weightSuperload:'>60t', localTermEscort:'Escolta / Vehículo Guía', localTermLoad:'Carga Especial Indivisible', permitSystem:'CNRT permit system', travelRestrictions:'Andes mountain passes seasonal', specialNotes:'Lithium mining and Patagonian wind energy creating significant OSOW demand in Cuyo and Patagonia.' },
  { countryCode:'CO', countryName:'Colombia', flag:'🇨🇴', slug:'co', tier:'C', agencyName:'MinTransporte (Ministerio de Transporte)', agencyUrl:'https://www.mintransporte.gov.co', permitPortalUrl:'https://www.mintransporte.gov.co/publicaciones/4455/cargas-extra-dimensionadas/', phone:'+57 1 381 6000', widthFirstEscort:'3.0m', heightTrigger:'4.4m', weightSuperload:'>60t', localTermEscort:'Vehículo Escolta', localTermLoad:'Carga Extradimensionada', permitSystem:'SIMIT permit system', travelRestrictions:'Bogotá urban access restrictions', specialNotes:'Pacific coast port access and oil & gas field equipment driving demand.' },
  { countryCode:'PE', countryName:'Peru', flag:'🇵🇪', slug:'pe', tier:'C', agencyName:'MTC (Ministerio de Transportes y Comunicaciones)', agencyUrl:'https://www.gob.pe/mtc', permitPortalUrl:'https://www.gob.pe/3349-solicitar-autorizacion-especial-de-transporte-de-mercaderia-peligrosa', phone:'+51 1 615 7800', widthFirstEscort:'3.0m', heightTrigger:'4.0m', weightSuperload:'>50t', localTermEscort:'Vehículo Escolta', localTermLoad:'Carga Especial', permitSystem:'MTC SUTRAN system', travelRestrictions:'Andean road seasonal closures', specialNotes:'Mining industry (copper, gold, silver) is primary OSOW driver. High-altitude Andean routes require specialist operators.' },
  { countryCode:'VN', countryName:'Vietnam', flag:'🇻🇳', slug:'vn', tier:'C', agencyName:'VR (Vietnam Register) / DRVN', agencyUrl:'https://www.vr.org.vn', permitPortalUrl:'https://cuctdduong.gov.vn', phone:'+84 24 3736 3300', widthFirstEscort:'2.5m', heightTrigger:'4.0m', weightSuperload:'>30t', localTermEscort:'Xe hộ tống', localTermLoad:'Hàng hóa quá khổ', permitSystem:'DRVN permit system', travelRestrictions:'Ho Chi Minh City urban restrictions', specialNotes:'Rapid industrialization and wind energy installations driving OSOW growth.' },
  { countryCode:'PH', countryName:'Philippines', flag:'🇵🇭', slug:'ph', tier:'C', agencyName:'LTO (Land Transportation Office)', agencyUrl:'https://www.lto.gov.ph', permitPortalUrl:'https://www.lto.gov.ph/index.php/permits', phone:'+63 2 8922 9061', widthFirstEscort:'2.5m', heightTrigger:'4.0m', weightSuperload:'>30t', localTermEscort:'Escort Vehicle', localTermLoad:'Oversize Load', permitSystem:'LTO Special Permit system', travelRestrictions:'MMDA coding restrictions in Metro Manila; island transfers via RORO', specialNotes:'Inter-island RORO ferry coordination required. Mining and renewable energy driving demand.' },

  // ═══ TIER D ═══
  { countryCode:'UY', countryName:'Uruguay', flag:'🇺🇾', slug:'uy', tier:'D', agencyName:'MTOP (Ministerio de Transporte y Obras Públicas)', agencyUrl:'https://www.gub.uy/ministerio-transporte-obras-publicas', permitPortalUrl:'https://www.gub.uy/ministerio-transporte-obras-publicas/tramites-y-servicios/tramites', phone:'+598 2 1990', widthFirstEscort:'3.0m', heightTrigger:'4.2m', weightSuperload:'>60t', localTermEscort:'Vehículo Escolta', localTermLoad:'Carga Excepcional', permitSystem:'MTOP permit system', travelRestrictions:'Cross-border with Argentina and Brazil requires multi-country permits', specialNotes:'Growing wind energy sector. Cross-border corridors with Argentina and Brazil.' },
  { countryCode:'PA', countryName:'Panama', flag:'🇵🇦', slug:'pa', tier:'D', agencyName:'ATTT (Autoridad de Tránsito y Transporte Terrestre)', agencyUrl:'https://www.attt.gob.pa', permitPortalUrl:'https://www.attt.gob.pa/permisos/', phone:'+507 501 5300', widthFirstEscort:'3.0m', heightTrigger:'4.5m', weightSuperload:'>60t', localTermEscort:'Vehículo Escolta', localTermLoad:'Carga Sobredimensionada', permitSystem:'ATTT e-permits', travelRestrictions:'Panama Canal Zone has separate authority', specialNotes:'Panama Canal port complex drives significant SPMT and heavy lift demand.' },
  { countryCode:'CR', countryName:'Costa Rica', flag:'🇨🇷', slug:'cr', tier:'D', agencyName:'COSEVI (Consejo de Seguridad Vial)', agencyUrl:'https://www.cosevi.go.cr', permitPortalUrl:'https://www.cosevi.go.cr/tramites/permisos', phone:'+506 2542 0100', widthFirstEscort:'3.0m', heightTrigger:'4.2m', weightSuperload:'>50t', localTermEscort:'Vehículo Escolta', localTermLoad:'Carga Extraordinaria', permitSystem:'COSEVI RITEVE system', travelRestrictions:'Mountain road seasonal closures during rainy season', specialNotes:'Renewable energy projects (wind, solar, hydro) driving OSOW demand.' },
];

export function getPermitAuthority(slug: string): PermitAuthority | null {
  return PERMIT_AUTHORITIES.find(p => p.slug === slug) ?? null;
}
