// =====================================================================
// Haul Command — Playbook End-to-End Test
// app/api/command/playbooks/test/route.ts
//
// Executes a full playbook cycle to validate the entire Command Layer
// pipeline: playbook → task decomposition → agent assignment →
// heartbeat reporting → money tracking → board visibility.
//
// GET /api/command/playbooks/test?market=AU&dry_run=true
// =====================================================================

import { createClient } from '@supabase/supabase-js';
import { NextRequest, NextResponse } from 'next/server';

const supabase = createClient(
  process.env.NEXT_PUBLIC_SUPABASE_URL!,
  process.env.SUPABASE_SERVICE_ROLE_KEY!
);

export async function GET(req: NextRequest) {
  const market = req.nextUrl.searchParams.get('market') || 'AU';
  const dryRun = req.nextUrl.searchParams.get('dry_run') !== 'false';

  const testResults: Record<string, any> = {
    test_id: `e2e_${Date.now()}`,
    market,
    dry_run: dryRun,
    started_at: new Date().toISOString(),
    steps: [],
  };

  try {
    // ── STEP 1: Verify agent roster is populated ──
    const { count: agentCount } = await supabase
      .from('hc_command_agents')
      .select('*', { count: 'exact', head: true });

    testResults.steps.push({
      step: 1,
      name: 'Agent Roster Check',
      status: (agentCount ?? 0) >= 40 ? 'PASS' : 'FAIL',
      detail: `${agentCount} agents registered (need 40+)`,
    });

    // ── STEP 2: Verify heartbeat definitions exist ──
    const { count: heartbeatCount } = await supabase
      .from('hc_command_heartbeats')
      .select('*', { count: 'exact', head: true });

    testResults.steps.push({
      step: 2,
      name: 'Heartbeat Definitions Check',
      status: (heartbeatCount ?? 0) >= 15 ? 'PASS' : 'FAIL',
      detail: `${heartbeatCount} heartbeat definitions (need 15+)`,
    });

    // ── STEP 3: Verify money trigger function exists ──
    const { data: triggerCheck } = await supabase
      .rpc('command_agent_health_summary')
      .single();

    testResults.steps.push({
      step: 3,
      name: 'Health Summary RPC Check',
      status: triggerCheck ? 'PASS' : 'FAIL',
      detail: triggerCheck || 'RPC not found',
    });

    // ── STEP 4: Execute playbook (market launch simulation) ──
    const { data: playbook } = await supabase
      .from('hc_command_playbooks')
      .select('*')
      .eq('slug', 'market-launch-tier-a')
      .single();

    testResults.steps.push({
      step: 4,
      name: 'Playbook Lookup',
      status: playbook ? 'PASS' : 'WARN',
      detail: playbook ? `Found: ${playbook.name}` : 'Tier-A playbook not found (will use default)',
    });

    // ── STEP 5: Simulate task creation from playbook ──
    if (!dryRun) {
      const testTasks = [
        { title: `[TEST] SEO Seed: ${market} pilot car pages`, domain: 'seo', priority: 2 },
        { title: `[TEST] Geo Aggregator: Seed ${market} listings`, domain: 'geo', priority: 2 },
        { title: `[TEST] AdGrid: Create ${market} ad inventory`, domain: 'adgrid', priority: 3 },
        { title: `[TEST] Content: Generate ${market} blog articles`, domain: 'content', priority: 3 },
        { title: `[TEST] Compliance: Map ${market} regulations`, domain: 'compliance', priority: 4 },
      ];

      const { data: createdTasks, error: taskErr } = await supabase
        .from('hc_command_tasks')
        .insert(testTasks.map(t => ({
          title: t.title,
          description: `Auto-generated by playbook test for market ${market}`,
          domain: t.domain,
          market: market,
          priority: t.priority,
          status: 'todo',
        })))
        .select();

      testResults.steps.push({
        step: 5,
        name: 'Task Creation',
        status: createdTasks?.length === testTasks.length ? 'PASS' : 'FAIL',
        detail: `Created ${createdTasks?.length ?? 0}/${testTasks.length} tasks`,
        task_ids: createdTasks?.map(t => t.id),
      });
    } else {
      testResults.steps.push({
        step: 5,
        name: 'Task Creation (DRY RUN)',
        status: 'SKIP',
        detail: 'Skipped in dry run mode. Set dry_run=false to execute.',
      });
    }

    // ── STEP 6: Simulate heartbeat ──
    if (!dryRun) {
      // Find the content-engine agent
      const { data: contentAgent } = await supabase
        .from('hc_command_agents')
        .select('id')
        .eq('slug', 'content-engine')
        .single();

      if (contentAgent) {
        // Create a test run
        const { data: testRun } = await supabase
          .from('hc_command_runs')
          .insert({
            agent_id: contentAgent.id,
            status: 'running',
            started_at: new Date().toISOString(),
            trigger: 'e2e_test',
          })
          .select('id')
          .single();

        // Complete the run
        if (testRun) {
          await supabase
            .from('hc_command_runs')
            .update({
              status: 'completed',
              completed_at: new Date().toISOString(),
              result: { test: true, market, pages_generated: 5 },
              entities_processed: 5,
              pages_published: 5,
            })
            .eq('id', testRun.id);

          testResults.steps.push({
            step: 6,
            name: 'Heartbeat Simulation',
            status: 'PASS',
            detail: `Run ${testRun.id} created and completed`,
          });
        }
      } else {
        testResults.steps.push({
          step: 6,
          name: 'Heartbeat Simulation',
          status: 'FAIL',
          detail: 'content-engine agent not found',
        });
      }
    } else {
      testResults.steps.push({
        step: 6,
        name: 'Heartbeat Simulation (DRY RUN)',
        status: 'SKIP',
        detail: 'Skipped in dry run mode',
      });
    }

    // ── STEP 7: Simulate money event ──
    if (!dryRun) {
      const { data: moneyEvt } = await supabase
        .from('hc_command_money_events')
        .insert({
          event_type: 'revenue',
          amount_cents: 9900,
          currency: 'usd',
          source: 'e2e_test',
          market: market,
          metadata: { test: true },
        })
        .select('id')
        .single();

      testResults.steps.push({
        step: 7,
        name: 'Money Event',
        status: moneyEvt ? 'PASS' : 'FAIL',
        detail: moneyEvt ? `Money event ${moneyEvt.id} logged ($99.00)` : 'Insert failed',
      });
    } else {
      testResults.steps.push({
        step: 7,
        name: 'Money Event (DRY RUN)',
        status: 'SKIP',
        detail: 'Skipped in dry run mode',
      });
    }

    // ── STEP 8: Verify Board API returns data ──
    const boardRes = await fetch(`${process.env.NEXT_PUBLIC_SITE_URL || 'http://localhost:3000'}/api/command/board`);
    const boardData = boardRes.ok ? await boardRes.json() : null;

    testResults.steps.push({
      step: 8,
      name: 'Board API Health',
      status: boardRes.ok ? 'PASS' : 'FAIL',
      detail: boardRes.ok
        ? `Board returned: ${boardData?.agents?.rollup?.total ?? 0} agents, ${boardData?.runs?.total ?? 0} runs`
        : `Board API returned ${boardRes.status}`,
    });

    // ── STEP 9: Verify unified activity view ──
    const { count: unifiedCount } = await supabase
      .from('command_unified_activity')
      .select('*', { count: 'exact', head: true });

    testResults.steps.push({
      step: 9,
      name: 'Unified Activity View',
      status: (unifiedCount ?? 0) >= 0 ? 'PASS' : 'FAIL',
      detail: `${unifiedCount ?? 0} total activity records (swarm + command)`,
    });

    // ── STEP 10: Verify money dashboard view ──
    const { data: moneyDash } = await supabase
      .from('command_money_dashboard')
      .select('*');

    testResults.steps.push({
      step: 10,
      name: 'Money Dashboard View',
      status: 'PASS',
      detail: `${moneyDash?.length ?? 0} revenue stream sources tracked`,
    });

    // ── SCORE ──
    const passed = testResults.steps.filter((s: any) => s.status === 'PASS').length;
    const failed = testResults.steps.filter((s: any) => s.status === 'FAIL').length;
    const skipped = testResults.steps.filter((s: any) => s.status === 'SKIP').length;
    const warned = testResults.steps.filter((s: any) => s.status === 'WARN').length;
    const total = testResults.steps.length;

    testResults.completed_at = new Date().toISOString();
    testResults.score = {
      passed,
      failed,
      skipped,
      warned,
      total,
      pass_rate: `${Math.round((passed / (total - skipped)) * 100)}%`,
      verdict: failed === 0 ? 'PASS' : failed <= 2 ? 'CONDITIONAL_PASS' : 'FAIL',
    };

    // Log test result to os_event_log
    await supabase.from('os_event_log').insert({
      event_type: 'command.e2e_test',
      entity_type: 'playbook_test',
      entity_id: testResults.test_id,
      payload: testResults.score,
    });

    return NextResponse.json(testResults, { status: failed === 0 ? 200 : 207 });
  } catch (err: any) {
    testResults.error = err.message;
    return NextResponse.json(testResults, { status: 500 });
  }
}
