CREATE TABLE IF NOT EXISTS state_regulations (
    state_code VARCHAR(2) PRIMARY KEY,
    state_name VARCHAR(50) NOT NULL,
    permit_authority_name VARCHAR(255),
    permit_authority_url TEXT,
    max_width_ft NUMERIC(5,2),
    max_height_ft NUMERIC(5,2),
    max_length_ft NUMERIC(5,2),
    max_gross_weight_lbs INTEGER,
    escort_required_width_ft NUMERIC(5,2),
    night_travel_allowed BOOLEAN,
    sunday_travel_allowed BOOLEAN,
    notes TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Note: The max measurements generally represent routine issue limits before engineering reviews (Superload) are required.
-- Regulations are subject to frequent changes; these values serve as the foundational routing logic.

INSERT INTO state_regulations (
    state_code, state_name, permit_authority_name, permit_authority_url, 
    max_width_ft, max_height_ft, max_length_ft, max_gross_weight_lbs, 
    escort_required_width_ft, night_travel_allowed, sunday_travel_allowed, notes
) VALUES
('AL', 'Alabama', 'ALDOT Permit Office', 'https://www.dot.state.al.us/publications/Design/pdf/SizeAndWeightLaws.pdf', 16.00, 16.00, 150.00, 150000, 12.00, false, false, 'Superloads evaluated over 150k lbs.'),
('AK', 'Alaska', 'Alaska DOT&PF Commercial Vehicle', 'https://dot.alaska.gov/mscve/', 14.00, 15.00, 120.00, 150000, 10.50, true, true, 'Regulations differ heavily by Dalton Highway vs other areas. Night travel generally permitted if properly lit.'),
('AZ', 'Arizona', 'ADOT Commercial Vehicle Permits', 'https://azdot.gov/motor-vehicles/commercial-services', 14.00, 16.00, 120.00, 250000, 14.00, true, true, 'Night travel allowed for moderate overweight on Interstates. Restrictions in Phoenix/Tucson metros.'),
('AR', 'Arkansas', 'ARDOT Permit Office', 'https://www.ardot.gov/divisions/highway-police/permits/', 20.00, 17.00, 150.00, 200000, 12.00, false, false, 'Travel prohibited on major holidays.'),
('CA', 'California', 'Caltrans Transportation Permits', 'https://dot.ca.gov/programs/traffic-operations/transportation-permits', 15.00, 17.00, 135.00, 250000, 12.00, false, false, 'Distinct regional rules. Extracon fines for non-compliance extremely high. Pilot car rules vary heavily by route.'),
('CO', 'Colorado', 'CDOT Freight & Permits', 'https://www.codot.gov/business/permits/freight', 17.00, 16.00, 130.00, 200000, 14.00, false, false, 'Mountain passes may require chain laws or complete closures for OSOW during winter months.'),
('CT', 'Connecticut', 'ConnDOT OS/OW Permits', 'https://portal.ct.gov/DOT/Permits/Oversize-Overweight-Vehicle-Permits', 14.00, 15.00, 120.00, 130000, 12.00, false, false, 'Very congested. Curfews heavily enforced in Hartford, New Haven, Waterbury areas.'),
('DE', 'Delaware', 'DelDOT Hauling Permits', 'https://deldot.gov/Business/dmt/index.shtml', 15.00, 15.00, 120.00, 120000, 12.00, false, false, 'No travel allowed on holidays/Sundays. Night moves explicitly forbidden.'),
('FL', 'Florida', 'FDOT Permit Office', 'https://www.fdot.gov/maintenance/owb.shtm', 16.00, 16.00, 150.00, 150000, 12.00, true, true, 'Blanket authority for night travel width up to 10 feet. Extremely restrictive in Keys (Monroe County).'),
('GA', 'Georgia', 'GDOT Oversize Permits', 'https://www.dot.ga.gov/GDOT/Pages/OversizePermits.aspx', 16.00, 16.00, 150.00, 150000, 12.00, false, false, 'No movement permitted during inclement weather or heavy fog.'),
('HI', 'Hawaii', 'HDOT Highways Division', 'https://hidot.hawaii.gov/highways/', 12.00, 14.00, 100.00, 100000, 12.00, false, false, 'Islands restrict large movements, frequent police escorts required.'),
('ID', 'Idaho', 'ITD Commercial Vehicle Services', 'https://itd.idaho.gov/cvs/', 16.00, 16.00, 150.00, 200000, 14.00, true, true, 'Up to 10'' wide can travel 24/7 on interstates.'),
('IL', 'Illinois', 'IDOT Permits', 'https://idot.illinois.gov/doing-business/permits/truck-size-weight-permits.html', 14.50, 15.00, 145.00, 120000, 14.50, false, false, 'Cook County / Chicago has specific heavy haul restrictions.'),
('IN', 'Indiana', 'INDOT OSW Permits', 'https://www.in.gov/dor/motor-carrier-services/osow-permits/', 16.00, 15.00, 110.00, 200000, 14.00, false, true, 'Sunday travel allowed from 12 PM (noon) to sunset for certain load sizes.'),
('IA', 'Iowa', 'Iowa DOT Motor Carrier', 'https://iowadot.gov/mvd/motorcarriers/motorcarriers', 16.00, 18.00, 120.00, 156000, 14.50, false, false, 'Superload status above 156,000 lbs. Good infrastructure backing heavy haul on farm corridors.'),
('KS', 'Kansas', 'KDOT Commercial Vehicle', 'https://www.truckingks.org/', 16.50, 17.00, 125.00, 150000, 14.00, true, true, 'Travel 24/7 allowed if width <= 10'' and proper lighting installed.'),
('KY', 'Kentucky', 'KYTC Overweight Permits', 'https://drive.ky.gov/Motor-Carriers/Pages/Oversize-Overweight.aspx', 16.00, 15.00, 115.00, 160000, 12.00, false, false, 'Escort required if over 10.5 ft on two-lane roads.'),
('LA', 'Louisiana', 'LADOTD Truck Permits', 'http://wwwsp.dotd.la.gov/Inside_LaDOTD/Divisions/Multimodal/Motor_Carrier/Pages/default.aspx', 16.00, 16.00, 125.00, 250000, 12.00, false, false, 'Very strict enforcement. New Orleans curfews.'),
('ME', 'Maine', 'MaineDOT Commercial Vehicles', 'https://www.maine.gov/sos/bmv/commercial/', 16.00, 16.00, 125.00, 130000, 12.00, false, false, 'Seasonal weight limits (spring thaw).'),
('MD', 'Maryland', 'MDOT SHA Hauling Permits', 'https://www.roads.maryland.gov/mdotsha/pages/index.aspx?PageId=292', 15.00, 16.00, 120.00, 150000, 13.00, false, false, 'Nighttime restricted. Check local county curfews.'),
('MA', 'Massachusetts', 'MassDOT Commercial Vehicle', 'https://www.mass.gov/heavy-commercial-vehicle-permits', 14.00, 15.00, 115.00, 130000, 12.00, false, false, 'Extensive bridge restrictions in the Boston area.'),
('MI', 'Michigan', 'MDOT Transport Permits', 'https://www.michigan.gov/mdot/business/permits', 16.00, 15.00, 150.00, 164000, 12.00, false, false, 'Highest unpermitted weight limits in the USA but strictly mandated axle groupings.'),
('MN', 'Minnesota', 'MnDOT Commercial Vehicle Operations', 'https://www.dot.state.mn.us/cvo/', 14.50, 16.00, 130.00, 145000, 14.50, false, false, 'Spring thaw restrictions aggressively enforced.'),
('MS', 'Mississippi', 'MDOT Permit Office', 'https://mdot.ms.gov/portal/permits', 16.00, 16.00, 120.00, 150000, 12.00, false, false, 'Continuous travel prohibited over 10 ft width. No Sunday travel.'),
('MO', 'Missouri', 'MoDOT Motor Carrier Services', 'https://www.modot.org/motor-carrier-services', 16.00, 16.00, 150.00, 160000, 12.00, true, true, 'Up to 10 wide allowed standard 24 hr. Routine limits are generous.'),
('MT', 'Montana', 'MDT Motor Carrier Services', 'https://www.mdt.mt.gov/business/mcs/', 18.00, 17.00, 150.00, 250000, 12.50, true, true, 'Night travel allowed if dimensions are low. Superload over 250K lbs.'),
('NE', 'Nebraska', 'NDOT Truck Permits', 'https://dot.nebraska.gov/business-center/permits/', 16.00, 16.00, 130.00, 160000, 12.00, false, false, 'Interstate and State highways vary greatly for escorts.'),
('NV', 'Nevada', 'NDOT Overdimensional Permits', 'https://www.dot.nv.gov/doing-business/commercial-vehicles', 17.00, 16.00, 110.00, 250000, 14.00, true, true, 'Night movement often allowed. Vegas/Reno have heavy curfews.'),
('NH', 'New Hampshire', 'NHDOT Overweight Permits', 'https://www.nh.gov/dot/org/operations/highwaymaintenance/overweight.htm', 14.50, 14.50, 100.00, 130000, 12.00, false, false, 'Tight secondary roads. Very restrictive.'),
('NJ', 'New Jersey', 'NJDOT Commercial Vehicle', 'https://www.state.nj.us/transportation/freight/cvo/', 14.00, 14.00, 120.00, 150000, 12.00, false, false, 'Extensive bridge issues. Major delays obtaining superloads.'),
('NM', 'New Mexico', 'NMDOT Motor Transportation', 'https://dot.state.nm.us/', 15.00, 16.00, 140.00, 170000, 14.00, false, false, 'Front escort required for anything over 14ft tall.'),
('NY', 'New York', 'NYSDOT Oversize Permits', 'https://www.dot.ny.gov/nypermits', 16.00, 16.00, 115.00, 200000, 12.00, false, false, 'NYC operates completely separate and requires different permits and rules. Statewide is restrictive.'),
('NC', 'North Carolina', 'NCDOT Oversize Permits', 'https://www.ncdot.gov/business/motor-carrier/', 15.00, 15.00, 115.00, 130000, 12.00, false, false, 'No holiday travel. Very difficult routing through mountains.'),
('ND', 'North Dakota', 'NDDOT Motor Carrier', 'https://www.dot.nd.gov/divisions/highways/commercial_vehicle.htm', 18.00, 18.00, 150.00, 200000, 14.50, true, true, 'Heavy haul very common due to oil and wind logistics.'),
('OH', 'Ohio', 'ODOT Special Hauling Permits', 'https://www.transportation.ohio.gov/working/permits/special-hauling', 14.00, 14.50, 120.00, 120000, 12.00, false, false, 'Turnpike has separate regulations.'),
('OK', 'Oklahoma', 'ODOT Oversize Permits', 'https://www.dps.state.ok.us/size_and_weight/', 16.00, 17.00, 130.00, 200000, 12.00, false, false, '14ft width requires 2 escorts on 2 lanes.'),
('OR', 'Oregon', 'ODOT Commerce and Compliance', 'https://www.oregon.gov/odot/mct/pages/index.aspx', 16.00, 17.00, 150.00, 250000, 12.00, true, true, 'Night travel heavily permitted. Weight formulas very specific.'),
('PA', 'Pennsylvania', 'PennDOT Hauling Permits', 'https://www.penndot.pa.gov/doing-business/permits/hauling/', 15.00, 15.00, 120.00, 201000, 13.00, false, false, 'Superload begins at 201,000 lbs. Bridges are heavily inspected.'),
('RI', 'Rhode Island', 'RIDOT Overweight Permits', 'https://www.dot.ri.gov/about/permits.php', 14.00, 14.00, 100.00, 130000, 12.00, false, false, 'Very congested. Strict curfews.'),
('SC', 'South Carolina', 'SCDOT Oversize', 'https://www.scdot.org/business/oversize.aspx', 16.00, 16.00, 125.00, 130000, 12.00, false, false, 'Escort on 2 lanes at 12 wide, 14 wide on interstate.'),
('SD', 'South Dakota', 'SDDOT Motor Carrier Information', 'https://dot.sd.gov/doing-business/motor-carriers', 18.00, 17.00, 130.00, 200000, 16.00, true, true, 'Lenient rules for agriculture/heavy haul. Very wide escort threshold on interstates.'),
('TN', 'Tennessee', 'TDOT Oversize & Overweight Permits', 'https://www.tn.gov/tdot/commercial-vehicle-services.html', 16.00, 15.00, 120.00, 165000, 12.50, false, false, 'Curfews in major cities (Nashville, Memphis, Knoxville, Chattanooga).'),
('TX', 'Texas', 'TxDMV Motor Carrier', 'https://www.txdmv.gov/motor-carriers/oversize-overweight-permits', 20.00, 18.00, 180.00, 250000, 14.00, false, false, 'Permits widely issued but superloads >254K require special engineering.'),
('UT', 'Utah', 'UDOT Motor Carrier', 'https://motorcarrier.utah.gov/', 17.00, 17.00, 150.00, 250000, 14.00, true, true, 'Very clear regulations. Allows huge combinations.'),
('VT', 'Vermont', 'VTrans Commercial Vehicle', 'https://vtrans.vermont.gov/commercial-vehicles', 14.00, 14.00, 100.00, 130000, 12.00, false, false, 'Bridge issues extreme. Thaw restrictions extreme.'),
('VA', 'Virginia', 'VDOT Hauling Permits', 'https://www.dmv.virginia.gov/commercial/#hauling.asp', 15.00, 15.00, 115.00, 150000, 12.00, false, false, 'No travel in Hampton Roads tunnels for OSOW.'),
('WA', 'Washington', 'WSDOT Commercial Vehicles', 'https://wsdot.wa.gov/travel/commercial-vehicles', 16.00, 16.00, 125.00, 200000, 11.00, true, true, 'Night movement standard in Seattle metro to avoid traffic.'),
('WV', 'West Virginia', 'WVDOH Special Permitting', 'https://transportation.wv.gov/highways/maintenance/Pages/hauling_permits.aspx', 15.00, 15.00, 110.00, 120000, 12.00, false, false, 'Mountains make routing very tedious with height/width.'),
('WI', 'Wisconsin', 'WisDOT Oversize/Overweight', 'https://wisconsindot.gov/Pages/dmv/com-drv-vehs/oversz-overwt/default.aspx', 16.00, 16.00, 150.00, 170000, 12.00, false, false, 'Fox Valley and Milwaukee curfews apply.'),
('WY', 'Wyoming', 'WYDOT Commercial Vehicles', 'https://www.dot.state.wy.us/home/trucking_commercial_vehicles.html', 18.00, 17.00, 130.00, 250000, 14.00, true, true, 'Very high wind restrictions routinely shut down light loads but OSOW restricted mostly by visibility.')
ON CONFLICT (state_code) DO UPDATE SET
    state_name = EXCLUDED.state_name,
    permit_authority_name = EXCLUDED.permit_authority_name,
    permit_authority_url = EXCLUDED.permit_authority_url,
    max_width_ft = EXCLUDED.max_width_ft,
    max_height_ft = EXCLUDED.max_height_ft,
    max_length_ft = EXCLUDED.max_length_ft,
    max_gross_weight_lbs = EXCLUDED.max_gross_weight_lbs,
    escort_required_width_ft = EXCLUDED.escort_required_width_ft,
    night_travel_allowed = EXCLUDED.night_travel_allowed,
    sunday_travel_allowed = EXCLUDED.sunday_travel_allowed,
    notes = EXCLUDED.notes,
    updated_at = NOW();
