-- WAVE-10: Complete Canonical 120 Country Seed
INSERT INTO country_registry (iso, name, tier, launch_status)
VALUES
  ('US', 'United States', 'A', 'live'),
  ('CA', 'Canada', 'A', 'live'),
  ('AU', 'Australia', 'A', 'expanding'),
  ('GB', 'United Kingdom', 'A', 'expanding'),
  ('NZ', 'New Zealand', 'A', 'waitlist'),
  ('ZA', 'South Africa', 'A', 'waitlist'),
  ('DE', 'Germany', 'A', 'waitlist'),
  ('NL', 'Netherlands', 'A', 'waitlist'),
  ('AE', 'United Arab Emirates', 'A', 'waitlist'),
  ('BR', 'Brazil', 'A', 'waitlist'),
  ('IE', 'Ireland', 'B', 'waitlist'),
  ('SE', 'Sweden', 'B', 'waitlist'),
  ('NO', 'Norway', 'B', 'waitlist'),
  ('DK', 'Denmark', 'B', 'waitlist'),
  ('FI', 'Finland', 'B', 'waitlist'),
  ('BE', 'Belgium', 'B', 'waitlist'),
  ('AT', 'Austria', 'B', 'waitlist'),
  ('CH', 'Switzerland', 'B', 'waitlist'),
  ('ES', 'Spain', 'B', 'waitlist'),
  ('FR', 'France', 'B', 'waitlist'),
  ('IT', 'Italy', 'B', 'waitlist'),
  ('PT', 'Portugal', 'B', 'waitlist'),
  ('SA', 'Saudi Arabia', 'B', 'waitlist'),
  ('QA', 'Qatar', 'B', 'waitlist'),
  ('MX', 'Mexico', 'B', 'waitlist'),
  ('IN', 'India', 'B', 'waitlist'),
  ('ID', 'Indonesia', 'B', 'waitlist'),
  ('TH', 'Thailand', 'B', 'waitlist'),
  ('PL', 'Poland', 'C', 'waitlist'),
  ('CZ', 'Czechia', 'C', 'waitlist'),
  ('SK', 'Slovakia', 'C', 'waitlist'),
  ('HU', 'Hungary', 'C', 'waitlist'),
  ('SI', 'Slovenia', 'C', 'waitlist'),
  ('EE', 'Estonia', 'C', 'waitlist'),
  ('LV', 'Latvia', 'C', 'waitlist'),
  ('LT', 'Lithuania', 'C', 'waitlist'),
  ('HR', 'Croatia', 'C', 'waitlist'),
  ('RO', 'Romania', 'C', 'waitlist'),
  ('BG', 'Bulgaria', 'C', 'waitlist'),
  ('GR', 'Greece', 'C', 'waitlist'),
  ('TR', 'Türkiye', 'C', 'waitlist'),
  ('KW', 'Kuwait', 'C', 'waitlist'),
  ('OM', 'Oman', 'C', 'waitlist'),
  ('BH', 'Bahrain', 'C', 'waitlist'),
  ('SG', 'Singapore', 'C', 'waitlist'),
  ('MY', 'Malaysia', 'C', 'waitlist'),
  ('JP', 'Japan', 'C', 'waitlist'),
  ('KR', 'South Korea', 'C', 'waitlist'),
  ('CL', 'Chile', 'C', 'waitlist'),
  ('AR', 'Argentina', 'C', 'waitlist'),
  ('CO', 'Colombia', 'C', 'waitlist'),
  ('PE', 'Peru', 'C', 'waitlist'),
  ('VN', 'Vietnam', 'C', 'waitlist'),
  ('PH', 'Philippines', 'C', 'waitlist'),
  ('UY', 'Uruguay', 'D', 'waitlist'),
  ('PA', 'Panama', 'D', 'waitlist'),
  ('CR', 'Costa Rica', 'D', 'waitlist'),
  ('IL', 'Israel', 'D', 'waitlist'),
  ('NG', 'Nigeria', 'D', 'waitlist'),
  ('EG', 'Egypt', 'D', 'waitlist'),
  ('KE', 'Kenya', 'D', 'waitlist'),
  ('MA', 'Morocco', 'D', 'waitlist'),
  ('RS', 'Serbia', 'D', 'waitlist'),
  ('UA', 'Ukraine', 'D', 'waitlist'),
  ('KZ', 'Kazakhstan', 'D', 'waitlist'),
  ('TW', 'Taiwan', 'D', 'waitlist'),
  ('PK', 'Pakistan', 'D', 'waitlist'),
  ('BD', 'Bangladesh', 'D', 'waitlist'),
  ('MN', 'Mongolia', 'D', 'waitlist'),
  ('TT', 'Trinidad & Tobago', 'D', 'waitlist'),
  ('JO', 'Jordan', 'D', 'waitlist'),
  ('GH', 'Ghana', 'D', 'waitlist'),
  ('TZ', 'Tanzania', 'D', 'waitlist'),
  ('GE', 'Georgia', 'D', 'waitlist'),
  ('AZ', 'Azerbaijan', 'D', 'waitlist'),
  ('CY', 'Cyprus', 'D', 'waitlist'),
  ('IS', 'Iceland', 'D', 'waitlist'),
  ('LU', 'Luxembourg', 'D', 'waitlist'),
  ('EC', 'Ecuador', 'D', 'waitlist'),
  ('BO', 'Bolivia', 'E', 'waitlist'),
  ('PY', 'Paraguay', 'E', 'waitlist'),
  ('GT', 'Guatemala', 'E', 'waitlist'),
  ('DO', 'Dominican Republic', 'E', 'waitlist'),
  ('HN', 'Honduras', 'E', 'waitlist'),
  ('SV', 'El Salvador', 'E', 'waitlist'),
  ('NI', 'Nicaragua', 'E', 'waitlist'),
  ('JM', 'Jamaica', 'E', 'waitlist'),
  ('GY', 'Guyana', 'E', 'waitlist'),
  ('SR', 'Suriname', 'E', 'waitlist'),
  ('BA', 'Bosnia & Herzegovina', 'E', 'waitlist'),
  ('ME', 'Montenegro', 'E', 'waitlist'),
  ('MK', 'North Macedonia', 'E', 'waitlist'),
  ('AL', 'Albania', 'E', 'waitlist'),
  ('MD', 'Moldova', 'E', 'waitlist'),
  ('IQ', 'Iraq', 'E', 'waitlist'),
  ('NA', 'Namibia', 'E', 'waitlist'),
  ('AO', 'Angola', 'E', 'waitlist'),
  ('MZ', 'Mozambique', 'E', 'waitlist'),
  ('ET', 'Ethiopia', 'E', 'waitlist'),
  ('CI', 'Côte d’Ivoire', 'E', 'waitlist'),
  ('SN', 'Senegal', 'E', 'waitlist'),
  ('BW', 'Botswana', 'E', 'waitlist'),
  ('ZM', 'Zambia', 'E', 'waitlist'),
  ('UG', 'Uganda', 'E', 'waitlist'),
  ('CM', 'Cameroon', 'E', 'waitlist'),
  ('KH', 'Cambodia', 'E', 'waitlist'),
  ('LK', 'Sri Lanka', 'E', 'waitlist'),
  ('UZ', 'Uzbekistan', 'E', 'waitlist'),
  ('LA', 'Laos', 'E', 'waitlist'),
  ('NP', 'Nepal', 'E', 'waitlist'),
  ('DZ', 'Algeria', 'E', 'waitlist'),
  ('TN', 'Tunisia', 'E', 'waitlist'),
  ('MT', 'Malta', 'E', 'waitlist'),
  ('BN', 'Brunei', 'E', 'waitlist'),
  ('RW', 'Rwanda', 'E', 'waitlist'),
  ('MG', 'Madagascar', 'E', 'waitlist'),
  ('PG', 'Papua New Guinea', 'E', 'waitlist'),
  ('TM', 'Turkmenistan', 'E', 'waitlist'),
  ('KG', 'Kyrgyzstan', 'E', 'waitlist'),
  ('MW', 'Malawi', 'E', 'waitlist')
ON CONFLICT (iso) DO UPDATE SET tier = EXCLUDED.tier, launch_status = EXCLUDED.launch_status;
