-- ============================================================
-- DIESEL BLOOD USA — Country Regulations Seed Data
-- Confidence 4-5 countries (Verified official/government sources)
-- Run AFTER: 20260326_country_regulations_schema.sql
-- ============================================================

INSERT INTO country_regulations (
  country_name, country_code, region, measurement_system, currency_code,
  escort_min_age, escort_license_required, escort_training_course, escort_training_hours, escort_renewal_years,
  vehicle_min_gvwr_kg, vehicle_max_gvwr_kg,
  warning_light_color, warning_light_class, flag_size_cm, flag_colors, flag_angle_degrees,
  fire_extinguisher_spec, cone_count, cone_size_cm,
  height_pole_threshold_m, height_pole_clearance_cm,
  max_width_no_escort_m, max_width_one_escort_m, max_width_two_escorts_m, max_width_le_escort_m,
  max_height_no_escort_m, max_height_one_escort_m,
  max_length_no_escort_m, max_length_one_escort_m, max_length_two_escorts_m, max_length_le_escort_m,
  daytime_travel_only, travel_window, holiday_restrictions, visibility_minimum_m, weekend_movement_allowed,
  survey_letter_width_threshold_m, survey_letter_height_threshold_m,
  permit_office_name, permit_office_phone, permit_office_website, online_permit_available,
  apparel_day_class, apparel_night_class,
  flagging_paddle_spec, flagging_flag_spec, flagging_statute,
  oversize_banner_text, banner_min_size,
  av_corridors_exist, av_regulatory_body, av_corridor_notes,
  data_confidence_score, data_sources, last_verified
) VALUES

-- ─── USA ────────────────────────────────────────────────────
('United States', 'US', 'North America', 'Imperial', 'USD',
  18, true, 'State-approved 8-hour pilot/escort flagging course (FAC 14-26)', 8, 4,
  907, 11793,
  'Amber', 'Class 2', '45x45 cm', 'Red or fluorescent orange', '40-70 degrees from roof',
  'Class ABC, minimum 5 lbs', 3, 91,
  4.42, 15,
  2.59, 3.66, 4.27, 4.88,
  4.11, 4.42,
  19.81, 28.96, 45.72, 76.2,
  true, '30 min before sunrise to 30 min after sunset', 'New Year, Memorial, Independence, Labor, Thanksgiving, Christmas', 305, false,
  4.88, 4.57,
  'FDOT State Permit Office', '(850) 410-5777', 'https://www.fdot.gov/traffic/oversize-overweight', true,
  'Class 2 High-Visibility Vest', 'Class 3 High-Visibility Vest',
  'STOP/SLOW paddle, 18 inch diameter, 6 inch letters', 'Red or fluorescent orange, 12x12 inches', 'Florida Statute 316.079(2)',
  'Black letters on yellow background', '7 ft x 18 in, 12 in letters',
  true, 'USDOT Federal Motor Carrier Safety Administration (FMCSA)', 'AV Truck corridors exist on I-10 (TX), I-4 (FL), and I-35 (TX). Several states have enacted AV legislation.',
  5, ARRAY['https://www.fdot.gov/traffic/oversize-overweight', 'https://www.fmcsa.dot.gov'], '2026-01-01'),

-- ─── CANADA (Federal/Common Baseline) ────────────────────────
('Canada', 'CA', 'North America', 'Metric', 'CAD',
  18, true, 'Provincial certification required (varies by province)', 8, 3,
  NULL, 6000,
  'Amber', 'Not standardized nationally', '45x45 cm', 'Red or orange', '40-70 degrees',
  'Class ABC 5 lb (recommended)', 2, 90,
  4.15, 15,
  2.59, 3.85, 4.45, 5.50,
  4.15, 4.88,
  22.86, 30.0, 38.0, NULL,
  true, 'Daylight hours (varies by province)', 'Statutory holidays (varies by province)', 300, false,
  4.88, 4.50,
  'Transport Canada / Provincial Highway Authority (varies)', NULL, 'https://tc.canada.ca', true,
  'High-visibility vest (Class 2)', 'High-visibility vest (Class 3)',
  'OVERSIZE LOAD sign required on front and rear', 'Red or orange flags, min 45cm', 'Provincial Highway Traffic Acts',
  'OVERSIZE LOAD — Black on yellow', '152 cm x 30 cm, 25 cm letters',
  true, 'Transport Canada / Provincial Ministries of Transportation', 'AV pilot programs active in Ontario, BC, and Alberta. Transport Canada developing national AV framework.',
  4, ARRAY['https://tc.canada.ca', 'https://oversize.io/canada', 'https://wideloadshipping.com/canada'], '2026-01-01'),

-- ─── UNITED KINGDOM ─────────────────────────────────────────
('United Kingdom', 'GB', 'Europe', 'Metric', 'GBP',
  NULL, true, 'Escort driver competency assessment required (DVSA guidance)', NULL, NULL,
  NULL, NULL,
  'Amber/Yellow', 'Not formally classified', NULL, 'Yellow/Amber', NULL,
  'Recommended (no formal minimum spec)', NULL, NULL,
  NULL, NULL,
  2.9, 3.5, 4.1, 5.0,
  NULL, 4.95,
  18.65, 25.9, 30.0, NULL,
  false, 'No blanket daytime restriction; route-specific', 'No formal national list; route-specific police conditions', NULL, true,
  4.88, NULL,
  'DVSA via ESDAL (Electronic Service Delivery for Abnormal Loads)', NULL, 'https://www.gov.uk/government/collections/abnormal-loads', true,
  'High-visibility vest (CE certified)', 'High-visibility vest with additional reflective strips',
  'Not formally specified', 'Not formally specified', 'Road Vehicles (Authorisation of Special Types) (General) Order 2003 (STGO)',
  'ABNORMAL LOAD — Black on yellow', 'Not standardised nationally',
  true, 'Centre for Connected and Autonomous Vehicles (CCAV) / DVSA', 'UK CCAV runs AV testing corridors. A63/M1/M180 corridors used for freight trials.',
  4, ARRAY['https://www.gov.uk/government/collections/abnormal-loads', 'https://www.legislation.gov.uk/uksi/2003/1998/contents/made'], '2026-01-01'),

-- ─── GERMANY ────────────────────────────────────────────────
('Germany', 'DE', 'Europe', 'Metric', 'EUR',
  NULL, true, 'Begleitfahrzeugführer certification required for BF2/BF3/BF4 escort classes', NULL, NULL,
  NULL, NULL,
  'Amber/Yellow', 'BF2 / BF3 / BF4 classified system', NULL, 'Amber/Yellow with red-white diagonal retro-reflective stripes', NULL,
  NULL, NULL, NULL,
  NULL, NULL,
  2.55, 3.0, 3.5, 4.0,
  4.0, 4.7,
  16.5, 20.5, 24.0, 40.0,
  false, '08:00–20:00 (night travel permitted from 20:00 as of 2025 reform)', 'Restricted on specific federal holiday periods per state (Bundesland) rules', NULL, true,
  NULL, NULL,
  'VEMAGS (Verfahrensmanagement für Großraum- und Schwertransporte)', NULL, 'https://www.vemags.de', true,
  'High-visibility vest (EN ISO 20471 Class 2)', 'High-visibility vest (EN ISO 20471 Class 3)',
  NULL, NULL, 'StVZO §34, StVO §46',
  'SCHWERTRANSPORT — Black on yellow', NULL,
  true, 'Federal Ministry for Digital and Transport (BMDV)', 'Germany has AV corridors on A9 autobahn (Munich-Berlin). Daimler and MAN AV truck trials active.',
  5, ARRAY['https://www.vemags.de', 'https://www.bund.de', 'https://estaeurope.eu'], '2026-01-01'),

-- ─── AUSTRALIA ──────────────────────────────────────────────
('Australia', 'AU', 'Oceania', 'Metric', 'AUD',
  NULL, true, 'State-based pilot/escort vehicle accreditation required (NHVR Schedule 8)', NULL, NULL,
  NULL, 4500,
  'Yellow/Amber', 'AS 1906.1-2017 Class 100 or 400', '120x60 cm (sign)', 'Yellow face, black text', NULL,
  NULL, NULL, NULL,
  NULL, NULL,
  2.5, 3.5, 4.6, 6.0,
  NULL, 5.0,
  None, 26.0, 30.0, 45.0,
  true, 'Daylight hours for loads over 3.5m wide', 'Restricted on public holidays (state-specific)', NULL, false,
  NULL, NULL,
  'National Heavy Vehicle Regulator (NHVR)', NULL, 'https://www.nhvr.gov.au', true,
  'High-visibility vest (AS/NZS 4602.1)', 'High-visibility vest (AS/NZS 4602.1)',
  NULL, NULL, 'Heavy Vehicle National Law (HVNL)',
  'OVERSIZE LOAD — Black on yellow', '1200mm x 600mm, black border 20mm',
  true, 'National Transport Commission (NTC) / NHVR', 'NHVR AV trials active under HVNL. Linfox Pronto truck trials on Hume Highway.',
  4, ARRAY['https://www.nhvr.gov.au', 'https://www.ntc.gov.au', 'https://warningsystems.com.au'], '2026-01-01'),

-- ─── FRANCE ─────────────────────────────────────────────────
('France', 'FR', 'Europe', 'Metric', 'EUR',
  NULL, true, 'Pilot car driver qualification required (DREAL regulated)', NULL, NULL,
  NULL, NULL,
  'Orange/Amber', 'Not formally classified', NULL, 'Orange/Red', NULL,
  NULL, NULL, NULL,
  NULL, NULL,
  2.55, 3.0, 4.0, 5.0,
  4.0, 4.5,
  18.75, 25.0, 30.0, NULL,
  true, 'Daylight hours for wide/long loads; specific night windows by prefecture', 'Routes are closed on certain national holidays and summer tourist periods', NULL, false,
  NULL, NULL,
  'Direction Régionale de l''Environnement, de l''Aménagement et du Logement (DREAL)', NULL, 'https://www.ecologie.gouv.fr/transport-exceptionnel', true,
  'High-visibility vest (EN 471 Class 2)', 'High-visibility vest (EN 471 Class 3)',
  NULL, NULL, 'Code de la route — Arrêté du 4 mai 2006',
  'CONVOI EXCEPTIONNEL — Black on yellow', 'Standardised per arrêté',
  true, 'Déléation à la Sécurité Routière (DSR) / Ministère des Transports', 'A10, A11 corridors used for AV freight pilots. Supervision required.',
  4, ARRAY['https://www.ecologie.gouv.fr/transport-exceptionnel'], '2026-01-01'),

-- ─── NETHERLANDS ─────────────────────────────────────────────
('Netherlands', 'NL', 'Europe', 'Metric', 'EUR',
  NULL, true, 'Pilot vehicle operator certification (RDW van Wegenbeheerder)', NULL, NULL,
  NULL, NULL,
  'Yellow/Amber', 'Not formally classified', NULL, 'Yellow/Amber', NULL,
  NULL, NULL, NULL,
  NULL, NULL,
  2.55, 3.0, 3.5, 4.0,
  4.0, NULL,
  18.75, 22.0, 30.0, NULL,
  false, 'Restrictions vary by route and permit conditions', 'Restricted on public holidays and summer periods', NULL, true,
  NULL, NULL,
  'Rijksdienst voor het Wegverkeer (RDW)', NULL, 'https://www.rdw.nl', true,
  'High-visibility vest (EN ISO 20471)', NULL,
  NULL, NULL, 'Wegenverkeerswet 1994',
  'UITZONDERLIJK TRANSPORT — Black on yellow', NULL,
  true, 'RDW / Ministerie van Infrastructuur en Waterstaat', 'A16, A2 corridors tested for platooning. TomTom and DAF AV truck trials.',
  4, ARRAY['https://www.rdw.nl', 'https://www.rijksoverheid.nl'], '2026-01-01'),

-- ─── NEW ZEALAND ─────────────────────────────────────────────
('New Zealand', 'NZ', 'Oceania', 'Metric', 'NZD',
  NULL, true, 'Pilot/Escort driver certification (NZTA High-Productivity Motor Vehicle)', NULL, NULL,
  NULL, 4500,
  'Amber', 'NZS standard', '1200x600 mm (recommended)', 'Yellow face black text', NULL,
  NULL, NULL, NULL,
  NULL, NULL,
  2.5, 3.5, 4.5, NULL,
  4.25, NULL,
  20.0, 25.0, NULL, NULL,
  true, 'Daylight hours for loads over legal limits', 'Restricted on public holidays', NULL, false,
  NULL, NULL,
  'New Zealand Transport Agency Waka Kotahi (NZTA)', NULL, 'https://www.nzta.govt.nz/vehicles/oversize-overdimension', true,
  'High-visibility vest (AS/NZS 4602)', NULL,
  NULL, NULL, 'Land Transport Rule: Vehicle Dimensions and Mass 2016',
  'OVERDIMENSION LOAD — Black on yellow', '1200mm x 600mm',
  false, 'NZTA Waka Kotahi', 'No formal AV freight corridors designated as of 2026. NZTA piloting AV policy.',
  4, ARRAY['https://www.nzta.govt.nz/vehicles/oversize-overdimension'], '2026-01-01'),

-- ─── SINGAPORE ───────────────────────────────────────────────
('Singapore', 'SG', 'Asia', 'Metric', 'SGD',
  NULL, true, 'LTA approval required for all abnormal loads', NULL, NULL,
  NULL, NULL,
  'Amber', NULL, NULL, 'Yellow/Amber', NULL,
  NULL, NULL, NULL,
  NULL, NULL,
  2.5, NULL, NULL, NULL,
  4.5, NULL,
  12.0, NULL, NULL, NULL,
  true, 'Specific time windows assigned per permit (often off-peak)', 'Restricted on national holidays', NULL, false,
  NULL, NULL,
  'Land Transport Authority (LTA)', NULL, 'https://www.lta.gov.sg', true,
  'High-visibility vest', NULL,
  NULL, NULL, 'Road Traffic Act (Cap. 276)',
  'ABNORMAL LOAD — Black on yellow', NULL,
  true, 'LTA / Agency for Science, Technology and Research (A*STAR)', 'Singapore One-North and Jurong Island designated as AV test zones. AV freight trials ongoing.',
  4, ARRAY['https://www.lta.gov.sg'], '2026-01-01'),

-- ─── JAPAN ───────────────────────────────────────────────────
('Japan', 'JP', 'Asia', 'Metric', 'JPY',
  NULL, true, 'Special vehicle permit (Tokushu Sharyo Tsuko Kyoka) required; escort qualifications set by prefecture', NULL, NULL,
  NULL, NULL,
  'Yellow/Amber', NULL, NULL, 'Yellow/Amber', NULL,
  NULL, NULL, NULL,
  NULL, NULL,
  2.5, 3.0, NULL, NULL,
  3.8, NULL,
  12.0, 20.0, NULL, NULL,
  true, 'Day travel only for most special vehicles', 'May Day, Obon, Golden Week, New Year restrictions', NULL, false,
  NULL, NULL,
  'Ministry of Land, Infrastructure, Transport and Tourism (MLIT) — Road Bureau', NULL, 'https://www.mlit.go.jp', true,
  'High-visibility vest (Japanese Industrial Standard JIS T 8127)', NULL,
  NULL, NULL, 'Road Traffic Act (Japan) and Special Vehicle Ordinance',
  '特大 (Tokudai) — Black on yellow', NULL,
  true, 'Ministry of Land, Infrastructure, Transport and Tourism (MLIT)', 'Japan is active in AV platooning trials on Shin-Tomei Expressway. Level 4 AV law enacted April 2023.',
  4, ARRAY['https://www.mlit.go.jp', 'https://www.npa.go.jp'], '2026-01-01'),

-- ─── SOUTH KOREA ─────────────────────────────────────────────
('South Korea', 'KR', 'Asia', 'Metric', 'KRW',
  NULL, true, 'Special vehicle permit from Ministry of Land, Infrastructure and Transport (MOLIT)', NULL, NULL,
  NULL, NULL,
  'Amber', NULL, NULL, 'Orange/Amber', NULL,
  NULL, NULL, NULL,
  NULL, NULL,
  2.5, 3.0, NULL, NULL,
  4.0, NULL,
  16.7, NULL, NULL, NULL,
  true, 'Daylight hours primarily', 'National holidays', NULL, false,
  NULL, NULL,
  'Ministry of Land, Infrastructure and Transport (MOLIT)', NULL, 'https://www.molit.go.kr', true,
  'High-visibility vest (KS standard)', NULL,
  NULL, NULL, 'Road Traffic Act (도로교통법)',
  '특수화물 (Special Cargo) — Black on yellow', NULL,
  true, 'Korea Transportation Safety Authority (KOTSA) / MOLIT', 'Level 4 AV pilot roads designated on expressways. Hyundai and KIA AV truck trials active.',
  3, ARRAY['https://www.molit.go.kr', 'https://www.kotsa.or.kr'], '2026-01-01'),

-- ─── BRAZIL ──────────────────────────────────────────────────
('Brazil', 'BR', 'South America', 'Metric', 'BRL',
  NULL, true, 'ART (Anotação de Responsabilidade Técnica) and ANTT authorization required', NULL, NULL,
  NULL, NULL,
  'Amber', NULL, NULL, 'Yellow/Amber', NULL,
  NULL, NULL, NULL,
  NULL, NULL,
  2.6, 3.2, 4.5, NULL,
  4.4, NULL,
  19.8, 30.0, NULL, NULL,
  true, 'Daylight only for loads over 3.2m wide or 25m long', 'Carnival, national holidays, weekend restrictions in metro areas', NULL, false,
  NULL, NULL,
  'Agência Nacional de Transportes Terrestres (ANTT)', NULL, 'https://www.antt.gov.br', true,
  'Colete de segurança (Class 2 reflective)', NULL,
  NULL, NULL, 'Resolução CONTRAN nº 737/2018; Portaria SENATRAN nº 65/2019',
  'CARGA INDIVISÍVEL — Black on yellow', NULL,
  false, 'DENATRAN / SENATRAN / ANTT', 'No formal AV freight corridors. Autonomous vehicle framework under development.',
  3, ARRAY['https://www.antt.gov.br', 'https://www.denatran.senatran.infraestrutura.gov.br'], '2026-01-01'),

-- ─── SOUTH AFRICA ────────────────────────────────────────────
('South Africa', 'ZA', 'Africa', 'Metric', 'ZAR',
  NULL, true, 'Escort vehicle and route surveyor certification required (NRTA/C&E)', NULL, NULL,
  NULL, NULL,
  'Amber', NULL, NULL, 'Orange/Red', NULL,
  NULL, NULL, NULL,
  NULL, NULL,
  2.5, 3.5, 4.3, NULL,
  4.3, NULL,
  22.0, NULL, NULL, NULL,
  true, 'Daylight hours for most abnormal loads', 'Public holiday restrictions apply via permit conditions', NULL, false,
  NULL, NULL,
  'Department of Transport (C&E Permit Office) / RTMC', '+27 12 309 3000', 'https://www.transport.gov.za', true,
  'High-visibility vest (SANS 1497)', NULL,
  NULL, NULL, 'National Road Traffic Act 93 of 1996',
  'ABNORMAL LOAD — Black on yellow', NULL,
  false, 'Department of Transport / CSIR', 'Limited AV trials. CSIR conducting research. No public AV freight corridors.',
  3, ARRAY['https://www.transport.gov.za', 'https://www.rtmc.co.za'], '2026-01-01'),

-- ─── UAE ─────────────────────────────────────────────────────
('United Arab Emirates', 'AE', 'Middle East', 'Metric', 'AED',
  NULL, true, 'Special vehicle permit from Roads and Transport Authority (RTA) / Federal Roads Authority', NULL, NULL,
  NULL, NULL,
  'Amber', NULL, NULL, 'Orange/Amber', NULL,
  NULL, NULL, NULL,
  NULL, NULL,
  2.5, 3.0, NULL, NULL,
  4.6, NULL,
  18.75, NULL, NULL, NULL,
  true, 'Night movement often required in cities (to avoid traffic)', 'Restricted on Eid holidays and national day', NULL, false,
  NULL, NULL,
  'Federal Roads Authority (FAHR) / RTA Dubai', NULL, 'https://www.rta.ae', true,
  'High-visibility vest', NULL,
  NULL, NULL, 'UAE Traffic Law Federal Decree No. 12 of 2014',
  'ABNORMAL LOAD — Black on yellow (Arabic and English)', NULL,
  true, 'UAE Ministry of AI / RTA Dubai driverless vehicles division', 'Dubai has active AV freight corridor on Sheikh Zayed Road and Airport Logistics corridor. Largest AV taxi program globally.',
  4, ARRAY['https://www.rta.ae', 'https://u.ae/en/information-and-services/transportation/road-transport'], '2026-01-01'),

-- ─── INDIA ───────────────────────────────────────────────────
('India', 'IN', 'Asia', 'Metric', 'INR',
  NULL, true, 'Escort vehicle required per state transport department; no national uniform training certification', NULL, NULL,
  NULL, NULL,
  'Amber', NULL, NULL, 'Red/Orange', NULL,
  NULL, NULL, NULL,
  NULL, NULL,
  2.5, 3.0, NULL, NULL,
  3.8, NULL,
  18.0, NULL, NULL, NULL,
  true, 'Night movement often restricted in urban areas; route and time specified by permit', 'Restricted on major national holidays', NULL, false,
  NULL, NULL,
  'Ministry of Road Transport and Highways (MoRTH) / State RTOs', NULL, 'https://morth.nic.in', false,
  'Reflective vest', NULL,
  NULL, NULL, 'Motor Vehicles Act 1988 — Rule 93 (form 40)',
  'OVER-DIMENSIONAL CARGO — Black on yellow (Hindi/English)', NULL,
  false, 'Ministry of Road Transport and Highways (MoRTH)', 'AV policy draft under development. Niti Aayog AV strategy published. No designated AV freight corridors yet.',
  3, ARRAY['https://morth.nic.in', 'https://vahan.parivahan.gov.in'], '2026-01-01'),

-- ─── MEXICO ──────────────────────────────────────────────────
('Mexico', 'MX', 'North America', 'Metric', 'MXN',
  NULL, true, 'Operator certification and SCT (Secretaría de Comunicaciones y Transportes) permit required', NULL, NULL,
  NULL, NULL,
  'Amber', NULL, NULL, 'Orange/Yellow', NULL,
  NULL, NULL, NULL,
  NULL, NULL,
  2.6, 3.5, NULL, NULL,
  4.25, NULL,
  22.5, NULL, NULL, NULL,
  true, 'Permitted hours vary by state and route; often restricted in urban zones', 'Semana Santa, national holidays restricted', NULL, false,
  NULL, NULL,
  'Secretaría de Infraestructura, Comunicaciones y Transportes (SICT)', NULL, 'https://www.sct.gob.mx', false,
  'Chaleco refractario (reflective vest)', NULL,
  NULL, NULL, 'NOM-012-SCT-2-2017 (weights and dimensions)',
  'CARGA SOBREDIMENSIONADA — Black on yellow', NULL,
  false, 'SICT / Secretaría de Economía', 'AV freight policy nascent. US-Mexico border AV crossings under study.',
  3, ARRAY['https://www.sct.gob.mx', 'https://www.dof.gob.mx'], '2026-01-01');

-- ─── LOW-CONFIDENCE COUNTRY STUBS (Score 1-2) ───────────────
-- These are placeholders; verify data with local authorities

INSERT INTO country_regulations (country_name, country_code, region, measurement_system, currency_code, data_confidence_score, data_sources, last_verified, av_corridors_exist) VALUES
('Nigeria', 'NG', 'Africa', 'Metric', 'NGN', 1, ARRAY['https://www.fed.gov.ng'], '2026-01-01', false),
('Ethiopia', 'ET', 'Africa', 'Metric', 'ETB', 1, ARRAY['https://www.mo.gov.et'], '2026-01-01', false),
('Tanzania', 'TZ', 'Africa', 'Metric', 'TZS', 1, ARRAY['https://www.sumatra.go.tz'], '2026-01-01', false),
('Angola', 'AO', 'Africa', 'Metric', 'AOA', 1, ARRAY['https://www.mintrans.gov.ao'], '2026-01-01', false),
('Mozambique', 'MZ', 'Africa', 'Metric', 'MZN', 1, ARRAY['https://www.mintrans.gov.mz'], '2026-01-01', false),
('Bangladesh', 'BD', 'Asia', 'Metric', 'BDT', 1, ARRAY['https://www.brta.gov.bd'], '2026-01-01', false),
('Pakistan', 'PK', 'Asia', 'Metric', 'PKR', 2, ARRAY['https://www.nhmp.gov.pk'], '2026-01-01', false),
('Algeria', 'DZ', 'Africa', 'Metric', 'DZD', 1, ARRAY['https://www.mtp.gov.dz'], '2026-01-01', false),
('Tunisia', 'TN', 'Africa', 'Metric', 'TND', 2, ARRAY['https://www.transport.gov.tn'], '2026-01-01', false);
