-- country_ingest_queue seeds
INSERT INTO country_ingest_queue (country_code, country_name, tier, crawl_priority, search_status, coverage_status) VALUES
('US', 'United States', 'Gold', 1, 'not_started', 'seeded_from_user_tier_map'),
('CA', 'Canada', 'Gold', 1, 'not_started', 'seeded_from_user_tier_map'),
('AU', 'Australia', 'Gold', 1, 'not_started', 'seeded_from_user_tier_map'),
('GB', 'United Kingdom', 'Gold', 1, 'not_started', 'seeded_from_user_tier_map'),
('NZ', 'New Zealand', 'Gold', 1, 'not_started', 'seeded_from_user_tier_map'),
('ZA', 'South Africa', 'Gold', 1, 'not_started', 'seeded_from_user_tier_map'),
('DE', 'Germany', 'Gold', 1, 'not_started', 'seeded_from_user_tier_map'),
('NL', 'Netherlands', 'Gold', 1, 'not_started', 'seeded_from_user_tier_map'),
('AE', 'United Arab Emirates', 'Gold', 1, 'not_started', 'seeded_from_user_tier_map'),
('BR', 'Brazil', 'Gold', 1, 'not_started', 'seeded_from_user_tier_map'),
('IE', 'Ireland', 'Blue', 2, 'not_started', 'seeded_from_user_tier_map'),
('SE', 'Sweden', 'Blue', 2, 'not_started', 'seeded_from_user_tier_map'),
('NO', 'Norway', 'Blue', 2, 'not_started', 'seeded_from_user_tier_map'),
('DK', 'Denmark', 'Blue', 2, 'not_started', 'seeded_from_user_tier_map'),
('FI', 'Finland', 'Blue', 2, 'not_started', 'seeded_from_user_tier_map'),
('BE', 'Belgium', 'Blue', 2, 'not_started', 'seeded_from_user_tier_map'),
('AT', 'Austria', 'Blue', 2, 'not_started', 'seeded_from_user_tier_map'),
('CH', 'Switzerland', 'Blue', 2, 'not_started', 'seeded_from_user_tier_map'),
('ES', 'Spain', 'Blue', 2, 'not_started', 'seeded_from_user_tier_map'),
('FR', 'France', 'Blue', 2, 'not_started', 'seeded_from_user_tier_map'),
('IT', 'Italy', 'Blue', 2, 'not_started', 'seeded_from_user_tier_map'),
('PT', 'Portugal', 'Blue', 2, 'not_started', 'seeded_from_user_tier_map'),
('SA', 'Saudi Arabia', 'Blue', 2, 'not_started', 'seeded_from_user_tier_map'),
('QA', 'Qatar', 'Blue', 2, 'not_started', 'seeded_from_user_tier_map'),
('MX', 'Mexico', 'Blue', 2, 'not_started', 'seeded_from_user_tier_map'),
('IN', 'India', 'Blue', 2, 'not_started', 'seeded_from_user_tier_map'),
('ID', 'Indonesia', 'Blue', 2, 'not_started', 'seeded_from_user_tier_map'),
('TH', 'Thailand', 'Blue', 2, 'not_started', 'seeded_from_user_tier_map'),
('PL', 'Poland', 'Silver', 3, 'not_started', 'seeded_from_user_tier_map'),
('CZ', 'Czech Republic', 'Silver', 3, 'not_started', 'seeded_from_user_tier_map'),
('SK', 'Slovakia', 'Silver', 3, 'not_started', 'seeded_from_user_tier_map'),
('HU', 'Hungary', 'Silver', 3, 'not_started', 'seeded_from_user_tier_map'),
('SI', 'Slovenia', 'Silver', 3, 'not_started', 'seeded_from_user_tier_map'),
('EE', 'Estonia', 'Silver', 3, 'not_started', 'seeded_from_user_tier_map'),
('LV', 'Latvia', 'Silver', 3, 'not_started', 'seeded_from_user_tier_map'),
('LT', 'Lithuania', 'Silver', 3, 'not_started', 'seeded_from_user_tier_map'),
('HR', 'Croatia', 'Silver', 3, 'not_started', 'seeded_from_user_tier_map'),
('RO', 'Romania', 'Silver', 3, 'not_started', 'seeded_from_user_tier_map'),
('BG', 'Bulgaria', 'Silver', 3, 'not_started', 'seeded_from_user_tier_map'),
('GR', 'Greece', 'Silver', 3, 'not_started', 'seeded_from_user_tier_map'),
('TR', 'Turkey', 'Silver', 3, 'not_started', 'seeded_from_user_tier_map'),
('KW', 'Kuwait', 'Silver', 3, 'not_started', 'seeded_from_user_tier_map'),
('OM', 'Oman', 'Silver', 3, 'not_started', 'seeded_from_user_tier_map'),
('BH', 'Bahrain', 'Silver', 3, 'not_started', 'seeded_from_user_tier_map'),
('SG', 'Singapore', 'Silver', 3, 'not_started', 'seeded_from_user_tier_map'),
('MY', 'Malaysia', 'Silver', 3, 'not_started', 'seeded_from_user_tier_map'),
('JP', 'Japan', 'Silver', 3, 'not_started', 'seeded_from_user_tier_map'),
('KR', 'South Korea', 'Silver', 3, 'not_started', 'seeded_from_user_tier_map'),
('CL', 'Chile', 'Silver', 3, 'not_started', 'seeded_from_user_tier_map'),
('AR', 'Argentina', 'Silver', 3, 'not_started', 'seeded_from_user_tier_map'),
('CO', 'Colombia', 'Silver', 3, 'not_started', 'seeded_from_user_tier_map'),
('PE', 'Peru', 'Silver', 3, 'not_started', 'seeded_from_user_tier_map'),
('VN', 'Vietnam', 'Silver', 3, 'not_started', 'seeded_from_user_tier_map'),
('PH', 'Philippines', 'Silver', 3, 'not_started', 'seeded_from_user_tier_map'),
('UY', 'Uruguay', 'Slate', 4, 'not_started', 'seeded_from_user_tier_map'),
('PA', 'Panama', 'Slate', 4, 'not_started', 'seeded_from_user_tier_map'),
('CR', 'Costa Rica', 'Slate', 4, 'not_started', 'seeded_from_user_tier_map'),
('IL', 'Israel', 'Slate', 4, 'not_started', 'seeded_from_user_tier_map'),
('NG', 'Nigeria', 'Slate', 4, 'not_started', 'seeded_from_user_tier_map'),
('EG', 'Egypt', 'Slate', 4, 'not_started', 'seeded_from_user_tier_map'),
('KE', 'Kenya', 'Slate', 4, 'not_started', 'seeded_from_user_tier_map'),
('MA', 'Morocco', 'Slate', 4, 'not_started', 'seeded_from_user_tier_map'),
('RS', 'Serbia', 'Slate', 4, 'not_started', 'seeded_from_user_tier_map'),
('UA', 'Ukraine', 'Slate', 4, 'not_started', 'seeded_from_user_tier_map'),
('KZ', 'Kazakhstan', 'Slate', 4, 'not_started', 'seeded_from_user_tier_map'),
('TW', 'Taiwan', 'Slate', 4, 'not_started', 'seeded_from_user_tier_map'),
('PK', 'Pakistan', 'Slate', 4, 'not_started', 'seeded_from_user_tier_map'),
('BD', 'Bangladesh', 'Slate', 4, 'not_started', 'seeded_from_user_tier_map'),
('MN', 'Mongolia', 'Slate', 4, 'not_started', 'seeded_from_user_tier_map'),
('TT', 'Trinidad and Tobago', 'Slate', 4, 'not_started', 'seeded_from_user_tier_map'),
('JO', 'Jordan', 'Slate', 4, 'not_started', 'seeded_from_user_tier_map'),
('GH', 'Ghana', 'Slate', 4, 'not_started', 'seeded_from_user_tier_map'),
('TZ', 'Tanzania', 'Slate', 4, 'not_started', 'seeded_from_user_tier_map'),
('GE', 'Georgia', 'Slate', 4, 'not_started', 'seeded_from_user_tier_map'),
('AZ', 'Azerbaijan', 'Slate', 4, 'not_started', 'seeded_from_user_tier_map'),
('CY', 'Cyprus', 'Slate', 4, 'not_started', 'seeded_from_user_tier_map'),
('IS', 'Iceland', 'Slate', 4, 'not_started', 'seeded_from_user_tier_map'),
('LU', 'Luxembourg', 'Slate', 4, 'not_started', 'seeded_from_user_tier_map'),
('EC', 'Ecuador', 'Slate', 4, 'not_started', 'seeded_from_user_tier_map'),
('BO', 'Bolivia', 'Copper', 5, 'not_started', 'seeded_from_user_tier_map'),
('PY', 'Paraguay', 'Copper', 5, 'not_started', 'seeded_from_user_tier_map'),
('GT', 'Guatemala', 'Copper', 5, 'not_started', 'seeded_from_user_tier_map'),
('DO', 'Dominican Republic', 'Copper', 5, 'not_started', 'seeded_from_user_tier_map'),
('HN', 'Honduras', 'Copper', 5, 'not_started', 'seeded_from_user_tier_map'),
('SV', 'El Salvador', 'Copper', 5, 'not_started', 'seeded_from_user_tier_map'),
('NI', 'Nicaragua', 'Copper', 5, 'not_started', 'seeded_from_user_tier_map'),
('JM', 'Jamaica', 'Copper', 5, 'not_started', 'seeded_from_user_tier_map'),
('GY', 'Guyana', 'Copper', 5, 'not_started', 'seeded_from_user_tier_map'),
('SR', 'Suriname', 'Copper', 5, 'not_started', 'seeded_from_user_tier_map'),
('BA', 'Bosnia and Herzegovina', 'Copper', 5, 'not_started', 'seeded_from_user_tier_map'),
('ME', 'Montenegro', 'Copper', 5, 'not_started', 'seeded_from_user_tier_map'),
('MK', 'North Macedonia', 'Copper', 5, 'not_started', 'seeded_from_user_tier_map'),
('AL', 'Albania', 'Copper', 5, 'not_started', 'seeded_from_user_tier_map'),
('MD', 'Moldova', 'Copper', 5, 'not_started', 'seeded_from_user_tier_map'),
('IQ', 'Iraq', 'Copper', 5, 'not_started', 'seeded_from_user_tier_map'),
('NA', 'Namibia', 'Copper', 5, 'not_started', 'seeded_from_user_tier_map'),
('AO', 'Angola', 'Copper', 5, 'not_started', 'seeded_from_user_tier_map'),
('MZ', 'Mozambique', 'Copper', 5, 'not_started', 'seeded_from_user_tier_map'),
('ET', 'Ethiopia', 'Copper', 5, 'not_started', 'seeded_from_user_tier_map'),
('CI', 'Cote d''Ivoire', 'Copper', 5, 'not_started', 'seeded_from_user_tier_map'),
('SN', 'Senegal', 'Copper', 5, 'not_started', 'seeded_from_user_tier_map'),
('BW', 'Botswana', 'Copper', 5, 'not_started', 'seeded_from_user_tier_map'),
('ZM', 'Zambia', 'Copper', 5, 'not_started', 'seeded_from_user_tier_map'),
('UG', 'Uganda', 'Copper', 5, 'not_started', 'seeded_from_user_tier_map'),
('CM', 'Cameroon', 'Copper', 5, 'not_started', 'seeded_from_user_tier_map'),
('KH', 'Cambodia', 'Copper', 5, 'not_started', 'seeded_from_user_tier_map'),
('LK', 'Sri Lanka', 'Copper', 5, 'not_started', 'seeded_from_user_tier_map'),
('UZ', 'Uzbekistan', 'Copper', 5, 'not_started', 'seeded_from_user_tier_map'),
('LA', 'Laos', 'Copper', 5, 'not_started', 'seeded_from_user_tier_map'),
('NP', 'Nepal', 'Copper', 5, 'not_started', 'seeded_from_user_tier_map'),
('DZ', 'Algeria', 'Copper', 5, 'not_started', 'seeded_from_user_tier_map'),
('TN', 'Tunisia', 'Copper', 5, 'not_started', 'seeded_from_user_tier_map'),
('MT', 'Malta', 'Copper', 5, 'not_started', 'seeded_from_user_tier_map'),
('BN', 'Brunei', 'Copper', 5, 'not_started', 'seeded_from_user_tier_map'),
('RW', 'Rwanda', 'Copper', 5, 'not_started', 'seeded_from_user_tier_map'),
('MG', 'Madagascar', 'Copper', 5, 'not_started', 'seeded_from_user_tier_map'),
('PG', 'Papua New Guinea', 'Copper', 5, 'not_started', 'seeded_from_user_tier_map'),
('TM', 'Turkmenistan', 'Copper', 5, 'not_started', 'seeded_from_user_tier_map'),
('KG', 'Kyrgyzstan', 'Copper', 5, 'not_started', 'seeded_from_user_tier_map'),
('MW', 'Malawi', 'Copper', 5, 'not_started', 'seeded_from_user_tier_map')
ON CONFLICT (country_code) DO NOTHING;

-- regulation_sources seeds
INSERT INTO regulation_sources (row_key, country_code, country_name, state_province, jurisdiction_level, source_type, year_stated, official_status, training_value_score, url, source_title, authority_name, language_code, notes) VALUES
('HC-001', 'US', 'United States', 'Florida', 'state', 'official_training_workbook', '2025', 'official', 98, 'https://www.eng.ufl.edu/techtransfer/wp-content/uploads/sites/251/2025/11/PE-Participant-Workbook-04-01-2025.pdf', 'PE Participant Workbook', 'University of Florida Tech Transfer', 'en', ''),
('HC-002', 'US', 'United States', 'New York', 'state', 'official_training_manual', '2025', 'official', 97, 'https://www.dot.ny.gov/portal/page/portal/nypermits/repository/Vehicle%20Escort%20Manual_Final_2025.pdf', 'Vehicle Escort Manual Final 2025', 'New York State Department of Transportation', 'en', ''),
('HC-003', 'US', 'United States', 'North Carolina', 'state', 'official_training_handbook', '2024', 'official', 96, 'https://connect.ncdot.gov/business/trucking/Documents/2024%20EVO%20Handbook.pdf', '2024 EVO Handbook', 'North Carolina Department of Transportation', 'en', ''),
('HC-004', 'US', 'United States', 'Georgia', 'state', 'official_training_workbook', 'undated_public_copy', 'official', 92, 'https://www.dot.ga.gov/PartnerSmart/permits/Documents/StudentWorkbook.pdf', 'Student Workbook', 'Georgia Department of Transportation', 'en', ''),
('HC-005', 'US', 'United States', 'Virginia', 'state', 'official_training_manual', 'undated_public_copy', 'official', 94, 'https://www.dmv.virginia.gov/sites/default/files/forms/hp405.pdf', 'Escort Vehicle Driver''s Manual', 'Virginia DMV', 'en', ''),
('HC-006', 'US', 'United States', 'Federal', 'federal', 'official_training_manual', '2017', 'official', 95, 'https://ops.fhwa.dot.gov/publications/fhwahop16050/fhwahop16050.pdf', 'Pilot/Escort Vehicle Operators Training Manual', 'Federal Highway Administration', 'en', ''),
('HC-007', 'CA', 'Canada', 'Alberta', 'province', 'official_training_handbook', '2019', 'official', 92, 'https://open.alberta.ca/dataset/e7e17bc6-80e2-425a-a915-56c30716d281/resource/a0156b1f-f8ff-4819-a065-59db945fb367/download/trans-escort-vehicle-operators-handbook.pdf', 'Escort Vehicle Operator''s Handbook', 'Government of Alberta', 'en', ''),
('HC-008', 'CA', 'Canada', 'British Columbia', 'province', 'official_operator_guide', '2026', 'official', 88, 'https://www2.gov.bc.ca/assets/gov/driving-and-transportation/cvse/commercial-transportation-manual/chapter-8.pdf', 'Commercial Transportation Manual Chapter 8', 'Government of British Columbia', 'en', ''),
('HC-009', 'AU', 'Australia', 'National', 'national', 'official_training_standard', 'undated_current_page', 'official', 86, 'https://www.nhvr.gov.au/document/229', 'Pilot and escort recognition and training – Information sheet', 'National Heavy Vehicle Regulator', 'en', ''),
('HC-010', 'AU', 'Australia', 'Queensland', 'state', 'official_operator_guide', '2023', 'official', 85, 'https://www.publications.qld.gov.au/dataset/4ab822b5-6ae5-44f8-934a-12c91badbb5a/resource/8bb71a5a-1423-4984-9226-e2da114affc0/download/queensland-access-conditions-guide-version-6-december-2023.pdf', 'Queensland Access Conditions Guide', 'Queensland Government', 'en', ''),
('HC-011', 'AU', 'Australia', 'South Australia', 'state', 'official_operator_guide', '2025', 'official', 90, 'https://www.sa.gov.au/__data/assets/pdf_file/0004/16177/Escorting-Guidelines.pdf', 'Escorting Guidelines for oversize and overmass vehicles and loads in South Australia', 'Government of South Australia', 'en', ''),
('HC-012', 'NZ', 'New Zealand', 'National', 'national', 'official_permit_manual', '2022', 'official', 84, 'https://www.nzta.govt.nz/assets/resources/vdam-permitting-manual/VDAM-Permitting-Manual-VOL-1-Record-of-Amends8-1-Aug-2022.pdf', 'Vehicle Dimensions and Mass Permitting Manual Volume 1', 'NZ Transport Agency Waka Kotahi', 'en', ''),
('HC-013', 'NZ', 'New Zealand', 'National', 'national', 'official_training_standard', '2023', 'official', 90, 'https://www.nzqa.govt.nz/nqfdocs/units/pdf/23892.pdf', 'Unit Standard 23892 - Pilot an overweight and overdimension load as a Class 1 certified pilot', 'New Zealand Qualifications Authority', 'en', ''),
('HC-014', 'GB', 'United Kingdom', 'National', 'national', 'official_operator_guide', '2012', 'official', 82, 'https://assets.publishing.service.gov.uk/media/5a801968e5274a2e8ab4e2db/Lighting_and_marking_COP_for_abnormal_load_self_escorting_vehicles_HE_rebranding_v1.pdf', 'Code of Practice for abnormal load self-escorting vehicles', 'UK Government', 'en', ''),
('HC-015', 'SE', 'Sweden', 'National', 'national', 'official_escort_certification', 'undated_current_page', 'official', 78, 'https://bransch.trafikverket.se/for-dig-i-branschen/vag/Transportdispens/nar-du-fatt-beslutet/Vagtransportledare/', 'Vägtransportledare', 'Trafikverket', 'sv', ''),
('HC-016', 'BE', 'Belgium', 'Wallonia', 'region', 'official_escort_certification', 'undated_current_page', 'official', 88, 'https://permis-environnement.spw.wallonie.be/contents/iodda/3984.html', 'Devenir accompagnateur de transport exceptionnel', 'Service public de Wallonie', 'fr', ''),
('HC-017', 'NL', 'Netherlands', 'National', 'national', 'official_permit_portal', 'undated_current_page', 'official', 80, 'https://www.rdw.nl/zakelijke-partners/exceptioneel-transport', 'Exceptioneel transport', 'RDW', 'nl', ''),
('HC-018', 'ES', 'Spain', 'National', 'national', 'official_operator_guide', '2022', 'official', 82, 'https://www.dgt.es/nuestros-servicios/autorizaciones-obras-y-usos-excepcionales-de-la-via/autorizaciones-especiales-de-circulacion/autorizaciones-complementarias-de-circulacion-para-vertes/comunicacion-de-inicio-de-viaje-acc/', 'Comunicación de inicio de viaje ACC', 'Dirección General de Tráfico', 'es', ''),
('HC-019', 'FI', 'Finland', 'National', 'national', 'official_operator_guide', '2020', 'official', 84, 'https://www.traficom.fi/sites/default/files/media/file/Erikoiskuljetusm%C3%A4%C3%A4r%C3%A4ys_FI.pdf', 'Erikoiskuljetukset ja erikoiskuljetusajoneuvot', 'Traficom', 'fi', ''),
('HC-020', 'FR', 'France', 'National', 'national', 'official_training_standard', '2011', 'official', 84, 'https://www.legifrance.gouv.fr/loda/id/JORFTEXT000023956514', 'Arrêté du 2 mai 2011 relatif aux modalités de mise en oeuvre de la formation professionnelle spécifique', 'Legifrance', 'fr', ''),
('HC-021', 'FR', 'France', 'National', 'national', 'official_statute_or_regulation', '2024', 'official', 82, 'https://www.legifrance.gouv.fr/loda/id/LEGITEXT000006053685', 'Arrêté du 4 mai 2006 relatif aux transports exceptionnels', 'Legifrance', 'fr', ''),
('HC-022', 'AT', 'Austria', 'National', 'national', 'official_permit_portal', 'undated_current_page', 'official', 76, 'https://www.asfinag.at/verkehr-sicherheit/lkw-bus/sondertransporte/', 'Sondertransporte', 'ASFINAG', 'de', ''),
('HC-023', 'JP', 'Japan', 'National', 'national', 'official_operator_guide', '2020', 'official', 85, 'https://www.mlit.go.jp/road/tokusya/haitijoken/pdf/03.pdf', '特殊車両の通行に係る誘導等ガイドライン', 'Ministry of Land Infrastructure Transport and Tourism', 'ja', ''),
('HC-024', 'JP', 'Japan', 'National', 'national', 'official_training_standard', '2020', 'official', 88, 'https://www.tokusya.ktr.mlit.go.jp/PR/pdf/videojuko-guide_202012.pdf', '特殊車両の通行に係る誘導等講習', 'Ministry of Land Infrastructure Transport and Tourism', 'ja', ''),
('HC-025', 'SG', 'Singapore', 'National', 'national', 'official_permit_portal', '2026', 'official', 83, 'https://onemotoring.lta.gov.sg/content/onemotoring/home/driving/commercial-vehicles.html', 'Commercial Vehicles', 'Land Transport Authority Singapore', 'en', ''),
('HC-026', 'SG', 'Singapore', 'National', 'national', 'official_operator_guide', '2014', 'official', 80, 'https://onemotoring.lta.gov.sg/content/dam/onemotoring/AHVMBrochure.pdf', 'AHVM Brochure', 'Land Transport Authority Singapore', 'en', ''),
('HC-027', 'BR', 'Brazil', 'National', 'national', 'official_training_manual', '2020', 'official', 90, 'https://www.gov.br/prf/pt-br/assuntos/escolta-de-cargas/m-17-manual-carga-indivisivel', 'M-017 - Manual dos Serviços de Escolta de Cargas Indivisíveis e Superdimensionadas', 'Polícia Rodoviária Federal', 'pt', ''),
('HC-028', 'BR', 'Brazil', 'National', 'national', 'official_statute_or_regulation', '2023', 'official', 88, 'https://www.gov.br/prf/pt-br/seguranca-viaria/escolta-de-cargas/copy_of_SEI_PRF46288632PortariaNormativa.pdf', 'Portaria Normativa PRF nº 24 de 26 de janeiro de 2023', 'Polícia Rodoviária Federal', 'pt', ''),
('HC-029', 'ZA', 'South Africa', 'National', 'national', 'official_permit_manual', '2010', 'official', 82, 'https://www.transport.gov.za/wp-content/uploads/2023/02/TRH11_AdministrativeGuidelines-1stEdition2010_Final_.pdf', 'TRH11 Administrative Guidelines for Granting Exemption Permits', 'Department of Transport South Africa', 'en', ''),
('HC-030', 'CL', 'Chile', 'National', 'national', 'official_permit_manual', '2023', 'official', 85, 'https://vialidad.mop.gob.cl/uploads/sites/9/2025/02/Manual_Autorizaciones_para_tansportes_especiales_v2023.pdf', 'Manual Autorizaciones para Transportes Especiales v2023', 'Dirección de Vialidad MOP', 'es', ''),
('HC-031', 'CL', 'Chile', 'National', 'national', 'official_permit_portal', '2026', 'official', 80, 'https://www.chileatiende.gob.cl/fichas/4429-autorizacion-para-que-vehiculos-con-sobrepeso-o-sobredimension-circulen-por-un-camino-publico', 'Autorización para vehículos con sobrepeso y/o sobredimensión', 'ChileAtiende / Dirección de Vialidad', 'es', ''),
('HC-032', 'CL', 'Chile', 'National', 'national', 'official_operator_guide', '2025', 'official', 78, 'https://vialidad.mop.gob.cl/uploads/sites/9/2025/11/Orientaciones-para-los-usuarios-de-servicios-de-escoltas-sobredimensionadas-2025.pdf', 'Orientaciones para los usuarios de servicios de escoltas sobredimensionadas 2025', 'Dirección de Vialidad MOP', 'es', '')
ON CONFLICT (row_key) DO NOTHING;
