import type {
  TopicHeroAnimationPreset,
  TopicHeroPageFamily,
  TopicHeroVisualPreset,
} from "./types";

export type TopicVisualOntologyEntry = {
  visualPreset: TopicHeroVisualPreset;
  animationPreset: TopicHeroAnimationPreset;
  visualObjects: string[];
  motionLanguage: string[];
  metadataLanguage: string[];
  conversionPurpose: string;
  accuracyGuardrails: string[];
};

const SHARED_GUARDRAILS = [
  "No fake official government seals, endorsements, badges, flags, road signs, or authority cues.",
  "No unsafe convoy layout, impossible escort markings, or misleading emergency/police appearance.",
  "No generic U.S.-only imagery or terminology on country-specific pages unless the page is explicitly U.S.",
  "No random AI text embedded inside images; visible text must be code-native or manually controlled.",
  "No unrelated generic trucking stock image when the page intent is permits, glossary, high pole, route survey, staging, training, or proof.",
];

export const TOPIC_VISUAL_ONTOLOGY: Record<TopicHeroPageFamily, TopicVisualOntologyEntry> = {
  homepage: {
    visualPreset: "command-center",
    animationPreset: "search-rotation",
    visualObjects: ["network map", "role chips", "proof cards", "market status", "next-action console"],
    motionLanguage: ["search placeholder rotation", "role chip drift", "network pulse"],
    metadataLanguage: ["global operating system", "120-country coverage", "role and market graph"],
    conversionPurpose: "Route visitors toward the highest-value role-specific next action.",
    accuracyGuardrails: SHARED_GUARDRAILS,
  },
  tools: {
    visualPreset: "tools-dashboard",
    animationPreset: "digits-tick",
    visualObjects: ["calculators", "route lines", "permit sheets", "measurement rulers", "escort-count cards", "rate cards"],
    motionLanguage: ["numbers ticking", "route line drawing", "dimension label pulse", "calculator cells pulsing"],
    metadataLanguage: ["calculator", "workflow", "tool family", "permit helper", "route support"],
    conversionPurpose: "Move tool intent into calculator use, provider search, load packets, and sponsor inventory.",
    accuracyGuardrails: SHARED_GUARDRAILS,
  },
  "tool-detail": {
    visualPreset: "tools-dashboard",
    animationPreset: "digits-tick",
    visualObjects: ["exact tool output", "inputs", "calculation cards", "related rules", "provider handoff"],
    motionLanguage: ["input pulse", "result reveal", "numbers ticking"],
    metadataLanguage: ["tool detail", "calculator", "workflow", "problem solved"],
    conversionPurpose: "Turn one calculation into a saved packet, provider match, claim path, or paid upgrade.",
    accuracyGuardrails: SHARED_GUARDRAILS,
  },
  glossary: {
    visualPreset: "semantic-map",
    animationPreset: "term-connect",
    visualObjects: ["term cards", "definition panels", "semantic graph nodes", "local terminology chips", "acronym badges"],
    motionLanguage: ["terms rotating", "nodes connecting", "definition reveal"],
    metadataLanguage: ["dictionary", "defined term", "semantic cluster", "local terminology"],
    conversionPurpose: "Convert learning intent into related tools, rules, training, providers, and sponsorable education surfaces.",
    accuracyGuardrails: SHARED_GUARDRAILS,
  },
  "glossary-term": {
    visualPreset: "semantic-map",
    animationPreset: "term-connect",
    visualObjects: ["term card", "examples", "related rules", "related tools", "training link"],
    motionLanguage: ["term-to-definition reveal", "related node connection"],
    metadataLanguage: ["defined term", "definition", "examples", "related terms"],
    conversionPurpose: "Move one definition into the next useful rule, tool, provider, or training path.",
    accuracyGuardrails: SHARED_GUARDRAILS,
  },
  regulations: {
    visualPreset: "regulatory-threshold",
    animationPreset: "threshold-sweep",
    visualObjects: ["permit documents", "threshold rulers", "country chips", "source-confidence meter", "authority path"],
    motionLanguage: ["ruler sweep", "country chip rotation", "confidence meter fill"],
    metadataLanguage: ["source confidence", "threshold", "authority path", "jurisdiction"],
    conversionPurpose: "Move rule intent into calculators, qualified provider search, correction flow, and data products.",
    accuracyGuardrails: SHARED_GUARDRAILS,
  },
  "regulation-detail": {
    visualPreset: "regulatory-threshold",
    animationPreset: "threshold-sweep",
    visualObjects: ["jurisdiction card", "threshold ruler", "official source path", "calculator handoff"],
    motionLanguage: ["threshold sweep", "source meter fill"],
    metadataLanguage: ["jurisdiction", "rule detail", "source-backed", "last reviewed"],
    conversionPurpose: "Turn one jurisdiction rule into verification, calculator use, provider discovery, or correction submission.",
    accuracyGuardrails: SHARED_GUARDRAILS,
  },
  training: {
    visualPreset: "training-badges",
    animationPreset: "badge-progress",
    visualObjects: ["badges", "certification cards", "module ladder", "operator report card", "rank progress"],
    motionLanguage: ["badge unlock", "progress fill", "module lighting"],
    metadataLanguage: ["course", "credential", "badge", "rank points", "career path"],
    conversionPurpose: "Move operators from learning intent into enrollment, report-card proof, and first-job readiness.",
    accuracyGuardrails: SHARED_GUARDRAILS,
  },
  "training-detail": {
    visualPreset: "training-badges",
    animationPreset: "badge-progress",
    visualObjects: ["course card", "module list", "credential badge", "rank impact", "report-card preview"],
    motionLanguage: ["module unlock", "rank point tick", "badge progress"],
    metadataLanguage: ["course instance", "training module", "badge", "credential"],
    conversionPurpose: "Convert course interest into enrollment, credential proof, and profile completion.",
    accuracyGuardrails: SHARED_GUARDRAILS,
  },
  directory: {
    visualPreset: "provider-graph",
    animationPreset: "pin-pulse",
    visualObjects: ["provider cards", "map pins", "role chips", "claim badges", "service-radius rings"],
    motionLanguage: ["map pins pulsing", "provider cards stacking", "role chips rotating"],
    metadataLanguage: ["provider graph", "claimable profile", "service area", "proof state"],
    conversionPurpose: "Move search intent into provider discovery, claims, load support packets, and AdGrid inventory.",
    accuracyGuardrails: SHARED_GUARDRAILS,
  },
  "directory-category": {
    visualPreset: "provider-graph",
    animationPreset: "pin-pulse",
    visualObjects: ["category provider cards", "role chips", "local map pins", "claim path"],
    motionLanguage: ["pin pulse", "role chip rotation"],
    metadataLanguage: ["provider category", "service area", "claimable", "near me"],
    conversionPurpose: "Turn category intent into provider contact, claim, sponsor gap, or support packet.",
    accuracyGuardrails: SHARED_GUARDRAILS,
  },
  profile: {
    visualPreset: "profile-proof-card",
    animationPreset: "trust-meter",
    visualObjects: ["operator card", "equipment coverage", "verification state", "service radius", "claim badge"],
    motionLanguage: ["trust meter fill", "service radius glow", "proof badge reveal"],
    metadataLanguage: ["profile", "trust card", "service area", "claim state"],
    conversionPurpose: "Move profile viewers into trust, contact, claim, upgrade, and return-loop actions.",
    accuracyGuardrails: SHARED_GUARDRAILS,
  },
  "route-intel": {
    visualPreset: "route-intel-map",
    animationPreset: "route-draw",
    visualObjects: ["route map", "convoy line", "clearance alerts", "staging nodes", "permit checkpoints"],
    motionLanguage: ["route path drawing", "hazard pulse", "checkpoint glow"],
    metadataLanguage: ["route intelligence", "clearance", "staging", "permit checkpoint"],
    conversionPurpose: "Move route intent into route checks, provider search, support packets, and corridor sponsor inventory.",
    accuracyGuardrails: SHARED_GUARDRAILS,
  },
  corridor: {
    visualPreset: "corridor-lane",
    animationPreset: "route-draw",
    visualObjects: ["lane endpoints", "demand signal", "rate card", "escort need", "staging support"],
    motionLanguage: ["lane draw", "demand pulse", "support node glow"],
    metadataLanguage: ["corridor", "lane", "route risk", "support points"],
    conversionPurpose: "Convert corridor interest into provider matching, sponsor inventory, route support, and data signals.",
    accuracyGuardrails: SHARED_GUARDRAILS,
  },
  "market-data": {
    visualPreset: "market-heatmap",
    animationPreset: "heat-breathe",
    visualObjects: ["heatmaps", "corridor demand bars", "rate trend cards", "shortage signals", "sponsor inventory"],
    motionLanguage: ["heatmap breathing", "rate bars changing", "demand counter ticking"],
    metadataLanguage: ["dataset", "market report", "demand index", "shortage signal"],
    conversionPurpose: "Move intelligence intent into data products, sponsor pricing, reports, and country expansion signals.",
    accuracyGuardrails: SHARED_GUARDRAILS,
  },
  "load-board": {
    visualPreset: "load-matching",
    animationPreset: "load-ticker",
    visualObjects: ["origin cards", "destination cards", "rate tag", "urgency badge", "capacity match"],
    motionLanguage: ["new-load ticker", "urgency pulse", "match score movement"],
    metadataLanguage: ["load", "origin", "destination", "urgency", "capacity"],
    conversionPurpose: "Move demand into load posting, provider matching, boosting, and saved lanes.",
    accuracyGuardrails: SHARED_GUARDRAILS,
  },
  "load-detail": {
    visualPreset: "load-matching",
    animationPreset: "load-ticker",
    visualObjects: ["move card", "origin/destination", "dimensions", "required support", "match panel"],
    motionLanguage: ["match score movement", "urgency pulse"],
    metadataLanguage: ["load detail", "dimensions", "route support", "urgency"],
    conversionPurpose: "Move one load into provider response, route checks, support packets, and boost options.",
    accuracyGuardrails: SHARED_GUARDRAILS,
  },
  country: {
    visualPreset: "country-market",
    animationPreset: "pin-pulse",
    visualObjects: ["local terminology", "country market status", "providers", "rules", "tools", "training"],
    motionLanguage: ["market status pulse", "local chip rotation", "map pin pulse"],
    metadataLanguage: ["country", "local terminology", "market maturity", "source confidence"],
    conversionPurpose: "Move country traffic into local rules, providers, tools, correction paths, and sponsor inventory.",
    accuracyGuardrails: SHARED_GUARDRAILS,
  },
  region: {
    visualPreset: "country-market",
    animationPreset: "pin-pulse",
    visualObjects: ["regional service areas", "state/province rules", "nearby providers", "corridors"],
    motionLanguage: ["regional pin pulse", "chip rotation"],
    metadataLanguage: ["region", "state", "province", "local availability"],
    conversionPurpose: "Move regional intent into near-me search, regulation checks, provider claims, and route support.",
    accuracyGuardrails: SHARED_GUARDRAILS,
  },
  city: {
    visualPreset: "country-market",
    animationPreset: "pin-pulse",
    visualObjects: ["city availability", "near-me map pins", "service category cards", "local corridors"],
    motionLanguage: ["near-me pin pulse", "service card reveal"],
    metadataLanguage: ["city", "near me", "local availability", "service area"],
    conversionPurpose: "Turn local search into request capture, claimable provider acquisition, and sponsor gaps.",
    accuracyGuardrails: SHARED_GUARDRAILS,
  },
  role: {
    visualPreset: "provider-graph",
    animationPreset: "search-rotation",
    visualObjects: ["role chips", "role path", "tools", "training", "directory bridge"],
    motionLanguage: ["role chip rotation", "next-action pulse"],
    metadataLanguage: ["role", "workflow", "money path", "trust objection"],
    conversionPurpose: "Move role recognition into one primary next best action and two secondary actions.",
    accuracyGuardrails: SHARED_GUARDRAILS,
  },
  service: {
    visualPreset: "provider-graph",
    animationPreset: "pin-pulse",
    visualObjects: ["service cards", "provider proof", "nearby coverage", "support packet"],
    motionLanguage: ["service chip rotation", "coverage pulse"],
    metadataLanguage: ["service", "provider category", "near me"],
    conversionPurpose: "Move service intent into provider search, claim, sponsor, and support packet flows.",
    accuracyGuardrails: SHARED_GUARDRAILS,
  },
  sponsor: {
    visualPreset: "sponsor-inventory",
    animationPreset: "heat-breathe",
    visualObjects: ["inventory tiles", "intent placement", "pricing signal", "sponsor slot"],
    motionLanguage: ["inventory glow", "demand pulse"],
    metadataLanguage: ["AdGrid", "sponsor slot", "intent inventory"],
    conversionPurpose: "Convert advertiser intent into sponsor checkout, pricing, and lead capture.",
    accuracyGuardrails: SHARED_GUARDRAILS,
  },
  claim: {
    visualPreset: "profile-proof-card",
    animationPreset: "trust-meter",
    visualObjects: ["claim card", "profile proof", "missing fields", "trust score"],
    motionLanguage: ["trust meter fill", "missing-field pulse"],
    metadataLanguage: ["claim", "profile", "proof", "verification"],
    conversionPurpose: "Move claim intent into profile correction, proof upload, upgrade, and return loop.",
    accuracyGuardrails: SHARED_GUARDRAILS,
  },
  pricing: {
    visualPreset: "sponsor-inventory",
    animationPreset: "digits-tick",
    visualObjects: ["plan cards", "value stack", "proof states", "upgrade path"],
    motionLanguage: ["value counter tick", "plan highlight"],
    metadataLanguage: ["pricing", "upgrade", "Pro", "sponsor"],
    conversionPurpose: "Move pricing traffic into the best paid action without fake scarcity.",
    accuracyGuardrails: SHARED_GUARDRAILS,
  },
  dashboard: {
    visualPreset: "utility-console",
    animationPreset: "none",
    visualObjects: ["context panel", "next action", "status card", "role message"],
    motionLanguage: ["static utility state"],
    metadataLanguage: ["dashboard", "account", "next action"],
    conversionPurpose: "Keep authenticated users oriented with one primary action and useful system status.",
    accuracyGuardrails: SHARED_GUARDRAILS,
  },
  admin: {
    visualPreset: "utility-console",
    animationPreset: "none",
    visualObjects: ["admin console", "status", "queue", "audit state"],
    motionLanguage: ["static utility state"],
    metadataLanguage: ["admin", "governance", "audit"],
    conversionPurpose: "Make internal system action clear without public SEO treatment.",
    accuracyGuardrails: SHARED_GUARDRAILS,
  },
  auth: {
    visualPreset: "utility-console",
    animationPreset: "none",
    visualObjects: ["secure access", "account action", "trust signal"],
    motionLanguage: ["static utility state"],
    metadataLanguage: ["auth", "sign in", "account"],
    conversionPurpose: "Move the user into authenticated work without generic blank screens.",
    accuracyGuardrails: SHARED_GUARDRAILS,
  },
  utility: {
    visualPreset: "utility-console",
    animationPreset: "none",
    visualObjects: ["context card", "status", "next action"],
    motionLanguage: ["static utility state"],
    metadataLanguage: ["utility", "system", "support"],
    conversionPurpose: "Prevent dead pages with a compact contextual action path.",
    accuracyGuardrails: SHARED_GUARDRAILS,
  },
};

export function getTopicVisualOntology(pageFamily: TopicHeroPageFamily): TopicVisualOntologyEntry {
  return TOPIC_VISUAL_ONTOLOGY[pageFamily] ?? TOPIC_VISUAL_ONTOLOGY.utility;
}
