/**
 * WorldMapView country data — 120 countries across 4 tiers
 * Extracted from WorldMapView.tsx for maintainability
 */

export interface TierCountry {
  iso: string;
  name: string;
  flag: string;
  tier: 'A' | 'B' | 'C' | 'D';
  operators: number;
  corridors: string[];
  live: boolean;
  nextMarket?: boolean; // explicitly planned next expansion
}

export const ALL_COUNTRIES: TierCountry[] = [
  // ── Tier A — Live (2 only: US + CA) ───────────────────────────
  { iso: 'US', name: 'United States', flag: '🇺🇸', tier: 'A', operators: 4200, corridors: ['I-10 Sun Belt', 'I-35 Central', 'I-40 Trans-Am', 'I-75 Southeast', 'I-95 East Coast'], live: true },
  { iso: 'CA', name: 'Canada', flag: '🇨🇦', tier: 'A', operators: 820, corridors: ['Trans-Canada Hwy', 'Hwy 401 Ontario', 'Hwy 2 Alberta'], live: true },

  // ── Tier B — Launching Soon (26: former Tier A + original Tier B) ──
  { iso: 'AU', name: 'Australia', flag: '🇦🇺', tier: 'B', operators: 0, corridors: ['Pacific Hwy', 'Hume Hwy', 'Stuart Hwy'], live: false, nextMarket: true },
  { iso: 'GB', name: 'United Kingdom', flag: '🇬🇧', tier: 'B', operators: 0, corridors: ['M1 London-Leeds', 'M6 North', 'A1(M)'], live: false },
  { iso: 'NZ', name: 'New Zealand', flag: '🇳🇿', tier: 'B', operators: 0, corridors: ['SH1 North', 'SH1 South'], live: false },
  { iso: 'ZA', name: 'South Africa', flag: '🇿🇦', tier: 'B', operators: 0, corridors: ['N1 Cape-JHB', 'N3 Durban', 'N4 Maputo'], live: false },
  { iso: 'DE', name: 'Germany', flag: '🇩🇪', tier: 'B', operators: 0, corridors: ['A1 Bremen-Cologne', 'A7 N-S', 'A3 Frankfurt'], live: false },
  { iso: 'NL', name: 'Netherlands', flag: '🇳🇱', tier: 'B', operators: 0, corridors: ['A15 Rotterdam', 'A2 Amsterdam-Eindhoven'], live: false },
  { iso: 'AE', name: 'UAE', flag: '🇦🇪', tier: 'B', operators: 0, corridors: ['E11 Sheikh Zayed', 'E311 Emirates'], live: false },
  { iso: 'BR', name: 'Brazil', flag: '🇧🇷', tier: 'B', operators: 0, corridors: ['BR-101 Coastal', 'BR-116 Dutra'], live: false },
  { iso: 'MX', name: 'Mexico', flag: '🇲🇽', tier: 'B', operators: 0, corridors: ['MEX-QRO Autopista'], live: false },
  { iso: 'FR', name: 'France', flag: '🇫🇷', tier: 'B', operators: 0, corridors: ['A1 Paris-Lille', 'A6 Paris-Lyon'], live: false },
  { iso: 'IT', name: 'Italy', flag: '🇮🇹', tier: 'B', operators: 0, corridors: ['A1 Autostrada del Sole'], live: false },
  { iso: 'ES', name: 'Spain', flag: '🇪🇸', tier: 'B', operators: 0, corridors: ['AP-7 Mediterranean'], live: false },
  { iso: 'IN', name: 'India', flag: '🇮🇳', tier: 'B', operators: 0, corridors: ['NH48 Delhi-Mumbai'], live: false },
  { iso: 'JP', name: 'Japan', flag: '🇯🇵', tier: 'B', operators: 0, corridors: ['Tomei Expressway'], live: false },
  { iso: 'KR', name: 'South Korea', flag: '🇰🇷', tier: 'B', operators: 0, corridors: ['Gyeongbu Expressway'], live: false },
  { iso: 'SE', name: 'Sweden', flag: '🇸🇪', tier: 'B', operators: 0, corridors: ['E6 Gothenburg-Malmö'], live: false },
  { iso: 'NO', name: 'Norway', flag: '🇳🇴', tier: 'B', operators: 0, corridors: ['E6 Oslo-Trondheim'], live: false },
  { iso: 'FI', name: 'Finland', flag: '🇫🇮', tier: 'B', operators: 0, corridors: ['E75 Helsinki-North'], live: false },
  { iso: 'PL', name: 'Poland', flag: '🇵🇱', tier: 'B', operators: 0, corridors: ['A2 Warsaw-Berlin'], live: false },
  { iso: 'AT', name: 'Austria', flag: '🇦🇹', tier: 'B', operators: 0, corridors: ['A1 Westautobahn'], live: false },
  { iso: 'BE', name: 'Belgium', flag: '🇧🇪', tier: 'B', operators: 0, corridors: ['E19 Brussels-Antwerp'], live: false },
  { iso: 'CH', name: 'Switzerland', flag: '🇨🇭', tier: 'B', operators: 0, corridors: ['A1 Geneva-Zurich'], live: false },
  { iso: 'DK', name: 'Denmark', flag: '🇩🇰', tier: 'B', operators: 0, corridors: ['E45 Aalborg-CPH'], live: false },
  { iso: 'SG', name: 'Singapore', flag: '🇸🇬', tier: 'B', operators: 0, corridors: ['AYE-PIE Corridor'], live: false },
  { iso: 'IE', name: 'Ireland', flag: '🇮🇪', tier: 'B', operators: 0, corridors: ['M1 Dublin-Belfast'], live: false },
  { iso: 'PT', name: 'Portugal', flag: '🇵🇹', tier: 'B', operators: 0, corridors: ['A1 Lisbon-Porto'], live: false },

  // ── Tier C — Planned (24) ──────────────────────────────────────
  { iso: 'SA', name: 'Saudi Arabia', flag: '🇸🇦', tier: 'C', operators: 0, corridors: ['Riyadh-Jeddah Hwy'], live: false },
  { iso: 'QA', name: 'Qatar', flag: '🇶🇦', tier: 'C', operators: 0, corridors: ['Al Shamal Road'], live: false },
  { iso: 'KW', name: 'Kuwait', flag: '🇰🇼', tier: 'C', operators: 0, corridors: ['Shuwaikh Port Access'], live: false },
  { iso: 'OM', name: 'Oman', flag: '🇴🇲', tier: 'C', operators: 0, corridors: ['Muscat-Salalah'], live: false },
  { iso: 'CL', name: 'Chile', flag: '🇨🇱', tier: 'C', operators: 0, corridors: ['Ruta 5 Pan-American'], live: false },
  { iso: 'AR', name: 'Argentina', flag: '🇦🇷', tier: 'C', operators: 0, corridors: ['RN 9 BA-Rosario'], live: false },
  { iso: 'CO', name: 'Colombia', flag: '🇨🇴', tier: 'C', operators: 0, corridors: ['Ruta del Sol'], live: false },
  { iso: 'PE', name: 'Peru', flag: '🇵🇪', tier: 'C', operators: 0, corridors: ['Pan-American South'], live: false },
  { iso: 'MY', name: 'Malaysia', flag: '🇲🇾', tier: 'C', operators: 0, corridors: ['North-South Expressway'], live: false },
  { iso: 'TH', name: 'Thailand', flag: '🇹🇭', tier: 'C', operators: 0, corridors: ['Motorway 7 East'], live: false },
  { iso: 'ID', name: 'Indonesia', flag: '🇮🇩', tier: 'C', operators: 0, corridors: ['Trans-Java Tollway'], live: false },
  { iso: 'PH', name: 'Philippines', flag: '🇵🇭', tier: 'C', operators: 0, corridors: ['NLEX-SLEX Manila'], live: false },
  { iso: 'CZ', name: 'Czech Republic', flag: '🇨🇿', tier: 'C', operators: 0, corridors: ['D1 Prague-Brno'], live: false },
  { iso: 'RO', name: 'Romania', flag: '🇷🇴', tier: 'C', operators: 0, corridors: ['A1 Bucharest-Sibiu'], live: false },
  { iso: 'HU', name: 'Hungary', flag: '🇭🇺', tier: 'C', operators: 0, corridors: ['M1 Budapest-Vienna'], live: false },
  { iso: 'IL', name: 'Israel', flag: '🇮🇱', tier: 'C', operators: 0, corridors: ['Route 6 Trans-Israel'], live: false },
  { iso: 'GR', name: 'Greece', flag: '🇬🇷', tier: 'C', operators: 0, corridors: ['A1 Athens-Thessaloniki'], live: false },
  { iso: 'SK', name: 'Slovakia', flag: '🇸🇰', tier: 'C', operators: 0, corridors: ['D1 Bratislava-Kosice'], live: false },
  { iso: 'HR', name: 'Croatia', flag: '🇭🇷', tier: 'C', operators: 0, corridors: ['A1 Zagreb-Split'], live: false },
  { iso: 'RS', name: 'Serbia', flag: '🇷🇸', tier: 'C', operators: 0, corridors: ['E75 Belgrade-Nis'], live: false },
  { iso: 'BG', name: 'Bulgaria', flag: '🇧🇬', tier: 'C', operators: 0, corridors: ['A1 Sofia-Burgas'], live: false },
  { iso: 'SI', name: 'Slovenia', flag: '🇸🇮', tier: 'C', operators: 0, corridors: ['A1 Koper-Ljubljana'], live: false },
  { iso: 'LT', name: 'Lithuania', flag: '🇱🇹', tier: 'C', operators: 0, corridors: ['A1 Via Baltica'], live: false },
  { iso: 'EE', name: 'Estonia', flag: '🇪🇪', tier: 'C', operators: 0, corridors: ['E67 Tallinn-Parnu'], live: false },

  // ── Tier D — Future (68) ───────────────────────────────────────
  { iso: 'NG', name: 'Nigeria', flag: '🇳🇬', tier: 'D', operators: 0, corridors: ['Lagos-Ibadan Expressway'], live: false },
  { iso: 'KE', name: 'Kenya', flag: '🇰🇪', tier: 'D', operators: 0, corridors: ['Mombasa Road A109'], live: false },
  { iso: 'GH', name: 'Ghana', flag: '🇬🇭', tier: 'D', operators: 0, corridors: ['Accra-Kumasi N1'], live: false },
  { iso: 'TZ', name: 'Tanzania', flag: '🇹🇿', tier: 'D', operators: 0, corridors: ['Dar-Dodoma A7'], live: false },
  { iso: 'EG', name: 'Egypt', flag: '🇪🇬', tier: 'D', operators: 0, corridors: ['Cairo-Alexandria Desert'], live: false },
  { iso: 'MA', name: 'Morocco', flag: '🇲🇦', tier: 'D', operators: 0, corridors: ['A2 Casablanca-Rabat'], live: false },
  { iso: 'PK', name: 'Pakistan', flag: '🇵🇰', tier: 'D', operators: 0, corridors: ['M1 Islamabad-Lahore'], live: false },
  { iso: 'BD', name: 'Bangladesh', flag: '🇧🇩', tier: 'D', operators: 0, corridors: ['Dhaka-Chittagong N1'], live: false },
  { iso: 'VN', name: 'Vietnam', flag: '🇻🇳', tier: 'D', operators: 0, corridors: ['AH1 Hanoi-HCMC'], live: false },
  { iso: 'TR', name: 'Turkey', flag: '🇹🇷', tier: 'D', operators: 0, corridors: ['O-4 Istanbul-Ankara'], live: false },
  { iso: 'RU', name: 'Russia', flag: '🇷🇺', tier: 'D', operators: 0, corridors: ['M11 Moscow-St. Petersburg'], live: false },
  { iso: 'KZ', name: 'Kazakhstan', flag: '🇰🇿', tier: 'D', operators: 0, corridors: ['M36 Almaty-Astana'], live: false },
  { iso: 'UZ', name: 'Uzbekistan', flag: '🇺🇿', tier: 'D', operators: 0, corridors: ['M39 Tashkent-Samarkand'], live: false },
  { iso: 'UA', name: 'Ukraine', flag: '🇺🇦', tier: 'D', operators: 0, corridors: ['M06 Kyiv-Chop'], live: false },
  { iso: 'ET', name: 'Ethiopia', flag: '🇪🇹', tier: 'D', operators: 0, corridors: ['A1 Addis-Djibouti'], live: false },
  { iso: 'AO', name: 'Angola', flag: '🇦🇴', tier: 'D', operators: 0, corridors: ['EN100 Luanda-Malanje'], live: false },
  { iso: 'CI', name: "Côte d'Ivoire", flag: '🇨🇮', tier: 'D', operators: 0, corridors: ['Abidjan Port Corridor'], live: false },
  { iso: 'CM', name: 'Cameroon', flag: '🇨🇲', tier: 'D', operators: 0, corridors: ['Douala-Yaoundé'], live: false },
  { iso: 'UG', name: 'Uganda', flag: '🇺🇬', tier: 'D', operators: 0, corridors: ['Northern Corridor'], live: false },
  { iso: 'ZM', name: 'Zambia', flag: '🇿🇲', tier: 'D', operators: 0, corridors: ['Great North Road'], live: false },
  { iso: 'ZW', name: 'Zimbabwe', flag: '🇿🇼', tier: 'D', operators: 0, corridors: ['A1 Harare-Bulawayo'], live: false },
  { iso: 'TN', name: 'Tunisia', flag: '🇹🇳', tier: 'D', operators: 0, corridors: ['A1 Tunis-Sfax'], live: false },
  { iso: 'DZ', name: 'Algeria', flag: '🇩🇿', tier: 'D', operators: 0, corridors: ['A1 Algiers-Annaba'], live: false },
  { iso: 'LY', name: 'Libya', flag: '🇱🇾', tier: 'D', operators: 0, corridors: ['Coastal Tripoli-Benghazi'], live: false },
  { iso: 'IQ', name: 'Iraq', flag: '🇮🇶', tier: 'D', operators: 0, corridors: ['Baghdad-Basra'], live: false },
  { iso: 'JO', name: 'Jordan', flag: '🇯🇴', tier: 'D', operators: 0, corridors: ['Desert Hwy Amman-Aqaba'], live: false },
  { iso: 'LB', name: 'Lebanon', flag: '🇱🇧', tier: 'D', operators: 0, corridors: ['Beirut-Damascus Hwy'], live: false },
  { iso: 'LK', name: 'Sri Lanka', flag: '🇱🇰', tier: 'D', operators: 0, corridors: ['E01 Colombo-Galle'], live: false },
  { iso: 'MM', name: 'Myanmar', flag: '🇲🇲', tier: 'D', operators: 0, corridors: ['AH1 Yangon-Mandalay'], live: false },
  { iso: 'KH', name: 'Cambodia', flag: '🇰🇭', tier: 'D', operators: 0, corridors: ['NR4 PP-Sihanoukville'], live: false },
  { iso: 'MN', name: 'Mongolia', flag: '🇲🇳', tier: 'D', operators: 0, corridors: ['A0201 UB-Darkhan'], live: false },
  { iso: 'GE', name: 'Georgia', flag: '🇬🇪', tier: 'D', operators: 0, corridors: ['Middle Corridor'], live: false },
  { iso: 'AZ', name: 'Azerbaijan', flag: '🇦🇿', tier: 'D', operators: 0, corridors: ['Baku-Tbilisi-Kars'], live: false },
  { iso: 'EC', name: 'Ecuador', flag: '🇪🇨', tier: 'D', operators: 0, corridors: ['E35 Quito-Guayaquil'], live: false },
  { iso: 'BO', name: 'Bolivia', flag: '🇧🇴', tier: 'D', operators: 0, corridors: ['Ruta 1 La Paz-Oruro'], live: false },
  { iso: 'PY', name: 'Paraguay', flag: '🇵🇾', tier: 'D', operators: 0, corridors: ['Ruta 9 Trans-Chaco'], live: false },
  { iso: 'UY', name: 'Uruguay', flag: '🇺🇾', tier: 'D', operators: 0, corridors: ['Ruta 1 MVD-Colonia'], live: false },
  { iso: 'VE', name: 'Venezuela', flag: '🇻🇪', tier: 'D', operators: 0, corridors: ['Ruta 1 Caracas-Valencia'], live: false },
  { iso: 'GT', name: 'Guatemala', flag: '🇬🇹', tier: 'D', operators: 0, corridors: ['CA-1 Inter-American'], live: false },
  { iso: 'PA', name: 'Panama', flag: '🇵🇦', tier: 'D', operators: 0, corridors: ['Pan-American Hwy'], live: false },
  { iso: 'CR', name: 'Costa Rica', flag: '🇨🇷', tier: 'D', operators: 0, corridors: ['Ruta 1 Inter-American'], live: false },
  { iso: 'DO', name: 'Dominican Republic', flag: '🇩🇴', tier: 'D', operators: 0, corridors: ['Autopista Duarte'], live: false },
  { iso: 'JM', name: 'Jamaica', flag: '🇯🇲', tier: 'D', operators: 0, corridors: ['Highway 2000'], live: false },
  { iso: 'TT', name: 'Trinidad & Tobago', flag: '🇹🇹', tier: 'D', operators: 0, corridors: ['Uriah Butler Hwy'], live: false },
  { iso: 'SN', name: 'Senegal', flag: '🇸🇳', tier: 'D', operators: 0, corridors: ['A1 Dakar-Thiès'], live: false },
  { iso: 'MZ', name: 'Mozambique', flag: '🇲🇿', tier: 'D', operators: 0, corridors: ['EN1 Maputo-Beira'], live: false },
  { iso: 'MW', name: 'Malawi', flag: '🇲🇼', tier: 'D', operators: 0, corridors: ['M1 Lilongwe-Blantyre'], live: false },
  { iso: 'NA', name: 'Namibia', flag: '🇳🇦', tier: 'D', operators: 0, corridors: ['B1 Windhoek-Walvis Bay'], live: false },
  { iso: 'BW', name: 'Botswana', flag: '🇧🇼', tier: 'D', operators: 0, corridors: ['A1 Gaborone-Francistown'], live: false },
  { iso: 'MU', name: 'Mauritius', flag: '🇲🇺', tier: 'D', operators: 0, corridors: ['M1 Port Louis Ring'], live: false },
  { iso: 'BH', name: 'Bahrain', flag: '🇧🇭', tier: 'D', operators: 0, corridors: ['King Fahad Causeway'], live: false },
  { iso: 'CY', name: 'Cyprus', flag: '🇨🇾', tier: 'D', operators: 0, corridors: ['A1 Nicosia-Limassol'], live: false },
  { iso: 'LV', name: 'Latvia', flag: '🇱🇻', tier: 'D', operators: 0, corridors: ['A1 Via Baltica Riga'], live: false },
  { iso: 'LU', name: 'Luxembourg', flag: '🇱🇺', tier: 'D', operators: 0, corridors: ['A3 Luxembourg-France'], live: false },
  { iso: 'IS', name: 'Iceland', flag: '🇮🇸', tier: 'D', operators: 0, corridors: ['Route 1 Ring Road'], live: false },
  { iso: 'MT', name: 'Malta', flag: '🇲🇹', tier: 'D', operators: 0, corridors: ['Valletta-Freeport Access'], live: false },
  { iso: 'AM', name: 'Armenia', flag: '🇦🇲', tier: 'D', operators: 0, corridors: ['North-South Highway'], live: false },
  { iso: 'NP', name: 'Nepal', flag: '🇳🇵', tier: 'D', operators: 0, corridors: ['Prithvi Hwy KTM-Pokhara'], live: false },
  { iso: 'LA', name: 'Laos', flag: '🇱🇦', tier: 'D', operators: 0, corridors: ['NR13 Vientiane-Luang Prabang'], live: false },
  { iso: 'BN', name: 'Brunei', flag: '🇧🇳', tier: 'D', operators: 0, corridors: ['Coastal Highway'], live: false },
  { iso: 'FJ', name: 'Fiji', flag: '🇫🇯', tier: 'D', operators: 0, corridors: ['Kings Road Suva-Nadi'], live: false },
  { iso: 'PG', name: 'Papua New Guinea', flag: '🇵🇬', tier: 'D', operators: 0, corridors: ['Highlands Highway'], live: false },
  { iso: 'CU', name: 'Cuba', flag: '🇨🇺', tier: 'D', operators: 0, corridors: ['Autopista Nacional'], live: false },
  { iso: 'HN', name: 'Honduras', flag: '🇭🇳', tier: 'D', operators: 0, corridors: ['CA-5 San Pedro Sula'], live: false },
  { iso: 'SV', name: 'El Salvador', flag: '🇸🇻', tier: 'D', operators: 0, corridors: ['CA-1 Pan-American'], live: false },
  { iso: 'NI', name: 'Nicaragua', flag: '🇳🇮', tier: 'D', operators: 0, corridors: ['NIC-1 Pan-American'], live: false },
  { iso: 'GY', name: 'Guyana', flag: '🇬🇾', tier: 'D', operators: 0, corridors: ['East Bank Demerara'], live: false },
  { iso: 'SR', name: 'Suriname', flag: '🇸🇷', tier: 'D', operators: 0, corridors: ['East-West Connection'], live: false },
];

// Map positions for dot-map visualization (x%, y%)
export const COUNTRY_POSITIONS: Record<string, { x: number; y: number }> = {
  US: { x: 22, y: 38 }, CA: { x: 20, y: 26 }, MX: { x: 18, y: 48 },
  BR: { x: 35, y: 62 }, AR: { x: 32, y: 72 }, CL: { x: 28, y: 70 },
  CO: { x: 26, y: 54 }, PE: { x: 26, y: 60 }, VE: { x: 30, y: 52 },
  EC: { x: 24, y: 56 }, BO: { x: 30, y: 64 }, PY: { x: 33, y: 66 },
  UY: { x: 34, y: 70 }, GT: { x: 16, y: 50 }, PA: { x: 22, y: 52 },
  CR: { x: 20, y: 52 }, DO: { x: 28, y: 46 }, JM: { x: 24, y: 46 },
  TT: { x: 30, y: 50 }, CU: { x: 22, y: 44 }, HN: { x: 18, y: 50 },
  SV: { x: 15, y: 51 }, NI: { x: 17, y: 53 }, GY: { x: 32, y: 54 },
  SR: { x: 34, y: 54 },
  GB: { x: 48, y: 28 }, IE: { x: 46, y: 29 }, FR: { x: 50, y: 34 },
  DE: { x: 52, y: 30 }, NL: { x: 51, y: 28 }, BE: { x: 50, y: 30 },
  ES: { x: 48, y: 37 }, PT: { x: 46, y: 37 }, IT: { x: 53, y: 36 },
  CH: { x: 52, y: 33 }, AT: { x: 54, y: 33 }, PL: { x: 55, y: 28 },
  CZ: { x: 54, y: 30 }, HU: { x: 56, y: 33 }, RO: { x: 58, y: 34 },
  SE: { x: 54, y: 20 }, NO: { x: 52, y: 18 }, FI: { x: 58, y: 18 },
  DK: { x: 52, y: 24 }, SK: { x: 56, y: 32 }, HR: { x: 54, y: 35 },
  RS: { x: 56, y: 35 }, BG: { x: 58, y: 36 }, GR: { x: 57, y: 38 },
  SI: { x: 54, y: 34 }, LT: { x: 57, y: 24 }, LV: { x: 58, y: 23 },
  EE: { x: 58, y: 20 }, LU: { x: 51, y: 31 }, IS: { x: 42, y: 14 },
  MT: { x: 53, y: 40 }, CY: { x: 62, y: 40 },
  UA: { x: 60, y: 30 }, RU: { x: 70, y: 22 },
  TR: { x: 62, y: 37 }, SA: { x: 64, y: 46 }, AE: { x: 67, y: 46 },
  QA: { x: 66, y: 46 }, KW: { x: 65, y: 43 }, OM: { x: 68, y: 48 },
  BH: { x: 66, y: 45 }, IL: { x: 62, y: 42 }, JO: { x: 62, y: 44 },
  LB: { x: 62, y: 40 }, IQ: { x: 64, y: 42 },
  GE: { x: 64, y: 36 }, AZ: { x: 66, y: 36 }, AM: { x: 65, y: 37 },
  IN: { x: 74, y: 48 }, PK: { x: 72, y: 42 }, BD: { x: 78, y: 46 },
  NP: { x: 76, y: 44 }, LK: { x: 76, y: 52 },
  TH: { x: 80, y: 50 }, MY: { x: 80, y: 55 }, SG: { x: 80, y: 56 },
  ID: { x: 82, y: 58 }, PH: { x: 84, y: 50 }, VN: { x: 82, y: 48 },
  MM: { x: 78, y: 48 }, KH: { x: 80, y: 52 }, LA: { x: 80, y: 48 },
  BN: { x: 83, y: 55 },
  JP: { x: 88, y: 36 }, KR: { x: 86, y: 38 }, MN: { x: 80, y: 30 },
  KZ: { x: 72, y: 30 }, UZ: { x: 70, y: 35 },
  AU: { x: 86, y: 70 }, NZ: { x: 92, y: 76 }, FJ: { x: 94, y: 66 },
  PG: { x: 88, y: 60 },
  ZA: { x: 58, y: 72 }, NG: { x: 52, y: 54 }, KE: { x: 62, y: 56 },
  GH: { x: 49, y: 54 }, TZ: { x: 62, y: 60 }, EG: { x: 60, y: 42 },
  MA: { x: 47, y: 42 }, ET: { x: 64, y: 54 }, AO: { x: 54, y: 64 },
  CI: { x: 48, y: 54 }, CM: { x: 52, y: 56 }, UG: { x: 60, y: 56 },
  ZM: { x: 58, y: 66 }, ZW: { x: 60, y: 68 }, TN: { x: 52, y: 40 },
  DZ: { x: 50, y: 42 }, LY: { x: 54, y: 42 }, SN: { x: 44, y: 50 },
  MZ: { x: 62, y: 68 }, MW: { x: 62, y: 66 }, NA: { x: 54, y: 70 },
  BW: { x: 56, y: 70 }, MU: { x: 68, y: 68 },
};

// Regulatory notes for localized panel content
export const COUNTRY_NOTES: Record<string, string> = {
  US: "State-by-state DOT permits. Federal max: 8'6\" wide, 13'6\" tall, 80,000 lbs GVW. Escort triggers vary by state.",
  CA: 'Provincial permits via MTO/MOTI. Width limits 3.1–4.9m by province. Spring weight restrictions enforced.',
  AU: 'NHVR national permits. PBS scheme for high-productivity vehicles. State escort requirements apply.',
  GB: 'STGO categories 1–3 for abnormal loads. Police notice required >3m wide. Highways England coordination.',
  NZ: 'NZTA oversize permits. Escort required >3.5m wide or >4.25m tall. Island-specific bridge limits.',
  ZA: 'RTMC abnormal load permits. Escort required >3.6m wide. Night moves restricted. Mining corridor active.',
  DE: 'BAG Schwertransport permits. Police escort >4.5m wide. Autobahn restrictions apply weekends/holidays.',
  NL: 'RDW ontheffing permits. Rotterdam is primary heavy-haul hub. Dense infrastructure — tight clearances.',
  AE: 'RTA/MoI permits. Police escort >3.5m wide. Night moves restricted on Sheikh Zayed Road.',
  BR: 'DNIT issues AET permits. Escort >3.2m wide. Each state has additional ART-level permits required.',
  MX: 'SCT special permits. Federal Police escort coordination for >4.0m wide loads.',
  FR: 'Préfecture transport exceptionnel permits. 4 categories by weight. Police escort above Category 3.',
  IN: 'State PWD permits. No national single-window. Manual police escorts common. NH48/NH44 primary corridors.',
  JP: 'MLIT special vehicle permits. Strict road-use time windows. Urban moves often restricted to night.',
  SA: 'Ministry of Transport permits. MOI police escort for loads >4m wide. Active NEOM corridor.',
  TR: 'KGM highway permits. Istanbul-Ankara O-4 is primary corridor. Bosphorus bridge restrictions.',
  NG: 'FRSC coordinates transport. Lagos-Ibadan expressway primary corridor. Port access heavily regulated.',
  KE: 'KeNHA permits. Northern Corridor (Mombasa-Nairobi) primary route. SGR rail alternative available.',
  EG: 'GARBLT permits. Suez Canal corridor is major transit route. Cairo urban restrictions strict.',
};

export const TIER_COLORS: Record<string, string> = {
  A: '#C6923A', // Gold — Live now
  B: '#3A7AC6', // Blue — Coming soon
  C: '#6B7A8D', // Slate — Planned
  D: '#3D5068', // Dark blue — Future markets
};

export const TIER_LABELS: Record<string, string> = {
  A: 'Live Now',
  B: 'Launching Soon',
  C: 'In Development',
  D: 'Future Markets',
};

export const COUNTRY_MAP = new Map(ALL_COUNTRIES.map(c => [c.iso, c]));
