-- ══════════════════════════════════════════════════════════════════════
-- hc_sitemap_urls SEED — Sprint 5 Dominance Mode
-- Run via Supabase SQL editor or psql:
--   psql $DATABASE_URL -f scripts/seed-sitemap-urls.sql
-- 
-- Seeds all static corridor, best-for, escort-requirements, and role pages
-- so the DB-driven primary sitemap serves them immediately (not just ISR fallback).
-- ══════════════════════════════════════════════════════════════════════

-- Use upsert to avoid duplicates on re-run
INSERT INTO hc_sitemap_urls (url, priority, changefreq, lastmod)
VALUES

-- ── HOME & CORE ─────────────────────────────────────────────────────────
('https://www.haulcommand.com', 1.0, 'daily', now()),
('https://www.haulcommand.com/directory', 0.95, 'daily', now()),
('https://www.haulcommand.com/pricing', 0.85, 'monthly', now()),
('https://www.haulcommand.com/available-now', 0.95, 'hourly', now()),
('https://www.haulcommand.com/loads', 0.90, 'hourly', now()),
('https://www.haulcommand.com/loads/new', 0.85, 'daily', now()),
('https://www.haulcommand.com/claim', 0.90, 'weekly', now()),
('https://www.haulcommand.com/onboarding', 0.85, 'weekly', now()),
('https://www.haulcommand.com/advertise', 0.70, 'monthly', now()),
('https://www.haulcommand.com/map', 0.80, 'daily', now()),

-- ── TOOLS ────────────────────────────────────────────────────────────────
('https://www.haulcommand.com/tools', 0.90, 'weekly', now()),
('https://www.haulcommand.com/tools/escort-calculator', 0.90, 'weekly', now()),
('https://www.haulcommand.com/tools/permit-checker/us', 0.90, 'weekly', now()),
('https://www.haulcommand.com/tools/escort-rules/us', 0.90, 'weekly', now()),
('https://www.haulcommand.com/rates', 0.80, 'weekly', now()),

-- ── ROLES HUB & ROLE PAGES ───────────────────────────────────────────────
('https://www.haulcommand.com/roles', 0.90, 'weekly', now()),
('https://www.haulcommand.com/roles/pilot-car-operator', 0.90, 'weekly', now()),
('https://www.haulcommand.com/roles/dispatcher', 0.85, 'weekly', now()),
('https://www.haulcommand.com/roles/heavy-haul-carrier', 0.85, 'weekly', now()),
('https://www.haulcommand.com/broker', 0.90, 'weekly', now()),

-- ── ESCORT REQUIREMENTS (50 US States) ──────────────────────────────────
('https://www.haulcommand.com/escort-requirements', 0.90, 'monthly', now()),
('https://www.haulcommand.com/escort-requirements/al', 0.80, 'monthly', now()),
('https://www.haulcommand.com/escort-requirements/ak', 0.80, 'monthly', now()),
('https://www.haulcommand.com/escort-requirements/az', 0.85, 'monthly', now()),
('https://www.haulcommand.com/escort-requirements/ar', 0.80, 'monthly', now()),
('https://www.haulcommand.com/escort-requirements/ca', 0.90, 'monthly', now()),
('https://www.haulcommand.com/escort-requirements/co', 0.85, 'monthly', now()),
('https://www.haulcommand.com/escort-requirements/ct', 0.75, 'monthly', now()),
('https://www.haulcommand.com/escort-requirements/de', 0.75, 'monthly', now()),
('https://www.haulcommand.com/escort-requirements/fl', 0.90, 'monthly', now()),
('https://www.haulcommand.com/escort-requirements/ga', 0.85, 'monthly', now()),
('https://www.haulcommand.com/escort-requirements/hi', 0.70, 'monthly', now()),
('https://www.haulcommand.com/escort-requirements/id', 0.80, 'monthly', now()),
('https://www.haulcommand.com/escort-requirements/il', 0.85, 'monthly', now()),
('https://www.haulcommand.com/escort-requirements/in', 0.80, 'monthly', now()),
('https://www.haulcommand.com/escort-requirements/ia', 0.80, 'monthly', now()),
('https://www.haulcommand.com/escort-requirements/ks', 0.80, 'monthly', now()),
('https://www.haulcommand.com/escort-requirements/ky', 0.80, 'monthly', now()),
('https://www.haulcommand.com/escort-requirements/la', 0.85, 'monthly', now()),
('https://www.haulcommand.com/escort-requirements/me', 0.75, 'monthly', now()),
('https://www.haulcommand.com/escort-requirements/md', 0.80, 'monthly', now()),
('https://www.haulcommand.com/escort-requirements/ma', 0.75, 'monthly', now()),
('https://www.haulcommand.com/escort-requirements/mi', 0.85, 'monthly', now()),
('https://www.haulcommand.com/escort-requirements/mn', 0.85, 'monthly', now()),
('https://www.haulcommand.com/escort-requirements/ms', 0.80, 'monthly', now()),
('https://www.haulcommand.com/escort-requirements/mo', 0.80, 'monthly', now()),
('https://www.haulcommand.com/escort-requirements/mt', 0.80, 'monthly', now()),
('https://www.haulcommand.com/escort-requirements/ne', 0.80, 'monthly', now()),
('https://www.haulcommand.com/escort-requirements/nv', 0.85, 'monthly', now()),
('https://www.haulcommand.com/escort-requirements/nh', 0.75, 'monthly', now()),
('https://www.haulcommand.com/escort-requirements/nj', 0.85, 'monthly', now()),
('https://www.haulcommand.com/escort-requirements/nm', 0.80, 'monthly', now()),
('https://www.haulcommand.com/escort-requirements/ny', 0.85, 'monthly', now()),
('https://www.haulcommand.com/escort-requirements/nc', 0.85, 'monthly', now()),
('https://www.haulcommand.com/escort-requirements/nd', 0.80, 'monthly', now()),
('https://www.haulcommand.com/escort-requirements/oh', 0.85, 'monthly', now()),
('https://www.haulcommand.com/escort-requirements/ok', 0.85, 'monthly', now()),
('https://www.haulcommand.com/escort-requirements/or', 0.85, 'monthly', now()),
('https://www.haulcommand.com/escort-requirements/pa', 0.85, 'monthly', now()),
('https://www.haulcommand.com/escort-requirements/ri', 0.70, 'monthly', now()),
('https://www.haulcommand.com/escort-requirements/sc', 0.80, 'monthly', now()),
('https://www.haulcommand.com/escort-requirements/sd', 0.80, 'monthly', now()),
('https://www.haulcommand.com/escort-requirements/tn', 0.85, 'monthly', now()),
('https://www.haulcommand.com/escort-requirements/tx', 0.95, 'monthly', now()),
('https://www.haulcommand.com/escort-requirements/ut', 0.80, 'monthly', now()),
('https://www.haulcommand.com/escort-requirements/vt', 0.70, 'monthly', now()),
('https://www.haulcommand.com/escort-requirements/va', 0.85, 'monthly', now()),
('https://www.haulcommand.com/escort-requirements/wa', 0.85, 'monthly', now()),
('https://www.haulcommand.com/escort-requirements/wv', 0.75, 'monthly', now()),
('https://www.haulcommand.com/escort-requirements/wi', 0.80, 'monthly', now()),
('https://www.haulcommand.com/escort-requirements/wy', 0.80, 'monthly', now()),

-- ── CORRIDORS — 35 corridors ($199/mo sponsorship each) ─────────────────
-- Gulf Coast
('https://www.haulcommand.com/corridors/tx/vs/la', 0.85, 'weekly', now()),
('https://www.haulcommand.com/corridors/tx/vs/ok', 0.85, 'weekly', now()),
('https://www.haulcommand.com/corridors/la/vs/ms', 0.85, 'weekly', now()),
('https://www.haulcommand.com/corridors/ms/vs/al', 0.85, 'weekly', now()),
('https://www.haulcommand.com/corridors/al/vs/ga', 0.85, 'weekly', now()),
('https://www.haulcommand.com/corridors/tx/vs/nm', 0.85, 'weekly', now()),
-- Southeast
('https://www.haulcommand.com/corridors/fl/vs/ga', 0.85, 'weekly', now()),
('https://www.haulcommand.com/corridors/ga/vs/sc', 0.85, 'weekly', now()),
('https://www.haulcommand.com/corridors/sc/vs/nc', 0.85, 'weekly', now()),
('https://www.haulcommand.com/corridors/nc/vs/va', 0.85, 'weekly', now()),
-- Mid-Atlantic
('https://www.haulcommand.com/corridors/va/vs/md', 0.85, 'weekly', now()),
('https://www.haulcommand.com/corridors/md/vs/pa', 0.85, 'weekly', now()),
('https://www.haulcommand.com/corridors/oh/vs/pa', 0.85, 'weekly', now()),
('https://www.haulcommand.com/corridors/pa/vs/nj', 0.85, 'weekly', now()),
('https://www.haulcommand.com/corridors/nj/vs/ny', 0.90, 'weekly', now()),
-- Midwest
('https://www.haulcommand.com/corridors/oh/vs/in', 0.85, 'weekly', now()),
('https://www.haulcommand.com/corridors/in/vs/il', 0.85, 'weekly', now()),
('https://www.haulcommand.com/corridors/il/vs/mo', 0.85, 'weekly', now()),
('https://www.haulcommand.com/corridors/mo/vs/ks', 0.85, 'weekly', now()),
('https://www.haulcommand.com/corridors/mi/vs/oh', 0.85, 'weekly', now()),
-- Plains
('https://www.haulcommand.com/corridors/tx/vs/ks', 0.85, 'weekly', now()),
('https://www.haulcommand.com/corridors/ks/vs/ne', 0.80, 'weekly', now()),
('https://www.haulcommand.com/corridors/nd/vs/sd', 0.80, 'weekly', now()),
-- Mountain
('https://www.haulcommand.com/corridors/mt/vs/wy', 0.80, 'weekly', now()),
('https://www.haulcommand.com/corridors/wy/vs/co', 0.85, 'weekly', now()),
('https://www.haulcommand.com/corridors/co/vs/ut', 0.85, 'weekly', now()),
('https://www.haulcommand.com/corridors/ut/vs/nv', 0.85, 'weekly', now()),
('https://www.haulcommand.com/corridors/id/vs/mt', 0.80, 'weekly', now()),
-- West Coast
('https://www.haulcommand.com/corridors/ca/vs/az', 0.90, 'weekly', now()),
('https://www.haulcommand.com/corridors/or/vs/wa', 0.85, 'weekly', now()),
('https://www.haulcommand.com/corridors/wa/vs/or', 0.85, 'weekly', now()),
('https://www.haulcommand.com/corridors/ca/vs/nv', 0.85, 'weekly', now()),
-- Canada
('https://www.haulcommand.com/corridors/ab/vs/sk', 0.80, 'weekly', now()),
('https://www.haulcommand.com/corridors/on/vs/qc', 0.80, 'weekly', now()),

-- ── BEST-FOR LOAD TYPE PAGES (10) ────────────────────────────────────────
('https://www.haulcommand.com/best-for/oversize-load', 0.85, 'weekly', now()),
('https://www.haulcommand.com/best-for/wide-load', 0.85, 'weekly', now()),
('https://www.haulcommand.com/best-for/heavy-haul', 0.85, 'weekly', now()),
('https://www.haulcommand.com/best-for/wind-turbine', 0.85, 'weekly', now()),
('https://www.haulcommand.com/best-for/bridge-beam', 0.80, 'weekly', now()),
('https://www.haulcommand.com/best-for/oil-field-equipment', 0.85, 'weekly', now()),
('https://www.haulcommand.com/best-for/construction-equipment', 0.85, 'weekly', now()),
('https://www.haulcommand.com/best-for/manufactured-home', 0.80, 'weekly', now()),
('https://www.haulcommand.com/best-for/crane', 0.85, 'weekly', now()),
('https://www.haulcommand.com/best-for/utility-poles', 0.80, 'weekly', now()),

-- ── FIND / ROLE INDEX PAGES (6 roles) ────────────────────────────────────
('https://www.haulcommand.com/find/pilot-car-operator', 0.90, 'weekly', now()),
('https://www.haulcommand.com/find/escort-driver', 0.85, 'weekly', now()),
('https://www.haulcommand.com/find/heavy-haul-broker', 0.85, 'weekly', now()),
('https://www.haulcommand.com/find/oversize-carrier', 0.85, 'weekly', now()),
('https://www.haulcommand.com/find/permit-service', 0.80, 'weekly', now()),
('https://www.haulcommand.com/find/route-surveyor', 0.80, 'weekly', now()),

-- ── FIND / ROLE / CITY — TOP 20 COMMERCIAL INTENT ────────────────────────
('https://www.haulcommand.com/find/pilot-car-operator/houston-tx', 0.90, 'daily', now()),
('https://www.haulcommand.com/find/pilot-car-operator/dallas-tx', 0.90, 'daily', now()),
('https://www.haulcommand.com/find/pilot-car-operator/los-angeles-ca', 0.90, 'daily', now()),
('https://www.haulcommand.com/find/pilot-car-operator/chicago-il', 0.90, 'daily', now()),
('https://www.haulcommand.com/find/pilot-car-operator/phoenix-az', 0.88, 'daily', now()),
('https://www.haulcommand.com/find/pilot-car-operator/atlanta-ga', 0.88, 'daily', now()),
('https://www.haulcommand.com/find/pilot-car-operator/denver-co', 0.88, 'daily', now()),
('https://www.haulcommand.com/find/pilot-car-operator/seattle-wa', 0.88, 'daily', now()),
('https://www.haulcommand.com/find/pilot-car-operator/nashville-tn', 0.85, 'daily', now()),
('https://www.haulcommand.com/find/pilot-car-operator/oklahoma-city-ok', 0.85, 'daily', now()),
('https://www.haulcommand.com/find/pilot-car-operator/baton-rouge-la', 0.85, 'daily', now()),
('https://www.haulcommand.com/find/pilot-car-operator/san-antonio-tx', 0.85, 'daily', now()),
('https://www.haulcommand.com/find/pilot-car-operator/portland-or', 0.85, 'daily', now()),
('https://www.haulcommand.com/find/pilot-car-operator/pittsburgh-pa', 0.85, 'daily', now()),
('https://www.haulcommand.com/find/pilot-car-operator/salt-lake-city-ut', 0.85, 'daily', now()),
('https://www.haulcommand.com/find/escort-driver/houston-tx', 0.85, 'daily', now()),
('https://www.haulcommand.com/find/escort-driver/dallas-tx', 0.85, 'daily', now()),
('https://www.haulcommand.com/find/escort-driver/los-angeles-ca', 0.85, 'daily', now()),
('https://www.haulcommand.com/find/heavy-haul-broker/houston-tx', 0.85, 'daily', now()),
('https://www.haulcommand.com/find/heavy-haul-broker/chicago-il', 0.85, 'daily', now()),

-- ── MARKET / STATE PAGES (50 states) ─────────────────────────────────────
('https://www.haulcommand.com/market/tx', 0.90, 'daily', now()),
('https://www.haulcommand.com/market/ca', 0.90, 'daily', now()),
('https://www.haulcommand.com/market/fl', 0.88, 'daily', now()),
('https://www.haulcommand.com/market/oh', 0.85, 'daily', now()),
('https://www.haulcommand.com/market/pa', 0.85, 'daily', now()),
('https://www.haulcommand.com/market/il', 0.85, 'daily', now()),
('https://www.haulcommand.com/market/ga', 0.85, 'daily', now()),
('https://www.haulcommand.com/market/nc', 0.83, 'daily', now()),
('https://www.haulcommand.com/market/az', 0.83, 'daily', now()),
('https://www.haulcommand.com/market/wa', 0.83, 'daily', now()),
('https://www.haulcommand.com/market/co', 0.83, 'daily', now()),
('https://www.haulcommand.com/market/la', 0.85, 'daily', now()),
('https://www.haulcommand.com/market/al', 0.80, 'daily', now()),
('https://www.haulcommand.com/market/mi', 0.80, 'daily', now()),
('https://www.haulcommand.com/market/mn', 0.80, 'daily', now()),
('https://www.haulcommand.com/market/tn', 0.80, 'daily', now()),
('https://www.haulcommand.com/market/or', 0.80, 'daily', now()),
('https://www.haulcommand.com/market/nv', 0.80, 'daily', now()),
('https://www.haulcommand.com/market/mo', 0.80, 'daily', now()),
('https://www.haulcommand.com/market/ok', 0.82, 'daily', now()),
('https://www.haulcommand.com/market/ny', 0.82, 'daily', now()),
('https://www.haulcommand.com/market/sc', 0.78, 'daily', now()),
('https://www.haulcommand.com/market/ky', 0.78, 'daily', now()),
('https://www.haulcommand.com/market/ut', 0.78, 'daily', now()),
('https://www.haulcommand.com/market/ia', 0.75, 'daily', now()),
('https://www.haulcommand.com/market/ar', 0.75, 'daily', now()),
('https://www.haulcommand.com/market/ms', 0.75, 'daily', now()),
('https://www.haulcommand.com/market/ks', 0.75, 'daily', now()),
('https://www.haulcommand.com/market/ne', 0.75, 'daily', now()),
('https://www.haulcommand.com/market/id', 0.75, 'daily', now()),
('https://www.haulcommand.com/market/nm', 0.75, 'daily', now()),
('https://www.haulcommand.com/market/sd', 0.72, 'daily', now()),
('https://www.haulcommand.com/market/nd', 0.72, 'daily', now()),
('https://www.haulcommand.com/market/mt', 0.75, 'daily', now()),
('https://www.haulcommand.com/market/wy', 0.75, 'daily', now()),
('https://www.haulcommand.com/market/wv', 0.72, 'daily', now()),
('https://www.haulcommand.com/market/vt', 0.65, 'daily', now()),
('https://www.haulcommand.com/market/nh', 0.65, 'daily', now()),
('https://www.haulcommand.com/market/me', 0.65, 'daily', now()),
('https://www.haulcommand.com/market/ri', 0.60, 'daily', now()),
('https://www.haulcommand.com/market/ct', 0.65, 'daily', now()),
('https://www.haulcommand.com/market/de', 0.65, 'daily', now()),
('https://www.haulcommand.com/market/md', 0.75, 'daily', now()),
('https://www.haulcommand.com/market/va', 0.80, 'daily', now()),
('https://www.haulcommand.com/market/in', 0.78, 'daily', now()),
('https://www.haulcommand.com/market/wi', 0.75, 'daily', now()),
('https://www.haulcommand.com/market/hi', 0.60, 'daily', now()),
('https://www.haulcommand.com/market/ak', 0.65, 'daily', now()),
('https://www.haulcommand.com/market/nj', 0.78, 'daily', now()),
('https://www.haulcommand.com/market/ma', 0.70, 'daily', now()),

-- ── TOP COUNTRY REGULATIONS ───────────────────────────────────────────────
('https://www.haulcommand.com/regulations/us', 0.85, 'monthly', now()),
('https://www.haulcommand.com/regulations/ca', 0.82, 'monthly', now()),
('https://www.haulcommand.com/regulations/au', 0.80, 'monthly', now()),
('https://www.haulcommand.com/regulations/gb', 0.80, 'monthly', now()),
('https://www.haulcommand.com/regulations/de', 0.78, 'monthly', now()),
('https://www.haulcommand.com/regulations/nl', 0.75, 'monthly', now()),
('https://www.haulcommand.com/regulations/nz', 0.75, 'monthly', now()),
('https://www.haulcommand.com/regulations/za', 0.75, 'monthly', now()),
('https://www.haulcommand.com/regulations/mx', 0.75, 'monthly', now()),
('https://www.haulcommand.com/regulations/br', 0.73, 'monthly', now()),
('https://www.haulcommand.com/regulations/sg', 0.70, 'monthly', now()),
('https://www.haulcommand.com/regulations/ae', 0.70, 'monthly', now()),
('https://www.haulcommand.com/regulations/no', 0.70, 'monthly', now()),
('https://www.haulcommand.com/regulations/se', 0.70, 'monthly', now()),
('https://www.haulcommand.com/regulations/fr', 0.70, 'monthly', now())

ON CONFLICT (url) DO UPDATE SET
    priority    = EXCLUDED.priority,
    changefreq  = EXCLUDED.changefreq,
    lastmod     = now();

-- Verify count after seed
SELECT COUNT(*) AS total_urls FROM hc_sitemap_urls;
