-- USPilotCars.com seed data — 218 operators
-- Generated: 2026-02-26T20:11:28.704Z
-- Target table: directory_listings

INSERT INTO directory_listings (name, slug, entity_type, city, region_code, country_code, claim_status, is_visible, rank_score, metadata)
VALUES
  ('C B Piloting Services, LLC', 'c-b-piloting-services-llc', 'escort_operator', '', 'AL', 'US', 'unclaimed', true, 10, '{"phone":"479-670-2176","website":"","services":[],"claim_hash":"7ca04b49b7973d09","source":"uspilotcars.com","additional_cities":[],"additional_regions":["AK","AZ","AR","CA","CO","CT","DE","FL","GA","ID","IL","IN","IA","KS","KY","LA","ME","MD","MA","MI","MN","MS","MO","MT","NE","NV","NH","NJ","NM","NY","NC","ND","OH","OK","OR","PA","RI","SC","SD","TN","TX","UT","VT","VA","WA","WV","WI","WY","AB","BC","NS","ON","QC","SK"]}'::jsonb),
  ('Permits & Dispatching For The Entire United States', 'permits-dispatching-for-the-entire-united-states', 'escort_operator', '', 'AL', 'US', 'unclaimed', true, 10, '{"phone":"631-669-3742","website":"","services":[],"claim_hash":"ee04dad991bc6722","source":"uspilotcars.com","additional_cities":[],"additional_regions":["AK","AZ","AR","CA","CO","CT","DE","FL","GA","ID","IL","IN","IA","KS","KY","LA","ME","MD","MA","MI","MN","MS","MO","MT","NE","NV","NH","NJ","NM","NY","NC","ND","OH","OK","OR","PA","RI","SC","SD","TN","TX","UT","VT","VA","WA","WV","WI","WY","AB","BC","NS","ON","QC","SK"]}'::jsonb),
  ('Mobile, Al', 'mobile-al', 'escort_operator', '', 'AL', 'US', 'unclaimed', true, 10, '{"phone":"251-957-2841","website":"","services":[],"claim_hash":"e3e0768fed636feb","source":"uspilotcars.com","additional_cities":[],"additional_regions":["FL","LA"]}'::jsonb),
  ('Jacksonville/Green Cove Springs, Fl', 'jacksonvillegreen-cove-springs-fl', 'escort_operator', '', 'AL', 'US', 'unclaimed', true, 10, '{"phone":"904-607-3646","website":"","services":[],"claim_hash":"002493514b65eed8","source":"uspilotcars.com","additional_cities":["Brunos Pilot Car Escort Svcs. LLC"],"additional_regions":["FL","SC"]}'::jsonb),
  ('Memphis, Tn', 'memphis-tn', 'escort_operator', '', 'AL', 'US', 'unclaimed', true, 10, '{"phone":"904-903-9300","website":"","services":[],"claim_hash":"5ce9e8b5fc3cda4f","source":"uspilotcars.com","additional_cities":[],"additional_regions":["AR","FL","IL","KY","VA"]}'::jsonb),
  ('Gonzales /Baton Rouge, La', 'gonzales-baton-rouge-la', 'escort_operator', 'Gator’S Highway Escort Svcs, LLC', 'AL', 'US', 'unclaimed', true, 10, '{"phone":"504-610-4162","website":"","services":[],"claim_hash":"ca5a1e696c2a57c0","source":"uspilotcars.com","additional_cities":[],"additional_regions":["LA","TX"]}'::jsonb),
  ('Jackson, Ms', 'jackson-ms', 'escort_operator', '', 'AL', 'US', 'unclaimed', true, 10, '{"phone":"601-612-0106","website":"","services":[],"claim_hash":"d87bdb6a5c606184","source":"uspilotcars.com","additional_cities":[],"additional_regions":["AR","FL","LA","PA","TX"]}'::jsonb),
  ('Chattanooga, Tn', 'chattanooga-tn', 'escort_operator', '', 'AL', 'US', 'unclaimed', true, 10, '{"phone":"423-355-0213","website":"","services":[],"claim_hash":"1ced8ce0bfd3cf48","source":"uspilotcars.com","additional_cities":[],"additional_regions":["KY"]}'::jsonb),
  ('Birmingham, Al', 'birmingham-al', 'escort_operator', '', 'AL', 'US', 'unclaimed', true, 10, '{"phone":"205-902-1738","website":"","services":[],"claim_hash":"d41f11fcdba552ae","source":"uspilotcars.com","additional_cities":[],"additional_regions":["FL"]}'::jsonb),
  ('Decatur/Huntsville/Birmingham, Al', 'decaturhuntsvillebirmingham-al', 'escort_operator', '', 'AL', 'US', 'unclaimed', true, 10, '{"phone":"256-466-5265","website":"","services":[],"claim_hash":"ca68914df782f1ad","source":"uspilotcars.com","additional_cities":[],"additional_regions":[]}'::jsonb),
  ('Birmingham, Al', 'birmingham-al', 'escort_operator', '', 'AL', 'US', 'unclaimed', true, 10, '{"phone":"205-299-0326","website":"","services":[],"claim_hash":"2b4e986817355c75","source":"uspilotcars.com","additional_cities":[],"additional_regions":[]}'::jsonb),
  ('Graham’S Pilot Car', 'grahams-pilot-car', 'escort_operator', 'Cars / National Service  
 
 
 
  A  
  L  
  A  
  B  
  A  
  M  
  A  
     
  P  
  I  
  L  
  O  
  T  
     
  C  
  A  
  R  
  S  
 
 
  A  
  L  
  A  
  B  
  A  
  M  
  A  
     
 
 
     
     
     
 
 
 
     
         
               
             Mobile', 'AL', 'US', 'unclaimed', true, 10, '{"phone":"251-957-2841","website":"","services":[],"claim_hash":"e586615b241401ac","source":"uspilotcars.com","additional_cities":[],"additional_regions":[]}'::jsonb),
  ('Yuma, Az', 'yuma-az', 'escort_operator', 'Cwt', 'AZ', 'US', 'unclaimed', true, 10, '{"phone":"928-920-7350","website":"","services":[],"claim_hash":"aab6e1b630612179","source":"uspilotcars.com","additional_cities":[],"additional_regions":[]}'::jsonb),
  ('Yuma, Az', 'yuma-az', 'escort_operator', '', 'AZ', 'US', 'unclaimed', true, 10, '{"phone":"928-210-3435","website":"","services":[],"claim_hash":"e47903dabd5148a8","source":"uspilotcars.com","additional_cities":[],"additional_regions":["CA","NV","NM"]}'::jsonb),
  ('Tucson, Az', 'tucson-az', 'escort_operator', 'Anstorm Sabre PCS, LLC', 'AZ', 'US', 'unclaimed', true, 10, '{"phone":"402-270-2125","website":"","services":[],"claim_hash":"e91b00cd98deedc7","source":"uspilotcars.com","additional_cities":[],"additional_regions":[]}'::jsonb),
  ('Phoenix, Az', 'phoenix-az', 'escort_operator', '', 'AZ', 'US', 'unclaimed', true, 10, '{"phone":"602-699-5755","website":"","services":[],"claim_hash":"5c0a59973a2b135b","source":"uspilotcars.com","additional_cities":[],"additional_regions":[]}'::jsonb),
  ('Holbrook/Flagstaff/Payson, Az', 'holbrookflagstaffpayson-az', 'escort_operator', 'S & G Transport LLC', 'AZ', 'US', 'unclaimed', true, 10, '{"phone":"928-651-2140","website":"","services":[],"claim_hash":"0e94dffeafba77fe","source":"uspilotcars.com","additional_cities":[],"additional_regions":["CO","NM","UT"]}'::jsonb),
  ('Moorhead, Mn', 'moorhead-mn', 'escort_operator', 'Thom Heavy Haul Escort LLC', 'AZ', 'US', 'unclaimed', true, 10, '{"phone":"218-329-7606","website":"","services":[],"claim_hash":"127775760c50fcbe","source":"uspilotcars.com","additional_cities":[],"additional_regions":["MN"]}'::jsonb),
  ('Mesa/Phoenix,Az', 'mesaphoenixaz', 'escort_operator', '', 'AZ', 'US', 'unclaimed', true, 10, '{"phone":"626-278-7545","website":"","services":[],"claim_hash":"86e45aae13567aa3","source":"uspilotcars.com","additional_cities":[],"additional_regions":[]}'::jsonb),
  ('Cortez, Co', 'cortez-co', 'escort_operator', '', 'AZ', 'US', 'unclaimed', true, 10, '{"phone":"970-759-6678","website":"","services":[],"claim_hash":"0e26a246294e36c2","source":"uspilotcars.com","additional_cities":[],"additional_regions":["CO","NM","UT"]}'::jsonb),
  ('Reno, Nv', 'reno-nv', 'escort_operator', '', 'AZ', 'US', 'unclaimed', true, 10, '{"phone":"775-560-5896","website":"","services":[],"claim_hash":"43bcebe5603c3646","source":"uspilotcars.com","additional_cities":["Blacksheep Pilot Car / T.J.S"],"additional_regions":["NV"]}'::jsonb),
  ('Madera, Ca', 'madera-ca', 'escort_operator', '', 'AZ', 'US', 'unclaimed', true, 10, '{"phone":"559-363-5656","website":"","services":[],"claim_hash":"734174bdedc7b845","source":"uspilotcars.com","additional_cities":[],"additional_regions":["CA","NV","NM","UT"]}'::jsonb),
  ('Sacramento, Ca', 'sacramento-ca', 'escort_operator', '', 'AZ', 'US', 'unclaimed', true, 10, '{"phone":"916-856-4960","website":"","services":[],"claim_hash":"ed30217534eb574c","source":"uspilotcars.com","additional_cities":[],"additional_regions":["CA","NV","OR","UT"]}'::jsonb),
  ('& Pilot Car', '-pilot-car', 'escort_operator', '', 'AZ', 'US', 'unclaimed', true, 10, '{"phone":"559-363-5656","website":"","services":[],"claim_hash":"571df8171df95679","source":"uspilotcars.com","additional_cities":[],"additional_regions":["CA","NV","NM","UT"]}'::jsonb),
  ('Warsaw, Mo', 'warsaw-mo', 'escort_operator', '', 'AR', 'US', 'unclaimed', true, 10, '{"phone":"660-281-6307","website":"","services":[],"claim_hash":"5d8e10e830c30eff","source":"uspilotcars.com","additional_cities":[],"additional_regions":["IL","IN","IA","KS","MI","MN","NE","OH","OK"]}'::jsonb),
  ('Texarkana, Ar', 'texarkana-ar', 'escort_operator', '', 'AR', 'US', 'unclaimed', true, 10, '{"phone":"903-744-3166","website":"","services":[],"claim_hash":"01178161e150a77e","source":"uspilotcars.com","additional_cities":[],"additional_regions":[]}'::jsonb),
  ('Houston, Tx', 'houston-tx', 'escort_operator', '', 'AR', 'US', 'unclaimed', true, 10, '{"phone":"281-923-8136","website":"","services":[],"claim_hash":"ac0a94cafafbb760","source":"uspilotcars.com","additional_cities":[],"additional_regions":["LA","OK","TX"]}'::jsonb),
  ('Norfolk, Ne', 'norfolk-ne', 'escort_operator', '', 'AR', 'US', 'unclaimed', true, 10, '{"phone":"402-803-0644","website":"","services":[],"claim_hash":"2c912290e7feed95","source":"uspilotcars.com","additional_cities":[],"additional_regions":["CO","IL","IA","KS","MN","NE","ND","OK","SD","TX","WI","WY"]}'::jsonb),
  ('Texarkana, Ar', 'texarkana-ar', 'escort_operator', '', 'AR', 'US', 'unclaimed', true, 10, '{"phone":"870-703-1576","website":"","services":[],"claim_hash":"9f2a2a4b52354069","source":"uspilotcars.com","additional_cities":[],"additional_regions":["LA","OK","TX"]}'::jsonb),
  ('Sallisaw, Ok', 'sallisaw-ok', 'escort_operator', '', 'AR', 'US', 'unclaimed', true, 10, '{"phone":"918-682-9636","website":"","services":[],"claim_hash":"96586a3e6360cff9","source":"uspilotcars.com","additional_cities":[],"additional_regions":["OK","TX"]}'::jsonb),
  ('Texarkana, Ar', 'texarkana-ar', 'escort_operator', '', 'AR', 'US', 'unclaimed', true, 10, '{"phone":"318-469-3748","website":"","services":[],"claim_hash":"3bc6c50383b6e9b0","source":"uspilotcars.com","additional_cities":[],"additional_regions":[]}'::jsonb),
  ('Northeast La', 'northeast-la', 'escort_operator', '', 'AR', 'US', 'unclaimed', true, 10, '{"phone":"318-432-4270","website":"","services":[],"claim_hash":"10b5ed044c64f486","source":"uspilotcars.com","additional_cities":[],"additional_regions":["LA","TX"]}'::jsonb),
  ('Long Beach, Ca', 'long-beach-ca', 'escort_operator', 'First Choice Pilot Cars', 'CA', 'US', 'unclaimed', true, 10, '{"phone":"424-203-3227","website":"","services":[],"claim_hash":"a837ae1b8927c4b5","source":"uspilotcars.com","additional_cities":[],"additional_regions":[]}'::jsonb),
  ('Fairfield, Ca', 'fairfield-ca', 'escort_operator', '', 'CA', 'US', 'unclaimed', true, 10, '{"phone":"707-592-4294","website":"","services":[],"claim_hash":"24591c99162153c7","source":"uspilotcars.com","additional_cities":[],"additional_regions":[]}'::jsonb),
  ('Ontario, Or', 'ontario-or', 'escort_operator', 'Northwest Pilot Cars', 'CA', 'US', 'unclaimed', true, 10, '{"phone":"541-823-7039","website":"","services":[],"claim_hash":"8219ac2eb8451f7d","source":"uspilotcars.com","additional_cities":[],"additional_regions":[]}'::jsonb),
  ('Reno, Nv', 'reno-nv', 'escort_operator', '', 'CA', 'US', 'unclaimed', true, 10, '{"phone":"775-745-5840","website":"","services":[],"claim_hash":"f35165fa03354f08","source":"uspilotcars.com","additional_cities":[],"additional_regions":["UT"]}'::jsonb),
  ('Long Beach, Ca', 'long-beach-ca', 'escort_operator', '', 'CA', 'US', 'unclaimed', true, 10, '{"phone":"951-378-2992","website":"","services":[],"claim_hash":"0fd8e6a5106594f2","source":"uspilotcars.com","additional_cities":[],"additional_regions":[]}'::jsonb),
  ('Sacramento, Ca', 'sacramento-ca', 'escort_operator', 'Zephyr Pilot, LLC', 'CA', 'US', 'unclaimed', true, 10, '{"phone":"530-526-9765","website":"","services":[],"claim_hash":"c9b9c9c15d0a8a25","source":"uspilotcars.com","additional_cities":[],"additional_regions":[]}'::jsonb),
  ('Long Beach, Ca', 'long-beach-ca', 'escort_operator', '', 'CA', 'US', 'unclaimed', true, 10, '{"phone":"951-442-4476","website":"","services":[],"claim_hash":"436e8af5021f2343","source":"uspilotcars.com","additional_cities":[],"additional_regions":[]}'::jsonb),
  ('Bellingham, Wa', 'bellingham-wa', 'escort_operator', '', 'CA', 'US', 'unclaimed', true, 10, '{"phone":"360-820-8388","website":"","services":[],"claim_hash":"abd33f7ec117ba41","source":"uspilotcars.com","additional_cities":[],"additional_regions":["OR","WA"]}'::jsonb),
  ('Sacramento, Ca/Reno, Nv', 'sacramento-careno-nv', 'escort_operator', '', 'CA', 'US', 'unclaimed', true, 10, '{"phone":"916-459-7079","website":"","services":[],"claim_hash":"167c0e4f6c636c82","source":"uspilotcars.com","additional_cities":[],"additional_regions":["NV"]}'::jsonb),
  ('Bakersfield, Ca', 'bakersfield-ca', 'escort_operator', '', 'CA', 'US', 'unclaimed', true, 10, '{"phone":"760-223-2397","website":"","services":[],"claim_hash":"fe4a972127d3ea7e","source":"uspilotcars.com","additional_cities":[],"additional_regions":[]}'::jsonb),
  ('Stockton, Ca', 'stockton-ca', 'escort_operator', '', 'CA', 'US', 'unclaimed', true, 10, '{"phone":"209-901-6130","website":"","services":[],"claim_hash":"03f912218b09a445","source":"uspilotcars.com","additional_cities":[],"additional_regions":[]}'::jsonb),
  ('Cripple Creek/Victor, Co', 'cripple-creekvictor-co', 'escort_operator', 'All State Pilot Cars', 'CO', 'US', 'unclaimed', true, 10, '{"phone":"719-465-4643","website":"","services":[],"claim_hash":"c7bc534eb97c016f","source":"uspilotcars.com","additional_cities":[],"additional_regions":[]}'::jsonb),
  ('Fort Collins, Co', 'fort-collins-co', 'escort_operator', '', 'CO', 'US', 'unclaimed', true, 10, '{"phone":"970-217-1334","website":"","services":[],"claim_hash":"3dbb60cd393a2f59","source":"uspilotcars.com","additional_cities":[],"additional_regions":["KS","NE","WY"]}'::jsonb),
  ('Peoria, Az', 'peoria-az', 'escort_operator', '', 'CO', 'US', 'unclaimed', true, 10, '{"phone":"623-910-3236","website":"","services":[],"claim_hash":"eda143aabecf14ba","source":"uspilotcars.com","additional_cities":[],"additional_regions":["NM"]}'::jsonb),
  ('Fort Morgan, Co', 'fort-morgan-co', 'escort_operator', '', 'CO', 'US', 'unclaimed', true, 10, '{"phone":"308-249-4899","website":"","services":[],"claim_hash":"8db9db3eaf701874","source":"uspilotcars.com","additional_cities":[],"additional_regions":["KS","NE","WY"]}'::jsonb),
  ('Pueblo, Co', 'pueblo-co', 'escort_operator', 'Roadrunner Pilot Car', 'CO', 'US', 'unclaimed', true, 10, '{"phone":"719-281-0806","website":"","services":[],"claim_hash":"56d5f27c2905afb2","source":"uspilotcars.com","additional_cities":[],"additional_regions":["KS","NM","WY"]}'::jsonb),
  ('Cheyenne, Wy', 'cheyenne-wy', 'escort_operator', '', 'CO', 'US', 'unclaimed', true, 10, '{"phone":"307-632-6409","website":"","services":[],"claim_hash":"2bc26cba6175d336","source":"uspilotcars.com","additional_cities":[],"additional_regions":["KS","MT","NE","UT","WY"]}'::jsonb),
  ('Odessa, Tx', 'odessa-tx', 'escort_operator', 'Hunters Pilot Car LLC', 'CO', 'US', 'unclaimed', true, 10, '{"phone":"432-924-2289","website":"","services":[],"claim_hash":"67549073a4c138e5","source":"uspilotcars.com","additional_cities":[],"additional_regions":["KS","OK","TX"]}'::jsonb),
  ('Denver/Pueblo, Co', 'denverpueblo-co', 'escort_operator', '', 'CO', 'US', 'unclaimed', true, 10, '{"phone":"626-278-7545","website":"","services":[],"claim_hash":"83d4178c292c85ad","source":"uspilotcars.com","additional_cities":[],"additional_regions":[]}'::jsonb),
  ('Aurora, Co', 'aurora-co', 'escort_operator', '', 'CO', 'US', 'unclaimed', true, 10, '{"phone":"303-550-1452","website":"","services":[],"claim_hash":"5a9bbf77e5ea34c9","source":"uspilotcars.com","additional_cities":[],"additional_regions":["KS","UT","WY"]}'::jsonb),
  ('Rifle, Co', 'rifle-co', 'escort_operator', '', 'CO', 'US', 'unclaimed', true, 10, '{"phone":"970-274-1337","website":"","services":[],"claim_hash":"ceaf380b0eb55311","source":"uspilotcars.com","additional_cities":[],"additional_regions":["KS","NM","UT","WY"]}'::jsonb),
  ('Burns /Cheyenne, Wy', 'burns-cheyenne-wy', 'escort_operator', '', 'CO', 'US', 'unclaimed', true, 10, '{"phone":"307-477-7771","website":"","services":[],"claim_hash":"75927f0bcd6fa351","source":"uspilotcars.com","additional_cities":[],"additional_regions":["MT","SD"]}'::jsonb),
  ('Vernal, Ut', 'vernal-ut', 'escort_operator', '', 'CO', 'US', 'unclaimed', true, 10, '{"phone":"435-790-1226","website":"","services":[],"claim_hash":"e368b91174335602","source":"uspilotcars.com","additional_cities":[],"additional_regions":["NV","UT","WY"]}'::jsonb),
  ('Cheyenne, Wy', 'cheyenne-wy', 'escort_operator', 'Professional Oversize Escort Svcs.', 'CO', 'US', 'unclaimed', true, 10, '{"phone":"307-275-6814","website":"","services":[],"claim_hash":"6b09fa4b63423a8f","source":"uspilotcars.com","additional_cities":[],"additional_regions":["NE","NM","WY"]}'::jsonb),
  ('Limon, Co', 'limon-co', 'escort_operator', '', 'CO', 'US', 'unclaimed', true, 10, '{"phone":"719-330-6080","website":"","services":[],"claim_hash":"abadff8b15178c12","source":"uspilotcars.com","additional_cities":[],"additional_regions":[]}'::jsonb),
  ('Canon City, Co', 'canon-city-co', 'escort_operator', '', 'CO', 'US', 'unclaimed', true, 10, '{"phone":"719-371-5700","website":"","services":[],"claim_hash":"7aee28055d29a573","source":"uspilotcars.com","additional_cities":[],"additional_regions":["KS","UT","WY"]}'::jsonb),
  ('Canon City, Co', 'canon-city-co', 'escort_operator', '', 'CO', 'US', 'unclaimed', true, 10, '{"phone":"719-429-9617","website":"","services":[],"claim_hash":"8b68dc30f5c1e566","source":"uspilotcars.com","additional_cities":[],"additional_regions":[]}'::jsonb),
  ('Brighton/ Fort Collins, Co', 'brighton-fort-collins-co', 'escort_operator', '', 'CO', 'US', 'unclaimed', true, 10, '{"phone":"720-810-6155","website":"","services":[],"claim_hash":"f3feb6481730f593","source":"uspilotcars.com","additional_cities":[],"additional_regions":["KS","SD","TX","WY"]}'::jsonb),
  ('Farmington, Nm', 'farmington-nm', 'escort_operator', '', 'CO', 'US', 'unclaimed', true, 10, '{"phone":"505-486-9835","website":"","services":[],"claim_hash":"c369f568464431bd","source":"uspilotcars.com","additional_cities":[],"additional_regions":["NM","TX","UT"]}'::jsonb),
  ('Burns/Cheyenne, Wy| East West Pilot Car Service, LLC', 'burnscheyenne-wy-east-west-pilot-car-service-llc', 'escort_operator', '', 'CO', 'US', 'unclaimed', true, 10, '{"phone":"307-477-7771","website":"","services":[],"claim_hash":"ff7e8462df417357","source":"uspilotcars.com","additional_cities":[],"additional_regions":[]}'::jsonb),
  ('Nyc/Long Island, Ny', 'nyclong-island-ny', 'escort_operator', '', 'CT', 'US', 'unclaimed', true, 10, '{"phone":"918-886-0992","website":"","services":[],"claim_hash":"1d24f1f6590d6c50","source":"uspilotcars.com","additional_cities":[],"additional_regions":["NJ","NY","PA"]}'::jsonb),
  ('Mile Makers Pilot Car Services', 'mile-makers-pilot-car-services', 'escort_operator', '', 'CT', 'US', 'unclaimed', true, 10, '{"phone":"301-305-7563","website":"","services":[],"claim_hash":"91bc4f1c5aa822bb","source":"uspilotcars.com","additional_cities":[],"additional_regions":["FL"]}'::jsonb),
  ('Baltimore, Md', 'baltimore-md', 'escort_operator', '', 'DE', 'US', 'unclaimed', true, 10, '{"phone":"240-818-6454","website":"","services":[],"claim_hash":"79f76fe052f3a672","source":"uspilotcars.com","additional_cities":[],"additional_regions":["MD","PA","VA"]}'::jsonb),
  ('Workers', 'workers', 'escort_operator', 'Program', 'FL', 'US', 'unclaimed', true, 10, '{"phone":"801-262-3525","website":"","services":[],"claim_hash":"b6f7e4b26e82f1c7","source":"uspilotcars.com","additional_cities":[],"additional_regions":[]}'::jsonb),
  ('Alachua, Fl | Amber Pilot Cars', 'alachua-fl-amber-pilot-cars', 'escort_operator', '', 'FL', 'US', 'unclaimed', true, 10, '{"phone":"919-809-2313","website":"","services":[],"claim_hash":"30f74b88b6169c38","source":"uspilotcars.com","additional_cities":[],"additional_regions":[]}'::jsonb),
  ('Houston, Tx', 'houston-tx', 'escort_operator', '', 'FL', 'US', 'unclaimed', true, 10, '{"phone":"832-594-9306","website":"","services":[],"claim_hash":"5884730b49023770","source":"uspilotcars.com","additional_cities":[],"additional_regions":["MI"]}'::jsonb),
  ('Alachua, Fl', 'alachua-fl', 'escort_operator', '', 'FL', 'US', 'unclaimed', true, 10, '{"phone":"919-809-2313","website":"","services":[],"claim_hash":"454c360cf2cad297","source":"uspilotcars.com","additional_cities":[],"additional_regions":[]}'::jsonb),
  ('Seminary, Ms', 'seminary-ms', 'escort_operator', '', 'FL', 'US', 'unclaimed', true, 10, '{"phone":"601-517-3789","website":"","services":[],"claim_hash":"60edad2e228d412f","source":"uspilotcars.com","additional_cities":[],"additional_regions":["LA"]}'::jsonb),
  ('Coldwater, Mi', 'coldwater-mi', 'escort_operator', '', 'IL', 'US', 'unclaimed', true, 10, '{"phone":"269-209-3698","website":"","services":[],"claim_hash":"70c6b5e580a09537","source":"uspilotcars.com","additional_cities":[],"additional_regions":["IN","MI","OH"]}'::jsonb),
  ('Menominee, Mi', 'menominee-mi', 'escort_operator', '', 'IL', 'US', 'unclaimed', true, 10, '{"phone":"715-587-0554","website":"","services":[],"claim_hash":"31d95ee3490644bf","source":"uspilotcars.com","additional_cities":[],"additional_regions":["MI","MN","WI"]}'::jsonb),
  ('Fort Wayne/Fremont/Gary/ Indy, In', 'fort-waynefremontgary-indy-in', 'escort_operator', '', 'IL', 'US', 'unclaimed', true, 10, '{"phone":"574-835-8743","website":"","services":[],"claim_hash":"aaf45bc0723c22e5","source":"uspilotcars.com","additional_cities":[],"additional_regions":["MI","OH"]}'::jsonb),
  ('Indianapolis, In 47331', 'indianapolis-in-47331', 'escort_operator', '', 'IL', 'US', 'unclaimed', true, 10, '{"phone":"308-529-8800","website":"","services":[],"claim_hash":"5c27bafd527c2bcb","source":"uspilotcars.com","additional_cities":[],"additional_regions":["KY"]}'::jsonb),
  ('Rockwood, Mi', 'rockwood-mi', 'escort_operator', '', 'IL', 'US', 'unclaimed', true, 10, '{"phone":"734-799-6833","website":"","services":[],"claim_hash":"1ff394de0e6a6225","source":"uspilotcars.com","additional_cities":[],"additional_regions":["IN","MI","PA"]}'::jsonb),
  ('Holland, Mi', 'holland-mi', 'escort_operator', '', 'IL', 'US', 'unclaimed', true, 10, '{"phone":"616-836-2283","website":"","services":[],"claim_hash":"41099c81dd2153ab","source":"uspilotcars.com","additional_cities":[],"additional_regions":["IN","MI","WI"]}'::jsonb),
  ('Fort Wayne/Fremont/Gary, In', 'fort-waynefremontgary-in', 'escort_operator', '', 'IN', 'US', 'unclaimed', true, 10, '{"phone":"574-835-8743","website":"","services":[],"claim_hash":"a18c7b94a999a46c","source":"uspilotcars.com","additional_cities":[],"additional_regions":[]}'::jsonb),
  ('Southfield, Mi', 'southfield-mi', 'escort_operator', '', 'IN', 'US', 'unclaimed', true, 10, '{"phone":"248-761-5343","website":"","services":[],"claim_hash":"7d04212452da5e99","source":"uspilotcars.com","additional_cities":[],"additional_regions":["MI","OH","ON"]}'::jsonb),
  ('Sheridan, In', 'sheridan-in', 'escort_operator', '', 'IN', 'US', 'unclaimed', true, 10, '{"phone":"317-371-4228","website":"","services":[],"claim_hash":"bd9c456407e4506e","source":"uspilotcars.com","additional_cities":[],"additional_regions":[]}'::jsonb),
  ('Indianapolis', 'indianapolis', 'escort_operator', '', 'IN', 'US', 'unclaimed', true, 10, '{"phone":"317-694-4444","website":"","services":[],"claim_hash":"7577ded845e11719","source":"uspilotcars.com","additional_cities":[],"additional_regions":["KY","MI","OH"]}'::jsonb),
  ('Indianapolis, In', 'indianapolis-in', 'escort_operator', '', 'IN', 'US', 'unclaimed', true, 10, '{"phone":"308-529-8800","website":"","services":[],"claim_hash":"d9db55f899d80b96","source":"uspilotcars.com","additional_cities":[],"additional_regions":["MI","WI"]}'::jsonb),
  ('Anderson, In', 'anderson-in', 'escort_operator', 'Taylor Piloting', 'IN', 'US', 'unclaimed', true, 10, '{"phone":"765-620-7438","website":"","services":[],"claim_hash":"4fb9b93aa0bd8cea","source":"uspilotcars.com","additional_cities":[],"additional_regions":["KY","TX"]}'::jsonb),
  ('Indianapolis, In', 'indianapolis-in', 'escort_operator', '', 'IN', 'US', 'unclaimed', true, 10, '{"phone":"765-389-3168","website":"","services":[],"claim_hash":"e5802811fa29cb55","source":"uspilotcars.com","additional_cities":[],"additional_regions":[]}'::jsonb),
  ('Murray, Ne |Towering Oak Pilot Cars', 'murray-ne-towering-oak-pilot-cars', 'escort_operator', '', 'IA', 'US', 'unclaimed', true, 10, '{"phone":"402-718-0698","website":"","services":[],"claim_hash":"0a52e812199913ac","source":"uspilotcars.com","additional_cities":[],"additional_regions":["KS","MO","NE"]}'::jsonb),
  ('Springfield, Mo', 'springfield-mo', 'escort_operator', '', 'IA', 'US', 'unclaimed', true, 10, '{"phone":"479-670-2176","website":"","services":[],"claim_hash":"294970a18ad7b0a2","source":"uspilotcars.com","additional_cities":[],"additional_regions":["KS","OK"]}'::jsonb),
  ('Greater Kansas City Area', 'greater-kansas-city-area', 'escort_operator', '', 'IA', 'US', 'unclaimed', true, 10, '{"phone":"913-485-3813","website":"","services":[],"claim_hash":"67322bb795a5a474","source":"uspilotcars.com","additional_cities":[],"additional_regions":["OK"]}'::jsonb),
  ('Wahpeton, Nd/St. Paul, Mn/Council Bluffs, Ia', 'wahpeton-ndst-paul-mncouncil-bluffs-ia', 'escort_operator', '', 'IA', 'US', 'unclaimed', true, 10, '{"phone":"701-899-0173","website":"","services":[],"claim_hash":"a753b801112a17c1","source":"uspilotcars.com","additional_cities":[],"additional_regions":["KS"]}'::jsonb),
  ('Chester & Alma, Ne/Yankton, Sd', 'chester-alma-neyankton-sd', 'escort_operator', '', 'IA', 'US', 'unclaimed', true, 10, '{"phone":"402-366-0730","website":"","services":[],"claim_hash":"6de6e333d250e024","source":"uspilotcars.com","additional_cities":[],"additional_regions":[]}'::jsonb),
  ('Council Bluffs, Ia', 'council-bluffs-ia', 'escort_operator', 'County Line Pilot Car, LLC', 'IA', 'US', 'unclaimed', true, 10, '{"phone":"402-984-0976","website":"","services":[],"claim_hash":"191490f3a5cf8ca9","source":"uspilotcars.com","additional_cities":[],"additional_regions":[]}'::jsonb),
  ('Kansas City, Ks', 'kansas-city-ks', 'escort_operator', '', 'IA', 'US', 'unclaimed', true, 10, '{"phone":"816-560-0906","website":"","services":[],"claim_hash":"25de82933dbe6fff","source":"uspilotcars.com","additional_cities":["Djs Pilot Cars, LLC"],"additional_regions":["KS","OK"]}'::jsonb),
  ('York, Ne', 'york-ne', 'escort_operator', '', 'IA', 'US', 'unclaimed', true, 10, '{"phone":"402-366-2028","website":"","services":[],"claim_hash":"cc569a1ef1fa4c1f","source":"uspilotcars.com","additional_cities":[],"additional_regions":["KS","NE","OK"]}'::jsonb),
  ('Grand Island, Ne', 'grand-island-ne', 'escort_operator', '', 'IA', 'US', 'unclaimed', true, 10, '{"phone":"308-940-3251","website":"","services":[],"claim_hash":"852c61ea971a3f76","source":"uspilotcars.com","additional_cities":[],"additional_regions":["KS","NE","SD"]}'::jsonb),
  ('Murray, Ne', 'murray-ne', 'escort_operator', '', 'IA', 'US', 'unclaimed', true, 10, '{"phone":"402-718-0698","website":"","services":[],"claim_hash":"f4090f9134142b2a","source":"uspilotcars.com","additional_cities":[],"additional_regions":["KS","NE"]}'::jsonb),
  ('Fort Wayne/Fremont, In', 'fort-waynefremont-in', 'escort_operator', '', 'KS', 'US', 'unclaimed', true, 10, '{"phone":"260-336-2412","website":"","services":[],"claim_hash":"1276f98491570f9e","source":"uspilotcars.com","additional_cities":[],"additional_regions":[]}'::jsonb),
  ('Wichita, Ks', 'wichita-ks', 'escort_operator', '', 'KS', 'US', 'unclaimed', true, 10, '{"phone":"903-744-3166","website":"","services":[],"claim_hash":"b9ce3982a8761aaf","source":"uspilotcars.com","additional_cities":[],"additional_regions":[]}'::jsonb),
  ('Woodward, Ok', 'woodward-ok', 'escort_operator', '', 'KS', 'US', 'unclaimed', true, 10, '{"phone":"580-216-7881","website":"","services":[],"claim_hash":"3e9f9dfd30d00cff","source":"uspilotcars.com","additional_cities":[],"additional_regions":["NE","TX"]}'::jsonb),
  ('Chester, Ne/Yankton, Sd', 'chester-neyankton-sd', 'escort_operator', '', 'KS', 'US', 'unclaimed', true, 10, '{"phone":"402-366-0730","website":"","services":[],"claim_hash":"373b623c50d6ad2d","source":"uspilotcars.com","additional_cities":[],"additional_regions":["NE","SD"]}'::jsonb),
  ('Johnson City, Tn', 'johnson-city-tn', 'escort_operator', '', 'KS', 'US', 'unclaimed', true, 10, '{"phone":"907-957-0107","website":"","services":[],"claim_hash":"06ab7e47936abbdd","source":"uspilotcars.com","additional_cities":[],"additional_regions":["MD","OH"]}'::jsonb),
  ('Salina, Ks', 'salina-ks', 'escort_operator', 'County Line Pilot Car, LLC', 'KS', 'US', 'unclaimed', true, 10, '{"phone":"402-984-0976","website":"","services":[],"claim_hash":"545ab06e33cd3a85","source":"uspilotcars.com","additional_cities":[],"additional_regions":[]}'::jsonb),
  ('Kansas City, Ks', 'kansas-city-ks', 'escort_operator', '', 'KS', 'US', 'unclaimed', true, 10, '{"phone":"913-485-3813","website":"","services":[],"claim_hash":"bcb0bf043deb652f","source":"uspilotcars.com","additional_cities":[],"additional_regions":[]}'::jsonb),
  ('Blue Springs, Mo', 'blue-springs-mo', 'escort_operator', '', 'KS', 'US', 'unclaimed', true, 10, '{"phone":"816-674-3253","website":"","services":[],"claim_hash":"c0b34bf4c8d9be42","source":"uspilotcars.com","additional_cities":[],"additional_regions":["OK"]}'::jsonb),
  ('So. Charleston, Wv', 'so-charleston-wv', 'escort_operator', '', 'KY', 'US', 'unclaimed', true, 10, '{"phone":"304-437-0403","website":"","services":[],"claim_hash":"cd7f096a0fd11e5b","source":"uspilotcars.com","additional_cities":[],"additional_regions":["MD","OH","PA","VA","WV"]}'::jsonb),
  ('Hamlin, Wv', 'hamlin-wv', 'escort_operator', 'Almost Heaven Pilot Cars', 'KY', 'US', 'unclaimed', true, 10, '{"phone":"304-360-4102","website":"","services":[],"claim_hash":"4cfdf71af9e27f55","source":"uspilotcars.com","additional_cities":[],"additional_regions":["OH","VA","WV"]}'::jsonb),
  ('Bowling Green, Ky', 'bowling-green-ky', 'escort_operator', '', 'KY', 'US', 'unclaimed', true, 10, '{"phone":"270-407-8412","website":"","services":[],"claim_hash":"10427a9916622c7b","source":"uspilotcars.com","additional_cities":[],"additional_regions":[]}'::jsonb),
  ('Cards', 'cards', 'escort_operator', 'All Credit', 'LA', 'US', 'unclaimed', true, 10, '{"phone":"337-551-3983","website":"http://www.louisianafrog.com/","services":[],"claim_hash":"1e02a78df6a42f56","source":"uspilotcars.com","additional_cities":[],"additional_regions":[]}'::jsonb),
  ('Waskom, Tx', 'waskom-tx', 'escort_operator', 'Bama Pilot Cars', 'LA', 'US', 'unclaimed', true, 10, '{"phone":"469-223-4620","website":"","services":[],"claim_hash":"b734065556227d3d","source":"uspilotcars.com","additional_cities":[],"additional_regions":["OK","TX"]}'::jsonb),
  ('Monmouth, Me', 'monmouth-me', 'escort_operator', '', 'ME', 'US', 'unclaimed', true, 10, '{"phone":"207-240-7876","website":"","services":[],"claim_hash":"e363a401c1b466a6","source":"uspilotcars.com","additional_cities":[],"additional_regions":[]}'::jsonb),
  ('Hertford, Nc', 'hertford-nc', 'escort_operator', 'R & C Pilot Cars', 'MD', 'US', 'unclaimed', true, 10, '{"phone":"252-340-0879","website":"","services":[],"claim_hash":"0204d59c8ec11b82","source":"uspilotcars.com","additional_cities":[],"additional_regions":[]}'::jsonb),
  ('Wheeling, Wv', 'wheeling-wv', 'escort_operator', '', 'MD', 'US', 'unclaimed', true, 10, '{"phone":"304-639-6410","website":"","services":[],"claim_hash":"0b29a25e7052ab97","source":"uspilotcars.com","additional_cities":[],"additional_regions":[]}'::jsonb),
  ('Callao, Va', 'callao-va', 'escort_operator', '', 'MD', 'US', 'unclaimed', true, 10, '{"phone":"804-238-8216","website":"","services":[],"claim_hash":"bd98e659957dd864","source":"uspilotcars.com","additional_cities":[],"additional_regions":["NC","PA","VA"]}'::jsonb),
  ('Woodbridge, Va', 'woodbridge-va', 'escort_operator', '', 'MD', 'US', 'unclaimed', true, 10, '{"phone":"703-898-8718","website":"","services":[],"claim_hash":"f538f2548ade9cf4","source":"uspilotcars.com","additional_cities":[],"additional_regions":["NC","VA","WV"]}'::jsonb),
  ('Baltimore, Md', 'baltimore-md', 'escort_operator', 'Coast-To-Coast Pilot Cars', 'MD', 'US', 'unclaimed', true, 10, '{"phone":"330-610-2492","website":"","services":[],"claim_hash":"620e0d67f77d0ee8","source":"uspilotcars.com","additional_cities":[],"additional_regions":[]}'::jsonb),
  ('Fort Mill, Sc/Washington, Dc', 'fort-mill-scwashington-dc', 'escort_operator', '', 'MD', 'US', 'unclaimed', true, 10, '{"phone":"704-492-3643","website":"","services":[],"claim_hash":"8fb48bb78f000403","source":"uspilotcars.com","additional_cities":[],"additional_regions":[]}'::jsonb),
  ('Nationwide Services', 'nationwide-services', 'escort_operator', '', 'MD', 'US', 'unclaimed', true, 10, '{"phone":"301-458-0111","website":"","services":[],"claim_hash":"3cad8ab1d4350f2d","source":"uspilotcars.com","additional_cities":[],"additional_regions":["PA","VA","WV"]}'::jsonb),
  ('Harrisburg, Pa', 'harrisburg-pa', 'escort_operator', '', 'MD', 'US', 'unclaimed', true, 10, '{"phone":"570-516-4112","website":"","services":[],"claim_hash":"5cf463b4bca46b3f","source":"uspilotcars.com","additional_cities":[],"additional_regions":["OH","PA","WV"]}'::jsonb),
  ('Pittsfield, Ma', 'pittsfield-ma', 'escort_operator', '', 'MA', 'US', 'unclaimed', true, 10, '{"phone":"413-441-0542","website":"","services":[],"claim_hash":"cca0583cd159e8b2","source":"uspilotcars.com","additional_cities":[],"additional_regions":[]}'::jsonb),
  ('Springfield, Ma', 'springfield-ma', 'escort_operator', '', 'MA', 'US', 'unclaimed', true, 10, '{"phone":"217-860-2201","website":"","services":[],"claim_hash":"3f90b58cf260d8b2","source":"uspilotcars.com","additional_cities":[],"additional_regions":[]}'::jsonb),
  ('Northeast Us', 'northeast-us', 'escort_operator', '', 'MA', 'US', 'unclaimed', true, 10, '{"phone":"203-994-2620","website":"","services":[],"claim_hash":"ec56484fecadf224","source":"uspilotcars.com","additional_cities":[],"additional_regions":[]}'::jsonb),
  ('Red Wing, Mn', 'red-wing-mn', 'escort_operator', '', 'MN', 'US', 'unclaimed', true, 10, '{"phone":"651-380-5578","website":"","services":[],"claim_hash":"80990c1a18d4ab5e","source":"uspilotcars.com","additional_cities":[],"additional_regions":[]}'::jsonb),
  ('Jamestown, Nd', 'jamestown-nd', 'escort_operator', '', 'MN', 'US', 'unclaimed', true, 10, '{"phone":"701-368-2415","website":"","services":[],"claim_hash":"2d51250fcc8adfc3","source":"uspilotcars.com","additional_cities":[],"additional_regions":["MT","ND","SD"]}'::jsonb),
  ('Fargo, Nd', 'fargo-nd', 'escort_operator', '', 'MN', 'US', 'unclaimed', true, 10, '{"phone":"701-532-0252","website":"","services":[],"claim_hash":"29b1033d9a5bc8f3","source":"uspilotcars.com","additional_cities":[],"additional_regions":["MT","ND","SD"]}'::jsonb),
  ('Granville, Nd', 'granville-nd', 'escort_operator', '', 'MN', 'US', 'unclaimed', true, 10, '{"phone":"701-240-4969","website":"","services":[],"claim_hash":"849ee6ccbde16ed2","source":"uspilotcars.com","additional_cities":[],"additional_regions":["MT","ND","SD","WY","SK"]}'::jsonb),
  ('Fargo, Nd', 'fargo-nd', 'escort_operator', 'Tri-State Piloting LLC', 'MN', 'US', 'unclaimed', true, 10, '{"phone":"701-552-3404","website":"","services":[],"claim_hash":"58c543bb4a14a3dd","source":"uspilotcars.com","additional_cities":[],"additional_regions":["MT","ND","SD"]}'::jsonb),
  ('Tcb Escorts LLC', 'tcb-escorts-llc', 'escort_operator', 'All Credit   
   Cards   
 
 
  Jackson', 'MS', 'US', 'unclaimed', true, 10, '{"phone":"601-612-0106","website":"","services":[],"claim_hash":"c586e99d5658692c","source":"uspilotcars.com","additional_cities":[],"additional_regions":[]}'::jsonb),
  ('Rapid City, Sd', 'rapid-city-sd', 'escort_operator', 'Dalaines Pilotcar', 'MT', 'US', 'unclaimed', true, 10, '{"phone":"605-545-2930","website":"","services":[],"claim_hash":"5b8e896a0fc47221","source":"uspilotcars.com","additional_cities":[],"additional_regions":["NE","ND","SD","WY"]}'::jsonb),
  ('Spokane, Wa', 'spokane-wa', 'escort_operator', '', 'MT', 'US', 'unclaimed', true, 10, '{"phone":"509-994-6690","website":"","services":[],"claim_hash":"fe730d4c9bb08bfb","source":"uspilotcars.com","additional_cities":[],"additional_regions":["OR","WA"]}'::jsonb),
  ('Billings, Mt', 'billings-mt', 'escort_operator', '', 'MT', 'US', 'unclaimed', true, 10, '{"phone":"406-697-5909","website":"","services":[],"claim_hash":"6ac01ebe8cf0a087","source":"uspilotcars.com","additional_cities":[],"additional_regions":["ND","SD"]}'::jsonb),
  ('Moorcroft, Wy', 'moorcroft-wy', 'escort_operator', '', 'MT', 'US', 'unclaimed', true, 10, '{"phone":"307-351-2322","website":"","services":[],"claim_hash":"ad3f0c1f69628d56","source":"uspilotcars.com","additional_cities":["Rogue Hotshots PCS LLC Witpac"],"additional_regions":["NE","SD","WY"]}'::jsonb),
  ('Post Falls, Id', 'post-falls-id', 'escort_operator', '', 'MT', 'US', 'unclaimed', true, 10, '{"phone":"208-449-1011","website":"","services":[],"claim_hash":"8dfcb192ec86c474","source":"uspilotcars.com","additional_cities":[],"additional_regions":["OR","WA"]}'::jsonb),
  ('Miles City, Mt', 'miles-city-mt', 'escort_operator', '', 'MT', 'US', 'unclaimed', true, 10, '{"phone":"406-853-1024","website":"","services":[],"claim_hash":"317ed53899edba43","source":"uspilotcars.com","additional_cities":[],"additional_regions":[]}'::jsonb),
  ('Casper. Wy', 'casper-wy', 'escort_operator', '', 'MT', 'US', 'unclaimed', true, 10, '{"phone":"307-389-7285","website":"","services":[],"claim_hash":"ed12d88c0238663b","source":"uspilotcars.com","additional_cities":[],"additional_regions":["SD","UT","WY"]}'::jsonb),
  ('Big Sky Pilots  &Nbsp;', 'big-sky-pilots-nbsp', 'escort_operator', 'Billings', 'MT', 'US', 'unclaimed', true, 10, '{"phone":"406-697-5909","website":"","services":[],"claim_hash":"9cfc5e1fbd54a240","source":"uspilotcars.com","additional_cities":[],"additional_regions":[]}'::jsonb),
  ('Norwalk, Iowa', 'norwalk-iowa', 'escort_operator', '', 'NE', 'US', 'unclaimed', true, 10, '{"phone":"515-205-7973","website":"","services":[],"claim_hash":"77dfeaad221e4205","source":"uspilotcars.com","additional_cities":[],"additional_regions":[]}'::jsonb),
  ('Burns, Wy', 'burns-wy', 'escort_operator', '', 'NE', 'US', 'unclaimed', true, 10, '{"phone":"307-477-7771","website":"","services":[],"claim_hash":"f7d11f2ed1188f16","source":"uspilotcars.com","additional_cities":[],"additional_regions":["WY"]}'::jsonb),
  ('I-80 & Ne Hwys. 183,281,81,283', 'i-80-ne-hwys-18328181283', 'escort_operator', 'County Line Pilot Car, LLC', 'NE', 'US', 'unclaimed', true, 10, '{"phone":"402-984-0976","website":"","services":[],"claim_hash":"0e6ce8cc3506caaf","source":"uspilotcars.com","additional_cities":[],"additional_regions":[]}'::jsonb),
  ('Columbus, Ne', 'columbus-ne', 'escort_operator', 'Anstorm Sabre PCS, LLC', 'NE', 'US', 'unclaimed', true, 10, '{"phone":"402-270-2125","website":"","services":[],"claim_hash":"292e196765fd734c","source":"uspilotcars.com","additional_cities":[],"additional_regions":[]}'::jsonb),
  ('Midwest Pilot Cars', 'midwest-pilot-cars', 'escort_operator', 'Omaha', 'NE', 'US', 'unclaimed', true, 10, '{"phone":"605-670-9654","website":"http://midwestpilotcars.com/","services":["height_pole","route_survey","multiple_cars","steering"],"claim_hash":"a6f91f89d6afe29f","source":"uspilotcars.com","additional_cities":[],"additional_regions":["TX","VA"]}'::jsonb),
  ('J &Amp; W Torrence Pilot Car', 'j-amp-w-torrence-pilot-car', 'escort_operator', 'Neill', 'NE', 'US', 'unclaimed', true, 10, '{"phone":"405-476-8006","website":"","services":[],"claim_hash":"d2dde70f40dd27ad","source":"uspilotcars.com","additional_cities":[],"additional_regions":[]}'::jsonb),
  ('Tammy Bzzz’S Pilot Car Service', 'tammy-bzzzs-pilot-car-service', 'escort_operator', 'York', 'NE', 'US', 'unclaimed', true, 10, '{"phone":"402-366-2028","website":"","services":[],"claim_hash":"2c8a84379003e5f4","source":"uspilotcars.com","additional_cities":[],"additional_regions":[]}'::jsonb),
  ('Ely/Wendover, Nv', 'elywendover-nv', 'escort_operator', '', 'NV', 'US', 'unclaimed', true, 10, '{"phone":"702-496-8313","website":"","services":[],"claim_hash":"df5af8c784f10af8","source":"uspilotcars.com","additional_cities":[],"additional_regions":[]}'::jsonb),
  ('Jerome, Id', 'jerome-id', 'escort_operator', '', 'NV', 'US', 'unclaimed', true, 10, '{"phone":"208-731-4198","website":"","services":[],"claim_hash":"166180a120e60810","source":"uspilotcars.com","additional_cities":[],"additional_regions":["OR","UT"]}'::jsonb),
  ('Reno, Nv', 'reno-nv', 'escort_operator', '', 'NV', 'US', 'unclaimed', true, 10, '{"phone":"775-622-9112","website":"","services":[],"claim_hash":"7fa576631e2d686d","source":"uspilotcars.com","additional_cities":[],"additional_regions":[]}'::jsonb),
  ('Dts Pilot Car Service', 'dts-pilot-car-service', 'escort_operator', 'Reno', 'NV', 'US', 'unclaimed', true, 10, '{"phone":"775-842-2633","website":"http://dtspilotcar.com/","services":[],"claim_hash":"0d006f1498112b25","source":"uspilotcars.com","additional_cities":[],"additional_regions":[]}'::jsonb),
  ('Nashua, Nh', 'nashua-nh', 'escort_operator', '', 'NH', 'US', 'unclaimed', true, 10, '{"phone":"217-860-2201","website":"","services":[],"claim_hash":"b108d7a5fc0356ec","source":"uspilotcars.com","additional_cities":[],"additional_regions":[]}'::jsonb),
  ('Albuquerque, Nm', 'albuquerque-nm', 'escort_operator', '', 'NM', 'US', 'unclaimed', true, 10, '{"phone":"505-330-6188","website":"","services":[],"claim_hash":"04ee320b284c3d2c","source":"uspilotcars.com","additional_cities":[],"additional_regions":[]}'::jsonb),
  ('Rio Rancho, Nm', 'rio-rancho-nm', 'escort_operator', '', 'NM', 'US', 'unclaimed', true, 10, '{"phone":"206-293-2672","website":"","services":[],"claim_hash":"9ca4b55976af831d","source":"uspilotcars.com","additional_cities":[],"additional_regions":[]}'::jsonb),
  ('Pueblo, Co', 'pueblo-co', 'escort_operator', '', 'NM', 'US', 'unclaimed', true, 10, '{"phone":"877-333-0115","website":"","services":[],"claim_hash":"a679562de1292d2b","source":"uspilotcars.com","additional_cities":[],"additional_regions":[]}'::jsonb),
  ('Albuquerque, Nm/Phoenix, Az', 'albuquerque-nmphoenix-az', 'escort_operator', '', 'NM', 'US', 'unclaimed', true, 10, '{"phone":"626-278-7545","website":"","services":[],"claim_hash":"d977d95915103ba7","source":"uspilotcars.com","additional_cities":[],"additional_regions":[]}'::jsonb),
  ('Abuquerque. Nm', 'abuquerque-nm', 'escort_operator', 'Anstorm Sabre PCS, LLC', 'NM', 'US', 'unclaimed', true, 10, '{"phone":"402-270-2125","website":"","services":[],"claim_hash":"bfde73782ab5ead0","source":"uspilotcars.com","additional_cities":[],"additional_regions":[]}'::jsonb),
  ('Albuquerque, Nm', 'albuquerque-nm', 'escort_operator', '', 'NM', 'US', 'unclaimed', true, 10, '{"phone":"505-377-5773","website":"","services":[],"claim_hash":"0898adbf39e58d26","source":"uspilotcars.com","additional_cities":[],"additional_regions":[]}'::jsonb),
  ('Midland/Lubbock/Pecos, Tx', 'midlandlubbockpecos-tx', 'escort_operator', '', 'NM', 'US', 'unclaimed', true, 10, '{"phone":"432-250-5865","website":"","services":[],"claim_hash":"0269745f0183d0b3","source":"uspilotcars.com","additional_cities":[],"additional_regions":[]}'::jsonb),
  ('Rifle, Co', 'rifle-co', 'escort_operator', 'Twin Guns Transport. & Heavy Haul', 'NM', 'US', 'unclaimed', true, 10, '{"phone":"970-456-2169","website":"","services":[],"claim_hash":"1d0d75630ff14cb4","source":"uspilotcars.com","additional_cities":[],"additional_regions":[]}'::jsonb),
  ('Socorro, Nm', 'socorro-nm', 'escort_operator', '', 'NM', 'US', 'unclaimed', true, 10, '{"phone":"480-239-7887","website":"","services":[],"claim_hash":"53192688a347444f","source":"uspilotcars.com","additional_cities":[],"additional_regions":[]}'::jsonb),
  ('Socorro, Nm', 'socorro-nm', 'escort_operator', '', 'NM', 'US', 'unclaimed', true, 10, '{"phone":"719-641-9158","website":"","services":[],"claim_hash":"daf474c0b142d5f9","source":"uspilotcars.com","additional_cities":[],"additional_regions":[]}'::jsonb),
  ('Pocatello. Id/Farmington, Nm', 'pocatello-idfarmington-nm', 'escort_operator', '', 'NM', 'US', 'unclaimed', true, 10, '{"phone":"208-479-7290","website":"","services":[],"claim_hash":"c77650db6a9b6816","source":"uspilotcars.com","additional_cities":[],"additional_regions":[]}'::jsonb),
  ('Jamestown, Ny', 'jamestown-ny', 'escort_operator', 'Coast-To-Coast Pilot Cars', 'NY', 'US', 'unclaimed', true, 10, '{"phone":"330-610-2492","website":"","services":[],"claim_hash":"509b10e34dec5e01","source":"uspilotcars.com","additional_cities":[],"additional_regions":[]}'::jsonb),
  ('Buffalo, Ny', 'buffalo-ny', 'escort_operator', '', 'NY', 'US', 'unclaimed', true, 10, '{"phone":"716-222-2658","website":"","services":[],"claim_hash":"4b36cd18d2f4eec4","source":"uspilotcars.com","additional_cities":[],"additional_regions":["OH","VA"]}'::jsonb),
  ('Ny Metro Area', 'ny-metro-area', 'escort_operator', '', 'NY', 'US', 'unclaimed', true, 10, '{"phone":"631-669-3742","website":"","services":[],"claim_hash":"d579393ed0538d48","source":"uspilotcars.com","additional_cities":[],"additional_regions":[]}'::jsonb),
  ('Savannah, Ga', 'savannah-ga', 'escort_operator', '', 'NC', 'US', 'unclaimed', true, 10, '{"phone":"912-401-9545","website":"","services":[],"claim_hash":"3b1249ce4de84488","source":"uspilotcars.com","additional_cities":[],"additional_regions":["PA","SC"]}'::jsonb),
  ('Johnson City, Tn', 'johnson-city-tn', 'escort_operator', '', 'NC', 'US', 'unclaimed', true, 10, '{"phone":"407-310-1035","website":"","services":[],"claim_hash":"40a351d01d4141ed","source":"uspilotcars.com","additional_cities":[],"additional_regions":["SC","VA"]}'::jsonb),
  ('Fort Mill, Sc', 'fort-mill-sc', 'escort_operator', '', 'NC', 'US', 'unclaimed', true, 10, '{"phone":"704-492-3643","website":"","services":[],"claim_hash":"15bb1a9e66081511","source":"uspilotcars.com","additional_cities":[],"additional_regions":["SC"]}'::jsonb),
  ('Greenville/ Columbia, Sc', 'greenville-columbia-sc', 'escort_operator', '', 'NC', 'US', 'unclaimed', true, 10, '{"phone":"916-955-8647","website":"","services":[],"claim_hash":"dcca2cdf654716a5","source":"uspilotcars.com","additional_cities":[],"additional_regions":["SC"]}'::jsonb),
  ('Charlotte, Nc', 'charlotte-nc', 'escort_operator', '', 'NC', 'US', 'unclaimed', true, 10, '{"phone":"704-202-3127","website":"","services":[],"claim_hash":"8b100544a8e6e33f","source":"uspilotcars.com","additional_cities":[],"additional_regions":["SC","VA"]}'::jsonb),
  ('Milwaukee, Wi | Aumor Inc..', 'milwaukee-wi-aumor-inc', 'escort_operator', '', 'ND', 'US', 'unclaimed', true, 10, '{"phone":"262-666-2266","website":"","services":[],"claim_hash":"299582db07905ced","source":"uspilotcars.com","additional_cities":[],"additional_regions":["OH","SD","TN"]}'::jsonb),
  ('Blaine, Mn', 'blaine-mn', 'escort_operator', '', 'ND', 'US', 'unclaimed', true, 10, '{"phone":"612-978-9393","website":"","services":[],"claim_hash":"5826863dd217a192","source":"uspilotcars.com","additional_cities":[],"additional_regions":["WI"]}'::jsonb),
  ('Milwaukee, Wi', 'milwaukee-wi', 'escort_operator', '', 'ND', 'US', 'unclaimed', true, 10, '{"phone":"262-666-2266","website":"","services":[],"claim_hash":"33fd37c66cf01995","source":"uspilotcars.com","additional_cities":[],"additional_regions":["OH","SD"]}'::jsonb),
  ('Youngstown, Oh', 'youngstown-oh', 'escort_operator', '', 'OH', 'US', 'unclaimed', true, 10, '{"phone":"330-770-2779","website":"","services":[],"claim_hash":"fedaaae226057218","source":"uspilotcars.com","additional_cities":[],"additional_regions":[]}'::jsonb),
  ('Charleston, Wv', 'charleston-wv', 'escort_operator', '', 'OH', 'US', 'unclaimed', true, 10, '{"phone":"304-549-8743","website":"","services":[],"claim_hash":"dad487af79fd01bb","source":"uspilotcars.com","additional_cities":[],"additional_regions":["VA","WV"]}'::jsonb),
  ('Oklahoma City, Ok', 'oklahoma-city-ok', 'escort_operator', '', 'OK', 'US', 'unclaimed', true, 10, '{"phone":"918-856-6160","website":"","services":[],"claim_hash":"e6e388bf80d548d2","source":"uspilotcars.com","additional_cities":[],"additional_regions":[]}'::jsonb),
  ('Del City, Ok', 'del-city-ok', 'escort_operator', 'Akn Trucking & Pilot Car Svcs. LLC.', 'OK', 'US', 'unclaimed', true, 10, '{"phone":"405-882-7001","website":"","services":[],"claim_hash":"1f606d31c7de9190","source":"uspilotcars.com","additional_cities":[],"additional_regions":[]}'::jsonb),
  ('Idabel, Ok', 'idabel-ok', 'escort_operator', '', 'OK', 'US', 'unclaimed', true, 10, '{"phone":"318-469-3748","website":"","services":[],"claim_hash":"24a3c7f107e5d363","source":"uspilotcars.com","additional_cities":[],"additional_regions":[]}'::jsonb),
  ('Oklahoma City, Ok', 'oklahoma-city-ok', 'escort_operator', 'Midwest Pilot Cars', 'OK', 'US', 'unclaimed', true, 10, '{"phone":"605-670-9654","website":"","services":[],"claim_hash":"6b740b4cae8c098a","source":"uspilotcars.com","additional_cities":[],"additional_regions":[]}'::jsonb),
  ('Oklahoma City, Ok', 'oklahoma-city-ok', 'escort_operator', 'Anstorm Sabre PCS, LLC', 'OK', 'US', 'unclaimed', true, 10, '{"phone":"402-270-2125","website":"","services":[],"claim_hash":"81fc532e8da2b3b5","source":"uspilotcars.com","additional_cities":[],"additional_regions":["TX"]}'::jsonb),
  ('Ba’S Pilot Car Service', 'bas-pilot-car-service', 'escort_operator', '', 'OK', 'US', 'unclaimed', true, 10, '{"phone":"903-744-3166","website":"","services":[],"claim_hash":"4c4315061bb34e2a","source":"uspilotcars.com","additional_cities":[],"additional_regions":["TX"]}'::jsonb),
  ('Jim’S Pilot Car Service', 'jims-pilot-car-service', 'escort_operator', 'Sallisaw', 'OK', 'US', 'unclaimed', true, 10, '{"phone":"918-682-9636","website":"http://www.jimpilotcar.com/","services":[],"claim_hash":"66057f2559813164","source":"uspilotcars.com","additional_cities":[],"additional_regions":[]}'::jsonb),
  ('Ashland, Or', 'ashland-or', 'escort_operator', 'A - Plus Pilot Car', 'OR', 'US', 'unclaimed', true, 10, '{"phone":"541-281-3474","website":"","services":[],"claim_hash":"7f676643e9555346","source":"uspilotcars.com","additional_cities":[],"additional_regions":[]}'::jsonb),
  ('Salem, Oregon', 'salem-oregon', 'escort_operator', 'Choice Pilot Cars', 'OR', 'US', 'unclaimed', true, 10, '{"phone":"503-303-8552","website":"","services":[],"claim_hash":"70da6922661139e1","source":"uspilotcars.com","additional_cities":[],"additional_regions":[]}'::jsonb),
  ('Beaverton/Portland/Salem, Or', 'beavertonportlandsalem-or', 'escort_operator', '', 'OR', 'US', 'unclaimed', true, 10, '{"phone":"503-775-6250","website":"","services":[],"claim_hash":"93d407dda71c1e29","source":"uspilotcars.com","additional_cities":[],"additional_regions":[]}'::jsonb),
  ('Meridian, Id/Ontario, Or', 'meridian-idontario-or', 'escort_operator', '', 'OR', 'US', 'unclaimed', true, 10, '{"phone":"208-608-2705","website":"","services":[],"claim_hash":"b441857699a9d39a","source":"uspilotcars.com","additional_cities":[],"additional_regions":[]}'::jsonb),
  ('Portland, Or', 'portland-or', 'escort_operator', '', 'OR', 'US', 'unclaimed', true, 10, '{"phone":"503-857-2556","website":"","services":[],"claim_hash":"07fb2f381742147d","source":"uspilotcars.com","additional_cities":[],"additional_regions":[]}'::jsonb),
  ('Jefferson, Or', 'jefferson-or', 'escort_operator', '', 'OR', 'US', 'unclaimed', true, 10, '{"phone":"503-269-6705","website":"","services":[],"claim_hash":"e77885d0482698b4","source":"uspilotcars.com","additional_cities":[],"additional_regions":[]}'::jsonb),
  ('Easton, Pa', 'easton-pa', 'escort_operator', 'Cevo Phoenix PCS', 'PA', 'US', 'unclaimed', true, 10, '{"phone":"610-217-2593","website":"","services":[],"claim_hash":"796c5688c547fa27","source":"uspilotcars.com","additional_cities":[],"additional_regions":[]}'::jsonb),
  ('Erie, Pa', 'erie-pa', 'escort_operator', '', 'PA', 'US', 'unclaimed', true, 10, '{"phone":"716-222-2658","website":"","services":[],"claim_hash":"03ccce1cdc82c424","source":"uspilotcars.com","additional_cities":[],"additional_regions":[]}'::jsonb),
  ('Gillett, Pa', 'gillett-pa', 'escort_operator', 'Farrell’S PCS Ny Cert. / Witpac', 'PA', 'US', 'unclaimed', true, 10, '{"phone":"570-494-6387","website":"","services":[],"claim_hash":"34ba7eccbf03467a","source":"uspilotcars.com","additional_cities":[],"additional_regions":[]}'::jsonb),
  ('Elon, Nc', 'elon-nc', 'escort_operator', 'Rocky’S Pilot Cars', 'SC', 'US', 'unclaimed', true, 10, '{"phone":"336-512-8098","website":"","services":[],"claim_hash":"003d36e65d362c09","source":"uspilotcars.com","additional_cities":[],"additional_regions":[]}'::jsonb),
  ('Sioux Falls, Sd', 'sioux-falls-sd', 'escort_operator', '', 'SD', 'US', 'unclaimed', true, 10, '{"phone":"605-670-9654","website":"","services":[],"claim_hash":"c5ea78387761e26e","source":"uspilotcars.com","additional_cities":[],"additional_regions":[]}'::jsonb),
  ('Yankton, Sd', 'yankton-sd', 'escort_operator', 'County Line Pilot Car, LLC', 'SD', 'US', 'unclaimed', true, 10, '{"phone":"402-984-0976","website":"","services":[],"claim_hash":"ea0e2485e8a3763d","source":"uspilotcars.com","additional_cities":[],"additional_regions":[]}'::jsonb),
  ('Houston/Killeen/Gainesville, Tx', 'houstonkilleengainesville-tx', 'escort_operator', '', 'TX', 'US', 'unclaimed', true, 10, '{"phone":"405-476-8006","website":"","services":[],"claim_hash":"620926ef21f155ce","source":"uspilotcars.com","additional_cities":[],"additional_regions":[]}'::jsonb),
  ('Waskom/Longview/Carthage, Tx', 'waskomlongviewcarthage-tx', 'escort_operator', 'Shumaker Pilot Car', 'TX', 'US', 'unclaimed', true, 10, '{"phone":"903-235-5822","website":"","services":[],"claim_hash":"d9a06a794ffe00fc","source":"uspilotcars.com","additional_cities":[],"additional_regions":[]}'::jsonb),
  ('Midland/Lubbock/Pecos/Odessa, Tx', 'midlandlubbockpecosodessa-tx', 'escort_operator', '', 'TX', 'US', 'unclaimed', true, 10, '{"phone":"432-250-5865","website":"","services":[],"claim_hash":"0d58bf028a089f87","source":"uspilotcars.com","additional_cities":[],"additional_regions":[]}'::jsonb),
  ('San Antonio/Austin, Tx', 'san-antonioaustin-tx', 'escort_operator', '', 'TX', 'US', 'unclaimed', true, 10, '{"phone":"210-861-4221","website":"","services":[],"claim_hash":"702ca68348051ee5","source":"uspilotcars.com","additional_cities":[],"additional_regions":[]}'::jsonb),
  ('Waskom, Tx', 'waskom-tx', 'escort_operator', '', 'TX', 'US', 'unclaimed', true, 10, '{"phone":"318-469-3748","website":"","services":[],"claim_hash":"718487e25d9513df","source":"uspilotcars.com","additional_cities":[],"additional_regions":[]}'::jsonb),
  ('Cards', 'cards', 'escort_operator', 'All Credit', 'TX', 'US', 'unclaimed', true, 10, '{"phone":"318-432-4270","website":"http://www.louisianafrog.com/","services":[],"claim_hash":"fe1bf177fb41525d","source":"uspilotcars.com","additional_cities":[],"additional_regions":[]}'::jsonb),
  ('Js Pilot Car', 'js-pilot-car', 'escort_operator', 'San Antonio/Austn', 'TX', 'US', 'unclaimed', true, 10, '{"phone":"210-861-4221","website":"","services":[],"claim_hash":"5c136eb9c59e0a06","source":"uspilotcars.com","additional_cities":[],"additional_regions":[]}'::jsonb),
  ('Hunter&#39;S PilOt Car LLC', 'hunter39s-pilot-car-llc', 'escort_operator', 'T  
  E  
  X  
  A  
  S  
     
     
 
 
  Odessa', 'TX', 'US', 'unclaimed', true, 10, '{"phone":"432-924-2289","website":"http://hunterspilotcar.com/","services":[],"claim_hash":"b3a560a93652ea66","source":"uspilotcars.com","additional_cities":[],"additional_regions":[]}'::jsonb),
  ('Cedar City, Ut', 'cedar-city-ut', 'escort_operator', '', 'UT', 'US', 'unclaimed', true, 10, '{"phone":"435-383-7385","website":"","services":[],"claim_hash":"feffd1cebdd22761","source":"uspilotcars.com","additional_cities":[],"additional_regions":[]}'::jsonb),
  ('Phoenix/Casa Grande, Az', 'phoenixcasa-grande-az', 'escort_operator', '', 'UT', 'US', 'unclaimed', true, 10, '{"phone":"480-239-7887","website":"","services":[],"claim_hash":"b487328ada4f93ce","source":"uspilotcars.com","additional_cities":[],"additional_regions":[]}'::jsonb),
  ('Salt Lake City, Ut', 'salt-lake-city-ut', 'escort_operator', '', 'UT', 'US', 'unclaimed', true, 10, '{"phone":"385-392-6193","website":"","services":[],"claim_hash":"838230cb69284e65","source":"uspilotcars.com","additional_cities":[],"additional_regions":[]}'::jsonb),
  ('Pocatello, Id', 'pocatello-id', 'escort_operator', '', 'UT', 'US', 'unclaimed', true, 10, '{"phone":"530-205-5966","website":"","services":[],"claim_hash":"ac3b8d2496e43823","source":"uspilotcars.com","additional_cities":[],"additional_regions":[]}'::jsonb),
  ('Slc, Ut/Phoenix,Az', 'slc-utphoenixaz', 'escort_operator', '', 'UT', 'US', 'unclaimed', true, 10, '{"phone":"626-278-7545","website":"","services":[],"claim_hash":"c2549cf1f31c4ea8","source":"uspilotcars.com","additional_cities":[],"additional_regions":[]}'::jsonb),
  ('Brattleboro, Vt', 'brattleboro-vt', 'escort_operator', '', 'VT', 'US', 'unclaimed', true, 10, '{"phone":"217-860-2201","website":"","services":[],"claim_hash":"84ba77086111221c","source":"uspilotcars.com","additional_cities":[],"additional_regions":[]}'::jsonb),
  ('Washington, Dc/Ft. Mill, Sc', 'washington-dcft-mill-sc', 'escort_operator', '', 'VA', 'US', 'unclaimed', true, 10, '{"phone":"704-492-3643","website":"","services":[],"claim_hash":"9745696e35423650","source":"uspilotcars.com","additional_cities":[],"additional_regions":[]}'::jsonb),
  ('Vancouver, Wa', 'vancouver-wa', 'escort_operator', '', 'WA', 'US', 'unclaimed', true, 10, '{"phone":"503-857-2556","website":"","services":[],"claim_hash":"ff274769d8fe1b59","source":"uspilotcars.com","additional_cities":[],"additional_regions":[]}'::jsonb),
  ('Tacoma, Wa', 'tacoma-wa', 'escort_operator', 'Choice Pilot Cars', 'WA', 'US', 'unclaimed', true, 10, '{"phone":"206-414-7405","website":"","services":[],"claim_hash":"df62a80d02330de8","source":"uspilotcars.com","additional_cities":[],"additional_regions":[]}'::jsonb),
  ('Spokane Area, Wa', 'spokane-area-wa', 'escort_operator', '', 'WA', 'US', 'unclaimed', true, 10, '{"phone":"503-857-2556","website":"","services":[],"claim_hash":"ed1194b6a70aecb3","source":"uspilotcars.com","additional_cities":[],"additional_regions":[]}'::jsonb),
  ('Vancouver, Wa', 'vancouver-wa', 'escort_operator', '', 'WA', 'US', 'unclaimed', true, 10, '{"phone":"503-775-6250","website":"","services":[],"claim_hash":"ad99a41dcde5d9eb","source":"uspilotcars.com","additional_cities":[],"additional_regions":[]}'::jsonb),
  ('Wenatchee, Wa', 'wenatchee-wa', 'escort_operator', '', 'WA', 'US', 'unclaimed', true, 10, '{"phone":"509-630-9132","website":"","services":[],"claim_hash":"7ae5c465f1916e2c","source":"uspilotcars.com","additional_cities":[],"additional_regions":[]}'::jsonb),
  ('Tacoma Area, Wa', 'tacoma-area-wa', 'escort_operator', '', 'WA', 'US', 'unclaimed', true, 10, '{"phone":"503-857-2556","website":"","services":[],"claim_hash":"bd7d0c30836be6e9","source":"uspilotcars.com","additional_cities":[],"additional_regions":[]}'::jsonb),
  ('Wheeling, Wv', 'wheeling-wv', 'escort_operator', '', 'WV', 'US', 'unclaimed', true, 10, '{"phone":"605-670-9654","website":"","services":[],"claim_hash":"df1e6a732b6dff58","source":"uspilotcars.com","additional_cities":[],"additional_regions":[]}'::jsonb),
  ('Clarksburg, Wv', 'clarksburg-wv', 'escort_operator', '', 'WV', 'US', 'unclaimed', true, 10, '{"phone":"304-677-0685","website":"","services":[],"claim_hash":"f563d83cddaa1ec6","source":"uspilotcars.com","additional_cities":[],"additional_regions":[]}'::jsonb),
  ('Huntington, Wv', 'huntington-wv', 'escort_operator', 'Almost Heaven Pilot Cars', 'WV', 'US', 'unclaimed', true, 10, '{"phone":"304-521-2401","website":"","services":[],"claim_hash":"8f035cbd89b42ffe","source":"uspilotcars.com","additional_cities":[],"additional_regions":[]}'::jsonb),
  ('Charleston, Wv', 'charleston-wv', 'escort_operator', 'Guerilla Movement', 'WV', 'US', 'unclaimed', true, 10, '{"phone":"888-827-7293","website":"","services":[],"claim_hash":"656edb0419de3167","source":"uspilotcars.com","additional_cities":[],"additional_regions":[]}'::jsonb),
  ('Adair, Il', 'adair-il', 'escort_operator', '', 'WI', 'US', 'unclaimed', true, 10, '{"phone":"309-252-0264","website":"","services":[],"claim_hash":"0476a83f91e48fdb","source":"uspilotcars.com","additional_cities":[],"additional_regions":[]}'::jsonb),
  ('Casper, Wy', 'casper-wy', 'escort_operator', '', 'WY', 'US', 'unclaimed', true, 10, '{"phone":"435-790-7558","website":"","services":[],"claim_hash":"855a275fc996ed51","source":"uspilotcars.com","additional_cities":[],"additional_regions":[]}'::jsonb),
  ('Gillette, Wy', 'gillette-wy', 'escort_operator', '', 'WY', 'US', 'unclaimed', true, 10, '{"phone":"307-680-4082","website":"","services":[],"claim_hash":"3f847d537d50ec9e","source":"uspilotcars.com","additional_cities":[],"additional_regions":[]}'::jsonb),
  ('Frontier Pilot Services, LLC', 'frontier-pilot-services-llc', 'escort_operator', 'Cars  
     
 
 
     
     
     
     
     
     
     
     
 
 
 
     
         
               
             Cheyenne', 'WY', 'US', 'unclaimed', true, 10, '{"phone":"307-632-6409","website":"","services":[],"claim_hash":"9f3dcf794922a665","source":"uspilotcars.com","additional_cities":[],"additional_regions":[]}'::jsonb),
  ('D/L Pilot Service', 'dl-pilot-service', 'escort_operator', 'Permits, Hp, Steering, Rte Survey, Rte Build, Cdl,Witpac, Twic  
               
               
             Gillette', 'WY', 'US', 'unclaimed', true, 10, '{"phone":"307-680-4082","website":"","services":[],"claim_hash":"ffeff43c8f03bc46","source":"uspilotcars.com","additional_cities":[],"additional_regions":[]}'::jsonb),
  ('Kitchener, On', 'kitchener-on', 'escort_operator', '', 'ON', 'CA', 'unclaimed', true, 10, '{"phone":"519-574-8914","website":"","services":[],"claim_hash":"9fdf5d322c3b0167","source":"uspilotcars.com","additional_cities":[],"additional_regions":[]}'::jsonb)
ON CONFLICT (slug) DO UPDATE SET
  metadata = EXCLUDED.metadata,
  city = COALESCE(NULLIF(EXCLUDED.city, ''), directory_listings.city),
  region_code = COALESCE(NULLIF(EXCLUDED.region_code, ''), directory_listings.region_code);
