// lib/swarm/agents-matching.ts — Matching Execution (9 agents)
import type { SwarmAgentDef } from "./types";

export const MATCHING_AGENTS: SwarmAgentDef[] = [
  {
    id: "load_to_operator_match", name: "Load-to-Operator Match Agent", domain: "matching_execution",
    purpose: "Score fit, urgency, route, trust to produce ranked matches",
    triggers: [
      { type: "event", name: "new_load_available", condition: "Load ready for matching" },
      { type: "event", name: "new_supply_claimed", condition: "Operator claimed + verified" },
    ],
    read_surfaces: ["loads", "listings", "trust_scores", "availability"], write_surfaces: ["match_results", "swarm_activity_log"],
    measurable_outputs: ["matches_produced", "avg_match_score", "time_to_match"],
    loops_fed: ["matching_loop", "trust_loop", "monetization_loop"], monetization_relation: "Each match → commission/success fee",
    enabled: true, implementation_ref: "lib/engines/load-fit.ts",
  },
  {
    id: "corridor_pricing_fit", name: "Corridor Pricing Fit Agent", domain: "matching_execution",
    purpose: "Ensure match pricing aligns with corridor rate intelligence",
    triggers: [{ type: "event", name: "match_proposed", condition: "Match needs pricing validation" }],
    read_surfaces: ["rate_observations", "corridor_demand_heat", "match_results"], write_surfaces: ["match_results", "swarm_activity_log"],
    measurable_outputs: ["price_validations", "rate_adjustments"],
    loops_fed: ["matching_loop", "data_loop"], monetization_relation: "Fair pricing → higher fill rate → more fees",
    enabled: true, implementation_ref: "lib/intelligence/load-rank.ts",
  },
  {
    id: "urgency_rescue", name: "Urgency Rescue Agent", domain: "matching_execution",
    purpose: "Activate rescue matching when urgent loads can't fill normally",
    triggers: [
      { type: "threshold", name: "no_match_found", condition: "Load unmatched > 2 hours" },
      { type: "event", name: "urgent_request_received", condition: "Broker flags urgent" },
    ],
    read_surfaces: ["loads", "listings", "match_results", "market_states"], write_surfaces: ["match_results", "agent_queue", "swarm_activity_log"],
    measurable_outputs: ["rescue_matches", "rescue_fill_rate"],
    loops_fed: ["matching_loop", "monetization_loop"], monetization_relation: "Rescue markup + concierge fee",
    enabled: true, implementation_ref: "supabase/functions/panic-fill-escalation",
  },
  {
    id: "route_readiness", name: "Route Readiness Agent", domain: "matching_execution",
    purpose: "Verify route is clear (permits, restrictions, weather) before confirming match",
    triggers: [{ type: "event", name: "match_confirmed", condition: "Match accepted by both parties" }],
    read_surfaces: ["routes", "regulations", "weather_data", "corridor_restrictions"], write_surfaces: ["route_readiness_checks", "swarm_activity_log"],
    measurable_outputs: ["routes_checked", "blockers_found", "alternatives_suggested"],
    loops_fed: ["matching_loop", "trust_loop"], monetization_relation: "Route intelligence upsell",
    enabled: true, implementation_ref: "supabase/functions/hc_route_iq_compute",
  },
  {
    id: "trust_weighted_ranker", name: "Trust-Weighted Ranker Agent", domain: "matching_execution",
    purpose: "Rank matches incorporating composite trust scores and response history",
    triggers: [{ type: "event", name: "matches_ready_for_ranking", condition: "Raw matches need ranking" }],
    read_surfaces: ["match_results", "composite_trust_scores", "response_history"], write_surfaces: ["match_results", "swarm_activity_log"],
    measurable_outputs: ["rankings_applied", "trust_overrides"],
    loops_fed: ["matching_loop", "trust_loop"], monetization_relation: "Premium ranking visibility",
    enabled: true, implementation_ref: "lib/engines/ranking-brain.ts",
  },
  {
    id: "fallback_supply", name: "Fallback Supply Agent", domain: "matching_execution",
    purpose: "Find alternative operators when primary matches decline or timeout",
    triggers: [
      { type: "event", name: "match_declined", condition: "Primary match rejected" },
      { type: "threshold", name: "response_timeout", condition: "No response > 1 hour" },
    ],
    read_surfaces: ["match_results", "listings", "availability"], write_surfaces: ["match_results", "swarm_activity_log"],
    measurable_outputs: ["fallbacks_generated", "fallback_fill_rate"],
    loops_fed: ["matching_loop", "supply_loop"], monetization_relation: "Fallback bundle offers",
    enabled: true, implementation_ref: "supabase/functions/match-generate",
  },
  {
    id: "multi_role_bundle_match", name: "Multi-Role Bundle Match Agent", domain: "matching_execution",
    purpose: "Match complex loads needing multiple roles (lead car + chase car + permit)",
    triggers: [{ type: "event", name: "multi_role_load", condition: "Load requires > 1 escort role" }],
    read_surfaces: ["loads", "listings", "role_alias_map"], write_surfaces: ["match_results", "swarm_activity_log"],
    measurable_outputs: ["bundles_matched", "roles_per_bundle"],
    loops_fed: ["matching_loop", "monetization_loop"], monetization_relation: "Bundle matching premium fee",
    enabled: true,
  },
  {
    id: "distance_time_fit", name: "Distance/Time Fit Agent", domain: "matching_execution",
    purpose: "Score operator proximity and availability window against load timeline",
    triggers: [{ type: "event", name: "match_scoring", condition: "Match needs distance/time scoring" }],
    read_surfaces: ["listings", "loads", "availability", "gps_positions"], write_surfaces: ["match_results", "swarm_activity_log"],
    measurable_outputs: ["distance_scores", "eta_estimates"],
    loops_fed: ["matching_loop"], monetization_relation: "Distance data feeds route intelligence product",
    enabled: true, implementation_ref: "supabase/functions/deadhead-estimate",
  },
  {
    id: "high_confidence_closer", name: "High Confidence Closer Agent", domain: "matching_execution",
    purpose: "Auto-close high-confidence matches when score > threshold and both verified",
    triggers: [{ type: "threshold", name: "high_confidence_match", condition: "Match score > 0.9 + both verified" }],
    read_surfaces: ["match_results", "composite_trust_scores"], write_surfaces: ["jobs", "notifications", "swarm_activity_log"],
    measurable_outputs: ["auto_closes", "auto_close_success_rate"],
    loops_fed: ["matching_loop", "monetization_loop"], monetization_relation: "Faster close → higher volume → more fees",
    enabled: true,
  },
];
