app = 'hc-nllb-translation'
primary_region = 'atl'

[build]
  dockerfile = "Dockerfile"

[compute]
  size = "performance-1x"

[env]
  MODEL_NAME = "facebook/nllb-200-distilled-600M"

[[services]]
  protocol = "tcp"
  internal_port = 8001
  processes = ["app"]

  [[services.ports]]
    port = 80
    handlers = ["http"]
    force_https = true

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]

  [services.concurrency]
    type = "connections"
    hard_limit = 25
    soft_limit = 20
