// lib/geo/countries.ts
// THE SINGLE SOURCE OF TRUTH FOR ALL 120 HAUL COMMAND COUNTRIES.

export type CountryTier = "A" | "B" | "C" | "D" | "E";

export interface HCCountry {
    iso2: string;
    name: string;
    tier: CountryTier;
    currency: string;
    admin1_label: string | null;
    admin1_enforced: boolean;
    region: HCRegion;
    ppp_multiplier: number;
    priority_score: number;
    year1_target: number;
    cross_border_corridors: string[];
    calling_code: string;
    primary_locale: string;
    drive_side: "right" | "left";
    distance_unit: "mi" | "km";
    weight_unit: "lbs" | "kg" | "tonnes";
}

export type HCRegion =
    | "north_america"
    | "europe_west"
    | "europe_north"
    | "europe_east"
    | "europe_south"
    | "middle_east"
    | "asia_pacific"
    | "latin_america"
    | "africa"
    | "oceania";

export const HC_COUNTRIES: readonly HCCountry[] = [
    // ── TIER A (10 countries) ────────────────────────────────

    {
        iso2: "US", name: "United States", tier: "A",
        currency: "USD", admin1_label: "State", admin1_enforced: true,
        region: "north_america", ppp_multiplier: 1.00, priority_score: 9.73,
        year1_target: 420000, cross_border_corridors: ["CA", "MX"],
        calling_code: "+1", primary_locale: "en-US",
        drive_side: "right", distance_unit: "mi", weight_unit: "lbs",
    },
    {
        iso2: "CA", name: "Canada", tier: "A",
        currency: "CAD", admin1_label: "Province", admin1_enforced: true,
        region: "north_america", ppp_multiplier: 1.00, priority_score: 8.85,
        year1_target: 120000, cross_border_corridors: ["US"],
        calling_code: "+1", primary_locale: "en-CA",
        drive_side: "right", distance_unit: "km", weight_unit: "kg",
    },
    {
        iso2: "AU", name: "Australia", tier: "A",
        currency: "AUD", admin1_label: "State", admin1_enforced: true,
        region: "oceania", ppp_multiplier: 1.00, priority_score: 8.65,
        year1_target: 90000, cross_border_corridors: ["NZ"],
        calling_code: "+61", primary_locale: "en-AU",
        drive_side: "left", distance_unit: "km", weight_unit: "kg",
    },
    {
        iso2: "GB", name: "United Kingdom", tier: "A",
        currency: "GBP", admin1_label: "Region", admin1_enforced: false,
        region: "europe_west", ppp_multiplier: 1.00, priority_score: 8.25,
        year1_target: 80000, cross_border_corridors: ["IE"],
        calling_code: "+44", primary_locale: "en-GB",
        drive_side: "left", distance_unit: "mi", weight_unit: "kg",
    },
    {
        iso2: "NZ", name: "New Zealand", tier: "A",
        currency: "NZD", admin1_label: "Region", admin1_enforced: false,
        region: "oceania", ppp_multiplier: 1.00, priority_score: 7.65,
        year1_target: 45000, cross_border_corridors: ["AU"],
        calling_code: "+64", primary_locale: "en-NZ",
        drive_side: "left", distance_unit: "km", weight_unit: "kg",
    },
    {
        iso2: "ZA", name: "South Africa", tier: "A",
        currency: "ZAR", admin1_label: "Province", admin1_enforced: false,
        region: "africa", ppp_multiplier: 0.42, priority_score: 7.15,
        year1_target: 60000, cross_border_corridors: [],
        calling_code: "+27", primary_locale: "en-ZA",
        drive_side: "left", distance_unit: "km", weight_unit: "kg",
    },
    {
        iso2: "DE", name: "Germany", tier: "A",
        currency: "EUR", admin1_label: "Bundesland", admin1_enforced: true,
        region: "europe_west", ppp_multiplier: 1.00, priority_score: 7.35,
        year1_target: 50000, cross_border_corridors: ["NL", "AT", "FR", "PL", "CZ"],
        calling_code: "+49", primary_locale: "de-DE",
        drive_side: "right", distance_unit: "km", weight_unit: "kg",
    },
    {
        iso2: "NL", name: "Netherlands", tier: "A",
        currency: "EUR", admin1_label: "Province", admin1_enforced: false,
        region: "europe_west", ppp_multiplier: 1.00, priority_score: 6.85,
        year1_target: 35000, cross_border_corridors: ["DE", "BE"],
        calling_code: "+31", primary_locale: "nl-NL",
        drive_side: "right", distance_unit: "km", weight_unit: "kg",
    },
    {
        iso2: "AE", name: "United Arab Emirates", tier: "A",
        currency: "AED", admin1_label: "Emirate", admin1_enforced: false,
        region: "middle_east", ppp_multiplier: 1.00, priority_score: 6.65,
        year1_target: 40000, cross_border_corridors: ["SA", "OM"],
        calling_code: "+971", primary_locale: "en-AE",
        drive_side: "right", distance_unit: "km", weight_unit: "kg",
    },
    {
        iso2: "BR", name: "Brazil", tier: "A",
        currency: "BRL", admin1_label: "Estado", admin1_enforced: true,
        region: "latin_america", ppp_multiplier: 0.58, priority_score: 6.55,
        year1_target: 60000, cross_border_corridors: [],
        calling_code: "+55", primary_locale: "pt-BR",
        drive_side: "right", distance_unit: "km", weight_unit: "kg",
    },

    // ── TIER B (18 countries) ────────────────────────────────

    {
        iso2: "IE", name: "Ireland", tier: "B",
        currency: "EUR", admin1_label: "County", admin1_enforced: false,
        region: "europe_west", ppp_multiplier: 1.00, priority_score: 6.30,
        year1_target: 0, cross_border_corridors: ["GB"],
        calling_code: "+353", primary_locale: "en-IE",
        drive_side: "left", distance_unit: "km", weight_unit: "kg",
    },
    {
        iso2: "SE", name: "Sweden", tier: "B",
        currency: "SEK", admin1_label: "Län", admin1_enforced: false,
        region: "europe_north", ppp_multiplier: 1.00, priority_score: 6.10,
        year1_target: 0, cross_border_corridors: ["NO", "DK", "FI"],
        calling_code: "+46", primary_locale: "sv-SE",
        drive_side: "right", distance_unit: "km", weight_unit: "kg",
    },
    {
        iso2: "NO", name: "Norway", tier: "B",
        currency: "NOK", admin1_label: "Fylke", admin1_enforced: false,
        region: "europe_north", ppp_multiplier: 1.00, priority_score: 6.05,
        year1_target: 0, cross_border_corridors: ["SE"],
        calling_code: "+47", primary_locale: "nb-NO",
        drive_side: "right", distance_unit: "km", weight_unit: "kg",
    },
    {
        iso2: "DK", name: "Denmark", tier: "B",
        currency: "DKK", admin1_label: "Region", admin1_enforced: false,
        region: "europe_north", ppp_multiplier: 1.00, priority_score: 5.75,
        year1_target: 0, cross_border_corridors: ["SE", "DE"],
        calling_code: "+45", primary_locale: "da-DK",
        drive_side: "right", distance_unit: "km", weight_unit: "kg",
    },
    {
        iso2: "FI", name: "Finland", tier: "B",
        currency: "EUR", admin1_label: "Maakunta", admin1_enforced: false,
        region: "europe_north", ppp_multiplier: 1.00, priority_score: 5.65,
        year1_target: 0, cross_border_corridors: ["SE", "EE"],
        calling_code: "+358", primary_locale: "fi-FI",
        drive_side: "right", distance_unit: "km", weight_unit: "kg",
    },
    {
        iso2: "BE", name: "Belgium", tier: "B",
        currency: "EUR", admin1_label: "Region", admin1_enforced: false,
        region: "europe_west", ppp_multiplier: 1.00, priority_score: 5.85,
        year1_target: 0, cross_border_corridors: ["NL", "FR", "DE"],
        calling_code: "+32", primary_locale: "nl-BE",
        drive_side: "right", distance_unit: "km", weight_unit: "kg",
    },
    {
        iso2: "AT", name: "Austria", tier: "B",
        currency: "EUR", admin1_label: "Bundesland", admin1_enforced: false,
        region: "europe_west", ppp_multiplier: 1.00, priority_score: 5.60,
        year1_target: 0, cross_border_corridors: ["DE", "IT", "CH"],
        calling_code: "+43", primary_locale: "de-AT",
        drive_side: "right", distance_unit: "km", weight_unit: "kg",
    },
    {
        iso2: "CH", name: "Switzerland", tier: "B",
        currency: "CHF", admin1_label: "Kanton", admin1_enforced: false,
        region: "europe_west", ppp_multiplier: 1.00, priority_score: 5.95,
        year1_target: 0, cross_border_corridors: ["DE", "FR", "IT", "AT"],
        calling_code: "+41", primary_locale: "de-CH",
        drive_side: "right", distance_unit: "km", weight_unit: "kg",
    },
    {
        iso2: "ES", name: "Spain", tier: "B",
        currency: "EUR", admin1_label: "Comunidad", admin1_enforced: false,
        region: "europe_south", ppp_multiplier: 0.82, priority_score: 6.05,
        year1_target: 0, cross_border_corridors: ["FR", "PT"],
        calling_code: "+34", primary_locale: "es-ES",
        drive_side: "right", distance_unit: "km", weight_unit: "kg",
    },
    {
        iso2: "FR", name: "France", tier: "B",
        currency: "EUR", admin1_label: "Région", admin1_enforced: false,
        region: "europe_west", ppp_multiplier: 0.82, priority_score: 6.40,
        year1_target: 0, cross_border_corridors: ["DE", "ES", "IT", "BE", "CH"],
        calling_code: "+33", primary_locale: "fr-FR",
        drive_side: "right", distance_unit: "km", weight_unit: "kg",
    },
    {
        iso2: "IT", name: "Italy", tier: "B",
        currency: "EUR", admin1_label: "Regione", admin1_enforced: false,
        region: "europe_south", ppp_multiplier: 0.82, priority_score: 6.00,
        year1_target: 0, cross_border_corridors: ["FR", "AT", "CH"],
        calling_code: "+39", primary_locale: "it-IT",
        drive_side: "right", distance_unit: "km", weight_unit: "kg",
    },
    {
        iso2: "PT", name: "Portugal", tier: "B",
        currency: "EUR", admin1_label: "Distrito", admin1_enforced: false,
        region: "europe_south", ppp_multiplier: 0.82, priority_score: 5.15,
        year1_target: 0, cross_border_corridors: ["ES"],
        calling_code: "+351", primary_locale: "pt-PT",
        drive_side: "right", distance_unit: "km", weight_unit: "kg",
    },
    {
        iso2: "SA", name: "Saudi Arabia", tier: "B",
        currency: "SAR", admin1_label: "Region", admin1_enforced: false,
        region: "middle_east", ppp_multiplier: 0.82, priority_score: 6.35,
        year1_target: 0, cross_border_corridors: ["AE", "BH", "KW", "OM"],
        calling_code: "+966", primary_locale: "ar-SA",
        drive_side: "right", distance_unit: "km", weight_unit: "kg",
    },
    {
        iso2: "QA", name: "Qatar", tier: "B",
        currency: "QAR", admin1_label: null, admin1_enforced: false,
        region: "middle_east", ppp_multiplier: 1.00, priority_score: 5.15,
        year1_target: 0, cross_border_corridors: ["SA"],
        calling_code: "+974", primary_locale: "ar-QA",
        drive_side: "right", distance_unit: "km", weight_unit: "kg",
    },
    {
        iso2: "MX", name: "Mexico", tier: "B",
        currency: "MXN", admin1_label: "Estado", admin1_enforced: true,
        region: "north_america", ppp_multiplier: 0.58, priority_score: 6.20,
        year1_target: 0, cross_border_corridors: ["US"],
        calling_code: "+52", primary_locale: "es-MX",
        drive_side: "right", distance_unit: "km", weight_unit: "kg",
    },
    {
        iso2: "IN", name: "India", tier: "B",
        currency: "INR", admin1_label: null, admin1_enforced: false,
        region: "asia_pacific", ppp_multiplier: 0.80, priority_score: 6.42,
        year1_target: 0, cross_border_corridors: [],
        calling_code: "+91", primary_locale: "eng-IN",
        drive_side: "left", distance_unit: "km", weight_unit: "kg",
    },
    {
        iso2: "ID", name: "Indonesia", tier: "B",
        currency: "IDR", admin1_label: null, admin1_enforced: false,
        region: "asia_pacific", ppp_multiplier: 0.80, priority_score: 6.76,
        year1_target: 0, cross_border_corridors: [],
        calling_code: "+62", primary_locale: "ind-ID",
        drive_side: "left", distance_unit: "km", weight_unit: "kg",
    },
    {
        iso2: "TH", name: "Thailand", tier: "B",
        currency: "THB", admin1_label: null, admin1_enforced: false,
        region: "asia_pacific", ppp_multiplier: 0.80, priority_score: 6.39,
        year1_target: 0, cross_border_corridors: [],
        calling_code: "+66", primary_locale: "tha-TH",
        drive_side: "left", distance_unit: "km", weight_unit: "kg",
    },

    // ── TIER C (26 countries) ────────────────────────────────

    {
        iso2: "PL", name: "Poland", tier: "C",
        currency: "PLN", admin1_label: "Województwo", admin1_enforced: false,
        region: "europe_east", ppp_multiplier: 0.58, priority_score: 5.30,
        year1_target: 0, cross_border_corridors: ["DE", "CZ", "SK", "LT"],
        calling_code: "+48", primary_locale: "pl-PL",
        drive_side: "right", distance_unit: "km", weight_unit: "kg",
    },
    {
        iso2: "CZ", name: "Czechia", tier: "C",
        currency: "CZK", admin1_label: "Kraj", admin1_enforced: false,
        region: "europe_east", ppp_multiplier: 0.82, priority_score: 4.60,
        year1_target: 0, cross_border_corridors: ["DE", "PL", "SK", "AT"],
        calling_code: "+420", primary_locale: "cs-CZ",
        drive_side: "right", distance_unit: "km", weight_unit: "kg",
    },
    {
        iso2: "SK", name: "Slovakia", tier: "C",
        currency: "EUR", admin1_label: "Kraj", admin1_enforced: false,
        region: "europe_east", ppp_multiplier: 0.82, priority_score: 4.10,
        year1_target: 0, cross_border_corridors: ["CZ", "PL", "HU", "AT"],
        calling_code: "+421", primary_locale: "sk-SK",
        drive_side: "right", distance_unit: "km", weight_unit: "kg",
    },
    {
        iso2: "HU", name: "Hungary", tier: "C",
        currency: "HUF", admin1_label: "Megye", admin1_enforced: false,
        region: "europe_east", ppp_multiplier: 0.58, priority_score: 4.45,
        year1_target: 0, cross_border_corridors: ["SK", "AT", "RO", "HR"],
        calling_code: "+36", primary_locale: "hu-HU",
        drive_side: "right", distance_unit: "km", weight_unit: "kg",
    },
    {
        iso2: "SI", name: "Slovenia", tier: "C",
        currency: "EUR", admin1_label: "Občina", admin1_enforced: false,
        region: "europe_east", ppp_multiplier: 0.82, priority_score: 3.65,
        year1_target: 0, cross_border_corridors: ["AT", "IT", "HR"],
        calling_code: "+386", primary_locale: "sl-SI",
        drive_side: "right", distance_unit: "km", weight_unit: "kg",
    },
    {
        iso2: "EE", name: "Estonia", tier: "C",
        currency: "EUR", admin1_label: "Maakond", admin1_enforced: false,
        region: "europe_north", ppp_multiplier: 0.82, priority_score: 3.40,
        year1_target: 0, cross_border_corridors: ["FI", "LV"],
        calling_code: "+372", primary_locale: "et-EE",
        drive_side: "right", distance_unit: "km", weight_unit: "kg",
    },
    {
        iso2: "LV", name: "Latvia", tier: "C",
        currency: "EUR", admin1_label: "Novads", admin1_enforced: false,
        region: "europe_north", ppp_multiplier: 0.58, priority_score: 3.25,
        year1_target: 0, cross_border_corridors: ["EE", "LT"],
        calling_code: "+371", primary_locale: "lv-LV",
        drive_side: "right", distance_unit: "km", weight_unit: "kg",
    },
    {
        iso2: "LT", name: "Lithuania", tier: "C",
        currency: "EUR", admin1_label: "Apskritis", admin1_enforced: false,
        region: "europe_north", ppp_multiplier: 0.58, priority_score: 3.55,
        year1_target: 0, cross_border_corridors: ["LV", "PL"],
        calling_code: "+370", primary_locale: "lt-LT",
        drive_side: "right", distance_unit: "km", weight_unit: "kg",
    },
    {
        iso2: "HR", name: "Croatia", tier: "C",
        currency: "EUR", admin1_label: "Županija", admin1_enforced: false,
        region: "europe_south", ppp_multiplier: 0.82, priority_score: 3.55,
        year1_target: 0, cross_border_corridors: ["SI", "HU"],
        calling_code: "+385", primary_locale: "hr-HR",
        drive_side: "right", distance_unit: "km", weight_unit: "kg",
    },
    {
        iso2: "RO", name: "Romania", tier: "C",
        currency: "RON", admin1_label: "Județ", admin1_enforced: false,
        region: "europe_east", ppp_multiplier: 0.58, priority_score: 3.95,
        year1_target: 0, cross_border_corridors: ["HU", "BG"],
        calling_code: "+40", primary_locale: "ro-RO",
        drive_side: "right", distance_unit: "km", weight_unit: "kg",
    },
    {
        iso2: "BG", name: "Bulgaria", tier: "C",
        currency: "BGN", admin1_label: "Oblast", admin1_enforced: false,
        region: "europe_east", ppp_multiplier: 0.58, priority_score: 3.55,
        year1_target: 0, cross_border_corridors: ["RO", "GR", "TR"],
        calling_code: "+359", primary_locale: "bg-BG",
        drive_side: "right", distance_unit: "km", weight_unit: "kg",
    },
    {
        iso2: "GR", name: "Greece", tier: "C",
        currency: "EUR", admin1_label: "Periféria", admin1_enforced: false,
        region: "europe_south", ppp_multiplier: 0.58, priority_score: 4.45,
        year1_target: 0, cross_border_corridors: ["BG", "TR"],
        calling_code: "+30", primary_locale: "el-GR",
        drive_side: "right", distance_unit: "km", weight_unit: "kg",
    },
    {
        iso2: "TR", name: "Turkey", tier: "C",
        currency: "TRY", admin1_label: "İl", admin1_enforced: false,
        region: "middle_east", ppp_multiplier: 0.58, priority_score: 5.45,
        year1_target: 0, cross_border_corridors: ["BG", "GR"],
        calling_code: "+90", primary_locale: "tr-TR",
        drive_side: "right", distance_unit: "km", weight_unit: "kg",
    },
    {
        iso2: "KW", name: "Kuwait", tier: "C",
        currency: "KWD", admin1_label: null, admin1_enforced: false,
        region: "middle_east", ppp_multiplier: 1.00, priority_score: 4.50,
        year1_target: 0, cross_border_corridors: ["SA"],
        calling_code: "+965", primary_locale: "ar-KW",
        drive_side: "right", distance_unit: "km", weight_unit: "kg",
    },
    {
        iso2: "OM", name: "Oman", tier: "C",
        currency: "OMR", admin1_label: "Governorate", admin1_enforced: false,
        region: "middle_east", ppp_multiplier: 0.82, priority_score: 4.05,
        year1_target: 0, cross_border_corridors: ["AE", "SA"],
        calling_code: "+968", primary_locale: "ar-OM",
        drive_side: "right", distance_unit: "km", weight_unit: "kg",
    },
    {
        iso2: "BH", name: "Bahrain", tier: "C",
        currency: "BHD", admin1_label: null, admin1_enforced: false,
        region: "middle_east", ppp_multiplier: 0.82, priority_score: 3.60,
        year1_target: 0, cross_border_corridors: ["SA"],
        calling_code: "+973", primary_locale: "ar-BH",
        drive_side: "right", distance_unit: "km", weight_unit: "kg",
    },
    {
        iso2: "SG", name: "Singapore", tier: "C",
        currency: "SGD", admin1_label: null, admin1_enforced: false,
        region: "asia_pacific", ppp_multiplier: 1.00, priority_score: 5.15,
        year1_target: 0, cross_border_corridors: ["MY"],
        calling_code: "+65", primary_locale: "en-SG",
        drive_side: "left", distance_unit: "km", weight_unit: "kg",
    },
    {
        iso2: "MY", name: "Malaysia", tier: "C",
        currency: "MYR", admin1_label: "State", admin1_enforced: false,
        region: "asia_pacific", ppp_multiplier: 0.82, priority_score: 5.05,
        year1_target: 0, cross_border_corridors: ["SG"],
        calling_code: "+60", primary_locale: "ms-MY",
        drive_side: "left", distance_unit: "km", weight_unit: "kg",
    },
    {
        iso2: "JP", name: "Japan", tier: "C",
        currency: "JPY", admin1_label: "Prefecture", admin1_enforced: false,
        region: "asia_pacific", ppp_multiplier: 1.00, priority_score: 5.40,
        year1_target: 0, cross_border_corridors: [],
        calling_code: "+81", primary_locale: "ja-JP",
        drive_side: "left", distance_unit: "km", weight_unit: "kg",
    },
    {
        iso2: "KR", name: "South Korea", tier: "C",
        currency: "KRW", admin1_label: "Province", admin1_enforced: false,
        region: "asia_pacific", ppp_multiplier: 1.00, priority_score: 5.00,
        year1_target: 0, cross_border_corridors: [],
        calling_code: "+82", primary_locale: "ko-KR",
        drive_side: "right", distance_unit: "km", weight_unit: "kg",
    },
    {
        iso2: "CL", name: "Chile", tier: "C",
        currency: "CLP", admin1_label: "Región", admin1_enforced: false,
        region: "latin_america", ppp_multiplier: 0.82, priority_score: 5.20,
        year1_target: 0, cross_border_corridors: ["AR", "PE"],
        calling_code: "+56", primary_locale: "es-CL",
        drive_side: "right", distance_unit: "km", weight_unit: "kg",
    },
    {
        iso2: "AR", name: "Argentina", tier: "C",
        currency: "ARS", admin1_label: "Provincia", admin1_enforced: false,
        region: "latin_america", ppp_multiplier: 0.42, priority_score: 5.00,
        year1_target: 0, cross_border_corridors: ["CL", "UY", "BR"],
        calling_code: "+54", primary_locale: "es-AR",
        drive_side: "right", distance_unit: "km", weight_unit: "kg",
    },
    {
        iso2: "CO", name: "Colombia", tier: "C",
        currency: "COP", admin1_label: "Departamento", admin1_enforced: false,
        region: "latin_america", ppp_multiplier: 0.42, priority_score: 5.00,
        year1_target: 0, cross_border_corridors: ["PA", "PE"],
        calling_code: "+57", primary_locale: "es-CO",
        drive_side: "right", distance_unit: "km", weight_unit: "kg",
    },
    {
        iso2: "PE", name: "Peru", tier: "C",
        currency: "PEN", admin1_label: "Región", admin1_enforced: false,
        region: "latin_america", ppp_multiplier: 0.42, priority_score: 4.70,
        year1_target: 0, cross_border_corridors: ["CL", "CO"],
        calling_code: "+51", primary_locale: "es-PE",
        drive_side: "right", distance_unit: "km", weight_unit: "kg",
    },
    {
        iso2: "VN", name: "Vietnam", tier: "C",
        currency: "VND", admin1_label: null, admin1_enforced: false,
        region: "asia_pacific", ppp_multiplier: 0.40, priority_score: 4.59,
        year1_target: 0, cross_border_corridors: [],
        calling_code: "+84", primary_locale: "vie-VN",
        drive_side: "right", distance_unit: "km", weight_unit: "kg",
    },
    {
        iso2: "PH", name: "Philippines", tier: "C",
        currency: "PHP", admin1_label: null, admin1_enforced: false,
        region: "asia_pacific", ppp_multiplier: 0.40, priority_score: 4.66,
        year1_target: 0, cross_border_corridors: [],
        calling_code: "+63", primary_locale: "eng-PH",
        drive_side: "right", distance_unit: "km", weight_unit: "kg",
    },

    // ── TIER D (25 countries) ────────────────────────────────

    {
        iso2: "UY", name: "Uruguay", tier: "D",
        currency: "UYU", admin1_label: "Departamento", admin1_enforced: false,
        region: "latin_america", ppp_multiplier: 0.82, priority_score: 3.35,
        year1_target: 0, cross_border_corridors: ["AR", "BR"],
        calling_code: "+598", primary_locale: "es-UY",
        drive_side: "right", distance_unit: "km", weight_unit: "kg",
    },
    {
        iso2: "PA", name: "Panama", tier: "D",
        currency: "USD", admin1_label: "Provincia", admin1_enforced: false,
        region: "latin_america", ppp_multiplier: 0.82, priority_score: 4.15,
        year1_target: 0, cross_border_corridors: ["CO", "CR"],
        calling_code: "+507", primary_locale: "es-PA",
        drive_side: "right", distance_unit: "km", weight_unit: "kg",
    },
    {
        iso2: "CR", name: "Costa Rica", tier: "D",
        currency: "CRC", admin1_label: "Provincia", admin1_enforced: false,
        region: "latin_america", ppp_multiplier: 0.82, priority_score: 3.35,
        year1_target: 0, cross_border_corridors: ["PA"],
        calling_code: "+506", primary_locale: "es-CR",
        drive_side: "right", distance_unit: "km", weight_unit: "kg",
    },
    {
        iso2: "IL", name: "Israel", tier: "D",
        currency: "ILS", admin1_label: null, admin1_enforced: false,
        region: "middle_east", ppp_multiplier: 0.40, priority_score: 3.62,
        year1_target: 0, cross_border_corridors: [],
        calling_code: "+972", primary_locale: "ara-IL",
        drive_side: "right", distance_unit: "km", weight_unit: "kg",
    },
    {
        iso2: "NG", name: "Nigeria", tier: "D",
        currency: "NGN", admin1_label: null, admin1_enforced: false,
        region: "africa", ppp_multiplier: 0.40, priority_score: 3.00,
        year1_target: 0, cross_border_corridors: [],
        calling_code: "+234", primary_locale: "eng-NG",
        drive_side: "right", distance_unit: "km", weight_unit: "kg",
    },
    {
        iso2: "EG", name: "Egypt", tier: "D",
        currency: "EGP", admin1_label: null, admin1_enforced: false,
        region: "africa", ppp_multiplier: 0.40, priority_score: 3.85,
        year1_target: 0, cross_border_corridors: [],
        calling_code: "+20", primary_locale: "ara-EG",
        drive_side: "right", distance_unit: "km", weight_unit: "kg",
    },
    {
        iso2: "KE", name: "Kenya", tier: "D",
        currency: "KES", admin1_label: null, admin1_enforced: false,
        region: "africa", ppp_multiplier: 0.40, priority_score: 3.81,
        year1_target: 0, cross_border_corridors: [],
        calling_code: "+254", primary_locale: "eng-KE",
        drive_side: "left", distance_unit: "km", weight_unit: "kg",
    },
    {
        iso2: "MA", name: "Morocco", tier: "D",
        currency: "MAD", admin1_label: null, admin1_enforced: false,
        region: "africa", ppp_multiplier: 0.40, priority_score: 3.03,
        year1_target: 0, cross_border_corridors: [],
        calling_code: "+212", primary_locale: "ara-MA",
        drive_side: "right", distance_unit: "km", weight_unit: "kg",
    },
    {
        iso2: "RS", name: "Serbia", tier: "D",
        currency: "RSD", admin1_label: null, admin1_enforced: false,
        region: "europe_west", ppp_multiplier: 0.40, priority_score: 3.05,
        year1_target: 0, cross_border_corridors: [],
        calling_code: "+381", primary_locale: "srp-RS",
        drive_side: "right", distance_unit: "km", weight_unit: "kg",
    },
    {
        iso2: "UA", name: "Ukraine", tier: "D",
        currency: "UAH", admin1_label: null, admin1_enforced: false,
        region: "europe_east", ppp_multiplier: 0.40, priority_score: 3.27,
        year1_target: 0, cross_border_corridors: [],
        calling_code: "+380", primary_locale: "ukr-UA",
        drive_side: "right", distance_unit: "km", weight_unit: "kg",
    },
    {
        iso2: "KZ", name: "Kazakhstan", tier: "D",
        currency: "KZT", admin1_label: null, admin1_enforced: false,
        region: "asia_pacific", ppp_multiplier: 0.40, priority_score: 3.27,
        year1_target: 0, cross_border_corridors: [],
        calling_code: "+7", primary_locale: "kaz-KZ",
        drive_side: "right", distance_unit: "km", weight_unit: "kg",
    },
    {
        iso2: "TW", name: "Taiwan", tier: "D",
        currency: "TWD", admin1_label: null, admin1_enforced: false,
        region: "asia_pacific", ppp_multiplier: 0.40, priority_score: 3.21,
        year1_target: 0, cross_border_corridors: [],
        calling_code: "+886", primary_locale: "zho-TW",
        drive_side: "right", distance_unit: "km", weight_unit: "kg",
    },
    {
        iso2: "PK", name: "Pakistan", tier: "D",
        currency: "PKR", admin1_label: null, admin1_enforced: false,
        region: "asia_pacific", ppp_multiplier: 0.40, priority_score: 3.34,
        year1_target: 0, cross_border_corridors: [],
        calling_code: "+92", primary_locale: "eng-PK",
        drive_side: "left", distance_unit: "km", weight_unit: "kg",
    },
    {
        iso2: "BD", name: "Bangladesh", tier: "D",
        currency: "BDT", admin1_label: null, admin1_enforced: false,
        region: "asia_pacific", ppp_multiplier: 0.40, priority_score: 3.25,
        year1_target: 0, cross_border_corridors: [],
        calling_code: "+880", primary_locale: "ben-BD",
        drive_side: "left", distance_unit: "km", weight_unit: "kg",
    },
    {
        iso2: "MN", name: "Mongolia", tier: "D",
        currency: "MNT", admin1_label: null, admin1_enforced: false,
        region: "asia_pacific", ppp_multiplier: 0.40, priority_score: 3.86,
        year1_target: 0, cross_border_corridors: [],
        calling_code: "+976", primary_locale: "mon-MN",
        drive_side: "right", distance_unit: "km", weight_unit: "kg",
    },
    {
        iso2: "TT", name: "Trinidad and Tobago", tier: "D",
        currency: "TTD", admin1_label: null, admin1_enforced: false,
        region: "north_america", ppp_multiplier: 0.40, priority_score: 3.48,
        year1_target: 0, cross_border_corridors: [],
        calling_code: "+1868", primary_locale: "eng-TT",
        drive_side: "left", distance_unit: "km", weight_unit: "kg",
    },
    {
        iso2: "JO", name: "Jordan", tier: "D",
        currency: "JOD", admin1_label: null, admin1_enforced: false,
        region: "middle_east", ppp_multiplier: 0.40, priority_score: 3.46,
        year1_target: 0, cross_border_corridors: [],
        calling_code: "+962", primary_locale: "ara-JO",
        drive_side: "right", distance_unit: "km", weight_unit: "kg",
    },
    {
        iso2: "GH", name: "Ghana", tier: "D",
        currency: "GHS", admin1_label: null, admin1_enforced: false,
        region: "africa", ppp_multiplier: 0.40, priority_score: 3.12,
        year1_target: 0, cross_border_corridors: [],
        calling_code: "+233", primary_locale: "eng-GH",
        drive_side: "right", distance_unit: "km", weight_unit: "kg",
    },
    {
        iso2: "TZ", name: "Tanzania", tier: "D",
        currency: "TZS", admin1_label: null, admin1_enforced: false,
        region: "africa", ppp_multiplier: 0.40, priority_score: 3.25,
        year1_target: 0, cross_border_corridors: [],
        calling_code: "+255", primary_locale: "eng-TZ",
        drive_side: "left", distance_unit: "km", weight_unit: "kg",
    },
    {
        iso2: "GE", name: "Georgia", tier: "D",
        currency: "GEL", admin1_label: null, admin1_enforced: false,
        region: "middle_east", ppp_multiplier: 0.40, priority_score: 3.27,
        year1_target: 0, cross_border_corridors: [],
        calling_code: "+995", primary_locale: "kat-GE",
        drive_side: "right", distance_unit: "km", weight_unit: "kg",
    },
    {
        iso2: "AZ", name: "Azerbaijan", tier: "D",
        currency: "AZN", admin1_label: null, admin1_enforced: false,
        region: "middle_east", ppp_multiplier: 0.40, priority_score: 3.67,
        year1_target: 0, cross_border_corridors: [],
        calling_code: "+994", primary_locale: "aze-AZ",
        drive_side: "right", distance_unit: "km", weight_unit: "kg",
    },
    {
        iso2: "CY", name: "Cyprus", tier: "D",
        currency: "EUR", admin1_label: null, admin1_enforced: false,
        region: "europe_south", ppp_multiplier: 0.40, priority_score: 3.01,
        year1_target: 0, cross_border_corridors: [],
        calling_code: "+357", primary_locale: "ell-CY",
        drive_side: "left", distance_unit: "km", weight_unit: "kg",
    },
    {
        iso2: "IS", name: "Iceland", tier: "D",
        currency: "ISK", admin1_label: null, admin1_enforced: false,
        region: "europe_north", ppp_multiplier: 0.40, priority_score: 3.56,
        year1_target: 0, cross_border_corridors: [],
        calling_code: "+354", primary_locale: "isl-IS",
        drive_side: "right", distance_unit: "km", weight_unit: "kg",
    },
    {
        iso2: "LU", name: "Luxembourg", tier: "D",
        currency: "EUR", admin1_label: null, admin1_enforced: false,
        region: "europe_west", ppp_multiplier: 0.40, priority_score: 3.48,
        year1_target: 0, cross_border_corridors: [],
        calling_code: "+352", primary_locale: "deu-LU",
        drive_side: "right", distance_unit: "km", weight_unit: "kg",
    },
    {
        iso2: "EC", name: "Ecuador", tier: "D",
        currency: "USD", admin1_label: null, admin1_enforced: false,
        region: "latin_america", ppp_multiplier: 0.40, priority_score: 3.57,
        year1_target: 0, cross_border_corridors: [],
        calling_code: "+593", primary_locale: "spa-EC",
        drive_side: "right", distance_unit: "km", weight_unit: "kg",
    },

    // ── TIER E (41 countries) ────────────────────────────────

    {
        iso2: "BO", name: "Bolivia", tier: "E",
        currency: "BOB", admin1_label: null, admin1_enforced: false,
        region: "latin_america", ppp_multiplier: 0.40, priority_score: 2.35,
        year1_target: 0, cross_border_corridors: [],
        calling_code: "+591", primary_locale: "aym-BO",
        drive_side: "right", distance_unit: "km", weight_unit: "kg",
    },
    {
        iso2: "PY", name: "Paraguay", tier: "E",
        currency: "PYG", admin1_label: null, admin1_enforced: false,
        region: "latin_america", ppp_multiplier: 0.40, priority_score: 1.94,
        year1_target: 0, cross_border_corridors: [],
        calling_code: "+595", primary_locale: "grn-PY",
        drive_side: "right", distance_unit: "km", weight_unit: "kg",
    },
    {
        iso2: "GT", name: "Guatemala", tier: "E",
        currency: "GTQ", admin1_label: null, admin1_enforced: false,
        region: "north_america", ppp_multiplier: 0.40, priority_score: 2.40,
        year1_target: 0, cross_border_corridors: [],
        calling_code: "+502", primary_locale: "spa-GT",
        drive_side: "right", distance_unit: "km", weight_unit: "kg",
    },
    {
        iso2: "DO", name: "Dominican Republic", tier: "E",
        currency: "DOP", admin1_label: null, admin1_enforced: false,
        region: "north_america", ppp_multiplier: 0.40, priority_score: 1.92,
        year1_target: 0, cross_border_corridors: [],
        calling_code: "+1", primary_locale: "spa-DO",
        drive_side: "right", distance_unit: "km", weight_unit: "kg",
    },
    {
        iso2: "HN", name: "Honduras", tier: "E",
        currency: "HNL", admin1_label: null, admin1_enforced: false,
        region: "north_america", ppp_multiplier: 0.40, priority_score: 1.86,
        year1_target: 0, cross_border_corridors: [],
        calling_code: "+504", primary_locale: "spa-HN",
        drive_side: "right", distance_unit: "km", weight_unit: "kg",
    },
    {
        iso2: "SV", name: "El Salvador", tier: "E",
        currency: "USD", admin1_label: null, admin1_enforced: false,
        region: "north_america", ppp_multiplier: 0.40, priority_score: 2.02,
        year1_target: 0, cross_border_corridors: [],
        calling_code: "+503", primary_locale: "spa-SV",
        drive_side: "right", distance_unit: "km", weight_unit: "kg",
    },
    {
        iso2: "NI", name: "Nicaragua", tier: "E",
        currency: "NIO", admin1_label: null, admin1_enforced: false,
        region: "north_america", ppp_multiplier: 0.40, priority_score: 1.97,
        year1_target: 0, cross_border_corridors: [],
        calling_code: "+505", primary_locale: "spa-NI",
        drive_side: "right", distance_unit: "km", weight_unit: "kg",
    },
    {
        iso2: "JM", name: "Jamaica", tier: "E",
        currency: "JMD", admin1_label: null, admin1_enforced: false,
        region: "north_america", ppp_multiplier: 0.40, priority_score: 2.34,
        year1_target: 0, cross_border_corridors: [],
        calling_code: "+1", primary_locale: "eng-JM",
        drive_side: "left", distance_unit: "km", weight_unit: "kg",
    },
    {
        iso2: "GY", name: "Guyana", tier: "E",
        currency: "GYD", admin1_label: null, admin1_enforced: false,
        region: "latin_america", ppp_multiplier: 0.40, priority_score: 2.20,
        year1_target: 0, cross_border_corridors: [],
        calling_code: "+592", primary_locale: "eng-GY",
        drive_side: "left", distance_unit: "km", weight_unit: "kg",
    },
    {
        iso2: "SR", name: "Suriname", tier: "E",
        currency: "SRD", admin1_label: null, admin1_enforced: false,
        region: "latin_america", ppp_multiplier: 0.40, priority_score: 1.96,
        year1_target: 0, cross_border_corridors: [],
        calling_code: "+597", primary_locale: "nld-SR",
        drive_side: "left", distance_unit: "km", weight_unit: "kg",
    },
    {
        iso2: "BA", name: "Bosnia and Herzegovina", tier: "E",
        currency: "BAM", admin1_label: null, admin1_enforced: false,
        region: "europe_west", ppp_multiplier: 0.40, priority_score: 2.29,
        year1_target: 0, cross_border_corridors: [],
        calling_code: "+387", primary_locale: "bos-BA",
        drive_side: "right", distance_unit: "km", weight_unit: "kg",
    },
    {
        iso2: "ME", name: "Montenegro", tier: "E",
        currency: "EUR", admin1_label: null, admin1_enforced: false,
        region: "europe_west", ppp_multiplier: 0.40, priority_score: 2.02,
        year1_target: 0, cross_border_corridors: [],
        calling_code: "+382", primary_locale: "cnr-ME",
        drive_side: "right", distance_unit: "km", weight_unit: "kg",
    },
    {
        iso2: "MK", name: "North Macedonia", tier: "E",
        currency: "MKD", admin1_label: null, admin1_enforced: false,
        region: "europe_west", ppp_multiplier: 0.40, priority_score: 2.12,
        year1_target: 0, cross_border_corridors: [],
        calling_code: "+389", primary_locale: "mkd-MK",
        drive_side: "right", distance_unit: "km", weight_unit: "kg",
    },
    {
        iso2: "AL", name: "Albania", tier: "E",
        currency: "ALL", admin1_label: null, admin1_enforced: false,
        region: "europe_west", ppp_multiplier: 0.40, priority_score: 2.05,
        year1_target: 0, cross_border_corridors: [],
        calling_code: "+355", primary_locale: "sqi-AL",
        drive_side: "right", distance_unit: "km", weight_unit: "kg",
    },
    {
        iso2: "MD", name: "Moldova", tier: "E",
        currency: "MDL", admin1_label: null, admin1_enforced: false,
        region: "europe_east", ppp_multiplier: 0.40, priority_score: 2.21,
        year1_target: 0, cross_border_corridors: [],
        calling_code: "+373", primary_locale: "ron-MD",
        drive_side: "right", distance_unit: "km", weight_unit: "kg",
    },
    {
        iso2: "IQ", name: "Iraq", tier: "E",
        currency: "IQD", admin1_label: null, admin1_enforced: false,
        region: "middle_east", ppp_multiplier: 0.40, priority_score: 2.09,
        year1_target: 0, cross_border_corridors: [],
        calling_code: "+964", primary_locale: "ara-IQ",
        drive_side: "right", distance_unit: "km", weight_unit: "kg",
    },
    {
        iso2: "NA", name: "Namibia", tier: "E",
        currency: "NAD", admin1_label: null, admin1_enforced: false,
        region: "africa", ppp_multiplier: 0.40, priority_score: 1.96,
        year1_target: 0, cross_border_corridors: [],
        calling_code: "+264", primary_locale: "afr-NA",
        drive_side: "left", distance_unit: "km", weight_unit: "kg",
    },
    {
        iso2: "AO", name: "Angola", tier: "E",
        currency: "AOA", admin1_label: null, admin1_enforced: false,
        region: "africa", ppp_multiplier: 0.40, priority_score: 1.63,
        year1_target: 0, cross_border_corridors: [],
        calling_code: "+244", primary_locale: "por-AO",
        drive_side: "right", distance_unit: "km", weight_unit: "kg",
    },
    {
        iso2: "MZ", name: "Mozambique", tier: "E",
        currency: "MZN", admin1_label: null, admin1_enforced: false,
        region: "africa", ppp_multiplier: 0.40, priority_score: 2.12,
        year1_target: 0, cross_border_corridors: [],
        calling_code: "+258", primary_locale: "por-MZ",
        drive_side: "left", distance_unit: "km", weight_unit: "kg",
    },
    {
        iso2: "ET", name: "Ethiopia", tier: "E",
        currency: "ETB", admin1_label: null, admin1_enforced: false,
        region: "africa", ppp_multiplier: 0.40, priority_score: 1.91,
        year1_target: 0, cross_border_corridors: [],
        calling_code: "+251", primary_locale: "amh-ET",
        drive_side: "right", distance_unit: "km", weight_unit: "kg",
    },
    {
        iso2: "CI", name: "Ivory Coast", tier: "E",
        currency: "XOF", admin1_label: null, admin1_enforced: false,
        region: "africa", ppp_multiplier: 0.40, priority_score: 2.01,
        year1_target: 0, cross_border_corridors: [],
        calling_code: "+225", primary_locale: "fra-CI",
        drive_side: "right", distance_unit: "km", weight_unit: "kg",
    },
    {
        iso2: "SN", name: "Senegal", tier: "E",
        currency: "XOF", admin1_label: null, admin1_enforced: false,
        region: "africa", ppp_multiplier: 0.40, priority_score: 2.36,
        year1_target: 0, cross_border_corridors: [],
        calling_code: "+221", primary_locale: "fra-SN",
        drive_side: "right", distance_unit: "km", weight_unit: "kg",
    },
    {
        iso2: "BW", name: "Botswana", tier: "E",
        currency: "BWP", admin1_label: null, admin1_enforced: false,
        region: "africa", ppp_multiplier: 0.40, priority_score: 1.71,
        year1_target: 0, cross_border_corridors: [],
        calling_code: "+267", primary_locale: "eng-BW",
        drive_side: "left", distance_unit: "km", weight_unit: "kg",
    },
    {
        iso2: "ZM", name: "Zambia", tier: "E",
        currency: "ZMW", admin1_label: null, admin1_enforced: false,
        region: "africa", ppp_multiplier: 0.40, priority_score: 1.79,
        year1_target: 0, cross_border_corridors: [],
        calling_code: "+260", primary_locale: "eng-ZM",
        drive_side: "left", distance_unit: "km", weight_unit: "kg",
    },
    {
        iso2: "UG", name: "Uganda", tier: "E",
        currency: "UGX", admin1_label: null, admin1_enforced: false,
        region: "africa", ppp_multiplier: 0.40, priority_score: 1.64,
        year1_target: 0, cross_border_corridors: [],
        calling_code: "+256", primary_locale: "eng-UG",
        drive_side: "left", distance_unit: "km", weight_unit: "kg",
    },
    {
        iso2: "CM", name: "Cameroon", tier: "E",
        currency: "XAF", admin1_label: null, admin1_enforced: false,
        region: "africa", ppp_multiplier: 0.40, priority_score: 2.30,
        year1_target: 0, cross_border_corridors: [],
        calling_code: "+237", primary_locale: "eng-CM",
        drive_side: "right", distance_unit: "km", weight_unit: "kg",
    },
    {
        iso2: "KH", name: "Cambodia", tier: "E",
        currency: "KHR", admin1_label: null, admin1_enforced: false,
        region: "asia_pacific", ppp_multiplier: 0.40, priority_score: 2.21,
        year1_target: 0, cross_border_corridors: [],
        calling_code: "+855", primary_locale: "khm-KH",
        drive_side: "right", distance_unit: "km", weight_unit: "kg",
    },
    {
        iso2: "LK", name: "Sri Lanka", tier: "E",
        currency: "LKR", admin1_label: null, admin1_enforced: false,
        region: "asia_pacific", ppp_multiplier: 0.40, priority_score: 1.93,
        year1_target: 0, cross_border_corridors: [],
        calling_code: "+94", primary_locale: "sin-LK",
        drive_side: "left", distance_unit: "km", weight_unit: "kg",
    },
    {
        iso2: "UZ", name: "Uzbekistan", tier: "E",
        currency: "UZS", admin1_label: null, admin1_enforced: false,
        region: "asia_pacific", ppp_multiplier: 0.40, priority_score: 1.70,
        year1_target: 0, cross_border_corridors: [],
        calling_code: "+998", primary_locale: "rus-UZ",
        drive_side: "right", distance_unit: "km", weight_unit: "kg",
    },
    {
        iso2: "LA", name: "Laos", tier: "E",
        currency: "LAK", admin1_label: null, admin1_enforced: false,
        region: "asia_pacific", ppp_multiplier: 0.40, priority_score: 1.67,
        year1_target: 0, cross_border_corridors: [],
        calling_code: "+856", primary_locale: "lao-LA",
        drive_side: "right", distance_unit: "km", weight_unit: "kg",
    },
    {
        iso2: "NP", name: "Nepal", tier: "E",
        currency: "NPR", admin1_label: null, admin1_enforced: false,
        region: "asia_pacific", ppp_multiplier: 0.40, priority_score: 1.69,
        year1_target: 0, cross_border_corridors: [],
        calling_code: "+977", primary_locale: "nep-NP",
        drive_side: "left", distance_unit: "km", weight_unit: "kg",
    },
    {
        iso2: "DZ", name: "Algeria", tier: "E",
        currency: "DZD", admin1_label: null, admin1_enforced: false,
        region: "africa", ppp_multiplier: 0.40, priority_score: 2.15,
        year1_target: 0, cross_border_corridors: [],
        calling_code: "+213", primary_locale: "ara-DZ",
        drive_side: "right", distance_unit: "km", weight_unit: "kg",
    },
    {
        iso2: "TN", name: "Tunisia", tier: "E",
        currency: "TND", admin1_label: null, admin1_enforced: false,
        region: "africa", ppp_multiplier: 0.40, priority_score: 2.33,
        year1_target: 0, cross_border_corridors: [],
        calling_code: "+216", primary_locale: "ara-TN",
        drive_side: "right", distance_unit: "km", weight_unit: "kg",
    },
    {
        iso2: "MT", name: "Malta", tier: "E",
        currency: "EUR", admin1_label: null, admin1_enforced: false,
        region: "europe_south", ppp_multiplier: 0.40, priority_score: 1.56,
        year1_target: 0, cross_border_corridors: [],
        calling_code: "+356", primary_locale: "eng-MT",
        drive_side: "left", distance_unit: "km", weight_unit: "kg",
    },
    {
        iso2: "BN", name: "Brunei", tier: "E",
        currency: "BND", admin1_label: null, admin1_enforced: false,
        region: "asia_pacific", ppp_multiplier: 0.40, priority_score: 2.26,
        year1_target: 0, cross_border_corridors: [],
        calling_code: "+673", primary_locale: "msa-BN",
        drive_side: "left", distance_unit: "km", weight_unit: "kg",
    },
    {
        iso2: "RW", name: "Rwanda", tier: "E",
        currency: "RWF", admin1_label: null, admin1_enforced: false,
        region: "africa", ppp_multiplier: 0.40, priority_score: 2.13,
        year1_target: 0, cross_border_corridors: [],
        calling_code: "+250", primary_locale: "eng-RW",
        drive_side: "right", distance_unit: "km", weight_unit: "kg",
    },
    {
        iso2: "MG", name: "Madagascar", tier: "E",
        currency: "MGA", admin1_label: null, admin1_enforced: false,
        region: "africa", ppp_multiplier: 0.40, priority_score: 2.00,
        year1_target: 0, cross_border_corridors: [],
        calling_code: "+261", primary_locale: "fra-MG",
        drive_side: "right", distance_unit: "km", weight_unit: "kg",
    },
    {
        iso2: "PG", name: "Papua New Guinea", tier: "E",
        currency: "PGK", admin1_label: null, admin1_enforced: false,
        region: "oceania", ppp_multiplier: 0.40, priority_score: 1.92,
        year1_target: 0, cross_border_corridors: [],
        calling_code: "+675", primary_locale: "eng-PG",
        drive_side: "left", distance_unit: "km", weight_unit: "kg",
    },
    {
        iso2: "TM", name: "Turkmenistan", tier: "E",
        currency: "TMT", admin1_label: null, admin1_enforced: false,
        region: "asia_pacific", ppp_multiplier: 0.40, priority_score: 1.81,
        year1_target: 0, cross_border_corridors: [],
        calling_code: "+993", primary_locale: "rus-TM",
        drive_side: "right", distance_unit: "km", weight_unit: "kg",
    },
    {
        iso2: "KG", name: "Kyrgyzstan", tier: "E",
        currency: "KGS", admin1_label: null, admin1_enforced: false,
        region: "asia_pacific", ppp_multiplier: 0.40, priority_score: 2.09,
        year1_target: 0, cross_border_corridors: [],
        calling_code: "+996", primary_locale: "kir-KG",
        drive_side: "right", distance_unit: "km", weight_unit: "kg",
    },
    {
        iso2: "MW", name: "Malawi", tier: "E",
        currency: "MWK", admin1_label: null, admin1_enforced: false,
        region: "africa", ppp_multiplier: 0.40, priority_score: 2.28,
        year1_target: 0, cross_border_corridors: [],
        calling_code: "+265", primary_locale: "eng-MW",
        drive_side: "left", distance_unit: "km", weight_unit: "kg",
    },

];

export const COUNTRY_BY_ISO2: ReadonlyMap<string, HCCountry> = new Map(HC_COUNTRIES.map(c => [c.iso2, c]));
export const ALL_ISO2_CODES: readonly string[] = HC_COUNTRIES.map(c => c.iso2);
export const COUNTRY_COUNT = HC_COUNTRIES.length;

export function getCountriesByTier(tier: CountryTier): HCCountry[] { return HC_COUNTRIES.filter(c => c.tier === tier); }
export function getCountriesByRegion(region: HCRegion): HCCountry[] { return HC_COUNTRIES.filter(c => c.region === region); }
export function getPPPMultiplier(iso2: string): number { return COUNTRY_BY_ISO2.get(iso2)?.ppp_multiplier ?? 0.58; }
export function getCrossCorridors(iso2: string): string[] { return COUNTRY_BY_ISO2.get(iso2)?.cross_border_corridors ?? []; }
export function isAdmin1Enforced(iso2: string): boolean { return COUNTRY_BY_ISO2.get(iso2)?.admin1_enforced ?? false; }
export function getCurrency(iso2: string): string { return COUNTRY_BY_ISO2.get(iso2)?.currency ?? "USD"; }
export function getLocale(iso2: string): string { return COUNTRY_BY_ISO2.get(iso2)?.primary_locale ?? "en-US"; }
export function countryFlag(iso2: string): string {
    const codePoints = [...iso2.toUpperCase()].map(c => 0x1f1e6 + c.charCodeAt(0) - 65);
    try { return String.fromCodePoint(...codePoints); } catch { return "🌍"; }
}
export function isHCCountry(iso2: string): boolean { return COUNTRY_BY_ISO2.has(iso2); }
export function getCountryName(iso2: string): string { return COUNTRY_BY_ISO2.get(iso2)?.name ?? iso2; }
export function getDistanceUnit(iso2: string): "mi" | "km" { return COUNTRY_BY_ISO2.get(iso2)?.distance_unit ?? "km"; }
export function getTierACountries(): HCCountry[] { return getCountriesByTier("A"); }
export function getTopCountries(n: number = 10): HCCountry[] { return [...HC_COUNTRIES].sort((a, b) => b.priority_score - a.priority_score).slice(0, n); }
