-- Route-support category registry normalization.
-- Do not create a parallel truck stop or infrastructure directory here:
-- directory_entities remains the canonical public graph, while truck_stops and
-- other source tables feed/verify specialized details.

insert into public.hc_directory_category_registry (
  category_key,
  public_label,
  route_slug,
  ecosystem_family,
  category_intent,
  primary_roles,
  secondary_roles,
  entity_subtypes,
  data_sources,
  source_ladder,
  claim_route,
  lead_route,
  sponsor_route,
  index_policy,
  minimum_records_to_index,
  minimum_country_records_to_index,
  schema_org_type,
  answer_card_intents,
  monetization_paths,
  trust_requirements,
  source_notes,
  active,
  updated_at
) values
  (
    'truck_stops',
    'Truck Stops',
    'truck-stops',
    'infrastructure',
    'Find fuel, parking, scales, showers, repair, and route-support stops for heavy-haul moves.',
    array['heavy_haul_driver','pilot_car_operator','dispatcher','carrier'],
    array['shipper','broker','insurance_partner','equipment_supplier'],
    array['truck_stop','fuel_station','cat_scale_location'],
    array['directory_entities','truck_stops','hc_places','hc_open_data_ingestion_queue','public_condition_reports'],
    array['official/facility source','operator/steward report','open data','community condition report'],
    '/claim',
    '/route-request',
    '/advertise',
    'index_when_useful_data',
    50,
    5,
    'LocalBusiness',
    array['near_me','route_support','oversize_parking','driver_readiness'],
    array['sponsored_listing','fuel_partner','equipment_offer','insurance_offer','data_product'],
    array['public_source','human_steward_claim_required','no_fake_availability','condition_reports_moderated'],
    'Canonical public category for truck stops. The truck_stops table remains a specialized source table, not a competing public directory.',
    true,
    now()
  ),
  (
    'rest_areas',
    'Rest Areas',
    'rest-areas',
    'infrastructure',
    'Find rest areas and pull-off support points with safety, lighting, restroom, and oversize-access notes.',
    array['heavy_haul_driver','pilot_car_operator','dispatcher'],
    array['carrier','shipper','safety_partner'],
    array['rest_area'],
    array['directory_entities','hc_places','hc_open_data_ingestion_queue','public_condition_reports'],
    array['official/public source','steward report','community condition report'],
    '/claim',
    '/route-request',
    '/advertise',
    'index_when_useful_data',
    50,
    5,
    'Place',
    array['near_me','route_support','restrooms','overnight_rules'],
    array['sponsored_safety_campaign','data_product','claim_stewardship'],
    array['public_source','human_steward_claim_required','condition_reports_moderated'],
    'Canonical category for rest_area. Legacy rest_stop aliases should feed this subtype.',
    true,
    now()
  ),
  (
    'route_support_weigh_stations',
    'Weigh Stations',
    'weigh-stations',
    'infrastructure',
    'Find weigh stations and scale-related route checkpoints with status, access, and compliance notes.',
    array['heavy_haul_driver','carrier','dispatcher'],
    array['broker','shipper','permit_agent'],
    array['weigh_station'],
    array['directory_entities','hc_places','hc_open_data_ingestion_queue','public_condition_reports'],
    array['official/public source','open data','steward report','community condition report'],
    '/claim',
    '/route-request',
    '/advertise',
    'index_when_useful_data',
    25,
    3,
    'GovernmentOffice',
    array['route_compliance','scale_access','near_me'],
    array['data_product','compliance_partner','sponsored_listing'],
    array['public_source','human_steward_claim_required','condition_reports_moderated'],
    'Canonical category for weigh_station. hc_places scale_weigh_station_public should map here.',
    true,
    now()
  ),
  (
    'route_support_truck_parking',
    'Truck Parking and Staging',
    'truck-parking',
    'infrastructure',
    'Find truck parking, staging yards, drop yards, and secure oversize holding locations.',
    array['heavy_haul_driver','pilot_car_operator','dispatcher','carrier'],
    array['shipper','broker','staging_yard_owner','security_partner'],
    array['truck_parking','staging_yard','industrial_yard','drop_yard','secure_storage','escort_staging_zone'],
    array['directory_entities','hc_places','hc_open_data_ingestion_queue','public_condition_reports'],
    array['facility source','steward report','open data','community condition report'],
    '/claim',
    '/route-request',
    '/advertise',
    'index_when_useful_data',
    25,
    3,
    'ParkingFacility',
    array['near_me','staging','oversize_parking','route_support'],
    array['sponsored_listing','paid_claim','security_offer','data_product'],
    array['public_source','human_steward_claim_required','condition_reports_moderated'],
    'Canonical category for truck_parking and staging aliases.',
    true,
    now()
  ),
  (
    'route_support_ports',
    'Ports and Cargo Gateways',
    'ports',
    'infrastructure',
    'Find ports, shipyards, cargo gateways, and heavy-haul access points tied to project cargo movement.',
    array['carrier','broker','shipper','dispatcher'],
    array['permit_agent','pilot_car_operator','port_authority','customs_broker'],
    array['port','shipyard','lng_terminal'],
    array['directory_entities','ports','port_infrastructure','hc_places','hc_open_data_ingestion_queue'],
    array['official/port source','authority source','open data','steward report'],
    '/claim',
    '/route-request',
    '/advertise',
    'index_when_useful_data',
    25,
    3,
    'Place',
    array['project_cargo','port_access','route_support','near_me'],
    array['sponsored_listing','port_sponsor','customs_partner','data_product'],
    array['public_source','authority_or_steward_claim_required','no_fake_capacity'],
    'Canonical category for port-related infrastructure records.',
    true,
    now()
  ),
  (
    'route_support_rail_intermodal',
    'Rail and Intermodal Terminals',
    'rail-intermodal',
    'infrastructure',
    'Find rail intermodal terminals, freight terminals, and transfer points relevant to heavy-haul planning.',
    array['carrier','broker','shipper','dispatcher'],
    array['rail_partner','permit_agent','pilot_car_operator'],
    array['rail_intermodal','freight_terminal'],
    array['directory_entities','ports','hc_places','hc_open_data_ingestion_queue'],
    array['official/terminal source','open data','steward report'],
    '/claim',
    '/route-request',
    '/advertise',
    'index_when_useful_data',
    15,
    2,
    'Place',
    array['project_cargo','intermodal_transfer','route_support'],
    array['sponsored_listing','data_product','partner_offer'],
    array['public_source','authority_or_steward_claim_required','no_fake_capacity'],
    'Canonical category for rail_intermodal. Aliases like intermodal_terminal and rail_terminal should normalize here.',
    true,
    now()
  ),
  (
    'route_support_border_crossings',
    'Border Crossings',
    'border-crossings',
    'infrastructure',
    'Find border crossings, customs route context, and cross-border heavy-haul support points.',
    array['carrier','broker','shipper','dispatcher','permit_agent'],
    array['customs_broker','pilot_car_operator','authority_reference'],
    array['border_crossing'],
    array['directory_entities','border_crossings','hc_places','hc_open_data_ingestion_queue'],
    array['official/customs source','authority source','open data','steward report'],
    '/claim',
    '/route-request',
    '/advertise',
    'index_when_useful_data',
    10,
    1,
    'GovernmentOffice',
    array['cross_border','customs','route_support','near_me'],
    array['customs_partner','sponsored_listing','data_product'],
    array['public_source','authority_or_steward_claim_required','no_fake_legal_advice'],
    'Canonical category for border_crossing. Misclassified operator-family rows should be infrastructure.',
    true,
    now()
  ),
  (
    'route_support_tunnels',
    'Tunnels and Tunnel Authorities',
    'tunnels',
    'infrastructure',
    'Find tunnels, tunnel authorities, and tunnel-related route restrictions for oversize movement planning.',
    array['carrier','dispatcher','permit_agent','heavy_haul_driver'],
    array['shipper','broker','pilot_car_operator','authority_reference'],
    array['tunnel','tunnel_authority'],
    array['directory_entities','authority_sources','hc_open_data_ingestion_queue','public_condition_reports'],
    array['official/authority source','route restriction source','steward report','community condition report'],
    '/claim',
    '/route-request',
    '/advertise',
    'noindex_until_threshold',
    10,
    1,
    'CivicStructure',
    array['clearance','restriction','route_support'],
    array['data_product','authority_reference','sponsored_safety_campaign'],
    array['public_source','authority_or_steward_claim_required','no_fake_clearance_guarantee'],
    'Canonical category for tunnel and tunnel_authority records. It is scaffolded even when current live rows are zero.',
    true,
    now()
  )
on conflict (category_key) do update
set public_label = excluded.public_label,
    route_slug = excluded.route_slug,
    ecosystem_family = excluded.ecosystem_family,
    category_intent = excluded.category_intent,
    primary_roles = excluded.primary_roles,
    secondary_roles = excluded.secondary_roles,
    entity_subtypes = excluded.entity_subtypes,
    data_sources = excluded.data_sources,
    source_ladder = excluded.source_ladder,
    claim_route = excluded.claim_route,
    lead_route = excluded.lead_route,
    sponsor_route = excluded.sponsor_route,
    index_policy = excluded.index_policy,
    minimum_records_to_index = excluded.minimum_records_to_index,
    minimum_country_records_to_index = excluded.minimum_country_records_to_index,
    schema_org_type = excluded.schema_org_type,
    answer_card_intents = excluded.answer_card_intents,
    monetization_paths = excluded.monetization_paths,
    trust_requirements = excluded.trust_requirements,
    source_notes = excluded.source_notes,
    active = excluded.active,
    updated_at = now();

update public.hc_directory_entity_types
set entity_family = 'infrastructure',
    updated_at = now()
where entity_subtype = any (array[
  'truck_stop',
  'rest_area',
  'weigh_station',
  'truck_parking',
  'port',
  'rail_intermodal',
  'border_crossing',
  'tunnel',
  'tunnel_authority'
])
and entity_family is distinct from 'infrastructure';

update public.directory_entities
set entity_family = 'infrastructure',
    role_family = coalesce(role_family, 'infrastructure'),
    primary_role = coalesce(primary_role, entity_subtype),
    seo_page_type = coalesce(seo_page_type, 'infrastructure_profile'),
    updated_at = now()
where entity_subtype = any (array[
  'truck_stop',
  'rest_area',
  'weigh_station',
  'truck_parking',
  'port',
  'rail_intermodal',
  'border_crossing',
  'tunnel',
  'tunnel_authority'
])
and entity_family is distinct from 'infrastructure';

create or replace view public.v_hc_route_support_category_audit
with (security_invoker = true) as
with target(subtype) as (
  values
    ('truck_stop'),
    ('rest_area'),
    ('weigh_station'),
    ('truck_parking'),
    ('port'),
    ('rail_intermodal'),
    ('border_crossing'),
    ('tunnel'),
    ('tunnel_authority')
)
select
  t.subtype as entity_subtype,
  count(de.id)::bigint as directory_count,
  count(de.id) filter (where de.entity_family = 'infrastructure')::bigint as infrastructure_family_count,
  count(de.id) filter (where de.is_claimable)::bigint as claimable_count,
  count(de.id) filter (where de.country_code is not null)::bigint as with_country_count,
  count(de.id) filter (where de.lat is not null and de.lng is not null)::bigint as with_geo_count,
  count(r.category_key)::bigint as registry_category_count,
  max(r.route_slug) as registry_route_slug
from target t
left join public.directory_entities de on de.entity_subtype = t.subtype
left join public.hc_directory_category_registry r on t.subtype = any (r.entity_subtypes) and r.active
group by t.subtype
order by t.subtype;

grant select on public.v_hc_route_support_category_audit to anon, authenticated;
