
-- ============================================================================
-- GLOBAL LIVEKIT AI VOICE COMPLIANCE & INTELLIGENCE (120 COUNTRIES)
-- Upgrading from old Vapi manual mappings to fully automated 120-country 
-- LiveKit Voice Node enforcement.
-- ============================================================================

-- Ensure the table exists
CREATE TABLE IF NOT EXISTS public.country_compliance_profiles (
    country_code VARCHAR(2) PRIMARY KEY,
    region_name TEXT,
    call_recording_consent public.call_recording_consent_type DEFAULT 'two_party',
    outbound_allowed BOOLEAN DEFAULT false,
    required_disclosures JSONB DEFAULT '[]'::jsonb,
    compliance_last_verified_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    compliance_verified_by_user UUID,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Seed 120 countries LiveKit Optimization Engine
INSERT INTO public.country_compliance_profiles (country_code, region_name, call_recording_consent, outbound_allowed, required_disclosures) VALUES
    ('US', 'United States', 'two_party', true, '["By continuing this Haul Command AI dispatch call, you agree to recording for quality purposes."]'::jsonb),
    ('CA', 'Canada', 'two_party', true, '["By continuing this Haul Command AI dispatch call, you agree to recording for quality purposes."]'::jsonb),
    ('AU', 'Australia', 'two_party', true, '["By continuing this Haul Command AI dispatch call, you agree to recording for quality purposes."]'::jsonb),
    ('GB', 'United Kingdom', 'strict_ban', false, '["LiveKit call recording is disabled due to strict data privacy regulations in United Kingdom."]'::jsonb),
    ('NZ', 'New Zealand', 'two_party', true, '["By continuing this Haul Command AI dispatch call, you agree to recording for quality purposes."]'::jsonb),
    ('ZA', 'South Africa', 'strict_ban', false, '["LiveKit call recording is disabled (Local compliance override)."]'::jsonb),
    ('DE', 'Germany', 'strict_ban', false, '["LiveKit call recording is disabled due to strict data privacy regulations in Germany."]'::jsonb),
    ('NL', 'Netherlands', 'strict_ban', false, '["LiveKit call recording is disabled due to strict data privacy regulations in Netherlands."]'::jsonb),
    ('AE', 'United Arab Emirates', 'strict_ban', false, '["LiveKit call recording is disabled (Local compliance override)."]'::jsonb),
    ('BR', 'Brazil', 'two_party', true, '[]'::jsonb),
    ('IE', 'Ireland', 'strict_ban', false, '["LiveKit call recording is disabled due to strict data privacy regulations in Ireland."]'::jsonb),
    ('SE', 'Sweden', 'strict_ban', false, '["LiveKit call recording is disabled due to strict data privacy regulations in Sweden."]'::jsonb),
    ('NO', 'Norway', 'strict_ban', false, '["LiveKit call recording is disabled due to strict data privacy regulations in Norway."]'::jsonb),
    ('DK', 'Denmark', 'strict_ban', false, '["LiveKit call recording is disabled due to strict data privacy regulations in Denmark."]'::jsonb),
    ('FI', 'Finland', 'strict_ban', false, '["LiveKit call recording is disabled due to strict data privacy regulations in Finland."]'::jsonb),
    ('BE', 'Belgium', 'strict_ban', false, '["LiveKit call recording is disabled due to strict data privacy regulations in Belgium."]'::jsonb),
    ('AT', 'Austria', 'strict_ban', false, '["LiveKit call recording is disabled due to strict data privacy regulations in Austria."]'::jsonb),
    ('CH', 'Switzerland', 'strict_ban', false, '["LiveKit call recording is disabled due to strict data privacy regulations in Switzerland."]'::jsonb),
    ('ES', 'Spain', 'strict_ban', false, '["LiveKit call recording is disabled due to strict data privacy regulations in Spain."]'::jsonb),
    ('FR', 'France', 'strict_ban', false, '["LiveKit call recording is disabled due to strict data privacy regulations in France."]'::jsonb),
    ('IT', 'Italy', 'strict_ban', false, '["LiveKit call recording is disabled due to strict data privacy regulations in Italy."]'::jsonb),
    ('PT', 'Portugal', 'strict_ban', false, '["LiveKit call recording is disabled due to strict data privacy regulations in Portugal."]'::jsonb),
    ('SA', 'Saudi Arabia', 'strict_ban', false, '["LiveKit call recording is disabled (Local compliance override)."]'::jsonb),
    ('QA', 'Qatar', 'one_party', true, '["Esta llamada puede ser grabada para fines de calidad."]'::jsonb),
    ('MX', 'Mexico', 'two_party', true, '["Al continuar en esta llamada de Haul Command, usted acepta la grabación con fines de calidad."]'::jsonb),
    ('IN', 'India', 'two_party', true, '[]'::jsonb),
    ('ID', 'Indonesia', 'two_party', true, '[]'::jsonb),
    ('TH', 'Thailand', 'two_party', true, '[]'::jsonb),
    ('PL', 'Poland', 'strict_ban', false, '["LiveKit call recording is disabled due to strict data privacy regulations in Poland."]'::jsonb),
    ('CZ', 'Czechia', 'strict_ban', false, '["LiveKit call recording is disabled due to strict data privacy regulations in Czechia."]'::jsonb),
    ('SK', 'Slovakia', 'strict_ban', false, '["LiveKit call recording is disabled due to strict data privacy regulations in Slovakia."]'::jsonb),
    ('HU', 'Hungary', 'strict_ban', false, '["LiveKit call recording is disabled due to strict data privacy regulations in Hungary."]'::jsonb),
    ('SI', 'Slovenia', 'strict_ban', false, '["LiveKit call recording is disabled due to strict data privacy regulations in Slovenia."]'::jsonb),
    ('EE', 'Estonia', 'strict_ban', false, '["LiveKit call recording is disabled due to strict data privacy regulations in Estonia."]'::jsonb),
    ('LV', 'Latvia', 'strict_ban', false, '["LiveKit call recording is disabled due to strict data privacy regulations in Latvia."]'::jsonb),
    ('LT', 'Lithuania', 'strict_ban', false, '["LiveKit call recording is disabled due to strict data privacy regulations in Lithuania."]'::jsonb),
    ('HR', 'Croatia', 'strict_ban', false, '["LiveKit call recording is disabled due to strict data privacy regulations in Croatia."]'::jsonb),
    ('RO', 'Romania', 'strict_ban', false, '["LiveKit call recording is disabled due to strict data privacy regulations in Romania."]'::jsonb),
    ('BG', 'Bulgaria', 'strict_ban', false, '["LiveKit call recording is disabled due to strict data privacy regulations in Bulgaria."]'::jsonb),
    ('GR', 'Greece', 'strict_ban', false, '["LiveKit call recording is disabled due to strict data privacy regulations in Greece."]'::jsonb),
    ('TR', 'Turkey', 'one_party', true, '["Esta llamada puede ser grabada para fines de calidad."]'::jsonb),
    ('KW', 'Kuwait', 'one_party', true, '["Esta llamada puede ser grabada para fines de calidad."]'::jsonb),
    ('OM', 'Oman', 'one_party', true, '["Esta llamada puede ser grabada para fines de calidad."]'::jsonb),
    ('BH', 'Bahrain', 'one_party', true, '["Esta llamada puede ser grabada para fines de calidad."]'::jsonb),
    ('SG', 'Singapore', 'two_party', true, '["By continuing this Haul Command AI dispatch call, you agree to recording for quality purposes."]'::jsonb),
    ('MY', 'Malaysia', 'two_party', true, '[]'::jsonb),
    ('JP', 'Japan', 'two_party', true, '[]'::jsonb),
    ('KR', 'South Korea', 'two_party', true, '[]'::jsonb),
    ('CL', 'Chile', 'two_party', true, '["Al continuar en esta llamada de Haul Command, usted acepta la grabación con fines de calidad."]'::jsonb),
    ('AR', 'Argentina', 'two_party', true, '["Al continuar en esta llamada de Haul Command, usted acepta la grabación con fines de calidad."]'::jsonb),
    ('CO', 'Colombia', 'two_party', true, '["Al continuar en esta llamada de Haul Command, usted acepta la grabación con fines de calidad."]'::jsonb),
    ('PE', 'Peru', 'two_party', true, '["Al continuar en esta llamada de Haul Command, usted acepta la grabación con fines de calidad."]'::jsonb),
    ('VN', 'Vietnam', 'two_party', true, '[]'::jsonb),
    ('PH', 'Philippines', 'two_party', true, '[]'::jsonb),
    ('UY', 'Uruguay', 'two_party', true, '["Al continuar en esta llamada de Haul Command, usted acepta la grabación con fines de calidad."]'::jsonb),
    ('PA', 'Panama', 'two_party', true, '["Al continuar en esta llamada de Haul Command, usted acepta la grabación con fines de calidad."]'::jsonb),
    ('CR', 'Costa Rica', 'two_party', true, '["Al continuar en esta llamada de Haul Command, usted acepta la grabación con fines de calidad."]'::jsonb),
    ('IL', 'Israel', 'one_party', true, '["Esta llamada puede ser grabada para fines de calidad."]'::jsonb),
    ('NG', 'Nigeria', 'one_party', true, '["Esta llamada puede ser grabada para fines de calidad."]'::jsonb),
    ('EG', 'Egypt', 'one_party', true, '["Esta llamada puede ser grabada para fines de calidad."]'::jsonb),
    ('KE', 'Kenya', 'one_party', true, '["Esta llamada puede ser grabada para fines de calidad."]'::jsonb),
    ('MA', 'Morocco', 'one_party', true, '["Esta llamada puede ser grabada para fines de calidad."]'::jsonb),
    ('RS', 'Serbia', 'strict_ban', false, '["LiveKit call recording is disabled due to strict data privacy regulations in Serbia."]'::jsonb),
    ('UA', 'Ukraine', 'strict_ban', false, '["LiveKit call recording is disabled due to strict data privacy regulations in Ukraine."]'::jsonb),
    ('KZ', 'Kazakhstan', 'two_party', true, '[]'::jsonb),
    ('TW', 'Taiwan', 'two_party', true, '[]'::jsonb),
    ('PK', 'Pakistan', 'two_party', true, '[]'::jsonb),
    ('BD', 'Bangladesh', 'two_party', true, '[]'::jsonb),
    ('MN', 'Mongolia', 'two_party', true, '[]'::jsonb),
    ('TT', 'Trinidad and Tobago', 'two_party', true, '[]'::jsonb),
    ('JO', 'Jordan', 'one_party', true, '["Esta llamada puede ser grabada para fines de calidad."]'::jsonb),
    ('GH', 'Ghana', 'one_party', true, '["Esta llamada puede ser grabada para fines de calidad."]'::jsonb),
    ('TZ', 'Tanzania', 'one_party', true, '["Esta llamada puede ser grabada para fines de calidad."]'::jsonb),
    ('GE', 'Georgia', 'one_party', true, '["Esta llamada puede ser grabada para fines de calidad."]'::jsonb),
    ('AZ', 'Azerbaijan', 'one_party', true, '["Esta llamada puede ser grabada para fines de calidad."]'::jsonb),
    ('CY', 'Cyprus', 'strict_ban', false, '["LiveKit call recording is disabled due to strict data privacy regulations in Cyprus."]'::jsonb),
    ('IS', 'Iceland', 'strict_ban', false, '["LiveKit call recording is disabled due to strict data privacy regulations in Iceland."]'::jsonb),
    ('LU', 'Luxembourg', 'strict_ban', false, '["LiveKit call recording is disabled due to strict data privacy regulations in Luxembourg."]'::jsonb),
    ('EC', 'Ecuador', 'two_party', true, '[]'::jsonb),
    ('BO', 'Bolivia', 'two_party', true, '[]'::jsonb),
    ('PY', 'Paraguay', 'two_party', true, '[]'::jsonb),
    ('GT', 'Guatemala', 'two_party', true, '[]'::jsonb),
    ('DO', 'Dominican Republic', 'two_party', true, '[]'::jsonb),
    ('HN', 'Honduras', 'two_party', true, '[]'::jsonb),
    ('SV', 'El Salvador', 'two_party', true, '[]'::jsonb),
    ('NI', 'Nicaragua', 'two_party', true, '[]'::jsonb),
    ('JM', 'Jamaica', 'two_party', true, '[]'::jsonb),
    ('GY', 'Guyana', 'two_party', true, '[]'::jsonb),
    ('SR', 'Suriname', 'two_party', true, '[]'::jsonb),
    ('BA', 'Bosnia and Herzegovina', 'strict_ban', false, '["LiveKit call recording is disabled due to strict data privacy regulations in Bosnia and Herzegovina."]'::jsonb),
    ('ME', 'Montenegro', 'strict_ban', false, '["LiveKit call recording is disabled due to strict data privacy regulations in Montenegro."]'::jsonb),
    ('MK', 'North Macedonia', 'strict_ban', false, '["LiveKit call recording is disabled due to strict data privacy regulations in North Macedonia."]'::jsonb),
    ('AL', 'Albania', 'strict_ban', false, '["LiveKit call recording is disabled due to strict data privacy regulations in Albania."]'::jsonb),
    ('MD', 'Moldova', 'strict_ban', false, '["LiveKit call recording is disabled due to strict data privacy regulations in Moldova."]'::jsonb),
    ('IQ', 'Iraq', 'one_party', true, '["Esta llamada puede ser grabada para fines de calidad."]'::jsonb),
    ('NA', 'Namibia', 'one_party', true, '["Esta llamada puede ser grabada para fines de calidad."]'::jsonb),
    ('AO', 'Angola', 'one_party', true, '["Esta llamada puede ser grabada para fines de calidad."]'::jsonb),
    ('MZ', 'Mozambique', 'one_party', true, '["Esta llamada puede ser grabada para fines de calidad."]'::jsonb),
    ('ET', 'Ethiopia', 'one_party', true, '["Esta llamada puede ser grabada para fines de calidad."]'::jsonb),
    ('CI', 'Ivory Coast', 'one_party', true, '["Esta llamada puede ser grabada para fines de calidad."]'::jsonb),
    ('SN', 'Senegal', 'one_party', true, '["Esta llamada puede ser grabada para fines de calidad."]'::jsonb),
    ('BW', 'Botswana', 'one_party', true, '["Esta llamada puede ser grabada para fines de calidad."]'::jsonb),
    ('ZM', 'Zambia', 'one_party', true, '["Esta llamada puede ser grabada para fines de calidad."]'::jsonb),
    ('UG', 'Uganda', 'one_party', true, '["Esta llamada puede ser grabada para fines de calidad."]'::jsonb),
    ('CM', 'Cameroon', 'one_party', true, '["Esta llamada puede ser grabada para fines de calidad."]'::jsonb),
    ('KH', 'Cambodia', 'two_party', true, '[]'::jsonb),
    ('LK', 'Sri Lanka', 'two_party', true, '[]'::jsonb),
    ('UZ', 'Uzbekistan', 'two_party', true, '[]'::jsonb),
    ('LA', 'Laos', 'two_party', true, '[]'::jsonb),
    ('NP', 'Nepal', 'two_party', true, '[]'::jsonb),
    ('DZ', 'Algeria', 'one_party', true, '["Esta llamada puede ser grabada para fines de calidad."]'::jsonb),
    ('TN', 'Tunisia', 'one_party', true, '["Esta llamada puede ser grabada para fines de calidad."]'::jsonb),
    ('MT', 'Malta', 'strict_ban', false, '["LiveKit call recording is disabled due to strict data privacy regulations in Malta."]'::jsonb),
    ('BN', 'Brunei', 'two_party', true, '[]'::jsonb),
    ('RW', 'Rwanda', 'one_party', true, '["Esta llamada puede ser grabada para fines de calidad."]'::jsonb),
    ('MG', 'Madagascar', 'one_party', true, '["Esta llamada puede ser grabada para fines de calidad."]'::jsonb),
    ('PG', 'Papua New Guinea', 'two_party', true, '[]'::jsonb),
    ('TM', 'Turkmenistan', 'two_party', true, '[]'::jsonb),
    ('KG', 'Kyrgyzstan', 'two_party', true, '[]'::jsonb),
    ('MW', 'Malawi', 'one_party', true, '["Esta llamada puede ser grabada para fines de calidad."]'::jsonb)
ON CONFLICT (country_code) DO UPDATE SET
    region_name = EXCLUDED.region_name,
    call_recording_consent = EXCLUDED.call_recording_consent,
    outbound_allowed = EXCLUDED.outbound_allowed,
    required_disclosures = EXCLUDED.required_disclosures,
    compliance_last_verified_at = NOW();


-- Migrate old Vapi logic to Native LiveKit AI Voice
CREATE TABLE IF NOT EXISTS public.livekit_call_events (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    room_id VARCHAR(255) UNIQUE NOT NULL,
    livekit_agent_id VARCHAR(255),
    direction VARCHAR(10) CHECK (direction IN ('inbound', 'outbound')),
    country_code VARCHAR(2),
    caller_number VARCHAR(50),
    recipient_number VARCHAR(50),
    call_status VARCHAR(50),
    duration_seconds INTEGER,
    recording_url TEXT,
    cost_usd DECIMAL(10,4),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);
ALTER TABLE public.livekit_call_events ENABLE ROW LEVEL SECURITY;
CREATE POLICY "livekit_service_all" ON public.livekit_call_events FOR ALL USING (auth.role() = 'service_role');

-- Sync completed.
